      SUBROUTINE LOCGEO(VECT,VECLOC,CELSIZ,NSIZE)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC
CC    CONVERTS GLOBAL GEOMETRY (VECT) TO LOCAL GEOMETRY (VECLOC)
CC    FIRST THREE ARE COORDINATES, SECOND THREE DIRECTION COSINES
CC    CELSIZ CONTAINS THE PARAMETERS DEFINING THE CELL VOLUME,
CC    I.E. THE PARAMETERS OF SYSTEM SHAPE AS DESCRIBED IN THE
CC    GEANT USER'S GUIDE, GEOM 050.
CC
CC    11-3-85  HEDIN
CC    12-1-85  TRIPPE ADDED NSIZE TO ALLOW ALL SYSTEM SHAPES.
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:GCBANK.INC'
      INCLUDE 'D0$INC:GCLINK.INC'
      INCLUDE 'D0$INC:GCVOLU.INC/LIST'
      REAL TEMP(3),CELSIZ(*),VECT(*),VECLOC(*)
      INTEGER NSIZE,I,J
      INTEGER NGPAR,JPAR
C
      DO 10 I=1,3
 10   VECLOC(I)=VECT(I)-GTRAN(I,NLEVEL)
      IF(GRMAT(10,NLEVEL).EQ.0.) THEN
CCCC    TRIVIAL TRANSFORMATION
        DO 12 I=1,3
 12     VECLOC(3+I)=VECT(3+I)
      ELSE
        DO 11 I=1,3
        VECLOC(3+I)=0.
        TEMP(I)=0.
        DO 11 J=1,3
        TEMP(I)=TEMP(I)+GRMAT(3*(I-1)+J,NLEVEL)*VECLOC(J)
        VECLOC(3+I)=VECLOC(3+I)+GRMAT(3*(I-1)+J,NLEVEL)*VECT(3+J)
 11     CONTINUE
        DO 111 I=1,3
 111    VECLOC(I)=TEMP(I)
      ENDIF

cc      DO 13 I=1,NSIZE
cc 13   CELSIZ(I)=GPAR(I,NLEVEL)

      NGPAR=IQ(JGPAR+NLEVEL)
      JPAR=LQ(JGPAR-NLEVEL)
      DO I=1,NGPAR
        CELSIZ(I)=Q(JPAR+I)
      ENDDO

      RETURN
      END
