      SUBROUTINE EZERR_CHECK(STRING,RVALUE,ITYPE,TOTAL,IER)
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : This routine finds problems in RCP input
C-                         by looping over the ITYPE array that is generated by
C-                         EZZDEC. This routine is intended to be used in
C-                         EZFSIZ (RCPSIZE) where it is not desired to use
C-                         ZEBRA to actually read in the RCP file with INRCP.
C-                         This routine is intended to simulate what error
C-                         checking is done in INRCP.
C-
C-   Inputs  : STRING [C] - RCP line
C-             RVALUE [F] - Array of RCP values for the line
C-             ITYPE  [I] - Array of variable types for the line
C-             TOTAL  [I] - Number of values in array RVALUE
C-   Outputs : IER    [I} - error code (0 if OK)
C-   Controls: none
C-
C-   Created  19-JUN-1991   Chip Stewart
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      INTEGER  ITYPE(*),TOTAL,IP,IV,IER
      INCLUDE 'D0$PARAMS:SRCP.DEF'
      REAL RVALUE(*)
      CHARACTER*132 STRING
C----------------------------------------------------------------------
C
C ****  DETERMINE IF ERROR IN RCP ARGUMENT bad argument
C
      IP = 1
      DO IV = 1, TOTAL
        IF(ITYPE(IP).LT.0) THEN         ! If ITYPE is negative then
                                        ! something bad happened
          IER = EZS_BAD_VALUE
          GOTO 999
        END IF
        IF(ITYPE(IP).GT.10) THEN
          IP = IP + (ITYPE(IP) - 7)/4   ! Loop over long character strings
        ELSE
          IP = IP + 1
        END IF
      END DO
  999 RETURN
      END
