CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VZEBRA_UTIL()
      VZEBRA_UTIL = ' ZEBRA_UTIL'//
     X                   '  OFFICIAL V3.29'//
     X                   ' 11-JUL-1997 12:42:09.79'
      Return
      End
