      SUBROUTINE ACP_OPEN(FDSCRP,ACCESS,FILE,ISEQ,TAPE,NSTAT)
C Modified: 16-JUL-1992 Kirill Denisenko
      IMPLICIT NONE
      INCLUDE 'D0$PARAMS:ACPDEF.PARAMS'
      INCLUDE 'D0$INC:ACP_USER.INC'
      INCLUDE 'D0$INC:ACPOUT.INC'

      INTEGER FDSCRP,NSTAT,ISEQ,RBSTATUS
      LOGICAL TAPE

      CHARACTER*40 TDRIVE
      CHARACTER*(*) ACCESS

C Variables associated with RBIO package
      CHARACTER*160 NAME
      CHARACTER*70 OFILE
      CHARACTER*(*) FILE
      CHARACTER*1 NULL

      NSTAT = 0
      NULL = CHAR(0)

      IF( TAPE ) THEN
        CALL RBFNAME(FDSCRP,NAME,RBSTATUS)
        CALL RBLDAS(NAME,'F','F',RBSTATUS)
        CALL RBLDAN(NAME,'S',ISEQ,RBSTATUS)
        CALL RBLDAS(NAME,'D',FILE,RBSTATUS)
        CALL RBLDAN(NAME,'B',OUTBYT,RBSTATUS)
        CALL RBLDAN(NAME,'R',OUTBYT,RBSTATUS)
        CALL ACP_SIGHOLD
        CALL RBOPEN(FDSCRP,NAME,RBSTATUS)
        CALL ACP_SIGRELEASE
        IF(RBSTATUS.NE.0) THEN
           CALL CPERROR('ACP_OPEN')
          NSTAT = -1
        ENDIF
      ELSE
        CALL ACP_SIGHOLD
        CALL RBFOPEN(FDSCRP,FILE,ACCESS,RBSTATUS)
        CALL ACP_SIGRELEASE
        IF(RBSTATUS.NE.0)  THEN
          CALL CPERROR('ACP_OPEN')
          NSTAT = -1
        ENDIF
      ENDIF

      RETURN


      ENTRY ACP_CLOSE(FDSCRP,TAPE,NSTAT)

      NSTAT = 0

      CALL ACP_SIGHOLD
      IF( TAPE ) THEN
        CALL RBCLOSE(FDSCRP,RBSTATUS)
      ELSE
        CALL RBFCLOSE(FDSCRP,RBSTATUS)
      ENDIF
      CALL ACP_SIGRELEASE

      RETURN

      END
