      SUBROUTINE FTYPE(CHRS,I,J)
      CHARACTER*(*) CHRS
      INTEGER I,J

      CALL ACP_SIGHOLD
C&IF IBMAIX
C&      OPEN(66,STATUS='UNKNOWN')
C&ELSE
      OPEN(66,ACCESS='APPEND')
C&ENDIF
      WRITE(66,101) CHRS,I
      WRITE(6,*) CHRS,I
      CLOSE(66)
      CALL ACP_SIGRELEASE
      RETURN

101   FORMAT(1X,A,2I8)
      END
