      SUBROUTINE RCPTYPE(VSN,FILE,ISEQ,NEVENT,NBLOCKS)
      CHARACTER*(*) FILE,VSN
      CHARACTER*20 RCPFILE
      CHARACTER*5 HOST
      INTEGER ISEQ,NEVENT,NBLOCKS,STAT,HLEN
      LOGICAL FIRST

      CHARACTER*26 CHT
      CHARACTER*3 MON
      CHARACTER*2 DAY
      CHARACTER*4 YEAR
      CHARACTER*8 TM
      CHARACTER*20 DATE
      INTEGER  TIME,STIME
      DATA HLEN /5/
      DATA FIRST /.TRUE./
      SAVE FIRST

      STIME = TIME()
      CALL CCTIME(STIME,CHT)
      DAY = CHT(9:10)
      MON = CHT(5:7)
      YEAR = CHT(21:24)
      TM = CHT(12:19)
      DATE = DAY//'-'//MON//'-'//YEAR//' '//TM
      RCPFILE = VSN//'.rcpdat'

      CALL ACP_SIGHOLD
C&IF IBMAIX
C&      OPEN(77,FILE=RCPFILE,STATUS='UNKNOWN')
C&ELSE
      OPEN(77,FILE=RCPFILE,ACCESS='APPEND')
C&ENDIF
      IF(FIRST) THEN
        STAT = CGETHOSTNAME(HOST,%VAL(HLEN))
        WRITE(77,*) 'HOST:	',HOST
        FIRST = .FALSE.
      ENDIF
      WRITE(77,101) VSN,ISEQ,FILE,NEVENT,NBLOCKS,DATE
      CLOSE(77)
      CALL ACP_SIGRELEASE
      RETURN

101   FORMAT(1X,A,I6,5X,A,2I8,5X,A)
      END
