CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VCALOR_OFF()
      VCALOR_OFF = ' CALOR_OFF'//
     X                   '  TEST V1.60_02'//
     X                   ' 10-JUN-1998 10:46:22.24'
      Return
      End
