CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VCALOR_OFF()
      VCALOR_OFF = ' CALOR_OFF'//
     X                   '  OFFICIAL V1.60'//
     X                   ' 14-JUL-1997 09:21:50.31'
      Return
      End
