      FUNCTION L2_VERT
C----------------------------------------------------------------------
C-
C-   PURPOSE AND METHODS : ROUTINE FOR RETURNING VERTEX USED IN LEVEL 2
C-        IF THE INFORMATION IN THE RELEVANT BANKS IS NOT ALREADY AVAILABLE FOR
C-        THIS EVENT, IT IS CREATED.
C-        AS A SIDE EFFECT, THE CHOSEN VERTEX IS ENTERED IN ESUM
C-
C-   RETURNED VALUE  : VERTEX POSTION USED BY LEVEL 2 
C-   INPUTS  : NONE
C-   OUTPUTS : NONE
C-   CONTROLS: 
C-
C-   CREATED  25-JUN-1992   AMBER S. BOEHNLEIN
C-   UPDATE   18-OCT-1993   TOM FAHLAND: ADDED THE CDC VERTEX CODE AND
C-                          EXTENDED OPTIONS BY ADDING ENTRY POINTS
C-                          TO USE ONLY NOMINAL, OR L0 VERTEX
C-   UPDATE   14-JUN-1994   R. MARKELOFF: SPURIOUS CALL TO EZRSET ON RETURN
C-   Updated  22-MAR-2004   sss - compile with g77
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$PARAMS:ESUM.PARAMS'
      REAL    L2_VERT,FZPOS,SZPOS,L2_VERT_L0,L2_VERT_NOMINAL
      REAL    FASTZ,SLOWZ,NOMINAL_VERTEX,VERTEX
      INTEGER ISHFT,FAST_FLAG,SLOW_FLAG,FLAG_WORD,MI_FLAG,
     &        IER,IPAR,USE_CDC_VERTEX_FOR(15)
      LOGICAL OK,USE_NOMINAL,CDC_CHOICE,FGOOD,
     &        SGOOD,USE_CDC,FIRST,USE_FASTZ
      DATA FIRST/.TRUE./
C----------------------------------------------------------------------
CC CHECK TO SEE IF NOMINAL VERTEX IS TO BE USED 
      L2_VERT=0.0
C
      IF (FIRST) THEN
        FIRST=.FALSE. 
        CALL GET_LUMINOSITY_PARAMETER(IPAR)
        CALL EZPICK('L2_VERT')
        CALL EZGET_l('USE_NOMINAL',USE_NOMINAL,IER)
        CALL EZGET_l('USE_FASTZ',USE_FASTZ,IER)
        CALL EZGET_l('USE_CDC',USE_CDC,IER)
        CALL EZGET('NOMINAL_VERTEX',NOMINAL_VERTEX,IER)
        CALL EZGET_iarr('USE_CDC_VERTEX_FOR',USE_CDC_VERTEX_FOR,IER)
        CALL EZRSET
        IF (IPAR.EQ.0) THEN       ! COOR HAS SENT NO LUMSET#
          USE_CDC = .FALSE.       ! DO NOT RUN CDC VERTEXING 
        ENDIF
      ENDIF
C
      IF (USE_NOMINAL) THEN
        L2_VERT=NOMINAL_VERTEX              
        FLAG_WORD=4
        GOTO 999 
      ENDIF
CC--------------------------------
CC-  USE FASTZ IF RCP SAYS TO DO SO
      IF (USE_FASTZ) THEN
        CALL GTL0VT(FASTZ,FAST_FLAG,SLOWZ,SLOW_FLAG,OK)
        IF (OK) THEN
          IF (FAST_FLAG.EQ.1) THEN
            FLAG_WORD = 3
            L2_VERT = FASTZ              ! CONTAINS DEFAULT VERTEX EVEN IF NO L0
            GOTO 999
          ENDIF
        ELSE
            L2_VERT=NOMINAL_VERTEX
            FLAG_WORD=4
            GOTO 999
        ENDIF
      ENDIF

CC--------------------------------
      IF (USE_CDC) THEN
        CALL  L2_L0_VERTEX( FZPOS, FGOOD, SZPOS, SGOOD, MI_FLAG )
        IF (MI_FLAG.GE.USE_CDC_VERTEX_FOR(IPAR))THEN 
          CALL L2_VERTEX_CDC(CDC_CHOICE,VERTEX)
          L2_VERT=VERTEX
          FLAG_WORD=1
          GOTO 999
        ELSE 
          GOTO 998
        ENDIF 
      ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC  LEVEL 0 PART OF CODE, WILL FIND SLOWZ IF EXIST, OR ELSE FATSZ
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 998  CONTINUE
      CALL GTL0VT(FASTZ,FAST_FLAG,SLOWZ,SLOW_FLAG,OK)
      FLAG_WORD = 0
      IF (OK) THEN
        L2_VERT = FASTZ              ! CONTAINS DEFAULT VERTEX EVEN IF NO L0
        IF (FAST_FLAG.EQ.1) THEN
          FLAG_WORD = 3
        ENDIF
        IF (SLOW_FLAG.GT.0) THEN
          L2_VERT = SLOWZ              !BUT USE SLOW IF IT EXISTED AT ALL
          FLAG_WORD=2
CC          FLAG_WORD = ISHFT(SLOW_FLAG,4) ! CODES 2-8 IN 2ND HEX DIGIT FOR SLOZ
        ENDIF
        GOTO 999
      ENDIF
      CALL EZPICK('L2_VERT')
      CALL EZGET_l('USE_NOMINAL',USE_NOMINAL,IER)
      CALL EZRSET
      IF (IER.EQ.0) THEN
          L2_VERT=NOMINAL_VERTEX              
          FLAG_WORD=4
          GOTO 999 
      ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
  999 CONTINUE
      CALL ESUMFL('FILT',ID_VERTEX,0.0,0.0,0.0,L2_VERT,FLAG_WORD)
 1000 RETURN
C######################################################################
      ENTRY L2_VERT_NOMINAL
      IF (FIRST) THEN
        FIRST=.FALSE. 
        CALL GET_LUMINOSITY_PARAMETER(IPAR)
        CALL EZPICK('L2_VERT')
        CALL EZGET_l('USE_NOMINAL',USE_NOMINAL,IER)
        CALL EZGET_l('USE_CDC',USE_CDC,IER)
        CALL EZGET('NOMINAL_VERTEX',NOMINAL_VERTEX,IER)
        CALL EZGET_iarr('USE_CDC_VERTEX_FOR',USE_CDC_VERTEX_FOR,IER)
        CALL EZRSET
      ENDIF
      L2_VERT=0.0
      IF (IER.EQ.0) THEN
        L2_VERT_NOMINAL=NOMINAL_VERTEX              
      ENDIF 
      RETURN 
C#####################################################################33
      ENTRY L2_VERT_L0
      IF (FIRST) THEN
        FIRST=.FALSE. 
        CALL GET_LUMINOSITY_PARAMETER(IPAR)
        CALL EZPICK('L2_VERT')
        CALL EZGET_l('USE_NOMINAL',USE_NOMINAL,IER)
        CALL EZGET_l('USE_CDC',USE_CDC,IER)
        CALL EZGET('NOMINAL_VERTEX',NOMINAL_VERTEX,IER)
        CALL EZGET_iarr('USE_CDC_VERTEX_FOR',USE_CDC_VERTEX_FOR,IER)
        CALL EZRSET
      ENDIF
      CALL GTL0VT(FASTZ,FAST_FLAG,SLOWZ,SLOW_FLAG,OK)
      FLAG_WORD = 0
      IF (OK) THEN
        L2_VERT_L0 = FASTZ              ! CONTAINS DEFAULT VERTEX EVEN IF NO L0
        IF (FAST_FLAG.EQ.1) THEN
          FLAG_WORD = 1
        ENDIF
        IF (SLOW_FLAG.GT.0) THEN
          L2_VERT_L0 = SLOWZ              !BUT USE SLOW IF IT EXISTED AT ALL
          FLAG_WORD = ISHFT(SLOW_FLAG,4) ! CODES 2-8 IN 2ND HEX DIGIT FOR SLOZ
        ENDIF
      ELSE
        L2_VERT_L0=NOMINAL_VERTEX              
      ENDIF
      RETURN
C
      END
