PACKAGE := cdc_util
$(PACKAGE)_LIB := yes
include GNUmakefile.subcommon

CDC_UTIL_NO_RANGE_CHECK := bkt0th prt0rw prrtst cdchit_strip cdchit_cell cdchit_hits
$(foreach f,$(CDC_UTIL_NO_RANGE_CHECK),tmp/DEB/cdc_util/source/$(f).o tmp/OPT/cdc_util/source/$(f).o) : FORT_COMMON_FLAGS += -fno-range-check
