CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VCDC_UTIL()
      VCDC_UTIL = ' CDC_UTIL'//
     X                   '  OFFICIAL V1.15'//
     X                   ' 14-JUL-1997 14:45:32.18'
      Return
      End
