      INTEGER FUNCTION IDCHRG(ID)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCC    RETURNS CHARGE OF PARTICLE FOR GIVEN ISAJET ID
CCC    OUTPUT = -1,0,-1 (ALL NON-STABLE RETURNS 0)  
CCC    DOES E,MU,PI,K,P               
CCC    HEDIN 5-87
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
       IMPLICIT NONE
       INTEGER ID
       IDCHRG=0
       IF(ID.EQ.12.OR.ID.EQ.14.OR.ID.EQ.-120.OR.ID.EQ.
     A -130.OR.ID.EQ.-1120) IDCHRG=-1
       IF(ID.EQ.-12.OR.ID.EQ.-14.OR.ID.EQ.120.OR.ID.EQ.
     A 130.OR.ID.EQ.1120) IDCHRG=1      
       RETURN
       END
