C==================================================================
      SUBROUTINE ISZ2D
C==================================================================
C
C  Description:  Displays tracks generated by ISAJET (2D view)
C
C  Author:
C  =======
C  Tami Kramer
C
C  Revision History:
C  ==================
C  Original Creation - November 23,1988
C
C===================================================================
C
      IMPLICIT NONE
      INCLUDE 'D0$INC:GRAPHF77.INC'
C
C  Local Declarations:
C  ====================
C
      INTEGER I,J             ! Loop variables
      INTEGER IDCHRG          ! DH function
      INTEGER I3D             ! Calling mode indicator for ISZEVT
      INTEGER SI              ! Max no. of particles
      PARAMETER(SI=1000)
      INTEGER ID(SI)          ! ID of particles returned from GIPART
      INTEGER NPART           ! Actual no. of parts returned from GIPART
      INTEGER ICHRG           ! =1 charged track, =0 neutral track
      INTEGER NMENU,IMES,ACT
      INTEGER GRFON,GRFINT
      INTEGER ITHMIN,IPMIN,IPTMIN
      INTEGER XYZPT
      REAL PX(SI),PY(SI)      ! XYZ components of momentum
      REAL PZ(SI)
      REAL P(SI)              ! Total momentum
      REAL M(SI)              ! Mass of particle
      REAL PHI(SI)            
      REAL THETA(SI),ETA(SI)  ! Angles of particle
      REAL X(SI),Y(SI),Z(SI)  ! XYZ space position of particle
      REAL THMIN,THMDE        ! Min. theta in radians and degrees
      REAL PMIN,PTMIN         ! Cuts on min P and Pt
      REAL PT(SI)             ! Calculated Pt of track
      REAL PI                 ! 3.1416
      REAL PTMAX              ! Max Pt of all particles - used to set
C                             ! windows for graphics.
C  Executable Code:
C  ================
C
      CALL GIPART(NPART,ID,PX,PY,PZ,P,M,PHI,THETA,ETA,X,Y,Z)
C
      CALL PUGETV('XYZ OR PT SPACE',XYZPT)
      IF (XYZPT .EQ. 1) CALL ISZPT2(NPART,ID,PX,PY,PZ,P,THETA)
      IF (XYZPT .NE. 1) THEN
         I3D = 0
         CALL ISZXYZ(NPART,ID,PX,PY,PZ,X,Y,Z,P,THETA,I3D)
      ENDIF
C
      RETURN
      END
C
