      SUBROUTINE PLTCYL(XS, YS, ZS, NS)
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : Draw a 3D Cylinder Bounded by 4 edges 
C-          in the zy plane. The vectors XS, etc are dimensioned 
C-          (2, 5) and could be (but need not be) generated by 
C-          MODVEC to describe a cylindrical shape.  It is assumed
C-          that vectors numbered 1, 2, 3, 4 correspond to the 'yz'
C-          cross-section of the cylinder.  The radius of the 
C-          cylinder is taken from YS(1,i).  XS(1,i) is assumed to 
C-          be zero.  XS(i,5), YS(i,5) contain the deviation of the
C-          front(i=1), back(i=2) planes from being centered on the
C-          Z-axis.
C-
C-   Inputs  :     XS      2 x NS X-vector  describing the begin and end
C-                         points of an edge
C-                 YS      Y-vector
C-                 ZS      Z-vector
C-                 NS      number of edges should be 4
C-   Outputs :     NONE
C-   Controls:     NONE
C-
C-   Modified 01-FEB-1990   Nobu Oshima(Use J3PLGN, when NS=12)
C-   Created  24-APR-1989   Stephen Kahn
C-   Updated  23-MAR-2004   compile with g77.
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
C
      INTEGER  NS, I, J
      REAL XS(4,NS), YS(4,NS), ZS(4,NS)
      REAL XPF(4), YPF(4), ZPF(4), XPB(4), YPB(4), ZPB(4)
C
C---
        DO 150 I = 1, 4                    ! first plot upper yz section
          CALL J3MOVE(XS(1,I), YS(1,I), ZS(1,I))
          CALL JR3DRA(XS(2,I)-XS(1,I),YS(2,I)-YS(1,I),ZS(2,I)-ZS(1,I))
  150   CONTINUE
C
        DO 160 I = 1, 4                    ! second plot lower yz section
          CALL J3MOVE(XS(1,I), -YS(1,I), ZS(1,I))
          CALL JR3DRA(XS(2,I)-XS(1,I),YS(1,I)-YS(2,I),ZS(2,I)-ZS(1,I))
  160   CONTINUE
C
        CALL JCIRCL(XS(1,5),YS(1,5),ZS(1,1),YS(1,1), 1)    ! inner front
        CALL JCIRCL(XS(1,5),YS(1,5),ZS(2,1),YS(2,1), 1)    ! outer front
        CALL JCIRCL(XS(2,5),YS(2,5),ZS(4,1),YS(4,1), 1)    ! inner back
        CALL JCIRCL(XS(2,5),YS(2,5),ZS(3,1),YS(3,1), 1)    ! outer back
C
               
C-
  999 RETURN
      END
