      SUBROUTINE CLUMIX(XCUT,ENER,XINT)
C----------------------------------------------------------------------
C-
C-   PURPOSE AND METHODS : FIRST AND FAST MERGING OF THE TRD CLUSTERS
C-  DIVIDE THE DRIFT DISTANCE IN BINS 'BINCM' WIDE AND LOOK FOR THE BIN
C-  IN WHICH THE NEW DELTA RAY LIES
C-
C-   OUTPUTS :
C-
C-   CREATED                A. ZYLBERSTEJN
C-   Updated  12-SEP-1988   A. ZYLBERSTEJN
C-   Updated  19-SEP-1988   J.R. HUBBARD/A. ZYLBERSTEJN
C-   Updated  11-OCT-1988   J.R. HUBBARD     Use S/R CLUCLE
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:CLUSM.INC/LIST'
      INCLUDE 'D0$INC:WORKSP.INC/LIST'
      INTEGER IINT,J
      REAL ENER,ESUP,EX,XINT,XCUT
      DATA ESUP/15./
C
      IINT = XINT/XCUT + 1.
      IF ( ENER.GT.ESUP )    GOTO 70
      IF ( NSMEAR.LT.1 )     GOTO 70
C
C  LOOK IF THERE ARE OTHER DELTA RAYS IN THE SAME BIN
C
      DO 60 J=1,NSMEAR
        IF ( ECLES(J).GT.ESUP ) GOTO 60
        IF(ABS(XINT-XCLES(J)).GT.XCUT)GO TO 60
C      IF(IPRNT.EQ.1)
C     + WRITE(LOUT,*)' DANS CLUMIX,J',J,' XINT',XINT,'XCLES(J)',XCLES(J)
C     +,' ENER,ECLES(J)',ENER,ECLES(J)
        EX = ECLES(J) + ENER
        XCLES(J) = (XINT*ENER+ECLES(J)*XCLES(J))/EX
        ECLES(J) = EX
        GOTO 100
   60 CONTINUE
   70 CONTINUE
      IF(NSMEAR.GE.LENGS) CALL CLUCLE(NSMEAR-LENGS+1)
      NSMEAR = NSMEAR + 1
      ECLES(NSMEAR) = ENER
      XCLES(NSMEAR) = XINT
      TIMEC(NSMEAR) = 0.
      YCLES(NSMEAR) = 0.
      IWS(NSMEAR) = IINT
      IESCAP(NSMEAR) = 0
  100 CONTINUE
      RETURN
      END
