      SUBROUTINE EDEGEN(GAMMA,DEDX)
C
C  GENERATE A RANDOM IONISATION ENERGY LOSS FROM PRE-CALCULATED TABLES
C
      IMPLICIT NONE
C
      INCLUDE 'D0$INC:D0LOG.INC/LIST'
      INCLUDE 'D0$INC:GCUNIT.INC/LIST'
C
      REAL GAMMA,DEDX
      INTEGER IREF,I
      INCLUDE 'D0$INC:DISDEL.INC/LIST'
C  LOOK FOR THE BIN IN GAMMA
      IF(GAMMA.GE.GADREF(NGAMD))THEN
        IREF=NGAMD
        GO TO 100
      END IF
      IF(GAMMA.LE.GADREF(1))THEN
        IREF=1
        GO TO 100
      END IF
      DO 20 I=1,NGAMD
        IF(GAMMA.GT.GADREF(I))GO TO 20
        IREF=I
        GO TO 22
   20 CONTINUE
   22 CONTINUE
C  LOOK FOR THE CLOSEST REFERENCED GAMMA
      IF(ABS(GADREF(IREF-1)-GAMMA).LT.ABS(GADREF(IREF)-GAMMA))
     +  IREF=IREF-1
      IF(DTRK.EQ.1.AND.PTRD.GT.1) THEN
        WRITE(LOUT,*)'GAMMA ',GAMMA,' GAM. REF. ',GADREF(IREF),
     +'IREF',IREF
      ENDIF
  100 CONTINUE
C      WRITE(LOUT,*)(DEDIST(I,IREF),I=1,NBDEL+1)
      CALL HISRAN(DEDIST(1,IREF),NBDEL+1,0.,1.,DEDX)
      IF(DEDX.GT.(NBDEL+1)*1.) THEN
        WRITE(LOUT,*)' ABNORMAL IONISATION LOSS',DEDX
        WRITE(LOUT,*)'IREF',IREF
      END IF
      RETURN
      END
