C EXRGEN
      SUBROUTINE EXRGEN(STET,GAMMA,DEXR)
C     ---------- ------
C
C  GENERATE A RANDOM  ENERGY DEPOSITION FOR X RAYS
C    FROM PRE-CALCULATED TABLES
C
      IMPLICIT NONE
      REAL GAMMA,STET,DEXR
      INTEGER IREF,I,JREF
C      INCLUDE 'D0$INC:DISDEL.INC/LIST'
      INCLUDE 'D0$INC:GCUNIT.INC/LIST'
      INCLUDE 'D0$INC:TABX.INC/LIST'
C
      INTEGER IG,IT,NUMB,NESSAI
      REAL EAVR,CLAVR
C NO RADIATION TRANSITION FOR ANGLES < 30 DEGREES
      IF(STET.LT.STREF(1))RETURN
C
C  LOOK FOR THE BIN IN THETA
      DO 20 I=1,NSTREF
      IF(STET.GT.STREF(I))GO TO 20
      IREF=I
      GO TO 22
  20  CONTINUE
  22  CONTINUE
C  LOOK FOR THE CLOSEST REFERENCED GAMMA
      IF(ABS(STREF(IREF-1)-STET).LT.ABS(STREF(IREF)-STET))
     +  IREF=IREF-1
C      WRITE(LOUT,*)'STET ',STET,' STET. REF. ',STREF(IREF),'IREF',IREF
C  LOOK FOR THE BIN IN GAMMA
      IF(GAMMA.GE.GAMREF(NGAREF))THEN
             JREF=NGAREF
             GO TO 100
      END IF
      IF(GAMMA.LE.GAMREF(1))THEN
             JREF=1
             GO TO 100
      END IF
      DO 40 I=1,NGAREF
      IF(GAMMA.GT.GAMREF(I))GO TO 40
      JREF=I
      GO TO 42
  40  CONTINUE
  42  CONTINUE
C  LOOK FOR THE CLOSEST REFERENCED GAMMA
      IF(ABS(GAMREF(JREF-1)-GAMMA).LT.ABS(GAMREF(JREF)-GAMMA))
     +  JREF=JREF-1
C      WRITE(LOUT,*)'GAMMA ',GAMMA,' GAM. REF. ',GAMREF(JREF),'JREF',JREF
  100 CONTINUE
C      WRITE(LOUT,*)(PROBX(I,IREF,JREF),I=1,NBINE)
      CALL HISRAN(PROBX(1,IREF,JREF),NBINE,0.,1.,DEXR)
      IF(DEXR.GT.(NBINE+1)*1.)THEN
               WRITE(LOUT,*)' ABNORMAL TRANSITION RADIATION ENERGY',DEXR
               WRITE(LOUT,*)'IREF',IREF,' JREF',JREF
      END IF
      RETURN
      END
