      SUBROUTINE RWXSPC(IK)
C----------------------------------------------------------------------
C-
C-   Purpose and Methods :
C-   READ OR WRITE TRANSITION X RAYS DIFFERENTIAL ENERGY SPECTRUM
C-
C-   Inputs  :
C-   Outputs :
C-   Controls:
C-
C-   Created                A. ZYLBERSTEJN
C-   Updated  19-SEP-1988   J.R. HUBBARD/A. ZYLBERSTEJN
C-   Updated  21-FEB-1989   A. Zylberstejn
C-   Updated  19-JUL-1989   A. Zylberstejn
C-
C----------------------------------------------------------------------
C
      IMPLICIT NONE
      INCLUDE 'D0$INC:GCONST.INC/LIST'
      INCLUDE 'D0$INC:GCUNIT.INC'
      INCLUDE 'D0$INC:RADDSC.INC'
      INCLUDE 'D0$INC:TABX.INC/LIST'
      INCLUDE 'D0$INC:XRAY.INC/LIST'
      INTEGER IUNIT,IER
C
      INTEGER IK,IT,IG,I
      REAL TET,VS,VSUM
C
      CALL GTUNIT(70,IUNIT,IER)
      IF(IK.EQ.1)THEN !WE WRITE THE TABLES
        OPEN(FILE='XRSPECT',UNIT=IUNIT,STATUS='NEW')
C        WRITE THE TABLES
        WRITE(IUNIT,'(I4,2G10.4)')NSTEP,EDOWN,XSTEP
        WRITE(IUNIT,'(I4,4G10.4)')NFOIL,XGAP,XFOIL,DXGAP,DXFOIL
C        PRINT*,' NSTREF,NGAREF',NSTREF,NGAREF
        DO 8 IT=1,NSTREF
          TET=ASIN(STREF(IT))*RADDEG
          DO 4  IG=1,NGAREF
C            PRINT*,' IT,IG,GAMREF,XNUMB',TET,GAMREF(IG),XNUMB(IT,IG)
            WRITE(IUNIT,'(3G10.4)')TET,GAMREF(IG),XNUMB(IT,IG)
            WRITE(IUNIT,'(10F7.4)')(100.*PROBX(I,IT,IG),I=1,NSTEP)
    4     CONTINUE
    8   CONTINUE
      ELSE              !WE READ THE TABLES
C       READ THE TABLES
C&IF VAXVMS,VAXELN,UFFARM,SIUNIX,ULTRIX,SUNOS,ALFOSF
        OPEN(FILE='XRSPECT',UNIT=IUNIT,STATUS='OLD',READONLY)
C&ENDIF
C&IF ETA10,IBMAIX
C&        OPEN(FILE='XRSPECT',UNIT=IUNIT,STATUS='OLD')
C&ENDIF
        READ(IUNIT,'(I4,2G10.4)')NSTEP,EDOWN,XSTEP
        READ(IUNIT,'(I4,4G10.4)')NFOIL,XGAP,XFOIL,DXGAP,DXFOIL
        WRITE(LOUT,1037)NFOIL,XGAP, XFOIL,DXGAP,DXFOIL
 1037   FORMAT(' RADIATOR: NB. OF FOILS:',I4,' XGAP',G12.4,' XFOIL',
     &    G12.4,' DXGAP',G12.4,' DXFOIL',G12.4)
        DO 14 IT=1,NSTREF
          DO 12 IG=1,NGAREF
            READ(IUNIT,'(3G10.4)')TET,GAMREF(IG),XNUMB(IT,IG)
            TET=TET*DEGRAD
            STREF(IT)=SIN(TET)
            READ(IUNIT,'(10F7.4)')(PROBX(I,IT,IG),I=1,NSTEP)
   12     CONTINUE
   14   CONTINUE
      END IF
C
      CLOSE(IUNIT)  ! CLOSE FILE
      CALL RLUNIT(70,IUNIT,IER)
C
      RETURN
 2000 FORMAT(3G10.4)
 2002 FORMAT(10F7.4)
 2200 FORMAT(' TETA',F7.1,' GAMREF',F7.0,' XNUMB',G10.4)
      END
