C DEC/CMS REPLACEMENT HISTORY, Element TRABSL.FOR
C *2    20-FEB-1987 12:45:00 A.Z. CHANGED THE SUBROUTINE NAME FROM ABKUR
C *1    15-JAN-1987 12:30:41 JONCKHEERE "New TRD routines"
C DEC/CMS REPLACEMENT HISTORY, Element TRABSL.FOR
      FUNCTION TRABSL(E1,GAS,N)
C     ---------=====
C  COMPUTATION OF ABSORPTION LENGTHS FOR X RAYS BY INTERPOLATION
C  IN ARRAY GAS (TABULATED IN TRDFMY)
C
      IMPLICIT NONE
C
      INTEGER IFOIS,I,N
      REAL TRABSL,AEH,AEL,AXMH,AXML,E1,F,FM,S1,S2
      REAL GAS(101)
C
      DATA IFOIS/0/
C
      IFOIS=IFOIS+1
C
        DO     100     I = 1,N,4
        AEH = GAS(I+3)
        IF(E1.LE.AEH)    GO TO 200
100     CONTINUE
200     AEL  = GAS(I+1)
        AXMH = GAS(I+4)
        AXML = GAS(I+2)
        AEH  = ALOG10(AEH)
        AEL  = ALOG10(AEL)
        AXMH = ALOG10(AXMH)
        AXML = ALOG10(AXML)
        F   = ALOG10(E1)
        FM = AXML + ( (AXML-AXMH) / (AEL-AEH) ) * (F-AEL)
        TRABSL = ( 10.**FM )
C        WRITE(16, 9000)TRABSL
C      PRINT *,'DANS TRABSL,E1,N',E1,N,' TRABSL',TRABSL
 9000 FORMAT(' EXIT TRABSL AVEC LA VALEUR ',G10.4)
C
      RETURN
      END
