      SUBROUTINE J_FORCE
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      LOGICAL DISCARD
      IF(HCPY) THEN
        CALL DEV_FORCE
      ELSE
C!!!    CALL X$SYNC(VD_ID,0)
C!!!    CALL X$SYNC(VD_ID,DISCARD)
        CALL X$FLUSH(VD_ID)
      ENDIF
      END
