      SUBROUTINE J_COORDS
C  PARAMETERS FOR CONVERSION TO SCREEN COORDINATES
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
C  FOR CONVERSION TO VIEWPORT COORDINATES
      DVX=VXMAX-VXMIN
      DU=UMAX-UMIN
      IF(DU.EQ.0.) DU=1.
      XSCALE=DVX/DU
      DVY=VYMAX-VYMIN
      DV=VMAX-VMIN
      IF(DV.EQ.0.) DV=1.
      YSCALE=DVY/DV
C  FOR CONVERSION TO DEVICE COORDS
      DX=WIDTH-2.*XMARG
      DCX=VCXMX-VCXMN
      IF(DCX.EQ.0.) DCX=1.
      XSCALS=DX/DCX
      DY=HEIGHT-2.*YMARG
      DCY=VCYMX-VCYMN
      IF(DCY.EQ.0.) DCY=1.
      YSCALS=DY/DCY
C  DONE, NOW TRIGGER
      IMDEV=1
      ITRANS=1
      END
