      SUBROUTINE JFSOPN(CODE,DSPDEV,LUN,FILNAM)
      INTEGER CODE,DSPDEV,LUN
      CHARACTER*(*) FILNAM
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(DSPDEV.NE.2.OR.CODE.NE.3)RETURN
      IUNIT=LUN
      IF(LUN.EQ.0) IUNIT=33
      FILENAM=FILNAM
      END
