      SUBROUTINE JJUST(IHORIZ,IVERT)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(.NOT.VISBL) GO TO 800
      IHJUST=IHORIZ
      IVJUST=IVERT
  800 IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IJJUST,IHORIZ)
      CALL J_PUTSG(-IJJUST,IVERT)
      END
