      SUBROUTINE JPAUSE(I)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(HCPY) RETURN
      ACCEPT 10,II
   10 FORMAT(O)
C  DO THE MOUSE MENU
C      CALL J_RZP3D
      IF(II.EQ.1)STOP
      END
