      SUBROUTINE JT2ALL(NAME,PX,PY,SX,SY,ROTANG,TX,TY)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(NSEGS.EQ.0) GO TO 1000
      DO 10 I=1,NSEGS
        ISEG=I
        IF(NAME.EQ.NUMSEG(I)) GO TO 20
   10 ENDDO
      GO TO 1000
   20 PXSEG(ISEG)=PX
      PYSEG(ISEG)=PY
      SXSEG(ISEG)=SX
      SYSEG(ISEG)=SY
      ROTSEG(ISEG)=ROTANG
      TXSEG(ISEG)=TX
      TYSEG(ISEG)=TY
      RETURN
 1000 WRITE(JUNIT,*) ' NO SUCH SEGMENT EXISTS',NAME
      END
