      SUBROUTINE JRMOVE(X,Y)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      XPOSN=XPOSN+X
      YPOSN=YPOSN+Y
      IF(HCPY) THEN
        CALL DEV_MOVE(XPOSN,YPOSN,0.)
        RETURN
      ENDIF
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IRMOVE,X)
      CALL J_PUTSG(-IRMOVE,Z)
      END
