      SUBROUTINE J_PLOT_ARRAY(NN,XX,YY)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      REAL XX(*),YY(*)
      INCLUDE 'SYS$LIBRARY:DECW$XLIBDEF.FOR'
      RECORD/X$POINT/PT_ARR(2000)
      NMX=NN
      IF(NMX.GT.2000) NMX=2000
      DO II=1,NMX
        CALL J_TRDEV(XX(II),YY(II),XP,YP)
        IF(XP.LT.0.) XP=0.
        IF(XP.GT.WIDTH) XP=WIDTH
        IF(YP.LT.0.) YP=0.
        IF(YP.GT.HEIGHT) YP=HEIGHT
        PT_ARR(II).X$W_GPNT_X=XP
        PT_ARR(II).X$W_GPNT_Y=HEIGHT-YP
      ENDDO
      IATNOW=ATB(IATB)
      IF(IATB.EQ.IPLGN.AND.ICOTYP.EQ.1) THEN
        CALL X$FILL_POLYGON(VD_ID,WD_ID,IATNOW,PT_ARR,NN,
     &           X$C_COMPLEX,X$C_COORD_MODE_ORIGIN)
      ELSE
        CALL X$DRAW_LINES(VD_ID,WD_ID,IATNOW,PT_ARR,NN,
     &           X$C_COORD_MODE_ORIGIN)
      ENDIF
      END
