      SUBROUTINE J_GETSTR(IX,LEN,STRING)
C  GET CHARACTER STRING FROM SEGMENT STORAGE
      CHARACTER*(*) STRING
      CHARACTER*120 STR
      INTEGER*4 ISTR(30)
      EQUIVALENCE (STR,ISTR)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      LEN=IBLOC(IX)
      IX=IX+1
      IF(LEN.EQ.0) RETURN
      NWDS=(LEN-1)/4+1
      DO I=1,30
        ISTR(I)=0
      ENDDO
      DO I=1,NWDS
        ISTR(I)=IBLOC(IX)
        IX=IX+1
      ENDDO
      STRING=STR
      END
