      LOGICAL FUNCTION J_TTYNW(CHR,ICTRL)
C READS ONE CHARACTER FROM THE TERMINAL LOOKAHEAD BUFFER.  NO ECHO.
      INTEGER STATUS,TCHAR,KB_ID
      CHARACTER*1 CHR
      INCLUDE '($SMGDEF)'
      STATUS=SMG$CREATE_VIRTUAL_KEYBOARD(KB_ID,'SYS$INPUT:')
C THE 0 BELOW IS THE TIMEOUT.  ONLY THE LOOKAHEAD BUFFER IS READ (NO WAIT)
      STATUS=SMG$READ_KEYSTROKE(KB_ID,TCHAR,,0,)
      IF(TCHAR.LT.32.OR.TCHAR.GT.127) GO TO 999
      CHR=CHAR(TCHAR)
      IF(TCHAR.EQ.127) GO TO 1000
      TTYNW=.TRUE.
  998 STATUS=SMG$DELETE_VIRTUAL_KEYBOARD(KB_ID)
      RETURN
  999 TTYNW=.FALSE.
      ICTRL=TCHAR
      GO TO 998
 1000 TTYNW=.FALSE.
      ICTRL=TCHAR
      END
