      SUBROUTINE NONSTANDARD(ICODE)
C  ENABLE OR DISABLE NONSTANDARD FEATURES OF THE EMULATOR
C       ICODE   1 - STROKE FONTS ONLY (DEFAULT)
C               2 - HARDWARE FONTS ENABLED
C               3 - ROTATE-PAN-ZOOM MENU OFF (DEFAULT)
C               4 - ROTATE-PAN-ZOOM MENU ON IN JPAUSE
C               5 - NORMAL RETAINED SEGMENT STORAGE (JROPEN)
C               6 - TEMPORARY SEGMENTS ONLY (INCLUDING JROPEN)
      IF(ICODE.LT.1.OR.ICODE.GT.6) RETURN
      GO TO (10,20,30,40,50,60) ICODE
   10 STFONT=.TRUE.
      RETURN
   20 STFONT=.FALSE.
      RETURN
   30 RZPOFF=.TRUE.
      RETURN
   40 RZPOFF=.FALSE.
      RETURN
   50 SEGENA=.TRUE.
      RETURN
   60 SEGENA=.FALSE.
      RETURN
      END
