      SUBROUTINE JLSTYL(LSTYL)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      ILSTYL=LSTYL
      IF(PUTS) CALL J_PUTSG(-IJSTYL,ILSTYL)
      LL=MOD(LSTYL,10)+1
      IF(HCPY) THEN
        CALL DEV_SETLIN(LSTYL)
        RETURN
      ENDIF
      IATB=ILINE
      GO TO (1,2,3,4,5,6,7,8,9,10)LL
    1 CALL J_SET_LINE_STYLE('FFFFFFFF'X)
      RETURN
    2 CALL J_SET_LINE_STYLE('F0F0F0F0'X)
      RETURN
    3 CALL J_SET_LINE_STYLE('55555555'X)
      RETURN
    4 CALL J_SET_LINE_STYLE('F5F5F5F5'X)
      RETURN
    5 CALL J_SET_LINE_STYLE('33333333'X)
      RETURN
    6 CALL J_SET_LINE_STYLE('FF00FF00'X)
      RETURN
    7 CALL J_SET_LINE_STYLE('FF33FF33'X)
      RETURN
    8 CALL J_SET_LINE_STYLE('FFF5FFF5'X)
      RETURN
    9 CALL J_SET_LINE_STYLE('FFF0FFF0'X)
      RETURN
   10 CALL J_SET_LINE_STYLE('FFFFFFF0'X)
      RETURN
      END
