      SUBROUTINE JINTEN(INTEN)
C  SET THE INTENSITY
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(.NOT.VISBL) GO TO 800
      IINTEN=INTEN
  800 IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(-IJINTN,INTEN)
      END
