      SUBROUTINE JCIRCL(X0,Y0,Z0,R,NSG)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
C!!!!SHOULD STORE PARAMETERS IN SEGMENT STORAGE, NOT SIDES
C  SET THIS UP AS A POLYGON IN SCRATCH SO THAT
C  IT FILLS ON CLOSE.
      IF(NSG.GE.1)THEN
        NS=NSG
      ELSE
C  DEFAULT NUMBER OF SIDES
        NS=100
      ENDIF
   10 DPHI=2.*3.14159/NS
      CSD=COS(DPHI)
      SND=SIN(DPHI)
      CS=1.
      SN=0.
      DO I=1,NS
        CSPR=CS*CSD-SN*SND
        SNPR=SN*CSD+CS*SND
        XPOLY(I)=X0+R*CSPR
        YPOLY(I)=Y0+R*SNPR
        ZPOLY(I)=Z0
        CS=CSPR
        SN=SNPR
      ENDDO
      CALL J3PLGN(XPOLY,YPOLY,ZPOLY,NS)
      END
