      SUBROUTINE JDETEC(NAME,DETVAL)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      INTEGER NAME,DETVAL
      DO 10 I=1,NSEGS
        IF(NAME.NE.NUMSEG(I)) GO TO 10
        IDETEC(I)=DETVAL
   10 ENDDO
      END
