      SUBROUTINE JSIZE(X,Y)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(X.LE.0. .OR. Y.LE.0.)THEN
C        TYPE *,' JSIZE BAD X,Y'
        RETURN
      ENDIF
      XSIZE=X
      YSIZE=Y
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IJSIZE,X)
      CALL J_PUTSG(-IJSIZE,Y)
      END
