      SUBROUTINE JR3DRA(X,Y,Z)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      XNOW=XPOSN+X
      YNOW=YPOSN+Y
      ZNOW=ZPOSN+Z
      IF(HCPY) THEN
        CALL DEV_DRAW(XNOW,YNOW,ZNOW)
        GO TO 10
      ENDIF
      CALL J_TR3XYZ(XPOSN,YPOSN,ZPOSN,XOLD,YOLD,ZOLD)
      CALL J_TR3XYZ(XNOW,YNOW,ZNOW,XNEW,YNEW,ZNEW)
      IATB=ILINE
      CALL J_LINE2(XOLD,YOLD,XNEW,YNEW)
   10 XPOSN=XNOW
      YPOSN=YNOW
      ZPOSN=ZNOW
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IR3DRA,X)
      CALL J_PUTSG(IR3DRA,Y)
      CALL J_PUTSG(-IR3DRA,Z)
      END
