      SUBROUTINE JR3MRK(X,Y,Z)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      XNOW=X+XPOSN
      YNOW=Y+YPOSN
      ZPOSN=ZPOSN+Z
      PUTSUP=.TRUE.
      CALL JMARK(XNOW,YNOW)
      PUTSUP=.FALSE.
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IR3MRK,X)
      CALL J_PUTSG(IR3MRK,Y)
      CALL J_PUTSG(-IR3MRK,Z)
      END
