      SUBROUTINE DEV_TEXT(STRING)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      CHARACTER*(*) STRING
      IF(IDV.EQ.1) THEN
        CALL PS_TEXT(STRING)
      ELSE
C        CALL TK_TEXT(STRING)
      ENDIF
      END
