      SUBROUTINE JDEVOF(IDEVI)
C --SHUT DOWN CURRENTLY ACTIVE DEVICE (OUTPUT HARDCOPY FILE FOR DEV=2)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(IDEVI.EQ.1) THEN
C!!!        CALL X$UNMAP_WINDOW(VD_ID,WD_ID)
      ELSE
        CALL J_HCOPY_END
        IDEVIC=1
      ENDIF
      END
