      SUBROUTINE JIQTXT(IDEV,CXSIZE,CYSIZE,ACTXSZ,ACTYSZ)
C  FIND ACTUAL SIZE OF FONT NEAREST TO (SMALLER THAN) DESIRED SIZE
C  ANYTHING IS POSSIBLE?
      ACTXSZ=CXSIZE
      ACTYSZ=CYSIZE
      END
