      SUBROUTINE JMOVE(X,Y)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      XPOSN=X
      YPOSN=Y
      IF(HCPY) THEN
        CALL DEV_MOVE(X,Y,0.)
        RETURN
      ENDIF
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(I2MOVE,X)
      CALL J_PUTSG(-I2MOVE,Y)
      END
