      SUBROUTINE JVSAVE(ARY)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      REAL ARY(*),RVW3(21),RVW4(14),RVW1(5),RHC4(16)
      EQUIVALENCE (RVW3,XVW),(RVW4,UMIN),(RVW1,IWCLIP)
      EQUIVALENCE (RHC4,WNX)
      DO I=1,21
        ARY(I)=RVW3(I)
      ENDDO
      DO I=1,14
        ARY(I+21)=RVW4(I)
      ENDDO
      DO I=1,5
        ARY(I+35)=RVW1(I)
      ENDDO
      DO I=1,16
        ARY(I+40)=RHC4(I)
      ENDDO
      END
