      SUBROUTINE J3MARK(X,Y,Z)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      CHARACTER*1 MARK(5)
      REAL X,Y
      DATA MARK/'.','+','*','O','X'/
      IF(.NOT.VISBL) GO TO 800
      IMRK=MOD(IMARK-1,5)+1
      IF(IMRK.LT.1) IMRK=1
      IF(IMRK.GT.5) IMRK=5
      XPOSN=X
      YPOSN=Y
      ZPOSN=Z
      IF(HCPY) THEN
        CALL DEV_MARK(X,Y,Z)
        RETURN
      ENDIF
C  SEE IF STROKE FONTS ONLY
      IF(STFONT) THEN
        CALL J_TR3XYZ(XPOSN,YPOSN,ZPOSN,XPR,YPR,ZDUMMY)
        DEL=XSIZE/2.
        IF(IMRK.EQ.1) DEL=DEL/3.
        CALL J_TR2XY(0.,0.,CENTR,DUM)
        CALL J_TR2XY(DEL,0.,DELPR,DUM)
        DELPR=DELPR-CENTR
        XLO=XPR-DELPR
        XHI=XPR+DELPR
        YLO=YPR-DELPR
        YHI=YPR+DELPR
        IATB=IFONT
        GO TO (100,200,200,100,300) IMRK
  100   CALL J_LINE2(XLO,YLO,XHI,YLO)
        CALL J_LINE2(XLO,YLO,XLO,YHI)
        CALL J_LINE2(XHI,YLO,XHI,YHI)
        CALL J_LINE2(XLO,YHI,XHI,YHI)
        RETURN
  200   CALL J_LINE2(XPR,YLO,XPR,YHI)
        CALL J_LINE2(XLO,YPR,XHI,YPR)
        IF(IMRK.EQ.3) GO TO 300
        RETURN
  300   CALL J_LINE2(XLO,YLO,XHI,YHI)
        CALL J_LINE2(XLO,YHI,XHI,YLO)
        RETURN
      ELSE
C!!!!!BELOW IS NOT QUITE RIGHT FOR JUSTIFICATION
        CALL J_TR3XYZ(XPOSN,YPOSN,ZPOSN,CRTX,CRTY,ZDUMMY)
        CALL J_TEXT(MARK(IMRK),CRTX,CRTY)
C     &  CRTX-6.,CRTY-11.)    ! CENTER JUSTIFY (SEE JMARK)
      ENDIF
  800 IF(.NOT.PUTS)RETURN
      IF(PUTSUP)RETURN
      CALL J_PUTSG(I3MARK,X)
      CALL J_PUTSG(I3MARK,Y)
      CALL J_PUTSG(-I3MARK,Z)
      END
