      LOGICAL FUNCTION J_TTYIN(CHR,ICTRL)
C  WAITS AND ACCEPTS ONE CHARACTER FROM THE TERMINAL.  NO ECHO.
      INTEGER STATUS,TCHAR,KB_ID
      CHARACTER*1 CHR
      INCLUDE '($SMGDEF)'
      STATUS=SMG$CREATE_VIRTUAL_KEYBOARD(KB_ID,'SYS$INPUT:')
      STATUS=SMG$READ_KEYSTROKE(KB_ID,TCHAR,,,)
      IF(TCHAR.LT.32.OR.TCHAR.GT.127) GO TO 999
      CHR=CHAR(TCHAR)
      IF(TCHAR.EQ.127) GO TO 1000
      TTYIN=.TRUE.
  998 STATUS=SMG$DELETE_VIRTUAL_KEYBOARD(KB_ID)
      RETURN
  999 TTYIN=.FALSE.
      ICTRL=TCHAR
      GO TO 998
 1000 TTYIN=.FALSE.
      ICTRL=TCHAR
      END
