      SUBROUTINE JBACKG(IBCOLR)
      INCLUDE 'SYS$LIBRARY:DECW$XLIBDEF.FOR'
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      RECORD /X$GC_VALUES/ XGCVL        ! gc values
      RECORD /X$COLOR/ XCOLORS(10)        ! COLOR
      IF (.NOT.IBW()) THEN
        XGCVL.X$L_GCVL_BACKGROUND=XCOLORS(IC+1).X$L_COLR_PIXEL
      ENDIF
      RETURN
      END
