      SUBROUTINE JCONWV(X,Y,Z,VX,VY)
C  CONVERT WORLD TO VIRTUAL WINDOW COORDINATES
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
C  TO ORIGIN OF UVN SYSTEM
   10 XTR=X-XVW
      YTR=Y-YVW
      ZTR=Z-ZVW
      XP=XTR
      YP=YTR
C      IF(IPROJ.NE.3)GO TO 20
C  THIS IS A PERSPECTIVE TRANSFORMATION.
C      SFACTR=VDIST/(VDIST+ZP)
C      XP=SFACTR*XP
C      YP=SFACTR*YP
   20 VX=(XP-UMIN)*XSCALE+VXMIN
      VY=(YP-VMIN)*YSCALE+VYMIN
      END
