      SUBROUTINE JLWIDE(LWIDE)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      INTEGER WIDDLE
      ILWID=LWIDE
      WIDDLE=FLOAT(LWIDE-16383)*20./16383.
      IF(WIDDLE.LT.1) WIDDLE=1
      IF(HCPY) THEN
        CALL DEV_LINEWI(WIDDLE)
        RETURN
      ENDIF
C  WIDDLE IS THE WIDTH IN PIXELS
      IATB=ILINE
      CALL J_SET_LINE_WIDTH(WIDDLE,MODE)
C  DEFAULT=16383
      IF(.NOT.PUTS) RETURN
      CALL J_PUTSG(-IJWID,ILWID)
      END
