      SUBROUTINE JEPSEG(DSPDEV,NAMARR,LENARR,ICODE)
C  PICK LIST OF SEGMENTS
      INTEGER*4 DSPDEV,NAMARR(*)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      ICD=ICODE+1
      IF(ICD.LT.1.OR.ICD.GT.4)RETURN
      GO TO (100,200,300,400)ICD
C  REMOVE
  100 IF(NPSEGS.EQ.0) RETURN
      DO 110 I=1,LENARR
        NAMNOW=NAMARR(I)
        DO 120 J=1,NPSEGS
          IF(NMPSEG(J).NE.NAMNOW) GO TO 120
C  PULL IT FROM LIST
          DO 130 K=J,NPSEGS
            NMPSEG(K)=NMPSEG(K+1)
  130     CONTINUE
  120   CONTINUE
  110 CONTINUE
      RETURN
C  ADD
  200 DO 210 I=1,LENARR
        IF(NPSEGS.EQ.NPMAX) GO TO 220
        NPSEGS=NPSEGS+1
        NMPSEG(NPSEGS)=NAMARR(I)
  210 CONTINUE
      RETURN
  220 WRITE(JUNIT,*)' PICK LIST OVERFLOW'
C  KILL
  300 NPSEGS=0
      RETURN
C  KILL AND ADD
  400 NPSEGS=0
      GO TO 200
      END
