      LOGICAL FUNCTION BUTTON(NBUT)
C  FIND THE STATE OF BUTTON N
      INCLUDE 'SYS$LIBRARY:DECW$XLIBDEF.FOR'
      COMMON/BTNCOM/VXX,VYY,IBTN,IDVNOW,ICLIC
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      ISTATE=X$L_BTEV_STATE
      IBUTTN=X$L_BTEV_BUTTON
      type 888,istate,ibuttn
  888 format(' istate,ibuttn:',2i)
      BUTTON=.FALSE.
      IF(NBUT.EQ.1.AND.(IRET.AND.4).GT.0) BUTTON=.TRUE.
      IF(NBUT.EQ.2.AND.(IRET.AND.2).GT.0) BUTTON=.TRUE.
      IF(NBUT.EQ.3.AND.(IRET.AND.1).GT.0) BUTTON=.TRUE.
      IF(NBUT.EQ.4.AND.(IRET.AND.8).GT.0) BUTTON=.TRUE.
      END
