      SUBROUTINE J3MOVE(X,Y,Z)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      XPOSN=X
      YPOSN=Y
      ZPOSN=Z
      IF(HCPY) THEN
        CALL DEV_MOVE(X,Y,Z)
        RETURN
      ENDIF
      IF(.NOT.PUTS)RETURN
      IF(PUTSUP)RETURN
      CALL J_PUTSG(I3MOVE,X)
      CALL J_PUTSG(I3MOVE,Y)
      CALL J_PUTSG(-I3MOVE,Z)
      RETURN
      END
