      SUBROUTINE JSGPRI(NAME,SEGPRI)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      INTEGER NAME,SEGPRI
      IF(NSEGS.EQ.0)RETURN
      DO 10 I=1,NSEGS
        IF(NAME.NE.NUMSEG(I)) GO TO 10
        IFOUND=I
        GO TO 100
   10 ENDDO
      RETURN
  100 ISPRIO(IFOUND)=SEGPRI
      END
