      SUBROUTINE JFRAME
C  CLEAR THE DISPLAY AREA AND REDRAW ALL RETAINED SEGMENTS
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      INTEGER IFIL(41)
      INTEGER*4 IPSAVD(23)
      EQUIVALENCE (IFIL,I3DRAW)
      DATA IFIL/1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
     &  21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,
     &  41/
      DATA IBCOLR / 0 /
C
C  CLEAR THE DISPLAY
C      CALL J_ERASE
C  JFRAME FLAG
      LFRAME=.TRUE.
C  MAKE THINGS VISIBLE
      VISBL=.TRUE.
C  PUT BACKGROUND COLOR INTO THE DISPLAY
      IF (.NOT. HCPY) THEN
        IPCTEM=IPCOLO
        IPDTEM=IPEDGE
        IPITEM=IPINT
        IPSTEM=IPSTYL
C-
C--- Define Background color...(8:Black)...
C-
        IF(IBCOLR.NE.0) THEN
          IPCOLO=IBCOLR
        ELSE
          IPCOLO=8
        ENDIF
        IPEDGE=1
        IPINT =0
        IPSTYL=1
C-
        CALL JRECT(UMIN,VMIN,UMAX,VMAX)
C-
        IPCOLO=IPCTEM
        IPEDGE=IPDTEM
        IPINT =IPITEM
        IPSTYL=IPSTEM
      ENDIF
C  ZERO THE POSITION
      XPOSN=0.
      YPOSN=0.
      ZPOSN=0.
C  SUPPRESS ENTRIES IN SEGMENT STORAGE (BLOCK PUTSG...)
      PUTS=.FALSE.
C
C  DRAW ALL VISIBLE SEGMENTS
      IF(NSEGS.EQ.0) GO TO 9000
C  SAVE DEFAULTS AND CURRENT CONDITIONS
      CALL JASAVE(IPSAVD)
C
      IF(IDEBUG.GT.5) CALL J_DMPSEG(JUNIT)
C  RUN THROUGH THE SEGMENTS
      DO 10 ISEG=1,NSEGS
        ISEGNM=NUMSEG(ISEG)
C  ENABLE SOON!!!
C  VISIBLE?
        IF(IVIS(ISEG).EQ.0) GO TO 10
        ISTEM=ISEG
        CALL J_DOSEGM(ISTEM)
   10 ENDDO
C  FORCE OUTPUT BUFFER IF NEEDED
      CALL J_FORCE
C  RESTORE DEFAULTS AND CURRENT CONDITIONS
      ISEGNM=-1
      CALL JALOAD(IPSAVD)
      CALL JARSET
      LFRAME=.FALSE.
      RETURN
 9000 LFRAME=.FALSE.
      RETURN
      END
