      SUBROUTINE JPINTR(I)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(.NOT.VISBL) GO TO 800
      IPSTYL=I
C  SET THE POLYGON FILL STYLE
  800 IF(.NOT.PUTS) RETURN
      CALL J_PUTSG(-IJPSTY,IPSTYL)
      END
