      SUBROUTINE JWINDO(X1,X2,Y1,Y2)
C  OPEN VIEWPLANE WINDOW
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(IFSPAC.EQ.0) CALL JVSPAC(VCXMNS,VCXMXS,VCYMNS,VCYMXS)
      UMIN=X1
      UMAX=X2
      VMIN=Y1
      VMAX=Y2
C  FIND TRANSFORMATION FACTORS FOR TR... ROUTINES
      IF(HCPY) CALL DEV_WINDOW_CORNERS(UMIN,UMAX,VMIN,VMAX)
      CALL J_COORDS
      END
