      SUBROUTINE JFONT(I)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IFONTC=I
      IF(HCPY) THEN
        CALL DEV_FONT(IFONTC)   ! J1STRG FONT SELECT FOR HARDCOPY
      ELSE
        CALL J_SETFON(IFONTC)   ! J1STRG FONT SELECT FOR WORKSTATION
      ENDIF
      CALL J_FONT(IFONTC)     ! JHSTRG FONT SELECT
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(-IJFONT,IFONTC)
      END
