      SUBROUTINE JVPORT(X1,X2,Y1,Y2)
C  SPECIFY AND SETUP VIEWPORT
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(IFSPAC.EQ.0) CALL JVSPAC(-1.,1.,-1.,1.)
      VXMIN=X1
      VXMAX=X2
      VYMIN=Y1
      VYMAX=Y2
      IF(HCPY) CALL DEV_VPORT(X1,X2,Y1,Y2)
      CALL J_COORDS
      IFPORT=1
      IMDEV=1
      ITRANS=1
      END
