      SUBROUTINE JMODEL(MATRIX)
C  ENABLE MODELING MATRIX (MAKE IT THE DEFAULT)
      REAL MATRIX(4,4)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      DO I=1,4
        DO J=1,4
          MMODEL(I,J)=MATRIX(I,J)
        ENDDO
      ENDDO
C  JUST TO BE SURE
      IMODEL=0
      END
