      SUBROUTINE J_SET_LINE_STYLE(STYLE)
      INTEGER STYLE
      COMMON/LINCOM/LWIDTH,LSTYLE,LCAPS
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      INCLUDE 'SYS$LIBRARY:DECW$XLIBDEF.FOR'
      INTEGER IDASHL(7,7),IDASHN(7)
      DATA IDASHL/
     &  20,20,0,0,0,0,0,
     &  4,8,0,0,0,0,0,
     &  20,16,4,16,0,0,
     &  12,20,0,0,0,0,0,
     &  40,25,0,0,0,0,0,
     &  4,12,4,12,4,12,40,12,
     &  12,16,40,16,0,0,0/
      DATA IDASHN/2,2,4,2,2,7,4/
      IF(ILSTYL.EQ.0) THEN
        LSTYLE=X$C_LINE_SOLID
      ELSE
        LSTY=ILSTYL
        IF(LSTY.LT.1.OR.LSTY.GT.7) LSTY=1
        LSTYLE=X$C_LINE_ON_OFF_DASH
C!!!        CALL X$SET_DASHES(VD_ID,ATB(ILINE),
C!!!     &              0,IDASHL(1,LSTY),IDASHN(LSTY))
      ENDIF
      LCAPS=X$C_CAP_BUTT
      CALL X$SET_LINE_ATTRIBUTES(VD_ID,ATB(ILINE),
     &              LWIDTH,LSTYLE,LCAPS,JSTY)
      END
