      SUBROUTINE JR3MOV(X,Y,Z)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      XPOSN=XPOSN+X
      YPOSN=YPOSN+Y
      ZPOSN=ZPOSN+Z
      IF(HCPY) THEN
        CALL DEV_DRAW(XPOSN,YPOSN,ZPOSN)
      ENDIF
       IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IR3MOV,X)
      CALL J_PUTSG(IR3MOV,Y)
      CALL J_PUTSG(-IR3MOV,Z)
      END
