      SUBROUTINE J3DRAW(X,Y,Z)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(HCPY) THEN
        CALL DEV_DRAW(X,Y,Z)
      ELSE
        CALL J_TR3XYZ(XPOSN,YPOSN,ZPOSN,XOLD,YOLD,ZOLD)
        CALL J_TR3XYZ(X,Y,Z,XNEW,YNEW,ZNEW)
        IATB=ILINE
        CALL J_LINE2(XOLD,YOLD,XNEW,YNEW)
      ENDIF
      XPOSN=X
      YPOSN=Y
      ZPOSN=Z
C      IF(IDEBUG.GT.5) TYPE 888,X,Y,Z,XOLD,YOLD,ZOLD,XNEW,YNEW,ZNEW
C  888 FORMAT(' J3DRAW:',9F)
      IF(.NOT.PUTS)RETURN
      IF(PUTSUP)RETURN
      CALL J_PUTSG(I3DRAW,X)
      CALL J_PUTSG(I3DRAW,Y)
      CALL J_PUTSG(-I3DRAW,Z)
      END
