      SUBROUTINE J_PUTSTR(IDSUBR,LEN,STRING)
C  PUT CHARACTER STRING INTO SEGMENT STORAGE
      CHARACTER*(*) STRING
      CHARACTER*120 STR
      INTEGER*4 ISTR(30)
      EQUIVALENCE (STR,ISTR)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(LEN.EQ.0) RETURN
      IBLOC(ISPTR)=IABS(IDSUBR)
      ISPTR=ISPTR+1
      IF(ISPTR.EQ.NBLOCX) GO TO 1000
      IBLOC(ISPTR)=LEN
      ISPTR=ISPTR+1
      IF(ISPTR.EQ.NBLOCX) GO TO 1000
      NWDS=(LEN-1)/4+1
      STR=STRING(1:LEN)
c      type 767,len,str
c  767 format(' in putstr-len,str:',i5,a)
      DO I=1,NWDS
        IBLOC(ISPTR)=ISTR(I)
        ISPTR=ISPTR+1
        IF(ISPTR.EQ.NBLOCX) GO TO 1000
      ENDDO
      NCALLS(NSEGS)=NCALLS(NSEGS)+1
      RETURN
 1000 WRITE(JUNIT,*)' PUTSTR--SEGMENT STORAGE OVERFLOW'
C  BE DRASTIC FOR NOW
      CALL JRCLOS
      RETURN
      END
