      SUBROUTINE JRDRAW(X,Y)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      XNOW=XPOSN+X
      YNOW=YPOSN+Y
      IF(HCPY) THEN
        CALL DEV_DRAW(XNOW,YNOW,0.)
        RETURN
      ENDIF
      CALL J_TR2XY(XPOSN,YPOSN,XOLD,YOLD)
      CALL J_TR2XY(XNOW,YNOW,XNEW,YNEW)
      IATB=ILINE
      CALL J_LINE2(XOLD,YOLD,XNEW,YNEW)
      XPOSN=XNOW
      YPOSN=YNOW
      IF(.NOT.PUTS)RETURN
      IF(PUTSUP) RETURN
      CALL J_PUTSG(IRDRAW,X)
      CALL J_PUTSG(-IRDRAW,Y)
      END
