      SUBROUTINE JELSEG(DSPDEV,PHYDEV,NAME,IASSC)
      INTEGER DSPDEV,PHYDEV
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(NSEGS.EQ.0) GO TO 1000
      DO I=1,NSEGS
        ISEG=I
        IF(NAME.EQ.NUMSEG(I)) GO TO 20
      ENDDO
      GO TO 1000
   20 IASSO(ISEG)=IASSC
      RETURN
 1000 WRITE(JUNIT,*) ' NO SUCH SEGMENT EXISTS',NAME
      END
