      SUBROUTINE JCLEAR
C  PURGE DISPLAY SURFACES AND SEGMENT STORAGE
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      CALL J_ERASE
      ISEGNM=-1
      NSEGS=0
      ISPTR=1
      PUTS=.FALSE.
      END
