      SUBROUTINE JISGMT(NAME,AARRAY)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      INTEGER NAME,AARRAY(19)
      DO I=1,19
        AARRAY(I)=0
      ENDDO
      IF(NSEGS.EQ.0) RETURN
      DO 100 I=1,NSEGS
        IF(NAME.NE.NUMSEG(I)) GO TO 100
        IFOUND=I
        GO TO 200
  100 ENDDO
      RETURN
C  SEGMENT EXISTS
  200 AARRAY(1)=1
      AARRAY(2)=IVIS(IFOUND)
      AARRAY(3)=IDETEC(IFOUND)
      AARRAY(5)=ITTYP(IFOUND)
C  THERE MAY BE MORE OF THESE IN THE FUTURE!!!
      END
