      SUBROUTINE JPIDEX(ICOLR,INTEN)
C  CURRENT POLYGON INTERIOR COLOR AND INTENSITY (12,13)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IF(.NOT.VISBL) GO TO 800
      IPCOLO=ICOLR
      IPINT=INTEN
  800 IF(.NOT.PUTS) RETURN
      CALL J_PUTSG(IJPCOL,ICOLR)
      CALL J_PUTSG(-IJPCOL,INTEN)
      END
