      SUBROUTINE DEV_POLY(N,PARRY)
      REAL PARRY(3,*)
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
      IFILL=0
      IF(IDV.EQ.1) THEN
        CALL PS_POLY(N,PARRY)
      ELSE
        CALL TK_POLY(N,PARRY)
      ENDIF
      END
