      SUBROUTINE JSVIEW(XVRP,YVRP,ZVRP,DIST,YANG,XZANG,VANGLE)
      YA=YANG*3.1415927/180.
      XZA=XZANG*3.1415927/180.
      XEYE=COS(YA)*COS(XZA)*DIST
      YEYE=SIN(YA)*DIST
      ZEYE=SIN(YA)*COS(XZA)*DIST
      CALL JCVIEW(XVRP,YVRP,ZVRP,XEYE,YEYE,ZEYE,VANGLE)
      END
