      SUBROUTINE J_PLAYBACK
C  REDRAW ALL RETAINED SEGMENTS.
C  SEGMENT STORAGE IS USED ONLY FOR PLAYBACK NEEDED TO DO HARDCOPY.
C  THE TRANSFORMATION FOR CURRENTLY CONNECTED ROTATABLE SEGMENTS
C  ARE PICKED UP FROM THE MATRIX CURRENTLY IN HARDWARE.
      INCLUDE 'D0$GRAPHICS_UTIL$XWNDI3:XWNEMU.INC'
C      INTEGER*4 IPSAVD(23)
C
C  ZERO THE POSITION
      XPOSN=0.
      YPOSN=0.
      ZPOSN=0.
C  SUPPRESS ENTRIES IN SEGMENT STORAGE (BLOCK J_PUTSG...)
      PUTS=.FALSE.
C
C  DRAW ALL VISIBLE SEGMENTS
      IF(NSEGS.EQ.0) RETURN
C  SAVE DEFAULTS AND CURRENT CONDITIONS
c      CALL JASAVE(IPSAVD)
C
      IF(IDEBUG.GT.5) CALL J_DMPSEG(JUNIT)
C
C  RUN THROUGH THE SEGMENTS
      DO 10 ISEG=1,NSEGS
        ISEGNM=NUMSEG(ISEG)
C        IF(IVIS(ISEG).EQ.0) GO TO 10
        ISTEM=ISEG
        CALL J_DOSEGM(ISTEM)
   10 ENDDO
C
C  FORCE OUTPUT BUFFER IF NEEDED
      CALL DEV_FORCE
C
C  RESTORE DEFAULTS AND CURRENT CONDITIONS
      ISEGNM=-1
c      CALL JALOAD(IPSAVD)
c      CALL JARSET
      RETURN
      END
