      INTEGER FUNCTION PARSFI(FILSPC,NODSPC,NODLEN,DEVSPC,DEVLEN,
     &                   DIRSPC,DIRLEN,NAMSPC,NAMLEN,TYPSPC,TYPLEN)
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : PARSE a file specification
C-
C-   Inputs  : FILSPC : File spec to parse
C-   Outputs : NODSPC : Node specification
C-             NODLEN : Length of node specification
C-             DEVSPC : Device specification
C-             DEVLEN : Length of device specification
C-             DIRSPC : Directory specification
C-             DIRLEN : Length of directory specification
C-             NAMSPC : Name specification
C-             NAMLEN : Length of name specification
C-             TYPSPC : Type specification
C-             TYPLEN : Length of type specification
C-   Controls: None
C-
C-   Created  11-JAN-1989   Jan S. Hoftun (from PAS version written by 
C-                                         Kamal Hammoutene)
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      CHARACTER*(*) FILSPC,NODSPC,DEVSPC,DIRSPC,NAMSPC,TYPSPC
      INTEGER NODLEN,DEVLEN,DIRLEN,NAMLEN,TYPLEN
      INTEGER STATUS
C&IF VAXVMS
      INCLUDE '($FABDEF)/LIST'
      INCLUDE '($NAMDEF)/LIST'
      INCLUDE '($RMSDEF)'
      RECORD /FABDEF/FILE_ACCESS_BLOCK
      RECORD /NAMDEF/NAME_BLOCK
      INTEGER INDEX,SYS$PARSE
      CHARACTER*128 RESULTANT_STRING,EXPANDED_STRING,FILLOC
C----------------------------------------------------------------------
      FILLOC=FILSPC
      FILE_ACCESS_BLOCK.FAB$W_IFI=0
      FILE_ACCESS_BLOCK.FAB$L_FOP=0
      FILE_ACCESS_BLOCK.FAB$L_STS=0
      FILE_ACCESS_BLOCK.FAB$L_STV=0
      FILE_ACCESS_BLOCK.FAB$L_ALQ=0
      FILE_ACCESS_BLOCK.FAB$W_DEQ=0
      FILE_ACCESS_BLOCK.FAB$B_FAC=0
      FILE_ACCESS_BLOCK.FAB$B_SHR=0
      FILE_ACCESS_BLOCK.FAB$L_CTX=0
      FILE_ACCESS_BLOCK.FAB$B_RTV=0
      FILE_ACCESS_BLOCK.FAB$B_ORG=0
      FILE_ACCESS_BLOCK.FAB$B_RAT=0
      FILE_ACCESS_BLOCK.FAB$B_RFM=0
      FILE_ACCESS_BLOCK.FAB$B_JOURNAL=0
      FILE_ACCESS_BLOCK.FAB$B_RU_FACILITY=0
C      FILE_ACCESS_BLOCK.FABDEF$$_FILL_7=0
      FILE_ACCESS_BLOCK.FAB$L_XAB=0
      FILE_ACCESS_BLOCK.FAB$L_NAM=0
      FILE_ACCESS_BLOCK.FAB$L_FNA=0
      FILE_ACCESS_BLOCK.FAB$L_DNA=0
      FILE_ACCESS_BLOCK.FAB$B_FNS=0
      FILE_ACCESS_BLOCK.FAB$B_DNS=0
      FILE_ACCESS_BLOCK.FAB$W_MRS=0
      FILE_ACCESS_BLOCK.FAB$L_MRN=0
      FILE_ACCESS_BLOCK.FAB$W_BLS=0
      FILE_ACCESS_BLOCK.FAB$B_BKS=0
      FILE_ACCESS_BLOCK.FAB$B_FSZ=0
      FILE_ACCESS_BLOCK.FAB$L_DEV=0
      FILE_ACCESS_BLOCK.FAB$L_SDC=0
      FILE_ACCESS_BLOCK.FAB$W_GBC=0
      FILE_ACCESS_BLOCK.FAB$B_ACMODES=0
      FILE_ACCESS_BLOCK.FAB$B_RCF=0
C      FILE_ACCESS_BLOCK.FABDEF$$_FILL_9=0
      FILE_ACCESS_BLOCK.FAB$B_BID=FAB$C_BID
      FILE_ACCESS_BLOCK.FAB$B_BLN=FAB$C_BLN
      FILE_ACCESS_BLOCK.FAB$L_FNA=%LOC(FILLOC)
      FILE_ACCESS_BLOCK.FAB$B_FNS=128
      FILE_ACCESS_BLOCK.FAB$L_NAM=%LOC(NAME_BLOCK)
      NAME_BLOCK.NAM$B_RSS=0
      NAME_BLOCK.NAM$B_RSL=0
      NAME_BLOCK.NAM$L_RSA=0
      NAME_BLOCK.NAM$B_NOP=0
      NAME_BLOCK.NAM$B_RFS=0
      NAME_BLOCK.NAM$B_ESS=0
      NAME_BLOCK.NAM$B_ESL=0
      NAME_BLOCK.NAM$L_ESA=0
      NAME_BLOCK.NAM$L_RLF=0
      NAME_BLOCK.NAM$T_DVI=' '
      NAME_BLOCK.NAM$W_FID(1)=0
      NAME_BLOCK.NAM$W_FID(2)=0
      NAME_BLOCK.NAM$W_FID(3)=0
      NAME_BLOCK.NAM$W_DID(1)=0
      NAME_BLOCK.NAM$W_DID(2)=0
      NAME_BLOCK.NAM$W_DID(3)=0
      NAME_BLOCK.NAM$L_WCC=0
      NAME_BLOCK.NAM$L_FNB=0
      NAME_BLOCK.NAM$B_NODE=0
      NAME_BLOCK.NAM$B_DEV=0
      NAME_BLOCK.NAM$B_DIR=0
      NAME_BLOCK.NAM$B_NAME=0
      NAME_BLOCK.NAM$B_TYPE=0
C      NAME_BLOCK.NAMDEF$$_FILL_6(1)=0
C      NAME_BLOCK.NAMDEF$$_FILL_6(2)=0
      NAME_BLOCK.NAM$B_VER=0
      NAME_BLOCK.NAM$L_NODE=0
      NAME_BLOCK.NAM$L_DEV=0
      NAME_BLOCK.NAM$L_DIR=0
      NAME_BLOCK.NAM$L_NAME=0
      NAME_BLOCK.NAM$L_TYPE=0
      NAME_BLOCK.NAM$L_VER=0
C      NAME_BLOCK.NAMDEF$$_FILL_7(1)=0
C      NAME_BLOCK.NAMDEF$$_FILL_7(2)=0
      NAME_BLOCK.NAM$B_BID=NAM$C_BID
      NAME_BLOCK.NAM$B_BLN=NAM$C_BLN
      NAME_BLOCK.NAM$L_ESA=%LOC(EXPANDED_STRING)
      NAME_BLOCK.NAM$B_ESS=128
C      NAME_BLOCK.NAM$B_NOP=NAME_BLOCK.NAM$M_NOCONCEAL
      NAME_BLOCK.NAM$B_NOP=NAM$M_SYNCHK
      NAME_BLOCK.NAM$L_RSA=%LOC(RESULTANT_STRING)
      NAME_BLOCK.NAM$B_RSL=128
      STATUS=SYS$PARSE(FILE_ACCESS_BLOCK)
      IF(STATUS.EQ.RMS$_NORMAL) THEN
        NODLEN=NAME_BLOCK.NAM$B_NODE
        NODSPC=EXPANDED_STRING(1:NODLEN)
        DEVLEN=NAME_BLOCK.NAM$B_DEV
        DEVSPC=EXPANDED_STRING(NODLEN+1:NODLEN+DEVLEN)
        DIRLEN=NAME_BLOCK.NAM$B_DIR
        DIRSPC=EXPANDED_STRING(NODLEN+DEVLEN+1:NODLEN+DEVLEN+DIRLEN)
        NAMLEN=NAME_BLOCK.NAM$B_NAME
        INDEX=NODLEN+DEVLEN+DIRLEN
        NAMSPC=EXPANDED_STRING(INDEX+1:INDEX+NAMLEN)
        TYPLEN=NAME_BLOCK.NAM$B_TYPE
        INDEX=NODLEN+DEVLEN+DIRLEN+NAMLEN
        TYPSPC=EXPANDED_STRING(INDEX+1:INDEX+TYPLEN)
      ENDIF
C&ELSE
C&      STATUS=0
C&ENDIF
      PARSFI=STATUS
  999 RETURN
      END
