      SUBROUTINE OUTMSG(STRNG)
      ENTRY INTMSG(STRNG)
      ENTRY MSGSCR(STRNG)
      CHARACTER*(*) STRNG
      M=MYL(STRNG)
      IF(M.EQ.0) RETURN
      TYPE 100,STRNG(1:M)
  100 FORMAT(' ',A)
      RETURN
      END
