CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VXFRAME()
      VXFRAME = ' XFRAME'//
     X                   '  TEST V0.01_11'//
     X                   ' 28-JUN-1996 18:19:10.36'
      Return
      End
