CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VISAZEB()
      VISAZEB = ' ISAZEB'//
     X                   '  OFFICIAL V2.15'//
     X                   ' 16-JUL-1997 12:57:52.61'
      Return
      End
