      SUBROUTINE ECHWRT(ILUN,IERR)
C----------------------------------------------------------------------
C-
C-   PURPOSE AND METHODS : Write a header to a D0DAD event catalog.  
C-     The format parameters can be changed via calls to ECFSET.
C-
C-   INPUTS  : 
C-   OUTPUTS : 
C-   CONTROLS: 
C-
C-   CREATED   8-NOV-1993   John D Hobbs
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:zebcom.inc'
      INCLUDE 'D0$INC:d0dadcom.inc/NOLIST'
      INTEGER ILUN,IERR,NPRECS,NRRECS,NW,IVAL
      CHARACTER*8 CSTR,CTAG*(*)
      INTEGER IECPAG,IECDLT,IECRUN,IRPREC,IECRD,IRECEC,IECTIM,IRUN0
      SAVE IECPAG,IECDLT,IECRUN,IRPREC,IECRD,IECTIM,IRECEC,IRUN0
      DATA IECPAG/KECPAG/,IECDLT/KECDLT/,IECRUN/KECRUN/,IRPREC/KRPREC/
      DATA IECRD/KECRD/,  IECTIM/KECTIM/,IRECEC/KRECEC/,IRUN0/KRUN0/
C----------------------------------------------------------------------
C
C  Initialize the header from defaults
C
      CALL D0DAD_CPAD(CECTAG)
      IERR=0
      WRITE(CSTR,1101) D0DADBASE,'EC'
 1101 FORMAT(A5,' ',A2)
C
      NRRECS=IECRUN/IRPREC
      IF( MOD(KECRUN,KRPREC).NE.0 ) NRRECS=NRRECS+1
      NPRECS=0
C
      CALL UCTOH(CSTR,IQ(LECHD+NDEC+1),4,8)
      IQ(LECHD+NDEC+JEC_RECVER)=100*VER_D0DAD_MAJOR + VER_D0DAD_MINOR
      IQ(LECHD+NDEC+JEC_IECHED)=KECHED
      IQ(LECHD+NDEC+JEC_IRECEC)=IRECEC
      IQ(LECHD+NDEC+JEC_IRPREC)=IRPREC
      CALL UCTOH(CECTAG,IQ(LECHD+NDEC+JEC_CECTAG),4,20)
      IQ(LECHD+NDEC+JEC_IRUN0)=IRUN0
      IQ(LECHD+NDEC+JEC_IRUN1)=IRUN0+NRRECS-1
      IQ(LECHD+NDEC+JEC_IECRUN)=0
      IQ(LECHD+NDEC+JEC_IECRD)=IECRD
      IQ(LECHD+NDEC+JEC_IECPG0)=IQ(LECHD+NDEC+JEC_IRUN1)+1
      IQ(LECHD+NDEC+JEC_IECPG1)=IQ(LECHD+NDEC+JEC_IECPG0)+NPRECS-1
      IQ(LECHD+NDEC+JEC_IECPAG)=IECPAG
      IQ(LECHD+NDEC+JEC_IEVT0)=IQ(LECHD+NDEC+JEC_IECPG1)+1
      IQ(LECHD+NDEC+JEC_IEVT1)=IQ(LECHD+NDEC+JEC_IEVT0)-1
      IQ(LECHD+NDEC+JEC_IECEVT)=0
      IQ(LECHD+NDEC+JEC_IECDLT)=IECDLT
      IQ(LECHD+NDEC+JEC_IECTIM)=IECTIM
      IQ(LECHD+NDEC+JEC_ISDIRT)=0
      IQ(LECHD+NDEC+JEC_INOORD)=0
      IQ(LECHD+NDEC+JEC_INDRCT)=0
      IQ(LECHD+NDEC+JEC_BSWAP)=TESTBSWAP
      IQ(LECHD+NDEC+JEC_EXTRA)=0
C
      CALL ECRWRT(ILUN,1,IQ(LECHD+NDEC+1),KECHED,0,IERR)
      IF( IERR.NE.0 ) GOTO 998
C
C  Allocate blank run section and physical record working array...
C
      NW=IRECEC*IRPREC
      CALL MZBOOK(IXDDAD,LPREC,LECHD,-LLPREC,'PAGE',0,0,NW,2,0)
      NW=NW*(IQ(LECHD+NDEC+JEC_IRUN1)-IQ(LECHD+NDEC+JEC_IRUN0)+1)
      CALL MZBOOK(IXDDAD,LRUNS,LECHD,-LLRUNS,'RUNS',0,0,NW,2,0)
      IF( LPREC.LE.0 .OR. LRUNS.LE.0 ) GOTO 997
C
C  Write blank run section...
C
      CALL ECWRIT(IQ(LRUNS+1),2,NW/IRECEC,IERR)
      IF( IERR.NE.0 ) GOTO 996
C
  999 CONTINUE
      RETURN
C
 998  CONTINUE
      IERR = -1
      RETURN
C
 997  CONTINUE
      IERR = -2
      RETURN
C
 996  CONTINUE
      IERR = -3
      RETURN
C 
      ENTRY ECFSET(CTAG,IVAL,IERR)
C-
C-  Adjust the format of an event catalog.  Must be called prior
C-  to D0DAD_OPEN.
C-
      IERR=0
      CALL CLTOU(CTAG)
      IF( CTAG.EQ.'KECRD' ) THEN
      ELSEIF(CTAG.EQ.'KECPAG') THEN
        IECPAG=IVAL
      ELSEIF(CTAG.EQ.'KECDLT') THEN
        IECDLT=IVAL
      ELSEIF(CTAG.EQ.'KECRUN') THEN
        IECRUN=IVAL
      ELSEIF(CTAG.EQ.'KRPREC') THEN
        IRPREC=IVAL
      ELSEIF(CTAG.EQ.'KECRD') THEN
        IECRD=IVAL
      ELSEIF(CTAG.EQ.'KECTIM') THEN
        IECTIM=IVAL
      ELSE
        IERR =  -1
      ENDIF
      RETURN
C
      ENTRY ECFGET(CTAG,IVAL,IERR)
C-
C-  Get the format of an event catalog.  Called by ECOPEN
C-
      IERR=0
      CALL CLTOU(CTAG)
      IF( CTAG.EQ.'KECRD' ) THEN
      ELSEIF(CTAG.EQ.'KECPAG') THEN
        IVAL=IECPAG
      ELSEIF(CTAG.EQ.'KECDLT') THEN
        IVAL=IECDLT
      ELSEIF(CTAG.EQ.'KECRUN') THEN
        IVAL=IECRUN
      ELSEIF(CTAG.EQ.'KRPREC') THEN
        IVAL=IRPREC
      ELSEIF(CTAG.EQ.'KECRD') THEN
        IVAL=IECRD
      ELSEIF(CTAG.EQ.'KECTIM') THEN
        IVAL=IECTIM
      ELSE
        IERR =  -1
      ENDIF
      RETURN
      END
