$! To setup GENERAL MENUS for D0USER
$ assign D0$D0USER$MENU:INTERRUPT.MENU INTERRUPT
$ assign  D0$D0USER$MENU:SETUP.MENU SETUP
$ assign  D0$D0USER$MENU:DONE_WITH_DATA.MENU DONE_WITH_DATA
$ assign  D0$D0USER$MENU:SUMMARIES.MENU SUMMARIES
$ assign  D0$D0USER$MENU:D0H_OPTIONS.MENU D0H_OPTIONS
$ assign  D0$D0USER$MENU:EXAMINE.MENU EXAMINE
$ assign  D0$PIXIE$MENU:PIXIE_CAL.MENU PIXIE
