# To setup GENERAL MENUS for D0USER
ln -sf `vff 'D0$D0USER$MENU:INTERRUPT.MENU'` INTERRUPT
ln -sf `vff 'D0$D0USER$MENU:SETUP.MENU'` SETUP
ln -sf `vff 'D0$D0USER$MENU:DONE_WITH_DATA.MENU'` DONE_WITH_DATA
ln -sf `vff 'D0$D0USER$MENU:SUMMARIES.MENU'` SUMMARIES
ln -sf `vff 'D0$D0USER$MENU:D0H_OPTIONS.MENU'` D0H_OPTIONS
ln -sf `vff 'D0$D0USER$MENU:EXAMINE.MENU'` EXAMINE
#ln -sf `vff 'D0$PIXIE$MENU:PIXIE_CAL.MENU'` PIXIE
