      INTEGER FUNCTION DECISA(ID)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC   RETURNS PARTICLE TYPE FOR GIVEN ID
CC   KLUGE ROUTINE AS ACTUALLY LOOKING FOR WHICH QUARK IS
CC   DECAYING. THIS ASSUMES THAT THE HEAVIEST IS THE ONE WE WANT
CC   HEDIN 8-87,6-89
CC       IF IDENT > 100 THEN PARTICLE, IF NOT JUST ID
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      INTEGER ID,I1,I2,I3,I
      I=IABS(ID)
      I1=I/1000
      I2=(I-I1*1000)
      I2=I2/100
      I3=I-I1*1000-I2*100
      I3=I3/10
      DECISA=0
      IF(I1.EQ.1.OR.I2.EQ.1.OR.I3.EQ.1) DECISA=1
      IF(I1.EQ.2.OR.I2.EQ.2.OR.I3.EQ.2) DECISA=2
      IF(I1.EQ.3.OR.I2.EQ.3.OR.I3.EQ.3) DECISA=3
      IF(I1.EQ.4.OR.I2.EQ.4.OR.I3.EQ.4) DECISA=4
      IF(I1.EQ.5.OR.I2.EQ.5.OR.I3.EQ.5) DECISA=5
      IF(I1.EQ.6.OR.I2.EQ.6.OR.I3.EQ.6) DECISA=6
      IF(I.LT.100) THEN
        DECISA=I           ! NOT HADRON
        IF(I.EQ.80) DECISA=7
        IF(I.EQ.90) DECISA=8
      ENDIF
      RETURN
      END
