      INTEGER FUNCTION GZMDFT_R(NMOD)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO REF MUON TIME-DISTANCE BANK FOR MODULE NMOD
CC
CC    HEDIN  9-91
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPO.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMDFH.LINK'
      INTEGER KSTPO,KSMUO,KMDFH,NMOD
C
      GZMDFT_R=0
      KSTPO=LC(LSTPH-IZSTPO)
      IF(KSTPO.NE.0) THEN
        KSMUO=LC(KSTPO-IZSMUO)
        IF(KSMUO.NE.0) THEN
          KMDFH=LC(KSMUO-IZMDFH)
          IF(KMDFH.NE.0) THEN
            GZMDFT_R=LC(KMDFH-NMOD)
          ENDIF
        ENDIF
      ENDIF
      RETURN
      END
