      INTEGER FUNCTION GZMDFT(NMOD)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO MUON TIME-DISTANCE BANK FOR MODULE NMOD
CC
CC    HEDIN  9-91
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPC.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMDFH.LINK'
      INTEGER KSTPC,KSMUO,KMDFH,NMOD
C
      GZMDFT=0
      KSTPC=LC(LSTPH-IZSTPC)
      IF(KSTPC.NE.0) THEN
        KSMUO=LC(KSTPC-IZSMUO)
        IF(KSMUO.NE.0) THEN
          KMDFH=LC(KSMUO-IZMDFH)
          IF(KMDFH.NE.0) THEN
            GZMDFT=LC(KMDFH-NMOD)
          ENDIF
        ENDIF
      ENDIF
      RETURN
      END
