      INTEGER FUNCTION GZMDDX(ITRAK)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK MDDX 
CC    'ITRAK' BANK 'MUON' TRACK NUMBER
CC
CC    HEDIN 12-3-89
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZMDDX.LINK'
      INTEGER I,ITRAK,LMUON,GZMUON
      GZMDDX=0
      LMUON=GZMUON(ITRAK)
      IF(LMUON.NE.0) THEN
        GZMDDX=LQ(LMUON-IZMDDX)
      ENDIF
      RETURN
      END
