      INTEGER FUNCTION GZMDFT_N(NMOD)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO NEW MUON TIME-DISTANCE BANK FOR MODULE NMOD
CC
CC    HEDIN  9-91
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPN.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMDFH.LINK'
      INTEGER KSTPN,KSMUO,KMDFH,NMOD
C
      GZMDFT_N=0
      KSTPN=LC(LSTPH-IZSTPN)
      IF(KSTPN.NE.0) THEN
        KSMUO=LC(KSTPN-IZSMUO)
        IF(KSMUO.NE.0) THEN
          KMDFH=LC(KSMUO-IZMDFH)
          IF(KMDFH.NE.0) THEN
            GZMDFT_N=LC(KMDFH-NMOD)
          ENDIF
        ENDIF
      ENDIF
      RETURN
      END
