      INTEGER FUNCTION GZMFIT(ITRAK)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK MFIT 
CC    'ITRAK' BANK 'MUON' TRACK NUMBER
CC
CC    HEDIN 12-3-89
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZMFIT.LINK'
      INTEGER I,ITRAK,LMUON,GZMUON
      GZMFIT=0
      LMUON=GZMUON(ITRAK)
      IF(LMUON.NE.0) THEN
        GZMFIT=LQ(LMUON-IZMFIT)
      ENDIF
      RETURN
      END
