c DEC/CMS REPLACEMENT HISTORY, Element GZMGNH.FOR
c *1    10-AUG-1987 18:17:44 HEDIN ""
c DEC/CMS REPLACEMENT HISTORY, Element GZMGNH.FOR
      INTEGER FUNCTION GZMGNH(I)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO MUON GAIN HEADER               
CC
CC    HEDIN  6-11-87
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPC.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMGNH.LINK'
      INTEGER KSTPC,KSMUO,KMGNH,I   
C
      GZMGNH=0
      KSTPC=LC(LSTPH-IZSTPC)
      IF(KSTPC.NE.0) THEN
        KSMUO=LC(KSTPC-IZSMUO)
        IF(KSMUO.NE.0) THEN
          GZMGNH=LC(KSMUO-IZMGNH)
        ENDIF
      ENDIF
      RETURN
      END
