      INTEGER FUNCTION GZMPED(NMOD)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO MUON PEDESTAL BANK FOR MODULE NMOD
CC
CC    HEDIN  1-20-87
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPC.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMPDH.LINK'
      INTEGER KSTPC,KSMUO,KMPDH,NMOD
C
      GZMPED=0
      IF (LSTPH .NE. 0) THEN
      KSTPC=LC(LSTPH-IZSTPC)
      IF(KSTPC.NE.0) THEN
        KSMUO=LC(KSTPC-IZSMUO)
        IF(KSMUO.NE.0) THEN
          KMPDH=LC(KSMUO-IZMPDH)
          IF(KMPDH.NE.0) THEN
            GZMPED=LC(KMPDH-NMOD)
          ENDIF
        ENDIF
      ENDIF
      ENDIF
      RETURN
      END
