C DEC/CMS REPLACEMENT HISTORY, Element GZMPDH.FOR
C *2    10-AUG-1987 18:21:18 HEDIN ""
C *1    26-JUN-1987 12:38:54 HEDIN "Gets muon pedestal header pointer"
C DEC/CMS REPLACEMENT HISTORY, Element GZMPDH.FOR
      INTEGER FUNCTION GZMPDH(I)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO MUON PEDESTAL HEADER               
CC
CC    HEDIN  6-11-87
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPC.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMPDH.LINK'
      INTEGER KSTPC,KSMUO,KMPDH,I   
C
      GZMPDH=0
      KSTPC=LC(LSTPH-IZSTPC)
      IF(KSTPC.NE.0) THEN
        KSMUO=LC(KSTPC-IZSMUO)
        IF(KSMUO.NE.0) THEN
          GZMPDH=LC(KSMUO-IZMPDH)
        ENDIF
      ENDIF
      RETURN
      END
