C DEC/CMS REPLACEMENT HISTORY, Element GZMPED_R.FOR
C *1    10-FEB-1987 18:16:08 HEDIN "Muon constant bank get pointer routine"
C DEC/CMS REPLACEMENT HISTORY, Element GZMPED_R.FOR
      INTEGER FUNCTION GZMPED_R(NMOD)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO REF MUON PEDESTAL BANK FOR MODULE NMOD
CC
CC    HEDIN  1-20-87
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPO.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMPDH.LINK'
      INTEGER KSTPO,KSMUO,KMPDH,NMOD
C
      GZMPED_R=0
      KSTPO=LC(LSTPH-IZSTPO)
      IF(KSTPO.NE.0) THEN
        KSMUO=LC(KSTPO-IZSMUO)
        IF(KSMUO.NE.0) THEN
          KMPDH=LC(KSMUO-IZMPDH)
          IF(KMPDH.NE.0) THEN
            GZMPED_R=LC(KMPDH-NMOD)
          ENDIF
        ENDIF
      ENDIF
      RETURN
      END
