      INTEGER FUNCTION GZMTRG(I)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK MTRG
CC
CC    HEDIN 10-7-86
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZMTRG.LINK'
      INTEGER I,LMUHT,GZMUHT
      GZMTRG=0
      LMUHT=GZMUHT(0)
      IF(LMUHT.NE.0) THEN
        GZMTRG=LQ(LMUHT-IZMTRG)
      ENDIF
      RETURN
      END
