c DEC/CMS REPLACEMENT HISTORY, Element GZMTMH.FOR
c *1    10-AUG-1987 18:17:48 HEDIN ""
c DEC/CMS REPLACEMENT HISTORY, Element GZMTMH.FOR
      INTEGER FUNCTION GZMTMH(I)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO MUON TIME     HEADER               
CC
CC    HEDIN  6-11-87
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPC.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMTMH.LINK'
      INTEGER KSTPC,KSMUO,KMTMH,I   
C
      GZMTMH=0
      KSTPC=LC(LSTPH-IZSTPC)
      IF(KSTPC.NE.0) THEN
        KSMUO=LC(KSTPC-IZSMUO)
        IF(KSMUO.NE.0) THEN
          GZMTMH=LC(KSMUO-IZMTMH)
        ENDIF
      ENDIF
      RETURN
      END
