C DEC/CMS REPLACEMENT HISTORY, Element GZMTIM_N.FOR
C *1    10-FEB-1987 18:16:12 HEDIN "Muon constant bank get pointer routine"
C DEC/CMS REPLACEMENT HISTORY, Element GZMTIM_N.FOR
      INTEGER FUNCTION GZMTIM_N(NMOD)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO NEW MUON TIME     BANK FOR MODULE NMOD
CC
CC    HEDIN  1-20-87
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPN.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMTMH.LINK'
      INTEGER KSTPN,KSMUO,KMTMH,NMOD
C
      GZMTIM_N=0
      KSTPN=LC(LSTPH-IZSTPN)
      IF(KSTPN.NE.0) THEN
        KSMUO=LC(KSTPN-IZSMUO)
        IF(KSMUO.NE.0) THEN
          KMTMH=LC(KSMUO-IZMTMH)
          IF(KMTMH.NE.0) THEN
            GZMTIM_N=LC(KMTMH-NMOD)
          ENDIF
        ENDIF
      ENDIF
      RETURN
      END
