C DEC/CMS REPLACEMENT HISTORY, Element GZMTIM.FOR
C *1    10-FEB-1987 18:16:10 HEDIN "Muon constant bank get pointer routine"
C DEC/CMS REPLACEMENT HISTORY, Element GZMTIM.FOR
      INTEGER FUNCTION GZMTIM(NMOD)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO MUON TIME     BANK FOR MODULE NMOD
CC
CC    HEDIN  1-20-87
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZSTPC.LINK'
      INCLUDE 'D0$LINKS:IZSMUO.LINK'
      INCLUDE 'D0$LINKS:IZMTMH.LINK'
      INTEGER KSTPC,KSMUO,KMTMH,NMOD
C
      GZMTIM=0
      KSTPC=LC(LSTPH-IZSTPC)
      IF(KSTPC.NE.0) THEN
        KSMUO=LC(KSTPC-IZSMUO)
        IF(KSMUO.NE.0) THEN
          KMTMH=LC(KSMUO-IZMTMH)
          IF(KMTMH.NE.0) THEN
            GZMTIM=LC(KMTMH-NMOD)
          ENDIF
        ENDIF
      ENDIF
      RETURN
      END
