      INTEGER FUNCTION GZMTRH(I)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK MTRH
CC
CC    HEDIN 11-24-86
CC    DH 11/89 call to GZPROC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZMTRH.LINK'
      INTEGER GZPROC,LPROC,I
      GZMTRH=0
      LPROC=GZPROC()
      IF(LPROC.NE.0) THEN
        GZMTRH=LQ(LPROC-IZMTRH) 
      ENDIF
      RETURN
      END
