      INTEGER FUNCTION GZMUCA(ITRAK)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK MUCA 
CC    'ITRAK' BANK 'MUON' TRACK NUMBER
CC
CC    HEDIN 12-3-89
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZMUCA.LINK'
      INTEGER I,ITRAK,LMUON,GZMUON
      GZMUCA=0
      LMUON=GZMUON(ITRAK)
      IF(LMUON.NE.0) THEN
        GZMUCA=LQ(LMUON-IZMUCA)
      ENDIF
      RETURN
      END
