      INTEGER FUNCTION GZMUHT(I)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK MUHT
CC
CC    HEDIN 10-7-86
CC    call GZHITS
CC    DH 11-91 set to 0
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZMUHT.LINK'
      INTEGER I,GZHITS,LHITS
      GZMUHT=0
      LHITS=GZHITS()  
      IF(LHITS.NE.0) THEN
        GZMUHT=LQ(LHITS-IZMUHT) 
      ENDIF
      RETURN
      END
