C DEC/CMS REPLACEMENT HISTORY, Element GZMUOH.FOR
C *1     9-DEC-1986 17:12:22 HEDIN "Finds pointer to muon Zebra bank"
C DEC/CMS REPLACEMENT HISTORY, Element GZMUOH.FOR
      INTEGER FUNCTION GZMUOH(I)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK MUOH
CC
CC    HEDIN 10-7-86
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZMUOH.LINK'
      INTEGER I,LMUHT,GZMUHT
      GZMUOH=0
      LMUHT=GZMUHT(0)
      IF(LMUHT.NE.0) THEN
        GZMUOH=LQ(LMUHT-IZMUOH)
      ENDIF
      RETURN
      END
