C DEC/CMS REPLACEMENT HISTORY, Element GZMUOF.FOR
C *1     9-DEC-1986 17:12:19 HEDIN "Finds pointer to muon Zebra bank"
C DEC/CMS REPLACEMENT HISTORY, Element GZMUOF.FOR
      INTEGER FUNCTION GZMUOF(I)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK MUOF
CC
CC    HEDIN 10-7-86
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZMUOF.LINK'
      INTEGER I,LRECO,LHITS,LMUHT,GZMUHT
      GZMUOF=0
      LMUHT=GZMUHT(0)                   
      IF(LMUHT.NE.0) THEN
        GZMUOF=LQ(LMUHT-IZMUOF)
      ENDIF
      RETURN
      END
