      INTEGER FUNCTION GZMUOT(ITRAK)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK MUOT 
CC    MUOT IS A LINEAR BANK, THIS POINTS TO 
CC    TRACK ITRAK (OR TRACK 1 IF ITRAK =0) 
CC    WHERE ITRAK IS THE 'ITRAK' TRACK IN LINESR STRUCTURE
CC
CC    HEDIN 11-24-86
CC    DH 5/89 ALLOW FOR MORE THAN ONE TRACK
C- Updated 08-28-1992 S. Abachi  Protection against gzmuot=0 in loop
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZMUOT.LINK'
      INTEGER I,ITRAK,LMTRH,GZMTRH
      GZMUOT=0
      LMTRH=GZMTRH(0)
      IF(LMTRH.NE.0) THEN
        GZMUOT=LQ(LMTRH-IZMUOT)
        IF(ITRAK.GE.2) THEN 
          DO I=1,ITRAK-1
            IF(GZMUOT. LE. 0) RETURN
            GZMUOT=LQ(GZMUOT)
          ENDDO   
        ENDIF
      ENDIF
      RETURN
      END
