      INTEGER FUNCTION GZPMUO(ITRAK)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK PMUO 
CC    PMUO IS A LINEAR BANK, THIS POINTS TO 
CC    TRACK ITRAK (OR TRACK 1 IF ITRAK =0) 
CC    WHERE ITRAK IS THE 'ITRAK' TRACK IN LINESR STRUCTURE
CC
CC    HEDIN 12-3-89
CC    KUNORI 29-MAR-90  USE 'LZFIND'
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZPMUO.LINK'
      INTEGER I,ITRAK,LPARH,GZPARH
      INTEGER LZFIND
      EXTERNAL LZFIND
C
      GZPMUO=0
      LPARH=GZPARH()
      IF(LPARH.NE.0) THEN
        IF(ITRAK.LE.0) THEN
          GZPMUO=LQ(LPARH-IZPMUO)
        ELSE
          I=ITRAK
          GZPMUO=LZFIND(IXCOM,LPARH-IZPMUO,I,-5) 
        ENDIF
C
      ENDIF
      RETURN
      END
