      INTEGER FUNCTION GZSTTH(ITRAK)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK STTH 
CC    WHERE ITRAK IS THE 'ITRAK' TRACK IN LINESR STRUCTURE
CC
CC    Created 7-MAY-1991 O.Eroshin
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZSTTH.LINK'
      INTEGER  ITRAK,LMUOT,GZMUOT
C
      GZSTTH =0
      LMUOT  = GZMUOT(ITRAK)
      IF(LMUOT.NE.0) THEN
        GZSTTH = LQ(LMUOT-IZSTTH)
      ENDIF
      RETURN
      END
