      SUBROUTINE MU_WAM_CEN_B_L2(MCELL,I,MCELL_OUT,NCLUSTERS)
C  Centroid positions for CF-layer module
C  Created 6-90  M. Fortner
C  MADE TO USE IN L2 OVERLAP CODE; 4/93 DF
C
      IMPLICIT NONE
      INTEGER MCELL(26,4),I,MCELL_OUT(26,4),NCLUSTERS,J
      LOGICAL FOUND
C
      J = NCLUSTERS + 1
      FOUND = .FALSE.
C
C                       LEFT SIDE / ODD CELL
      IF(MCELL(I,1).NE.0.AND.MCELL(I+2,3).NE.0) THEN
C	IF (MCELL_OUT(I,1).NE.0.AND.MCELL_OUT(I+2,3).EQ.0) 
C     1      MCELL_OUT(I+2,3)=MCELL_OUT(I,1)
C	IF (MCELL_OUT(I,1).EQ.0.AND.MCELL_OUT(I+2,3).NE.0)
C     1      MCELL_OUT(I,1)=MCELL_OUT(I+2,3)
	IF (MCELL_OUT(I,1).EQ.0.AND.MCELL_OUT(I+2,3).EQ.0) THEN
	  MCELL_OUT(I,1) = J
          MCELL_OUT(I+2,3) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF(MCELL(I+1,1).NE.0.AND.MCELL(I+1,2).NE.0) THEN
	IF (MCELL_OUT(I+1,1).NE.0.AND.MCELL_OUT(I+1,2).EQ.0) 
     1      MCELL_OUT(I+1,2)=MCELL_OUT(I+1,1)
	IF (MCELL_OUT(I+1,1).EQ.0.AND.MCELL_OUT(I+1,2).NE.0)
     1      MCELL_OUT(I+1,1)=MCELL_OUT(I+1,2)
	IF (MCELL_OUT(I+1,1).EQ.0.AND.MCELL_OUT(I+1,2).EQ.0) THEN
	  MCELL_OUT(I+1,1) = J
          MCELL_OUT(I+1,2) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF(MCELL(I+1,1).NE.0.AND.MCELL(I+1,3).NE.0) THEN
	IF (MCELL_OUT(I+1,1).NE.0.AND.MCELL_OUT(I+1,3).EQ.0) 
     1      MCELL_OUT(I+1,3)=MCELL_OUT(I+1,1)
	IF (MCELL_OUT(I+1,1).EQ.0.AND.MCELL_OUT(I+1,3).NE.0)
     1      MCELL_OUT(I+1,1)=MCELL_OUT(I+1,3)
	IF (MCELL_OUT(I+1,1).EQ.0.AND.MCELL_OUT(I+1,3).EQ.0) THEN
	  MCELL_OUT(I+1,1) = J
          MCELL_OUT(I+1,3) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF(MCELL(I+1,2).NE.0.AND.MCELL(I+1,3).NE.0) THEN
	IF (MCELL_OUT(I+1,2).NE.0.AND.MCELL_OUT(I+1,3).EQ.0) 
     1      MCELL_OUT(I+1,3)=MCELL_OUT(I+1,2)
	IF (MCELL_OUT(I+1,2).EQ.0.AND.MCELL_OUT(I+1,3).NE.0)
     1      MCELL_OUT(I+1,2)=MCELL_OUT(I+1,3)
	IF (MCELL_OUT(I+1,2).EQ.0.AND.MCELL_OUT(I+1,3).EQ.0) THEN
	  MCELL_OUT(I+1,2) = J
          MCELL_OUT(I+1,3) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF(MCELL(I,1).NE.0.AND.MCELL(I+1,2).NE.0) THEN
	IF (MCELL_OUT(I,1).NE.0.AND.MCELL_OUT(I+1,2).EQ.0) 
     1      MCELL_OUT(I+1,2)=MCELL_OUT(I,1)
	IF (MCELL_OUT(I,1).EQ.0.AND.MCELL_OUT(I+1,2).NE.0)
     1      MCELL_OUT(I,1)=MCELL_OUT(I+1,2)
	IF (MCELL_OUT(I,1).EQ.0.AND.MCELL_OUT(I+1,2).EQ.0) THEN
	  MCELL_OUT(I,1) = J
          MCELL_OUT(I+1,2) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF(MCELL(I+2,1).NE.0.AND.MCELL(I,3).NE.0) THEN
C	IF (MCELL_OUT(I+2,1).NE.0.AND.MCELL_OUT(I,3).EQ.0) 
C     1      MCELL_OUT(I,3)=MCELL_OUT(I+2,1)
C	IF (MCELL_OUT(I+2,1).EQ.0.AND.MCELL_OUT(I,3).NE.0)
C     1      MCELL_OUT(I+2,1)=MCELL_OUT(I,3)
	IF (MCELL_OUT(I+2,1).EQ.0.AND.MCELL_OUT(I,3).EQ.0) THEN
	  MCELL_OUT(I+2,1) = J
          MCELL_OUT(I,3) = J
          FOUND = .TRUE.
	END IF
      END IF
C
C                       RIGHT SIDE / EVEN CELL
      IF(MCELL(I+2,1).NE.0.AND.MCELL(I+1,2).NE.0) THEN
	IF (MCELL_OUT(I+2,1).NE.0.AND.MCELL_OUT(I+1,2).EQ.0) 
     1      MCELL_OUT(I+1,2)=MCELL_OUT(I+2,1)
	IF (MCELL_OUT(I+2,1).EQ.0.AND.MCELL_OUT(I+1,2).NE.0)
     1      MCELL_OUT(I+2,1)=MCELL_OUT(I+2,2)
	IF (MCELL_OUT(I+2,1).EQ.0.AND.MCELL_OUT(I+1,2).EQ.0) THEN
	  MCELL_OUT(I+2,1) = J
          MCELL_OUT(I+1,2) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF(MCELL(I+1,1).NE.0.AND.MCELL(I+2,3).NE.0) THEN
	IF (MCELL_OUT(I+1,1).NE.0.AND.MCELL_OUT(I+2,3).EQ.0) 
     1      MCELL_OUT(I+2,3)=MCELL_OUT(I+1,1)
	IF (MCELL_OUT(I+1,1).EQ.0.AND.MCELL_OUT(I+2,3).NE.0)
     1      MCELL_OUT(I+1,1)=MCELL_OUT(I+2,3)
	IF (MCELL_OUT(I+1,1).EQ.0.AND.MCELL_OUT(I+2,3).EQ.0) THEN
	  MCELL_OUT(I+1,1) = J
          MCELL_OUT(I+2,3) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF(MCELL(I+2,1).NE.0.AND.MCELL(I+1,3).NE.0) THEN
	IF (MCELL_OUT(I+2,1).NE.0.AND.MCELL_OUT(I+1,3).EQ.0) 
     1      MCELL_OUT(I+1,3)=MCELL_OUT(I+2,1)
	IF (MCELL_OUT(I+2,1).EQ.0.AND.MCELL_OUT(I+1,3).NE.0)
     1      MCELL_OUT(I+2,1)=MCELL_OUT(I+1,3)
	IF (MCELL_OUT(I+2,1).EQ.0.AND.MCELL_OUT(I+1,3).EQ.0) THEN
	  MCELL_OUT(I+2,1) = J
          MCELL_OUT(I+1,3) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF(MCELL(I+1,2).NE.0.AND.MCELL(I+2,3).NE.0) THEN
	IF (MCELL_OUT(I+1,2).NE.0.AND.MCELL_OUT(I+2,3).EQ.0) 
     1      MCELL_OUT(I+2,3)=MCELL_OUT(I+1,2)
	IF (MCELL_OUT(I+1,2).EQ.0.AND.MCELL_OUT(I+2,3).NE.0)
     1      MCELL_OUT(I+1,2)=MCELL_OUT(I+2,3)
	IF (MCELL_OUT(I+1,2).EQ.0.AND.MCELL_OUT(I+2,3).EQ.0) THEN
	  MCELL_OUT(I+1,2) = J
          MCELL_OUT(I+2,3) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF(MCELL(I+2,2).NE.0.AND.MCELL(I+1,3).NE.0) THEN
	IF (MCELL_OUT(I+2,2).NE.0.AND.MCELL_OUT(I+1,3).EQ.0) 
     1      MCELL_OUT(I+1,3)=MCELL_OUT(I+2,2)
	IF (MCELL_OUT(I+2,2).EQ.0.AND.MCELL_OUT(I+1,3).NE.0)
     1      MCELL_OUT(I+2,2)=MCELL_OUT(I+1,3)
	IF (MCELL_OUT(I+2,2).EQ.0.AND.MCELL_OUT(I+1,3).EQ.0) THEN
	  MCELL_OUT(I+2,2) = J
          MCELL_OUT(I+1,3) = J
          FOUND = .TRUE.
	END IF
      END IF
      IF (FOUND) NCLUSTERS = NCLUSTERS + 1
      RETURN
      END
