C VAX/DEC CMS REPLACEMENT HISTORY, Element MUADD.FOR
C *1    15-SEP-1993 17:48:10 DARIEN "New MF code for 1B MUD1"
C VAX/DEC CMS REPLACEMENT HISTORY, Element MUADD.FOR
      SUBROUTINE MUADD(IADD,NMOD,NPLN,NWIR,JERR)
C     ================================================
C     ROUTINE TO UNPACK MUON DRIFT CELL ADDRESS
C     INPUT IS IADD -- ADDRESS
C     OUTPUT IF MODULE,PLANE,WIRE
C      JERR=0 THEN OK
C
C     DH 9-10-85
CC  DH 10-86  FIRST WIRE IS 0, PLANES AND MODULES START FROM 1
CC      4-87 DIFFERENT ADDRESSING (16 BITS), PLANES 0-3
CC  KLUGE 3/88
C   MOVE OFF TOP ORDER BITS
C     DH 4/89 PUT BACK IN ERROR CHAECKING. SET UP FOR BASEMENT 3 MODULES
C     DH 10/89 NEW FORMAT
C     DH 2/90 USE LOWER 17 BITS FOR ADDRESS
C     EM 3/90 USE MUMDAT TO GET WIR&PLN INFO.
C     dh 11/90 use version number for MC vs data
C     DH 12/92 no error checking (use MUADD2 for errors
C     MF 9/13 drop MC support for 1B version
C     ================================================
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INTEGER IADD,NMOD,NPLN,NWIR,JERR
      INTEGER J
C
      JERR=0
      NMOD=IBITS(IADD,8,9)
      J=IBITS(IADD,0,8)
      NWIR=J/4
      NPLN=J-NWIR*4
C
      RETURN
      END
