      SUBROUTINE MUCALIB_OUT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    sees if should write out SMUO bank at the end of the
CC    MUCALIB job
CC
CC    March 1992, D. Hedin...v 2 change name of output file
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INTEGER IER,MUCALIB,CALIB_OUT,UNIT
      INTEGER GZSMUO,IERR
      LOGICAL OK
      CALL EZGET('MUCALIB',MUCALIB,IER)
      CALL EZGET('CALIB_OUT',CALIB_OUT,IER)
      IF(CALIB_OUT.GE.1) THEN
        CALL GTUNIT(789,UNIT,IERR)
        IF(IERR.EQ.0) THEN
          CALL D0OPEN(UNIT,'SMUO_MUCALIB.OUT','OU',OK)
          CALL FZFILE(UNIT,0,'O')
          LSMUO=GZSMUO('STPC')
          IF(LSMUO.NE.0) THEN
            CALL FZOUT(UNIT,IDVSTP,LSMUO,1,' ',1,0,0)
            CALL INTMSG(' SMUO_MUCALIB.OUT saved from MUCALIB_OUT ')
          ENDIF
          CALL RLUNIT(789,UNIT,IERR)
        ELSE
          CALL INTMSG(' MCONST:GTUNIT error ')
        ENDIF
      ENDIF
  999 RETURN
      END
