      SUBROUTINE MUGEOM(IMOD,IPLN,IWIR,VECT,WLEN,VOFF,IORENT)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC
CC    RETURNS THE LOCATION IN THE GLOBAL COORDINATE (VECT) OF THE
CC    CENTER OF WIRE IWIR IN PLANE IPLN AND MODULE IMOD
CC    ALSO WIRE LENGTH WLEN AND VERNIER OFFSET VOFF
CC     ALSO WIRE ORIENTATION IORENT 1=VERTICAL CENTRAL 2=HORIZONTAL CENTRAL
CC    THIS ORIENTATION IS A SIMPLIFICATION OF THE 16 DIFFERENT
CC    ORIENTATIONS POSSIBLE AS THE TRACKING DOES NOT NEED ALL THAT INFO
CC    LOOK AT THE CONVERSION ARRAY BELOW
CC
CC    11-6-85   HEDIN
CC    MODIFIED FOR TEST GEOMETRY 1-23-86 HEDIN
CC    FIRST WIRE IS WIRE 0  10-86     
CC    FIRST PLANE IS PLANE 0 4-87
CC    DH 12-87 ALLOW ELECTRONICS AT BOTH ENDS
CC    DH 12-87   GET INFO FROM CALIB FILE
CC    DH 9-88  REDO +/- SIGNS ON ORIENTATION CONVERSION
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INTEGER IMOD,IPLN,IWIR,IORENT,IT
      REAL SPAR(3),XPAR(3),ROTM(3,3),VOFF
      INTEGER NSPAR,NBUF,IBUF(1),ICONSH(16)
      CHARACTER*4 HSHAPE
C
      REAL WLEN,VECT(3)
C
CCC   COVERT FROM 16 ORIENTATIONS TO TRACKING ORIENTATIONS
CCC   THESE MAY NOT BE RIGHT
      DATA ICONSH/
CC    MINUS MEANS ELECTRONICS NOT ON LOWEST END IN GLOBAL
CC    DNE DSW ENU ESD UNW USE WND WSU      CENTRAL
     A  2, -2,  1, -1, -2,  2, -1,  1, 
CC    NDW NED NUE NWU SDE SEU SUW SWD      ENDS
     A -4, -3,  4,  3,  4,  3, -4, -3/
CC
      CALL MUCELL(IMOD,IPLN,IWIR,HSHAPE,NSPAR,SPAR,XPAR,ROTM,VOFF,
     A NBUF,IBUF)
CC
      DO 1 IT=1,3
 1    VECT(IT)=XPAR(IT)     ! LOCATION OF CENTER OF WIRE
      IORENT=ICONSH(IBUF(1)) ! CONVERT ORIENTATION
      WLEN=2.*SPAR(3)        ! TOTAL WIRE LENGTH
CC
      RETURN
      END
