      SUBROUTINE PRMFIT(ITRAK,PRUNIT)
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : UNPACK MFIT BANK
C-
C-   Inputs  : ITRAK.PRUNIT
C-   Outputs : 
C-   Controls: 
C-
C-   Created  10-DEC-1991   A.Klatchko
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INTEGER ITRAK,LMFIT,GZMFIT,PRUNIT
C----------------------------------------------------------------------
      LMFIT = GZMFIT(ITRAK)
      WRITE(PRUNIT,*)'NUMBER OF WIDE ANGLE POINTS,10A+B=',IQ(LMFIT+2)
      WRITE(PRUNIT,*)'NUMBER OF WIDE SMALL POINTS,10A+B=',IQ(LMFIT+3)
      WRITE(PRUNIT,*)'QUADRANT NUMBER=',IQ(LMFIT+4),'FIT DIMENSION=',   
     &    IQ(LMFIT+5)
      WRITE(PRUNIT,*)'FIT ORIGIN=',IQ(LMFIT+6),'FIT METHOD=',IQ(LMFIT+7)
      WRITE(PRUNIT,*)'QUALITY FLAG=',IQ(LMFIT+8)
      WRITE(PRUNIT,*)'CHARGE=',IQ(LMFIT+10)
      WRITE(PRUNIT,*)'MUON COORDINATES IN ORIGIN=',Q(LMFIT+11),
     &  Q(LMFIT+12),Q(LMFIT+13)   
      WRITE(PRUNIT,*)'MUON COORDINATES IN MAGNET=',Q(LMFIT+14),
     &  Q(LMFIT+15),Q(LMFIT+16)   
      WRITE(PRUNIT,*)'DIRECTION COSINES OUT OF MAGNET=',Q(LMFIT+17),
     &  Q(LMFIT+18),Q(LMFIT+19)   
      WRITE(PRUNIT,*)'MUON MOMENTUM PX,PY,PZ,P,PT=',Q(LMFIT+20),
     &  Q(LMFIT+21),Q(LMFIT+22),Q(LMFIT+23),Q(LMFIT+24)   
      WRITE(PRUNIT,*)'MUON MOMENTUM ERROR PX,PY,PZ,P,PT=',Q(LMFIT+25),
     &  Q(LMFIT+26),Q(LMFIT+27),Q(LMFIT+28),Q(LMFIT+29)   
      WRITE(PRUNIT,*)'CHI SQUARED PER DEGREE OF FREEDOM=',Q(LMFIT+30)
      WRITE(PRUNIT,*)'MEAN MAGNETIC FIELD=',Q(LMFIT+31)
      WRITE(PRUNIT,*)'ENERGY LOSS IN THE CALORIMETER=',Q(LMFIT+32)
      WRITE(PRUNIT,*)'ENERGY LOSS IN THE TOROID=',Q(LMFIT+33)
  999 RETURN
      END
