      SUBROUTINE PRMTRG(PRUNIT,LMTRG)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC
CC    PRINT OUT MTRG - MUON TRIGGER BANKS; FROM TRGR BANK
CC
CC    PRUNIT - UNIT NUMBER FOR PRINTOUT
CC    LMUOH - BANK ADDRESS
CC
CC    D. FEIN  27-FEB-1992
C-    Modified MF 12/93 IBM/unix compatibility
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INTEGER PRUNIT,LMTRG,LTRG,ND,GZMTRG
      INTEGER HEAD,SYNC,CONT,VERS,REVS,TRIG,DATA1,L1,L15,CRATE
      INTEGER I,J,K,FILE,OTC(16),CCT,INFO,NOTC,LOTC(16),STAT(16)
      INTEGER COUNT,DATA(2,100),TWC,TOKEN,CHECK
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      LTRG=LMTRG
      IF(LTRG.EQ.0) THEN
  100   FORMAT(' NO MTRG BANK')
        LTRG=GZMTRG(0)
        IF(LTRG.EQ.0) THEN
          WRITE(PRUNIT,100)
          RETURN
        ENDIF
      ENDIF
C
      CRATE = 0
      J = 10
      ND = IQ(LMTRG - 1)   ! TOT # OF WORDS IN BANK
  101 FORMAT('     BANK MTRG : MUON TRIGGER INFORMATION(L1 & L1.5) '/)
      WRITE(PRUNIT,101)
  102 FORMAT('  LEVEL 1 TRIGGER CRATE INFORMATION '/)
      WRITE(PRUNIT,102)
      HEAD = IQ(LMTRG+1)
      SYNC = IQ(LMTRG+2)
      CONT = IQ(LMTRG+3)
      VERS = IQ(LMTRG+4)
      REVS = IQ(LMTRG+5)
      TRIG = IQ(LMTRG+6)
      DATA1 = IQ(LMTRG+7)
      L1   = IQ(LMTRG+8)
      L15  = IQ(LMTRG+9)
      CALL MVBITS(CONT,24,8,CRATE,0)
      WRITE(PRUNIT,110)CRATE
      WRITE(PRUNIT,111)SYNC
      WRITE(PRUNIT,112)CONT
      WRITE(PRUNIT,113)VERS
      WRITE(PRUNIT,114)REVS
      WRITE(PRUNIT,115)TRIG
      WRITE(PRUNIT,116)DATA1
      WRITE(PRUNIT,117)L1
      WRITE(PRUNIT,118)L15
C
      WRITE(PRUNIT,*)
  103 FORMAT('  LEVEL 1.5 TRIGGER CRATE INFORMATION '/)
      WRITE(PRUNIT,103)
      IF (J.EQ.ND) GOTO 998
C
      DO WHILE (J.LT.ND)
        NOTC = 0
        COUNT = 0
        DO I = 1,16
          STAT(I) = 0
          LOTC(I) = 0
        END DO
        HEAD = IQ(LMTRG+J+1) ! # CRATE WORDS - 1
        SYNC = IQ(LMTRG+J+2)
        CONT = IQ(LMTRG+J+3)
        VERS = IQ(LMTRG+J+4)
        TRIG = IQ(LMTRG+J+5)
        FILE = IQ(LMTRG+J+6)
        INFO = IQ(LMTRG+J+7)
        CCT  = IQ(LMTRG+J+8)
        DO I = 1,16
          OTC(I) = IQ(LMTRG+J+8+I)
          CALL MVBITS(OTC(I),16,16,LOTC(I),0)
          CALL MVBITS(OTC(I),0,16,STAT(I),0)
        END DO
        I = IQ(LMTRG+J+25)            ! BEGIN DATA MARKER = 0
        CALL MVBITS(CONT,24,8,CRATE,0)
        CALL MVBITS(CONT,16,8,NOTC,0)
        WRITE(PRUNIT,110)CRATE
        WRITE(PRUNIT,111)SYNC
        WRITE(PRUNIT,112)CONT
        WRITE(PRUNIT,113)VERS
        WRITE(PRUNIT,119)TRIG
        WRITE(PRUNIT,120)FILE
        WRITE(PRUNIT,121)INFO
        WRITE(PRUNIT,122)CCT
        WRITE(PRUNIT,*)
        IF (NOTC.EQ.8) THEN
          WRITE(PRUNIT,123)(LOTC(I),I=1,NOTC)
          WRITE(PRUNIT,124)(STAT(I),I=1,NOTC)
        ELSE
          IF (NOTC.EQ.12) THEN
            WRITE(PRUNIT,127)(LOTC(I),I=1,NOTC)
            WRITE(PRUNIT,128)(STAT(I),I=1,NOTC)
          ELSE
            WRITE(PRUNIT,131)(LOTC(I),I=1,NOTC)
            WRITE(PRUNIT,132)(STAT(I),I=1,NOTC)
          END IF
        END IF
C
        IF (IQ(LMTRG+J+26).EQ.(HEAD+1)) THEN
          WRITE(PRUNIT,*)
          WRITE(PRUNIT,*)'    NO DATA FOR THIS CRATE'
          GOTO 910
        ELSE
  800     COUNT = COUNT + 1
          DATA(1,COUNT) = IQ(LMTRG+J+25+(2*COUNT-1))
          DATA(2,COUNT) = IQ(LMTRG+J+25+(2*COUNT))
          IF (IQ(LMTRG+J+25+(2*COUNT+1)).EQ.(HEAD+1)) THEN
            GOTO 900
          ELSE
            GOTO 800
          END IF
        END IF
  900   WRITE(PRUNIT,*)
        WRITE(PRUNIT,*)
        WRITE(PRUNIT,149)
        WRITE(PRUNIT,157)
        WRITE(PRUNIT,150)
        DO I = 1,COUNT
          WRITE(PRUNIT,151)I,DATA(1,I),DATA(2,I)
        END DO
        WRITE(PRUNIT,*)
  910   TWC = IQ(LMTRG+J+26+(2*COUNT))
        TRIG = IQ(LMTRG+J+27+(2*COUNT))
        TOKEN = IQ(LMTRG+J+28+(2*COUNT))
        CHECK = IQ(LMTRG+J+29+(2*COUNT))
        WRITE(PRUNIT,*)
        WRITE(PRUNIT,152)
        WRITE(PRUNIT,153)TWC
        WRITE(PRUNIT,154)TRIG
        WRITE(PRUNIT,155)TOKEN
        WRITE(PRUNIT,156)CHECK
C
        J = J + HEAD + 1
      END DO
C
  110 FORMAT('  CRATE #           ',I8)
  111 FORMAT('  SYNC WORD         ',Z8)
  112 FORMAT('  CONTROLLER WORD   ',Z8)
  113 FORMAT('  VERSION NUMBER    ',Z8)
  114 FORMAT('  REVISION NUMBER   ',Z8)
  115 FORMAT('  SPECIFIC TRIGGER  ',Z8)
  116 FORMAT('  DATA BLOCK COUNT  ',I8)
  117 FORMAT('  L1 MUON TRIG BIT  ',Z8)
  118 FORMAT('  L15 MUON TRIG BIT ',Z8)
  119 FORMAT('  RUN TRIGGER TYPE  ',Z8)
  120 FORMAT('  DOWNLOAD FILE(S)  ',Z8)
  121 FORMAT('  OTC INFO WORD     ',Z8)
  122 FORMAT('  CCT LATCH WORD    ',Z8)
  123 FORMAT('  OTC #  ',8I5)
  124 FORMAT('  STATUS ',8Z5)
  127 FORMAT('  OTC #  ',12I5)
  128 FORMAT('  STATUS ',12Z5)
  131 FORMAT('  OTC #  ',16I5)
  132 FORMAT('  STATUS ',16Z5)
  149 FORMAT('         OTC DATA BLOCK')
  150 FORMAT('  HIT #    FIRST WORD    SECOND WORD')
  151 FORMAT(3X,I2,6X,Z8,7X,Z8)
  152 FORMAT('       OTC CRATE TRAILER'/)
  153 FORMAT('  TOTAL WORD COUNT  ',I8)
  154 FORMAT('  TRIG # | CRATE ID ',Z8)
  155 FORMAT('  TOKEN PASS STATUS ',Z8)
  156 FORMAT('  CHECKSUM          ',Z8)
  157 FORMAT('         --------------'/)
C
      GOTO 999
C
  998 WRITE(PRUNIT,*)'  NO 1.5 TRIGGER CRATE INFORMATION '
  999 RETURN
      END
