C DEC/CMS REPLACEMENT HISTORY, Element PRMTRH.FOR
C *1     9-DEC-1986 17:08:18 HEDIN "MUON ZEBRA UTILITY"
C DEC/CMS REPLACEMENT HISTORY, Element PRMTRH.FOR
      SUBROUTINE PRMTRH(PRUNIT,LMTRH,NMTRH,CFL,IFL)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC
CC    PRINT OUT MTRH - MUON TRACK HEADER  
CC
CC    PRUNIT - UNIT NUMBER FOR PRINTOUT
CC    LMTRH - BANK ADDRESS
CC    NMTRH - BANK NUMBER
CC    CFL - FLAG TO CONTROL PRINT OUT
CC    IFL - HOW MUCH TO PRINT
CC
CC    THERE WILL ONLY BE A SINGLE MUON TRACK HEADER
CC    SO IGNORE CFL
CC
CC    DH  11-86
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INTEGER PRUNIT,LMTRH,NMTRH,IFL,LHIT
      CHARACTER CFL*(*)
      INTEGER   GZMTRH
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      LHIT=LMTRH
      IF(LHIT.EQ.0) THEN
 100      FORMAT(' NO MTRH BANK')
        LHIT=GZMTRH(0) 
        IF(LHIT.EQ.0) THEN
          WRITE(PRUNIT,100)
          RETURN
        ENDIF
      ENDIF
C
      IF(IFL.NE.0) THEN          ! PARTIAL PRINTOUT
        WRITE(PRUNIT,101)
 101    FORMAT('0',10X,' BANK MTRH: MUON TRACK HEADER    '//
     A  ' #MUON TRACKS FOUND ')
        WRITE(PRUNIT,102) IQ(LHIT+1)
 102    FORMAT(3I10/)
      ENDIF
      IF(IFL.EQ.0) THEN           ! COMPLETE PRINTOUT
C
        WRITE(PRUNIT,101)
        WRITE(PRUNIT,102) IQ(LHIT+1)
      ENDIF
      RETURN
      END
