      SUBROUTINE PRMUHT(PRUNIT,LMUHT,NMUHT,CFL,IFL)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC
CC    PRINT OUT MUHT - MUON HITS HEADER   
CC
CC    PRUNIT - UNIT NUMBER FOR PRINTOUT
CC    LMUHT - BANK ADDRESS
CC    NMUHT - BANK NUMBER
CC    CFL - FLAG TO CONTROL PRINT OUT
CC    IFL - HOW MUCH TO PRINT
CC
CC    THERE WILL ONLY BE A SINGLE MUON HIT HEADER
CC    SO IGNORE CFL
CC
CC    DH  11-86
C       15-DEC-1993 S. Hagopian -  Use either Run Ia or Ib format
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INTEGER PRUNIT,LMUHT,NMUHT,IFL,LHIT
      CHARACTER CFL*(*)
      INTEGER N,GZMUHT
      INTEGER NBANK
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      LHIT=LMUHT
      IF(LHIT.EQ.0) THEN
 100      FORMAT(' NO MUHT BANK')
        LHIT=GZMUHT(0) 
        IF(LHIT.EQ.0) THEN
          WRITE(PRUNIT,100)
          RETURN
        ENDIF
      ENDIF
C
      IF(IFL.NE.0) THEN          ! PARTIAL PRINTOUT
        WRITE(PRUNIT,101)
 101    FORMAT('0',10X,' BANK MUHT: MUON HIT HEADER    '//
     A  '   #RAW MUON HITS   #MUON HITS   #MUON MODULES HIT ')
        WRITE(PRUNIT,102) IQ(LHIT+1),IQ(LHIT+2),IQ(LHIT+3)
 102    FORMAT(3I14/)
      ENDIF
      IF(IFL.EQ.0) THEN           ! COMPLETE PRINTOUT
C
        WRITE(PRUNIT,101)
        WRITE(PRUNIT,102) IQ(LHIT+1),IQ(LHIT+2),IQ(LHIT+3)
        NBANK=IQ(LHIT-1)
        WRITE(PRUNIT,103) (IQ(LHIT+N),N=11,NBANK)
 103    FORMAT(' POINTER INTO MUOF ',/16(20I4/)//)
      ENDIF
      RETURN
      END
