      SUBROUTINE PRSAMH(PRUNIT,LSAMH,NSAMH,CFL,IFL)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC
CC    PRINT OUT SAMH - PROCESSED MUON HITS
CC
CC    PRUNIT - UNIT NUMBER FOR PRINTOUT
CC    LSAMH - BANK ADDRESS
CC    NSAMH - BANK NUMBER
CC    CFL - FLAG TO CONTROL PRINT OUT
CC    IFL - HOW MUCH TO PRINT
CC
CC    THERE WILL ONLY BE A SINGLE RAW MUON BANK
CC    SO IGNORE CFL
CC
CC    O.Eroshin 20-MAR-1991
C-   Updated  13-JUN-1991   Daria Zieminska corrected a write statement;
C-                          corrected IADD 
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INTEGER PRUNIT,LSAMH,NSAMH,IFL,LHIT
      CHARACTER CFL*(*)
      INTEGER LZLOC,NMUONH,I,J,K,L,N,GZSAMH,NST,NPL
      INTEGER IADD,IMOD(8),IPLN(8),ICELL(8),IERR
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IF(IFL.NE.0) THEN          ! PARTIAL PRINTOUT
        WRITE(PRUNIT,101)
 101    FORMAT('0',10X,' BANK SAMH: MUON PROCESSED HITS'//
     A  '  ADDRESS    TYPE  X WIRE  Y WIRE  Z WIRE ')
      END IF
      DO 100 NST=1,6
        DO 200 NPL=1,3
          LHIT=GZSAMH(NST,NPL)
          IF (LHIT.EQ.0) GO TO 200
C
      NMUONH=IQ(LHIT-1)/15       ! 15 WORDS/HIT
      IF(IFL.NE.0) THEN          ! PARTIAL PRINTOUT
        DO 10 I=1,NMUONH
        K=15*(I-1)+LHIT
        IADD = IQ(K+2)
        CALL SAADD(IADD,IMOD(1),ICELL(1),IERR)
        WRITE(PRUNIT,102)IMOD(1),ICELL(1),IQ(K+5),(Q(K+J),J=6,8)
 102    FORMAT(1X,2I4,4x,I3,1X,3F8.2)
 10     CONTINUE
      ENDIF
      IF(IFL.EQ.0) THEN           ! COMPLETE PRINTOUT
C
        WRITE(PRUNIT,103)
 103    FORMAT('0',10X,' BANK SAMH: MUON PROCESSED HITS'//)
        J=0
  20    CONTINUE
        K=8
        L=LHIT+15*J
        IF(J+K.GT.NMUONH) K=NMUONH-J
        J=J+K
        DO 30 N = 1,K
        IADD = IQ(L+15*(N-1)+2)
        CALL SAADD(IADD,IMOD(N),ICELL(N),IERR)
 30     CONTINUE
        WRITE(PRUNIT,111)(IQ(L+15*(N-1)+1),N=1,K)
        WRITE(PRUNIT,112)(IMOD(N),ICELL(N),N=1,K)
        WRITE(PRUNIT,113)(IQ(L+15*(N-1)+5),N=1,K)
        WRITE(PRUNIT,114)(Q(L+15*(N-1)+ 6),N=1,K)
        WRITE(PRUNIT,115)(Q(L+15*(N-1)+ 7),N=1,K)
        WRITE(PRUNIT,116)(Q(L+15*(N-1)+ 8),N=1,K)
        WRITE(PRUNIT,117)(Q(L+15*(N-1)+ 9),N=1,K)
        WRITE(PRUNIT,118)(Q(L+15*(N-1)+10),N=1,K)
        WRITE(PRUNIT,119)(Q(L+15*(N-1)+11),N=1,K)
        WRITE(PRUNIT,120)(Q(L+15*(N-1)+12),N=1,K)
        WRITE(PRUNIT,121)(Q(L+15*(N-1)+13),N=1,K)
        WRITE(PRUNIT,122)(Q(L+15*(N-1)+14),N=1,K)
        WRITE(PRUNIT,123)(Q(L+15*(N-1)+15),N=1,K)
        WRITE(PRUNIT,140)
        IF(J.LT.NMUONH) GO TO 20
      ENDIF
  200 CONTINUE
  100 CONTINUE
 111  FORMAT(' FLAG    ',8(1X,I8))
 112  FORMAT(' WIR_ADD ',8(1X,I4,1X,I3))
 113  FORMAT(' TYPE    ',8(1X,I8))
 114  FORMAT(' X WIRE  ',8F9.1)
 115  FORMAT(' Y WIRE  ',8F9.1)
 116  FORMAT(' Z WIRE  ',8F9.1)
 117  FORMAT(' VX WIRE ',8F9.1)
 118  FORMAT(' VY WIRE ',8F9.1)
 119  FORMAT(' VZ WIRE ',8F9.1)
 120  FORMAT(' TIME    ',8F9.1)
 121  FORMAT(' DEL T   ',8F9.1)
 122  FORMAT(' DIST    ',8F9.1)
 123  FORMAT(' DEL D   ',8F9.1)
 140  FORMAT('0')
      RETURN
      END
