      SUBROUTINE TOP_FIT_SETUP_SMEAR
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : SETS UP SMEAR RESOLUTIONS
C-
C-   Inputs  :
C-   Outputs :
C-   Controls:
C-
C-   Created  13-MAR-1994   Rajendran Raja
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:TOP_FIT_SMEAR.INC'
      INTEGER IER
C----------------------------------------------------------------------
C
      CALL EZPICK('TOP_FIT_RCP')
      CALL EZGET('ELECTRON_RESOLN',ELECTRON_RESOLN_S,IER)
      CALL EZGET('MUON_RESOLN',MUON_RESOLN_S,IER)
      CALL EZGET('JET_RESOLN',JET_RESOLN_S,IER)
      CALL EZGET('REST_RESOLN',REST_RESOLN_S,IER)
C
      CALL EZGET('ELEC_ETA_RESOLN',ELEC_ETA_RESOLN_S,IER)
      CALL EZGET('MUON_ETA_RESOLN',MUON_ETA_RESOLN_S,IER)
      CALL EZGET('JET_ETA_RESOLN',JET_ETA_RESOLN_S,IER)
C
      CALL EZGET('ELEC_PHI_RESOLN',ELEC_PHI_RESOLN_S,IER)
      CALL EZGET('MUON_PHI_RESOLN',MUON_PHI_RESOLN_S,IER)
      CALL EZGET('JET_PHI_RESOLN',JET_PHI_RESOLN_S,IER)
C
      CALL UCOPYSD(ELECTRON_RESOLN_S,ELECTRON_RESOLN,3)
      CALL UCOPYSD(MUON_RESOLN_S,MUON_RESOLN,3)
      CALL UCOPYSD(JET_RESOLN_S,JET_RESOLN,3)
      CALL UCOPYSD(REST_RESOLN_S,REST_RESOLN,3)
C
      CALL UCOPYSD(ELEC_ETA_RESOLN_S,ELEC_ETA_RESOLN,3)
      CALL UCOPYSD(MUON_ETA_RESOLN_S,MUON_ETA_RESOLN,3)
      CALL UCOPYSD(JET_ETA_RESOLN_S,JET_ETA_RESOLN,3)
      CALL UCOPYSD(ELEC_PHI_RESOLN_S,ELEC_PHI_RESOLN,3)
      CALL UCOPYSD(MUON_PHI_RESOLN_S,MUON_PHI_RESOLN,3)
      CALL UCOPYSD(JET_PHI_RESOLN_S,JET_PHI_RESOLN,3)
      CALL EZRSET
C
  999 RETURN
      END
