.FACILITY COMPACK 120 /PREFIX=COMPACK__

.SEVERITY INFORMATIONAL
    ILLCOL      "Illegal number of columns"

.SEVERITY SEVERE
    NOMATCH 	"No setup menu matches --> !AS"
    NOSETUP	"No logical definition for setup file --> !AS"

.SEVERITY INFORMATIONAL
    NOSMG	"Full screen operations have been disabled"
    UNIMPL	"Unimplemented command -->"
    AMBIG	"Ambigous command -->"
    OUTRANGE	"Selection out of range"
    NOFILE      "File open failed (not found?)"
    NOTVALID	"Not a valid selection --> " 
    BADSPL	"Number in split part must be 3 -" 
    ILLINT	"Bad character in INTEGER --> "
    ILLREA	"Bad character in REAL number --> "
    NOSLOT	"No more menu slots available"
    REALIM	"Real number outside limits"
    INTLIM	"Integer outside limits"
    NOFILS	"No files available in this directory"
    LENSTR	"String too long to be converted to integer"
    NONEST	"Command files cannot be nested"
    NOOPT	"No match with any of the options"
    ILLSPA      "Illegal spacing [1--3 allowed]"

.SEVERITY SEVERE
    MAXLEV	"Maximum number of sublevels exceeded"
    MAXPAR	"Maximum allowed number of parameters is currently !AS"
    ALREXIST	"Menu level already exists: !AS"

.END

