      SUBROUTINE INTMEN(TOPS,USENAM,DSPNAM)
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : Setup interrupt menu and return to main task.
C-
C-   Inputs  : TOPS:   Title for top of display.
C-             USENAM: Name of menu level to use
C-             DSPNAM: Name of dispatch routine to use (EXTERNAL)
C-   Outputs : None
C-   Controls: Interrupt menu will take control of menu part of screen
C-
C-   Created  22-SEP-1988   Jan S. Hoftun
C-
C-      27-Oct-1989 Penelope Constanta-Fanourakis      
C-          Replaced closing of LUN 5 with an assignement
C-	    of INPLUN to be 5
C-
C-   Revised   2-APR-1991   Scott Snyder
C-    smg$enable_unsolicited_input never calls the AST routine if
C-    there is data in the typeahead buffer when it's called.  So
C-    call QIOAST after SETQIO.  Also move the call to MENDIS to before
C-    SETQIO - QIOAST can call MENDIS, and code generated by Digital's
C-    fortrash isn't exactly a paragon of reentrancy...
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      CHARACTER*(*) TOPS,USENAM
      EXTERNAL DSPNAM
C
C     Get definitions for COMPACK
C
      INCLUDE 'D0$PARAMS:MAXLEV.DEF'
      INCLUDE 'D0$INC:COMNUM.INC'
      INCLUDE 'D0$INC:COMCHR.INC'
      INCLUDE 'D0$INC:SMGCOM.INC'
C&IF VAXVMS
      INCLUDE '($SSDEF)'
C&ENDIF
      CHARACTER*40 BLNK
      CHARACTER*80 TNAM,TRANUP
      INTEGER I,USELEV,K,ISTAT,LIBSAV, SYS$SETAST
      DATA BLNK/' '/
      EXTERNAL QIOAST
C----------------------------------------------------------------------
      IF(.NOT.ASTFLG) THEN
        IF(RDCOM.AND.FSAVE) THEN
          FULSCR=.TRUE.
        ENDIF
        ISTAT=LIBSAV()      !Save screen
        PF=0
        USELEV=1
        TNAM=TRANUP(USENAM)
        DO I=1,MAXLEV
          IF(NAMLEV(I).EQ.TNAM) THEN
            USELEV=I
            GOTO 2
          ENDIF
        ENDDO
    2   CONTINUE
C
C     Set up current level of menu
C
        OLDLEV=CURLEV
        CURLEV=USELEV
        SAVLEV=USELEV
        SAVPOS=POS
C
C     Put title line in the center of TOPMEN if in setup mode or
C     in toplin(0) for safe-keeping if not in setup mode
C
        IF(.NOT.ONEFLG) THEN
          K=PBCOLS/4-(LEN(TOPS)+1)/2
          WRITE(TOPLIN(0,CURLEV),101) BLNK(1:K),TOPS
  101     FORMAT(2(A:))
        ENDIF
        ASTFLG=.TRUE.
        CANFLG=.FALSE.                         ! Indicate CANMEN hasn't been called to QIOAST
        PROMP1='In INTERRUPT mode: '//TOPS
        PROMP2='Select: {command, #, HELP (#), MENU } >'
        POS=1                                  ! Make sure to start with first item
        IF(.NOT.TRMFLG) THEN
          TRMFLG=SAVTRM                        ! TRMFLG=.FALSE. when NOT reading from terminal with SMG
          ! while in INTERRUPT mode, read from terminal if possible
        ENDIF
        IF(RDCOM.AND..NOT.SMGON) THEN
C          CLOSE(5)     ! Close command file to get interrupt menu to work
	  INPLUN=5	! Make input to be the terminal
          RDCOM=.FALSE.
        ENDIF
        CALL MENDIS(.TRUE.)                       ! Display menu
        CALL SETQIO(DSPNAM)
c
c boy, it sure would be nice to be able to use $dclast here.
c  but life is tough, and we can't, since QIOAST takes _two_ parameters...
c
C&IF VAXVMS
        ISTAT = SYS$SETAST(%VAL(0))
        CALL QIOAST(PASTID, DSPNAM)
        IF (ISTAT .EQ. SS$_WASSET)
     &    CALL SYS$SETAST(%VAL(1))
C&ENDIF
      ENDIF
      RETURN
      END
