      SUBROUTINE PAXGRM(PAX,IROT)
C-------------------------------------------------------------------
C
C     THIS SUBROUTINE CREATES A GEANT ROTATION BANK FROM THE 
C     PRINCIPLE AXIS ROTATION PARAMETERS.  THIS SUBROUTINE CALLS
C     PAXROT TO MAKE THE ROTATION MATRIX.  GEANT ANGLES ARE
C     EXTRACTED FROM THE MATRIX.
C
C     AUTHOR: S. KAHN              14 APRIL 1987
C
C-------------------------------------------------------------------
      IMPLICIT NONE
      REAL PAX(3), THETAD(3), PHID(3)
      REAL*8 THETA, PHI, WX, WY, WZ, ROTMAT(3, 3)
      INTEGER IROT, N
      INCLUDE 'D0$INC:PI.DEF'
C
C     GET ROTATION MATRIX FROM PRINCIPLE AXIS ANGLES
C
      CALL PAXROT(PAX, ROTMAT)
C
C     EXTRACT GEANT ANGLES
C
      DO 20 N= 1, 3
      WX = ROTMAT(1, N)
      WY = ROTMAT(2, N)
      WZ = ROTMAT(3, N)
C
      CALL POLANG(WX, WY, WZ, THETA, PHI)
      THETAD(N) = THETA/RADIAN
      PHID(N) = PHI/ RADIAN
  20  CONTINUE
C
C     LIFT GEANT ROTATION BANK
C
      CALL GSROTM(IROT,THETAD(1), PHID(1),THETAD(2),PHID(2),
     +  THETAD(3), PHID(3))
C
      RETURN
      END
