PACKAGE := muon_util
$(PACKAGE)_LIB := yes
include GNUmakefile.subcommon


MUON_UTIL_NO_RANGE_CHECK := mud1fl mud1sq1b
$(foreach f,$(MUON_UTIL_NO_RANGE_CHECK),tmp/DEB/muon_util/source/$(f).o tmp/OPT/muon_util/source/$(f).o) : FORT_COMMON_FLAGS += -fno-range-check
