PACKAGE := vtx_util
$(PACKAGE)_LIB := yes
$(PACKAGE)_EXCEPT_FOR := beamfit.for vtx_accum_tracks.for vtx_end_run.for \
                         vtx_find_beam.for  # structures
include GNUmakefile.subcommon
