CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VVTX_UTIL()
      VVTX_UTIL = ' VTX_UTIL'//
     X                   '  OFFICIAL V1.13'//
     X                   ' 27-JUL-1995 16:31:46.01'
      Return
      End
