!------------------------------------------------------------
!
! Name      : TRD_UTIL.MMS
!
! Purpose   : Update target: TRD_UTIL.TSP
!
! Created   2-SEP-97   09:27:35  USERLIB V6.00 18-FEB-1991
!------------------------------------------------------------
!

 
.FIRST
  @ D0$WARNING == 0
  @ D0$ERROR == 0
  @ D0$FATAL == 0
  @ ON WARNING THEN GOSUB ERROR_COUNT
 
.LAST
  @ EXIT
  @ ERROR_COUNT:
  @ IF $SEVERITY .EQ. 0 THEN D0$WARNING == D0$WARNING + 1
  @ IF $SEVERITY .EQ. 2 THEN D0$ERROR == D0$ERROR + 1
  @ IF $SEVERITY .EQ. 4 THEN D0$FATAL == D0$FATAL + 1
  @ ON WARNING THEN GOSUB ERROR_COUNT
  @ RETURN
  
.IFDEF DO_PRE
NOTHING.NL : SYS$LOGIN:LOGIN.COM
  @ WRITE SYS$OUTPUT "Executing Pre-processing Commands"
.ENDIF
  
  
 
.IFDEF DO_INTER
NOTHING.NL : SYS$LOGIN:LOGIN.COM
  @ WRITE SYS$OUTPUT "Executing Intermediate-processing Commands"
.ENDIF
  
  
 
.IFDEF DO_POST
NOTHING.NL : SYS$LOGIN:LOGIN.COM
  @ WRITE SYS$OUTPUT "Executing Post-processing Commands"
  @ IF F$SEARCH("D0$RELEASE:[TRD_UTIL.SOURCE]COSMIC_TRD.RCP") .NES. "" THEN -
  COPY/NOCONF/LOG D0$RELEASE:[TRD_UTIL.SOURCE]COSMIC_TRD.RCP D0$TRD_UTIL:
  @ IF F$SEARCH("D0$RELEASE:[TRD_UTIL.SOURCE]MC_TRD.RCP") .NES. "" THEN -
  COPY/NOCONF/LOG D0$RELEASE:[TRD_UTIL.SOURCE]MC_TRD.RCP D0$TRD_UTIL:
  @ IF F$SEARCH("D0$RELEASE:[TRD_UTIL.SOURCE]TRD.RCP") .NES. "" THEN -
  COPY/NOCONF/LOG D0$RELEASE:[TRD_UTIL.SOURCE]TRD.RCP D0$TRD_UTIL:
  @ IF F$SEARCH("D0$RELEASE:[TRD_UTIL.SOURCE]TRD_ANALYSIS.RCP") .NES. "" THEN -
  COPY/NOCONF/LOG D0$RELEASE:[TRD_UTIL.SOURCE]TRD_ANALYSIS.RCP D0$TRD_UTIL:
  @ IF F$SEARCH("D0$RELEASE:[TRD_UTIL.SOURCE]TRD_OMNI_1B.RCP") .NES. "" THEN -
  COPY/NOCONF/LOG D0$RELEASE:[TRD_UTIL.SOURCE]TRD_OMNI_1B.RCP D0$TRD_UTIL:
  @ IF F$SEARCH("D0$RELEASE:[TRD_UTIL.SOURCE]TRD_TRDFIX.RCP") .NES. "" THEN -
  COPY/NOCONF/LOG D0$RELEASE:[TRD_UTIL.SOURCE]TRD_TRDFIX.RCP D0$TRD_UTIL:
.ENDIF
 
 
.IFDEF DO_OFFICIAL
NOTHING.NL : SYS$LOGIN:LOGIN.COM
  @ WRITE SYS$OUTPUT "Executing Officializing Commands"
.ENDIF
 
.IFDEF D0LIB_RELEASE
TRD_UTIL.TSP : -
                 D0$TRD_UTIL:$(PREFIX)TRD_UTIL.OLB(-
                    BKCDD4=D0$SCRATCH:[TRD_UTIL]BKCDD4.OBJ,-
                    BKGTLY=D0$SCRATCH:[TRD_UTIL]BKGTLY.OBJ,-
                    BKGTRH=D0$SCRATCH:[TRD_UTIL]BKGTRH.OBJ,-
                    BKSTRD=D0$SCRATCH:[TRD_UTIL]BKSTRD.OBJ,-
                    BKTANA=D0$SCRATCH:[TRD_UTIL]BKTANA.OBJ,-
                    BKTCOR=D0$SCRATCH:[TRD_UTIL]BKTCOR.OBJ,-
                    BKTDST=D0$SCRATCH:[TRD_UTIL]BKTDST.OBJ,-
                    BKTGAI=D0$SCRATCH:[TRD_UTIL]BKTGAI.OBJ,-
                    BKTGBD=D0$SCRATCH:[TRD_UTIL]BKTGBD.OBJ,-
                    BKTGCH=D0$SCRATCH:[TRD_UTIL]BKTGCH.OBJ,-
                    BKTGEN=D0$SCRATCH:[TRD_UTIL]BKTGEN.OBJ,-
                    BKTGNS=D0$SCRATCH:[TRD_UTIL]BKTGNS.OBJ,-
                    BKTHIT=D0$SCRATCH:[TRD_UTIL]BKTHIT.OBJ,-
                    BKTLYR=D0$SCRATCH:[TRD_UTIL]BKTLYR.OBJ,-
                    BKTND1=D0$SCRATCH:[TRD_UTIL]BKTND1.OBJ,-
                    BKTND2=D0$SCRATCH:[TRD_UTIL]BKTND2.OBJ,-
                    BKTPBD=D0$SCRATCH:[TRD_UTIL]BKTPBD.OBJ,-
                    BKTPCH=D0$SCRATCH:[TRD_UTIL]BKTPCH.OBJ,-
                    BKTPDH=D0$SCRATCH:[TRD_UTIL]BKTPDH.OBJ,-
                    BKTPED=D0$SCRATCH:[TRD_UTIL]BKTPED.OBJ,-
                    BKTPRL=D0$SCRATCH:[TRD_UTIL]BKTPRL.OBJ,-
                    BKTPZS=D0$SCRATCH:[TRD_UTIL]BKTPZS.OBJ,-
                    BKTRDH=D0$SCRATCH:[TRD_UTIL]BKTRDH.OBJ,-
                    BKTRDT=D0$SCRATCH:[TRD_UTIL]BKTRDT.OBJ,-
                    BKTTRH=D0$SCRATCH:[TRD_UTIL]BKTTRH.OBJ,-
                    CLDR=D0$SCRATCH:[TRD_UTIL]CLDR.OBJ,-
                    CLIKEN=D0$SCRATCH:[TRD_UTIL]CLIKEN.OBJ,-
                    CLIKET=D0$SCRATCH:[TRD_UTIL]CLIKET.OBJ,-
                    CLUSTF=D0$SCRATCH:[TRD_UTIL]CLUSTF.OBJ,-
                    CLUSTF_LEV2=D0$SCRATCH:[TRD_UTIL]CLUSTF_LEV2.OBJ,-
                    CORDENSITY=D0$SCRATCH:[TRD_UTIL]CORDENSITY.OBJ,-
                    COREPI=D0$SCRATCH:[TRD_UTIL]COREPI.OBJ,-
                    CORPRE=D0$SCRATCH:[TRD_UTIL]CORPRE.OBJ,-
                    CORTEM=D0$SCRATCH:[TRD_UTIL]CORTEM.OBJ,-
                    CTCOR=D0$SCRATCH:[TRD_UTIL]CTCOR.OBJ,-
                    DELTA_TRD_CELLS=D0$SCRATCH:[TRD_UTIL]DELTA_TRD_CELLS.OBJ,-
                    DENSITY_OF_TRD_HITS=D0$SCRATCH:[TRD_UTIL]DENSITY_OF_TRD_HITS.OBJ,-
                    DICHO=D0$SCRATCH:[TRD_UTIL]DICHO.OBJ,-
                    DICHOTOM=D0$SCRATCH:[TRD_UTIL]DICHOTOM.OBJ,-
                    DIFWIRE=D0$SCRATCH:[TRD_UTIL]DIFWIRE.OBJ,-
                    DIST_TRACK_ANODE=D0$SCRATCH:[TRD_UTIL]DIST_TRACK_ANODE.OBJ,-
                    DO_FFT=D0$SCRATCH:[TRD_UTIL]DO_FFT.OBJ,-
                    DRAWPT=D0$SCRATCH:[TRD_UTIL]DRAWPT.OBJ,-
                    DRAWPT_XY=D0$SCRATCH:[TRD_UTIL]DRAWPT_XY.OBJ,-
                    EPSILON_T_END=D0$SCRATCH:[TRD_UTIL]EPSILON_T_END.OBJ,-
                    ETO3EF=D0$SCRATCH:[TRD_UTIL]ETO3EF.OBJ,-
                    ETOTEF=D0$SCRATCH:[TRD_UTIL]ETOTEF.OBJ,-
                    ETR3EF=D0$SCRATCH:[TRD_UTIL]ETR3EF.OBJ,-
                    ETRUEF=D0$SCRATCH:[TRD_UTIL]ETRUEF.OBJ,-
                    ETRUNC_REF_MC=D0$SCRATCH:[TRD_UTIL]ETRUNC_REF_MC.OBJ,-
                    EXTRAP=D0$SCRATCH:[TRD_UTIL]EXTRAP.OBJ,-
                    FETCH_URAN_CDFIX=D0$SCRATCH:[TRD_UTIL]FETCH_URAN_CDFIX.OBJ,-
                    FETCH_URAN_TROP=D0$SCRATCH:[TRD_UTIL]FETCH_URAN_TROP.OBJ,-
                    FINDVERSION=D0$SCRATCH:[TRD_UTIL]FINDVERSION.OBJ,-
                    GET_TRD_COR_ANG=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_ANG.OBJ,-
                    GET_TRD_COR_APC=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_APC.OBJ,-
                    GET_TRD_COR_BY_RUN=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_BY_RUN.OBJ,-
                    GET_TRD_COR_ELE=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_ELE.OBJ,-
                    GET_TRD_COR_EPI=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_EPI.OBJ,-
                    GET_TRD_COR_GAS=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_GAS.OBJ,-
                    GET_TRD_COR_HVT=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_HVT.OBJ,-
                    GET_TRD_COR_PED=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_PED.OBJ,-
                    GET_TRD_COR_SEC=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_SEC.OBJ,-
                    GET_TRD_COR_WIR=D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_WIR.OBJ,-
                    GET_TRD_NBW=D0$SCRATCH:[TRD_UTIL]GET_TRD_NBW.OBJ,-
                    GET_TRD_ON_MDST=D0$SCRATCH:[TRD_UTIL]GET_TRD_ON_MDST.OBJ,-
                    GTDBM=D0$SCRATCH:[TRD_UTIL]GTDBM.OBJ,-
                    GTISAT=D0$SCRATCH:[TRD_UTIL]GTISAT.OBJ,-
                    GZGTRH=D0$SCRATCH:[TRD_UTIL]GZGTRH.OBJ,-
                    GZSTRD=D0$SCRATCH:[TRD_UTIL]GZSTRD.OBJ,-
                    GZTACH=D0$SCRATCH:[TRD_UTIL]GZTACH.OBJ,-
                    GZTANA=D0$SCRATCH:[TRD_UTIL]GZTANA.OBJ,-
                    GZTCA1=D0$SCRATCH:[TRD_UTIL]GZTCA1.OBJ,-
                    GZTCA2=D0$SCRATCH:[TRD_UTIL]GZTCA2.OBJ,-
                    GZTCAN=D0$SCRATCH:[TRD_UTIL]GZTCAN.OBJ,-
                    GZTCHA=D0$SCRATCH:[TRD_UTIL]GZTCHA.OBJ,-
                    GZTCOR=D0$SCRATCH:[TRD_UTIL]GZTCOR.OBJ,-
                    GZTDCO=D0$SCRATCH:[TRD_UTIL]GZTDCO.OBJ,-
                    GZTDEL=D0$SCRATCH:[TRD_UTIL]GZTDEL.OBJ,-
                    GZTDEN=D0$SCRATCH:[TRD_UTIL]GZTDEN.OBJ,-
                    GZTDFA=D0$SCRATCH:[TRD_UTIL]GZTDFA.OBJ,-
                    GZTDOR=D0$SCRATCH:[TRD_UTIL]GZTDOR.OBJ,-
                    GZTDPI=D0$SCRATCH:[TRD_UTIL]GZTDPI.OBJ,-
                    GZTDST=D0$SCRATCH:[TRD_UTIL]GZTDST.OBJ,-
                    GZTEDE=D0$SCRATCH:[TRD_UTIL]GZTEDE.OBJ,-
                    GZTEL1=D0$SCRATCH:[TRD_UTIL]GZTEL1.OBJ,-
                    GZTEL2=D0$SCRATCH:[TRD_UTIL]GZTEL2.OBJ,-
                    GZTELE=D0$SCRATCH:[TRD_UTIL]GZTELE.OBJ,-
                    GZTELH=D0$SCRATCH:[TRD_UTIL]GZTELH.OBJ,-
                    GZTGAI=D0$SCRATCH:[TRD_UTIL]GZTGAI.OBJ,-
                    GZTGCH=D0$SCRATCH:[TRD_UTIL]GZTGCH.OBJ,-
                    GZTGEO=D0$SCRATCH:[TRD_UTIL]GZTGEO.OBJ,-
                    GZTHIT=D0$SCRATCH:[TRD_UTIL]GZTHIT.OBJ,-
                    GZTLIK=D0$SCRATCH:[TRD_UTIL]GZTLIK.OBJ,-
                    GZTLTA=D0$SCRATCH:[TRD_UTIL]GZTLTA.OBJ,-
                    GZTMAA1=D0$SCRATCH:[TRD_UTIL]GZTMAA1.OBJ,-
                    GZTMAA2=D0$SCRATCH:[TRD_UTIL]GZTMAA2.OBJ,-
                    GZTMAB1=D0$SCRATCH:[TRD_UTIL]GZTMAB1.OBJ,-
                    GZTMAB2=D0$SCRATCH:[TRD_UTIL]GZTMAB2.OBJ,-
                    GZTMAC1=D0$SCRATCH:[TRD_UTIL]GZTMAC1.OBJ,-
                    GZTMAC2=D0$SCRATCH:[TRD_UTIL]GZTMAC2.OBJ,-
                    GZTMAE1=D0$SCRATCH:[TRD_UTIL]GZTMAE1.OBJ,-
                    GZTMAE2=D0$SCRATCH:[TRD_UTIL]GZTMAE2.OBJ,-
                    GZTMXE1=D0$SCRATCH:[TRD_UTIL]GZTMXE1.OBJ,-
                    GZTMXE2=D0$SCRATCH:[TRD_UTIL]GZTMXE2.OBJ,-
                    GZTND1=D0$SCRATCH:[TRD_UTIL]GZTND1.OBJ,-
                    GZTND2=D0$SCRATCH:[TRD_UTIL]GZTND2.OBJ,-
                    GZTPCA1=D0$SCRATCH:[TRD_UTIL]GZTPCA1.OBJ,-
                    GZTPCA2=D0$SCRATCH:[TRD_UTIL]GZTPCA2.OBJ,-
                    GZTPCB1=D0$SCRATCH:[TRD_UTIL]GZTPCB1.OBJ,-
                    GZTPCB2=D0$SCRATCH:[TRD_UTIL]GZTPCB2.OBJ,-
                    GZTPCC1=D0$SCRATCH:[TRD_UTIL]GZTPCC1.OBJ,-
                    GZTPCC2=D0$SCRATCH:[TRD_UTIL]GZTPCC2.OBJ,-
                    GZTPDE=D0$SCRATCH:[TRD_UTIL]GZTPDE.OBJ,-
                    GZTPDH=D0$SCRATCH:[TRD_UTIL]GZTPDH.OBJ,-
                    GZTPE31=D0$SCRATCH:[TRD_UTIL]GZTPE31.OBJ,-
                    GZTPE32=D0$SCRATCH:[TRD_UTIL]GZTPE32.OBJ,-
                    GZTPEC1=D0$SCRATCH:[TRD_UTIL]GZTPEC1.OBJ,-
                    GZTPEC2=D0$SCRATCH:[TRD_UTIL]GZTPEC2.OBJ,-
                    GZTPET1=D0$SCRATCH:[TRD_UTIL]GZTPET1.OBJ,-
                    GZTPET2=D0$SCRATCH:[TRD_UTIL]GZTPET2.OBJ,-
                    GZTPHY=D0$SCRATCH:[TRD_UTIL]GZTPHY.OBJ,-
                    GZTPI1=D0$SCRATCH:[TRD_UTIL]GZTPI1.OBJ,-
                    GZTPI2=D0$SCRATCH:[TRD_UTIL]GZTPI2.OBJ,-
                    GZTPIO=D0$SCRATCH:[TRD_UTIL]GZTPIO.OBJ,-
                    GZTPLE1=D0$SCRATCH:[TRD_UTIL]GZTPLE1.OBJ,-
                    GZTPLE2=D0$SCRATCH:[TRD_UTIL]GZTPLE2.OBJ,-
                    GZTPR1=D0$SCRATCH:[TRD_UTIL]GZTPR1.OBJ,-
                    GZTPR2=D0$SCRATCH:[TRD_UTIL]GZTPR2.OBJ,-
                    GZTPRL=D0$SCRATCH:[TRD_UTIL]GZTPRL.OBJ,-
                    GZTPRO=D0$SCRATCH:[TRD_UTIL]GZTPRO.OBJ,-
                    GZTPT31=D0$SCRATCH:[TRD_UTIL]GZTPT31.OBJ,-
                    GZTPT32=D0$SCRATCH:[TRD_UTIL]GZTPT32.OBJ,-
                    GZTPTR1=D0$SCRATCH:[TRD_UTIL]GZTPTR1.OBJ,-
                    GZTPTR2=D0$SCRATCH:[TRD_UTIL]GZTPTR2.OBJ,-
                    GZTRDH=D0$SCRATCH:[TRD_UTIL]GZTRDH.OBJ,-
                    GZTRDT=D0$SCRATCH:[TRD_UTIL]GZTRDT.OBJ,-
                    GZTREL=D0$SCRATCH:[TRD_UTIL]GZTREL.OBJ,-
                    GZTRPD=D0$SCRATCH:[TRD_UTIL]GZTRPD.OBJ,-
                    GZTRWG=D0$SCRATCH:[TRD_UTIL]GZTRWG.OBJ,-
                    GZTTRH=D0$SCRATCH:[TRD_UTIL]GZTTRH.OBJ,-
                    GZTWGH=D0$SCRATCH:[TRD_UTIL]GZTWGH.OBJ,-
                    HIS_DENS=D0$SCRATCH:[TRD_UTIL]HIS_DENS.OBJ,-
                    HPLIS=D0$SCRATCH:[TRD_UTIL]HPLIS.OBJ,-
                    INTOCH=D0$SCRATCH:[TRD_UTIL]INTOCH.OBJ,-
                    LIKEEF=D0$SCRATCH:[TRD_UTIL]LIKEEF.OBJ,-
                    LIKE_REF_MC=D0$SCRATCH:[TRD_UTIL]LIKE_REF_MC.OBJ,-
                    LIKNEF=D0$SCRATCH:[TRD_UTIL]LIKNEF.OBJ,-
                    LIK_REF_MC=D0$SCRATCH:[TRD_UTIL]LIK_REF_MC.OBJ,-
                    LUVW_DENS=D0$SCRATCH:[TRD_UTIL]LUVW_DENS.OBJ,-
                    MONTE_CARLO_DATA=D0$SCRATCH:[TRD_UTIL]MONTE_CARLO_DATA.OBJ,-
                    NEURO_DENS=D0$SCRATCH:[TRD_UTIL]NEURO_DENS.OBJ,-
                    PACK_INTEGER=D0$SCRATCH:[TRD_UTIL]PACK_INTEGER.OBJ,-
                    PACK_REAL=D0$SCRATCH:[TRD_UTIL]PACK_REAL.OBJ,-
                    PACK_TPRL=D0$SCRATCH:[TRD_UTIL]PACK_TPRL.OBJ,-
                    PHI_TRD=D0$SCRATCH:[TRD_UTIL]PHI_TRD.OBJ,-
                    PRCDD4=D0$SCRATCH:[TRD_UTIL]PRCDD4.OBJ,-
                    PRGTLY=D0$SCRATCH:[TRD_UTIL]PRGTLY.OBJ,-
                    PRGTRH=D0$SCRATCH:[TRD_UTIL]PRGTRH.OBJ,-
                    PRHTLY=D0$SCRATCH:[TRD_UTIL]PRHTLY.OBJ,-
                    PRSTRD=D0$SCRATCH:[TRD_UTIL]PRSTRD.OBJ,-
                    PRTANA=D0$SCRATCH:[TRD_UTIL]PRTANA.OBJ,-
                    PRTDST=D0$SCRATCH:[TRD_UTIL]PRTDST.OBJ,-
                    PRTHIT=D0$SCRATCH:[TRD_UTIL]PRTHIT.OBJ,-
                    PRTLYR=D0$SCRATCH:[TRD_UTIL]PRTLYR.OBJ,-
                    PRTPRL=D0$SCRATCH:[TRD_UTIL]PRTPRL.OBJ,-
                    PRTPRL_OLD=D0$SCRATCH:[TRD_UTIL]PRTPRL_OLD.OBJ,-
                    PRTRAC=D0$SCRATCH:[TRD_UTIL]PRTRAC.OBJ,-
                    PRTRDH=D0$SCRATCH:[TRD_UTIL]PRTRDH.OBJ,-
                    PRTRDT=D0$SCRATCH:[TRD_UTIL]PRTRDT.OBJ,-
                    PRTREL=D0$SCRATCH:[TRD_UTIL]PRTREL.OBJ,-
                    PRTRLC=D0$SCRATCH:[TRD_UTIL]PRTRLC.OBJ,-
                    PRTRLE=D0$SCRATCH:[TRD_UTIL]PRTRLE.OBJ,-
                    PRTROP=D0$SCRATCH:[TRD_UTIL]PRTROP.OBJ,-
                    PRTRPD=D0$SCRATCH:[TRD_UTIL]PRTRPD.OBJ,-
                    PRTRWG=D0$SCRATCH:[TRD_UTIL]PRTRWG.OBJ,-
                    PRTTRH=D0$SCRATCH:[TRD_UTIL]PRTTRH.OBJ,-
                    READ_URAN_CDFIX=D0$SCRATCH:[TRD_UTIL]READ_URAN_CDFIX.OBJ,-
                    RELATIVE_AGEING=D0$SCRATCH:[TRD_UTIL]RELATIVE_AGEING.OBJ,-
                    RESET_TRDCOR=D0$SCRATCH:[TRD_UTIL]RESET_TRDCOR.OBJ,-
                    ROADPH=D0$SCRATCH:[TRD_UTIL]ROADPH.OBJ,-
                    RUN1A=D0$SCRATCH:[TRD_UTIL]RUN1A.OBJ,-
                    RUN_NUMBER_ZONE=D0$SCRATCH:[TRD_UTIL]RUN_NUMBER_ZONE.OBJ,-
                    SELTRA=D0$SCRATCH:[TRD_UTIL]SELTRA.OBJ,-
                    SUMHIS=D0$SCRATCH:[TRD_UTIL]SUMHIS.OBJ,-
                    TANAFL=D0$SCRATCH:[TRD_UTIL]TANAFL.OBJ,-
                    TCELLF=D0$SCRATCH:[TRD_UTIL]TCELLF.OBJ,-
                    TCELL_IN_ROAD=D0$SCRATCH:[TRD_UTIL]TCELL_IN_ROAD.OBJ,-
                    TCHNB=D0$SCRATCH:[TRD_UTIL]TCHNB.OBJ,-
                    TCODER=D0$SCRATCH:[TRD_UTIL]TCODER.OBJ,-
                    TDACTV=D0$SCRATCH:[TRD_UTIL]TDACTV.OBJ,-
                    TDBINI=D0$SCRATCH:[TRD_UTIL]TDBINI.OBJ,-
                    TDEFLI=D0$SCRATCH:[TRD_UTIL]TDEFLI.OBJ,-
                    TDIFWIRE=D0$SCRATCH:[TRD_UTIL]TDIFWIRE.OBJ,-
                    TDSTDRP=D0$SCRATCH:[TRD_UTIL]TDSTDRP.OBJ,-
                    TDSTFL=D0$SCRATCH:[TRD_UTIL]TDSTFL.OBJ,-
                    TFOURIER=D0$SCRATCH:[TRD_UTIL]TFOURIER.OBJ,-
                    TGNINI=D0$SCRATCH:[TRD_UTIL]TGNINI.OBJ,-
                    TGTGNS=D0$SCRATCH:[TRD_UTIL]TGTGNS.OBJ,-
                    TGTPDS=D0$SCRATCH:[TRD_UTIL]TGTPDS.OBJ,-
                    THIST_VER=D0$SCRATCH:[TRD_UTIL]THIST_VER.OBJ,-
                    THITFIL=D0$SCRATCH:[TRD_UTIL]THITFIL.OBJ,-
                    THIT_GET=D0$SCRATCH:[TRD_UTIL]THIT_GET.OBJ,-
                    THIT_UNPACK=D0$SCRATCH:[TRD_UTIL]THIT_UNPACK.OBJ,-
                    THOTWIRE=D0$SCRATCH:[TRD_UTIL]THOTWIRE.OBJ,-
                    TLYRFL=D0$SCRATCH:[TRD_UTIL]TLYRFL.OBJ,-
                    TMULAY=D0$SCRATCH:[TRD_UTIL]TMULAY.OBJ,-
                    TPDINI=D0$SCRATCH:[TRD_UTIL]TPDINI.OBJ,-
                    TPRLFIL=D0$SCRATCH:[TRD_UTIL]TPRLFIL.OBJ,-
                    TPRLFL=D0$SCRATCH:[TRD_UTIL]TPRLFL.OBJ,-
                    TRATRD=D0$SCRATCH:[TRD_UTIL]TRATRD.OBJ,-
                    TRCELL=D0$SCRATCH:[TRD_UTIL]TRCELL.OBJ,-
                    TRCFAD=D0$SCRATCH:[TRD_UTIL]TRCFAD.OBJ,-
                    TRCHAN=D0$SCRATCH:[TRD_UTIL]TRCHAN.OBJ,-
                    TRCROSS=D0$SCRATCH:[TRD_UTIL]TRCROSS.OBJ,-
                    TRDANA=D0$SCRATCH:[TRD_UTIL]TRDANA.OBJ,-
                    TRDBOK=D0$SCRATCH:[TRD_UTIL]TRDBOK.OBJ,-
                    TRDBOK_ON=D0$SCRATCH:[TRD_UTIL]TRDBOK_ON.OBJ,-
                    TRDCAN_UPDATE=D0$SCRATCH:[TRD_UTIL]TRDCAN_UPDATE.OBJ,-
                    TRDCON=D0$SCRATCH:[TRD_UTIL]TRDCON.OBJ,-
                    TRDDEF=D0$SCRATCH:[TRD_UTIL]TRDDEF.OBJ,-
                    TRDDMP=D0$SCRATCH:[TRD_UTIL]TRDDMP.OBJ,-
                    TRDDRP=D0$SCRATCH:[TRD_UTIL]TRDDRP.OBJ,-
                    TRDFIL=D0$SCRATCH:[TRD_UTIL]TRDFIL.OBJ,-
                    TRDFIX=D0$SCRATCH:[TRD_UTIL]TRDFIX.OBJ,-
                    TRDHIT=D0$SCRATCH:[TRD_UTIL]TRDHIT.OBJ,-
                    TRDHIT_U=D0$SCRATCH:[TRD_UTIL]TRDHIT_U.OBJ,-
                    TRDHV_UPDATE=D0$SCRATCH:[TRD_UTIL]TRDHV_UPDATE.OBJ,-
                    TRDINI=D0$SCRATCH:[TRD_UTIL]TRDINI.OBJ,-
                    TRDISA=D0$SCRATCH:[TRD_UTIL]TRDISA.OBJ,-
                    TRDNDR=D0$SCRATCH:[TRD_UTIL]TRDNDR.OBJ,-
                    TRDNOR=D0$SCRATCH:[TRD_UTIL]TRDNOR.OBJ,-
                    TRDPAR=D0$SCRATCH:[TRD_UTIL]TRDPAR.OBJ,-
                    TRDPAT=D0$SCRATCH:[TRD_UTIL]TRDPAT.OBJ,-
                    TRDPAT_LEV2=D0$SCRATCH:[TRD_UTIL]TRDPAT_LEV2.OBJ,-
                    TRDTFIL=D0$SCRATCH:[TRD_UTIL]TRDTFIL.OBJ,-
                    TRDTFL=D0$SCRATCH:[TRD_UTIL]TRDTFL.OBJ,-
                    TRDTMIN=D0$SCRATCH:[TRD_UTIL]TRDTMIN.OBJ,-
                    TRDUNP=D0$SCRATCH:[TRD_UTIL]TRDUNP.OBJ,-
                    TRDUSM=D0$SCRATCH:[TRD_UTIL]TRDUSM.OBJ,-
                    TRD_ANALYSIS=D0$SCRATCH:[TRD_UTIL]TRD_ANALYSIS.OBJ,-
                    TRD_ANALYSIS_INI=D0$SCRATCH:[TRD_UTIL]TRD_ANALYSIS_INI.OBJ,-
                    TRD_ANALYSIS_IN_RECO=D0$SCRATCH:[TRD_UTIL]TRD_ANALYSIS_IN_RECO.OBJ,-
                    TRD_ANAL_CATH=D0$SCRATCH:[TRD_UTIL]TRD_ANAL_CATH.OBJ,-
                    TRD_BADRUN=D0$SCRATCH:[TRD_UTIL]TRD_BADRUN.OBJ,-
                    TRD_BADSECTOR=D0$SCRATCH:[TRD_UTIL]TRD_BADSECTOR.OBJ,-
                    TRD_CALURAPT=D0$SCRATCH:[TRD_UTIL]TRD_CALURAPT.OBJ,-
                    TRD_CHECK_BANK=D0$SCRATCH:[TRD_UTIL]TRD_CHECK_BANK.OBJ,-
                    TRD_CHECK_GEOM=D0$SCRATCH:[TRD_UTIL]TRD_CHECK_GEOM.OBJ,-
                    TRD_CHECK_INTEGRITY=D0$SCRATCH:[TRD_UTIL]TRD_CHECK_INTEGRITY.OBJ,-
                    TRD_CHGHBK=D0$SCRATCH:[TRD_UTIL]TRD_CHGHBK.OBJ,-
                    TRD_CLEAN_CLUST=D0$SCRATCH:[TRD_UTIL]TRD_CLEAN_CLUST.OBJ,-
                    TRD_COMBINE_ELEMENTS=D0$SCRATCH:[TRD_UTIL]TRD_COMBINE_ELEMENTS.OBJ,-
                    TRD_CORGAS=D0$SCRATCH:[TRD_UTIL]TRD_CORGAS.OBJ,-
                    TRD_CORHV=D0$SCRATCH:[TRD_UTIL]TRD_CORHV.OBJ,-
                    TRD_COR_STATUS=D0$SCRATCH:[TRD_UTIL]TRD_COR_STATUS.OBJ,-
                    TRD_COR_TEMP=D0$SCRATCH:[TRD_UTIL]TRD_COR_TEMP.OBJ,-
                    TRD_CYLIND=D0$SCRATCH:[TRD_UTIL]TRD_CYLIND.OBJ,-
                    TRD_DISPATCH=D0$SCRATCH:[TRD_UTIL]TRD_DISPATCH.OBJ,-
                    TRD_DO_PRINT=D0$SCRATCH:[TRD_UTIL]TRD_DO_PRINT.OBJ,-
                    TRD_DST_COR=D0$SCRATCH:[TRD_UTIL]TRD_DST_COR.OBJ,-
                    TRD_DST_COR_ERR=D0$SCRATCH:[TRD_UTIL]TRD_DST_COR_ERR.OBJ,-
                    TRD_DST_COR_IN_RECO=D0$SCRATCH:[TRD_UTIL]TRD_DST_COR_IN_RECO.OBJ,-
                    TRD_ELECTRON_PION=D0$SCRATCH:[TRD_UTIL]TRD_ELECTRON_PION.OBJ,-
                    TRD_END_UPDATE=D0$SCRATCH:[TRD_UTIL]TRD_END_UPDATE.OBJ,-
                    TRD_ENERGY_FIRED_CELLS=D0$SCRATCH:[TRD_UTIL]TRD_ENERGY_FIRED_CELLS.OBJ,-
                    TRD_ENERGY_MAX_CELLS=D0$SCRATCH:[TRD_UTIL]TRD_ENERGY_MAX_CELLS.OBJ,-
                    TRD_ENVIRONMENT=D0$SCRATCH:[TRD_UTIL]TRD_ENVIRONMENT.OBJ,-
                    TRD_EPS_COR=D0$SCRATCH:[TRD_UTIL]TRD_EPS_COR.OBJ,-
                    TRD_EPS_MC=D0$SCRATCH:[TRD_UTIL]TRD_EPS_MC.OBJ,-
                    TRD_EXM_ANAL=D0$SCRATCH:[TRD_UTIL]TRD_EXM_ANAL.OBJ,-
                    TRD_FILLS_EVT=D0$SCRATCH:[TRD_UTIL]TRD_FILLS_EVT.OBJ,-
                    TRD_FINDS_GROUP=D0$SCRATCH:[TRD_UTIL]TRD_FINDS_GROUP.OBJ,-
                    TRD_FIND_VER=D0$SCRATCH:[TRD_UTIL]TRD_FIND_VER.OBJ,-
                    TRD_FIRST_UPDATE=D0$SCRATCH:[TRD_UTIL]TRD_FIRST_UPDATE.OBJ,-
                    TRD_HISTOS=D0$SCRATCH:[TRD_UTIL]TRD_HISTOS.OBJ,-
                    TRD_HITS=D0$SCRATCH:[TRD_UTIL]TRD_HITS.OBJ,-
                    TRD_INTERSECTION=D0$SCRATCH:[TRD_UTIL]TRD_INTERSECTION.OBJ,-
                    TRD_MENU=D0$SCRATCH:[TRD_UTIL]TRD_MENU.OBJ,-
                    TRD_NEXT=D0$SCRATCH:[TRD_UTIL]TRD_NEXT.OBJ,-
                    TRD_NUM_LAYERS=D0$SCRATCH:[TRD_UTIL]TRD_NUM_LAYERS.OBJ,-
                    TRD_NWIRE_PER_LAYER=D0$SCRATCH:[TRD_UTIL]TRD_NWIRE_PER_LAYER.OBJ,-
                    TRD_ON_MICRO=D0$SCRATCH:[TRD_UTIL]TRD_ON_MICRO.OBJ,-
                    TRD_PREVIOUS=D0$SCRATCH:[TRD_UTIL]TRD_PREVIOUS.OBJ,-
                    TRD_REWB=D0$SCRATCH:[TRD_UTIL]TRD_REWB.OBJ,-
                    TRD_SEPARATE_ELEMENTS=D0$SCRATCH:[TRD_UTIL]TRD_SEPARATE_ELEMENTS.OBJ,-
                    TRD_TO_CDC_DEDX=D0$SCRATCH:[TRD_UTIL]TRD_TO_CDC_DEDX.OBJ,-
                    TRD_UPDATE_EVENT=D0$SCRATCH:[TRD_UTIL]TRD_UPDATE_EVENT.OBJ,-
                    TRD_URAN_FETCH=D0$SCRATCH:[TRD_UTIL]TRD_URAN_FETCH.OBJ,-
                    TRD_URAN_INSERT=D0$SCRATCH:[TRD_UTIL]TRD_URAN_INSERT.OBJ,-
                    TRD_USER_DIALOG=D0$SCRATCH:[TRD_UTIL]TRD_USER_DIALOG.OBJ,-
                    TRD_ZCATH=D0$SCRATCH:[TRD_UTIL]TRD_ZCATH.OBJ,-
                    TRD_ZPOS=D0$SCRATCH:[TRD_UTIL]TRD_ZPOS.OBJ,-
                    TREAD_MONITOR=D0$SCRATCH:[TRD_UTIL]TREAD_MONITOR.OBJ,-
                    TREDEP=D0$SCRATCH:[TRD_UTIL]TREDEP.OBJ,-
                    TREDEP_LEV2=D0$SCRATCH:[TRD_UTIL]TREDEP_LEV2.OBJ,-
                    TRFPNT=D0$SCRATCH:[TRD_UTIL]TRFPNT.OBJ,-
                    TRGGN=D0$SCRATCH:[TRD_UTIL]TRGGN.OBJ,-
                    TRGPED=D0$SCRATCH:[TRD_UTIL]TRGPED.OBJ,-
                    TRGVER=D0$SCRATCH:[TRD_UTIL]TRGVER.OBJ,-
                    TRH_ON=D0$SCRATCH:[TRD_UTIL]TRH_ON.OBJ,-
                    TRH_OUT=D0$SCRATCH:[TRD_UTIL]TRH_OUT.OBJ,-
                    TRISIS=D0$SCRATCH:[TRD_UTIL]TRISIS.OBJ,-
                    TRISRC=D0$SCRATCH:[TRD_UTIL]TRISRC.OBJ,-
                    TRISRC_CLUST_EM=D0$SCRATCH:[TRD_UTIL]TRISRC_CLUST_EM.OBJ,-
                    TRISRC_CLUST_PHOT=D0$SCRATCH:[TRD_UTIL]TRISRC_CLUST_PHOT.OBJ,-
                    TRISRC_FULL=D0$SCRATCH:[TRD_UTIL]TRISRC_FULL.OBJ,-
                    TRISRC_TRACK=D0$SCRATCH:[TRD_UTIL]TRISRC_TRACK.OBJ,-
                    TRISTP=D0$SCRATCH:[TRD_UTIL]TRISTP.OBJ,-
                    TRISTR=D0$SCRATCH:[TRD_UTIL]TRISTR.OBJ,-
                    TRREAD=D0$SCRATCH:[TRD_UTIL]TRREAD.OBJ,-
                    TRREMP=D0$SCRATCH:[TRD_UTIL]TRREMP.OBJ,-
                    TRUNIT=D0$SCRATCH:[TRD_UTIL]TRUNIT.OBJ,-
                    TSETWC=D0$SCRATCH:[TRD_UTIL]TSETWC.OBJ,-
                    TSETWC_LEV2=D0$SCRATCH:[TRD_UTIL]TSETWC_LEV2.OBJ,-
                    TTRAKS=D0$SCRATCH:[TRD_UTIL]TTRAKS.OBJ,-
                    TTRHFL=D0$SCRATCH:[TRD_UTIL]TTRHFL.OBJ,-
                    TVERIF=D0$SCRATCH:[TRD_UTIL]TVERIF.OBJ,-
                    TWIRCOR=D0$SCRATCH:[TRD_UTIL]TWIRCOR.OBJ,-
                    TWIRHOT=D0$SCRATCH:[TRD_UTIL]TWIRHOT.OBJ,-
                    T_COR_CABLE=D0$SCRATCH:[TRD_UTIL]T_COR_CABLE.OBJ,-
                    UNPACK_INTEGER=D0$SCRATCH:[TRD_UTIL]UNPACK_INTEGER.OBJ,-
                    UNPACK_REAL=D0$SCRATCH:[TRD_UTIL]UNPACK_REAL.OBJ,-
                    UNPACK_REAL_STP=D0$SCRATCH:[TRD_UTIL]UNPACK_REAL_STP.OBJ,-
                    UNPACK_TPRL=D0$SCRATCH:[TRD_UTIL]UNPACK_TPRL.OBJ,-
                    URANIUM_TO_EPICOR=D0$SCRATCH:[TRD_UTIL]URANIUM_TO_EPICOR.OBJ,-
                    VAXTIMECOMP=D0$SCRATCH:[TRD_UTIL]VAXTIMECOMP.OBJ,-
                    WRITE_TRDCOR=D0$SCRATCH:[TRD_UTIL]WRITE_TRDCOR.OBJ,-
                    ZDEXPD_TRD=D0$SCRATCH:[TRD_UTIL]ZDEXPD_TRD.OBJ,-
                    Z_CATHODE=D0$SCRATCH:[TRD_UTIL]Z_CATHODE.OBJ-
                    )
     @ WRITE SYS$OUTPUT "  "
     @ WRITE SYS$OUTPUT " USERLIB - Updated target: TRD_UTIL.TSP"
 
D0$SCRATCH:[TRD_UTIL]BKCDD4.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKCDD4.FOR,-
   D0$INC:GCUNIT.INC,-
   D0$LINKS:IZCDD4.LINK,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]BKGTLY.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKGTLY.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]BKGTRH.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKGTRH.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZGTRH.LINK
  
D0$SCRATCH:[TRD_UTIL]BKSTRD.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKSTRD.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZSTPC.LINK,-
   D0$LINKS:IZSTPO.LINK,-
   D0$LINKS:IZSTPN.LINK,-
   D0$LINKS:IZSTRD.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTANA.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTANA.FOR,-
   D0$INC:TRD_NWORD.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]BKTCOR.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTCOR.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTCOR.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTDST.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTDST.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTDST.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTGAI.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTGAI.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGAI.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTGBD.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTGBD.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGBD.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTGCH.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTGCH.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGAI.LINK,-
   D0$LINKS:IZTGCH.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTGEN.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTGEN.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGEN.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTGNS.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTGNS.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGNS.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTHIT.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTHIT.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTHIT.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTLYR.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTLYR.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]BKTND1.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTND1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTND1.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTND2.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTND2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTND2.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTPBD.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTPBD.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPBD.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTPCH.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTPCH.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPDH.LINK,-
   D0$LINKS:IZTPCH.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTPDH.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTPDH.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPDH.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTPED.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTPED.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPED.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTPRL.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTPRL.FOR,-
   D0$INC:QUEST.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]BKTPZS.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTPZS.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPZS.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTRDH.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTRDH.FOR,-
   D0$INC:FADDIG.INC,-
   D0$LINKS:IZTRDH.LINK,-
   D0$LINKS:IZHITS.LINK,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]BKTRDT.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTRDT.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTRDT.LINK
  
D0$SCRATCH:[TRD_UTIL]BKTTRH.OBJ      : -
   D0$TRD_UTIL$SOURCE:BKTTRH.FOR,-
   D0$INC:TRDBGU.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTTRH.LINK
  
D0$SCRATCH:[TRD_UTIL]CLDR.OBJ        : -
   D0$TRD_UTIL$SOURCE:CLDR.FOR
  
D0$SCRATCH:[TRD_UTIL]CLIKEN.OBJ      : -
   D0$TRD_UTIL$SOURCE:CLIKEN.FOR,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]CLIKET.OBJ      : -
   D0$TRD_UTIL$SOURCE:CLIKET.FOR,-
   D0$INC:GCONST.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]CLUSTF.OBJ      : -
   D0$TRD_UTIL$SOURCE:CLUSTF.FOR,-
   D0$INC:TRDBGU.INC,-
   D0$INC:CLUREC.INC,-
   D0$INC:GCFLAG.INC,-
   D0$INC:D0LOG.INC,-
   D0$INC:TGRAV.INC
  
D0$SCRATCH:[TRD_UTIL]CLUSTF_LEV2.OBJ       : -
   D0$TRD_UTIL$SOURCE:CLUSTF_LEV2.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:CLUREC.INC,-
   D0$INC:TGRAV.INC,-
   D0$INC:TRD_PED.INC
  
D0$SCRATCH:[TRD_UTIL]CORDENSITY.OBJ  : -
   D0$TRD_UTIL$SOURCE:CORDENSITY.FOR
  
D0$SCRATCH:[TRD_UTIL]COREPI.OBJ      : -
   D0$TRD_UTIL$SOURCE:COREPI.FOR
  
D0$SCRATCH:[TRD_UTIL]CORPRE.OBJ      : -
   D0$TRD_UTIL$SOURCE:CORPRE.FOR
  
D0$SCRATCH:[TRD_UTIL]CORTEM.OBJ      : -
   D0$TRD_UTIL$SOURCE:CORTEM.FOR
  
D0$SCRATCH:[TRD_UTIL]CTCOR.OBJ       : -
   D0$TRD_UTIL$SOURCE:CTCOR.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTCY1.LINK
  
D0$SCRATCH:[TRD_UTIL]DELTA_TRD_CELLS.OBJ   : -
   D0$TRD_UTIL$SOURCE:DELTA_TRD_CELLS.FOR
  
D0$SCRATCH:[TRD_UTIL]DENSITY_OF_TRD_HITS.OBJ : -
   D0$TRD_UTIL$SOURCE:DENSITY_OF_TRD_HITS.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRWCOD_512.INC
  
D0$SCRATCH:[TRD_UTIL]DICHO.OBJ       : -
   D0$TRD_UTIL$SOURCE:DICHO.FOR
  
D0$SCRATCH:[TRD_UTIL]DICHOTOM.OBJ    : -
   D0$TRD_UTIL$SOURCE:DICHOTOM.FOR
  
D0$SCRATCH:[TRD_UTIL]DIFWIRE.OBJ     : -
   D0$TRD_UTIL$SOURCE:DIFWIRE.FOR,-
   D0$INC:FIRSHT.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:TRDBGU.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]DIST_TRACK_ANODE.OBJ  : -
   D0$TRD_UTIL$SOURCE:DIST_TRACK_ANODE.FOR,-
   D0$INC:FIRSHT.INC,-
   D0$INC:GEOMTR.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]DO_FFT.OBJ      : -
   D0$TRD_UTIL$SOURCE:DO_FFT.FOR,-
   D0$INC:FADCCN.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]DRAWPT.OBJ      : -
   D0$TRD_UTIL$SOURCE:DRAWPT.FOR
  
D0$SCRATCH:[TRD_UTIL]DRAWPT_XY.OBJ   : -
   D0$TRD_UTIL$SOURCE:DRAWPT_XY.FOR
  
D0$SCRATCH:[TRD_UTIL]EPSILON_T_END.OBJ     : -
   D0$TRD_UTIL$SOURCE:EPSILON_T_END.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRD_PHI_Z.INC,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]ETO3EF.OBJ      : -
   D0$TRD_UTIL$SOURCE:ETO3EF.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:GCONST.INC
  
D0$SCRATCH:[TRD_UTIL]ETOTEF.OBJ      : -
   D0$TRD_UTIL$SOURCE:ETOTEF.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:GCONST.INC
  
D0$SCRATCH:[TRD_UTIL]ETR3EF.OBJ      : -
   D0$TRD_UTIL$SOURCE:ETR3EF.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:GCONST.INC
  
D0$SCRATCH:[TRD_UTIL]ETRUEF.OBJ      : -
   D0$TRD_UTIL$SOURCE:ETRUEF.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:GCONST.INC
  
D0$SCRATCH:[TRD_UTIL]ETRUNC_REF_MC.OBJ     : -
   D0$TRD_UTIL$SOURCE:ETRUNC_REF_MC.FOR
  
D0$SCRATCH:[TRD_UTIL]EXTRAP.OBJ      : -
   D0$TRD_UTIL$SOURCE:EXTRAP.FOR
  
D0$SCRATCH:[TRD_UTIL]FETCH_URAN_CDFIX.OBJ  : -
   D0$TRD_UTIL$SOURCE:FETCH_URAN_CDFIX.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:D3U.INC
  
D0$SCRATCH:[TRD_UTIL]FETCH_URAN_TROP.OBJ   : -
   D0$TRD_UTIL$SOURCE:FETCH_URAN_TROP.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTROP.LINK
  
D0$SCRATCH:[TRD_UTIL]FINDVERSION.OBJ       : -
   D0$TRD_UTIL$SOURCE:FINDVERSION.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_ANG.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_ANG.FOR,-
   D0$INC:TRINTR.INC
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_APC.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_APC.FOR,-
   D0$INC:TCNTRL.INC
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_BY_RUN.OBJ : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_BY_RUN.FOR
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_ELE.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_ELE.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_EPI.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_EPI.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TCNTRL.INC
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_GAS.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_GAS.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTROP.LINK,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTCY1.LINK
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_HVT.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_HVT.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTROP.LINK,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_PED.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_PED.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZCDD4.LINK
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_SEC.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_SEC.FOR
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_COR_WIR.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_COR_WIR.FOR,-
   D0$INC:TRD_NB_OF_WIRES.INC
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_NBW.OBJ       : -
   D0$TRD_UTIL$SOURCE:GET_TRD_NBW.FOR,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]GET_TRD_ON_MDST.OBJ   : -
   D0$TRD_UTIL$SOURCE:GET_TRD_ON_MDST.FOR,-
   D0$INC:TRD_NWORD.INC,-
   D0$INC:TRD_DST_ENERGIES.INC,-
   D0$INC:TRDLIK.INC,-
   D0$INC:WORD_IN_TPRL.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBWRK.INC
  
D0$SCRATCH:[TRD_UTIL]GTDBM.OBJ       : -
   D0$TRD_UTIL$SOURCE:GTDBM.FOR,-
   D0$INC:D3U.INC,-
   D0$INC:QUEST.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$PARAMS:BYTE_ORDER.PARAMS
  
D0$SCRATCH:[TRD_UTIL]GTISAT.OBJ      : -
   D0$TRD_UTIL$SOURCE:GTISAT.FOR,-
   D0$INC:GEOMTR.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDVOL.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:GCONST.INC,-
   D0$LINKS:IZISAE.LINK,-
   D0$LINKS:IZISV1.LINK,-
   D0$LINKS:IZISV2.LINK,-
   D0$LINKS:IZISP1.LINK,-
   D0$LINKS:IZISP2.LINK
  
D0$SCRATCH:[TRD_UTIL]GZGTRH.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZGTRH.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZGTRH.LINK
  
D0$SCRATCH:[TRD_UTIL]GZSTRD.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZSTRD.FOR,-
   D0$LINKS:IZSTPC.LINK,-
   D0$LINKS:IZSTRD.LINK,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]GZTACH.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTACH.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTACH.LINK,-
   D0$LINKS:IZGEAN.LINK,-
   D0$LINKS:IZHSTR.LINK,-
   D0$LINKS:IZTDMC.LINK,-
   D0$LINKS:IZTDDA.LINK,-
   D0$PARAMS:BYTE_ORDER.PARAMS
  
D0$SCRATCH:[TRD_UTIL]GZTANA.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTANA.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]GZTCA1.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTCA1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTCA1.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTCA2.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTCA2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTCA2.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTCAN.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTCAN.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTCAN.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTCHA.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTCHA.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTCHA.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTCOR.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTCOR.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTCOR.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTDCO.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTDCO.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTDCO.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTDEL.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTDEL.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTDEL.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTDEN.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTDEN.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTDEN.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTDFA.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTDFA.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTDFA.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTDOR.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTDOR.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTDOR.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTDPI.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTDPI.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTDPI.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTDST.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTDST.FOR,-
   D0$LINKS:IZTDST.LINK,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]GZTEDE.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTEDE.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTEDE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTEL1.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTEL1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTEL1.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTEL2.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTEL2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTEL2.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTELE.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTELE.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTELE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTELH.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTELH.FOR,-
   D0$LINKS:IZTELH.LINK,-
   D0$LINKS:IZTGAI.LINK,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]GZTGAI.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTGAI.FOR,-
   D0$LINKS:IZTGAI.LINK,-
   D0$LINKS:IZSTRD.LINK,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]GZTGCH.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTGCH.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGCH.LINK,-
   D0$LINKS:IZTGAI.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTGEO.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTGEO.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGEO.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTHIT.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTHIT.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTHIT.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTLIK.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTLIK.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTLIK.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTLTA.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTLTA.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTLTA.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMAA1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMAA1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMAE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMAA2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMAA2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMAE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMAB1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMAB1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMAE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMAB2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMAB2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMAE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMAC1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMAC1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMAE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMAC2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMAC2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMAE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMAE1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMAE1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMAE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMAE2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMAE2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMAE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMXE1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMXE1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMXE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTMXE2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTMXE2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTMXE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTND1.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTND1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTND1.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTND2.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTND2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTND2.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPCA1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPCA1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPCA.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPCA2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPCA2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPCA.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPCB1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPCB1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPCB.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPCB2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPCB2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPCB.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPCC1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPCC1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPCC.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPCC2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPCC2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPCC.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPDE.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPDE.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPDE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPDH.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPDH.FOR,-
   D0$LINKS:IZTPDH.LINK,-
   D0$LINKS:IZSTRD.LINK,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]GZTPE31.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPE31.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPE3.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPE32.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPE32.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPE3.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPEC1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPEC1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPEC.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPEC2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPEC2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPEC.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPET1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPET1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPET.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPET2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPET2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPET.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPHY.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPHY.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPHY.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPI1.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPI1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPI1.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPI2.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPI2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPI2.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPIO.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPIO.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPIO.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPLE1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPLE1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPLE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPLE2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPLE2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPLE.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPR1.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPR1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPR1.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPR2.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPR2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPR2.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPRL.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPRL.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTPRL.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPRO.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTPRO.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPRO.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPT31.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPT31.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPT3.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPT32.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPT32.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPTR.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPTR1.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPTR1.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPTR.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTPTR2.OBJ     : -
   D0$TRD_UTIL$SOURCE:GZTPTR2.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPTR.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTRDH.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTRDH.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTRDH.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTRDT.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTRDT.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTRDT.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTREL.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTREL.FOR,-
   D0$LINKS:IZTELH.LINK,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]GZTRPD.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTRPD.FOR,-
   D0$LINKS:IZTPDH.LINK,-
   D0$LINKS:IZSTRD.LINK,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]GZTRWG.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTRWG.FOR,-
   D0$LINKS:IZTWGH.LINK,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]GZTTRH.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTTRH.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTTRH.LINK
  
D0$SCRATCH:[TRD_UTIL]GZTWGH.OBJ      : -
   D0$TRD_UTIL$SOURCE:GZTWGH.FOR,-
   D0$LINKS:IZTWGH.LINK,-
   D0$LINKS:IZTGAI.LINK,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]HIS_DENS.OBJ    : -
   D0$TRD_UTIL$SOURCE:HIS_DENS.FOR,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]HPLIS.OBJ       : -
   D0$TRD_UTIL$SOURCE:HPLIS.FOR
  
D0$SCRATCH:[TRD_UTIL]INTOCH.OBJ      : -
   D0$TRD_UTIL$SOURCE:INTOCH.FOR
  
D0$SCRATCH:[TRD_UTIL]LIKEEF.OBJ      : -
   D0$TRD_UTIL$SOURCE:LIKEEF.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:GCONST.INC
  
D0$SCRATCH:[TRD_UTIL]LIKE_REF_MC.OBJ       : -
   D0$TRD_UTIL$SOURCE:LIKE_REF_MC.FOR
  
D0$SCRATCH:[TRD_UTIL]LIKNEF.OBJ      : -
   D0$TRD_UTIL$SOURCE:LIKNEF.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:GCONST.INC
  
D0$SCRATCH:[TRD_UTIL]LIK_REF_MC.OBJ  : -
   D0$TRD_UTIL$SOURCE:LIK_REF_MC.FOR
  
D0$SCRATCH:[TRD_UTIL]LUVW_DENS.OBJ   : -
   D0$TRD_UTIL$SOURCE:LUVW_DENS.FOR
  
D0$SCRATCH:[TRD_UTIL]MONTE_CARLO_DATA.OBJ  : -
   D0$TRD_UTIL$SOURCE:MONTE_CARLO_DATA.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]NEURO_DENS.OBJ  : -
   D0$TRD_UTIL$SOURCE:NEURO_DENS.FOR,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]PACK_INTEGER.OBJ      : -
   D0$TRD_UTIL$SOURCE:PACK_INTEGER.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]PACK_REAL.OBJ   : -
   D0$TRD_UTIL$SOURCE:PACK_REAL.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]PACK_TPRL.OBJ   : -
   D0$TRD_UTIL$SOURCE:PACK_TPRL.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRD_NWORD.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]PHI_TRD.OBJ     : -
   D0$TRD_UTIL$SOURCE:PHI_TRD.FOR,-
   D0$INC:PI.DEF
  
D0$SCRATCH:[TRD_UTIL]PRCDD4.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRCDD4.FOR,-
   D0$INC:D0LOG.INC,-
   D0$INC:FADCCN.INC,-
   D0$INC:TRINFO.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:WORKSP.INC,-
   D0$LINKS:IZCDD4.LINK
  
D0$SCRATCH:[TRD_UTIL]PRGTLY.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRGTLY.FOR,-
   D0$INC:D0LOG.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:WORKSP.INC,-
   D0$LINKS:IZGTRH.LINK,-
   D0$LINKS:IZGEAN.LINK,-
   D0$LINKS:IZGHIT.LINK
  
D0$SCRATCH:[TRD_UTIL]PRGTRH.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRGTRH.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]PRHTLY.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRHTLY.FOR,-
   D0$INC:D0LOG.INC,-
   D0$INC:FADCCN.INC,-
   D0$INC:GCUNIT.INC,-
   D0$INC:TRDHLN.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]PRSTRD.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRSTRD.FOR,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]PRTANA.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTANA.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBWRK.INC,-
   D0$INC:ZLINKC.INC
  
D0$SCRATCH:[TRD_UTIL]PRTDST.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTDST.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]PRTHIT.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTHIT.FOR,-
   D0$INC:CLUREC.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:THIT_INFO.INC,-
   D0$INC:ZEBWRK.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]PRTLYR.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTLYR.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]PRTPRL.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTPRL.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTPRL.LINK,-
   D0$INC:TRD_NWORD.INC
  
D0$SCRATCH:[TRD_UTIL]PRTPRL_OLD.OBJ  : -
   D0$TRD_UTIL$SOURCE:PRTPRL_OLD.FOR,-
   D0$INC:TCNTRL.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTPRL.LINK
  
D0$SCRATCH:[TRD_UTIL]PRTRAC.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTRAC.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTACH.LINK
  
D0$SCRATCH:[TRD_UTIL]PRTRDH.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTRDH.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]PRTRDT.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTRDT.FOR,-
   D0$LINKS:IZTRDT.LINK,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]PRTREL.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTREL.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGAI.LINK,-
   D0$LINKS:IZTELH.LINK
  
D0$SCRATCH:[TRD_UTIL]PRTRLC.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTRLC.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTLIK.LINK,-
   D0$LINKS:IZTRLC.LINK
  
D0$SCRATCH:[TRD_UTIL]PRTRLE.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTRLE.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTLIK.LINK,-
   D0$LINKS:IZTRLE.LINK
  
D0$SCRATCH:[TRD_UTIL]PRTROP.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTROP.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTROP.LINK
  
D0$SCRATCH:[TRD_UTIL]PRTRPD.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTRPD.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPDH.LINK
  
D0$SCRATCH:[TRD_UTIL]PRTRWG.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTRWG.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTWGH.LINK
  
D0$SCRATCH:[TRD_UTIL]PRTTRH.OBJ      : -
   D0$TRD_UTIL$SOURCE:PRTTRH.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTTRH.LINK
  
D0$SCRATCH:[TRD_UTIL]READ_URAN_CDFIX.OBJ   : -
   D0$TRD_UTIL$SOURCE:READ_URAN_CDFIX.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:D3U.INC
  
D0$SCRATCH:[TRD_UTIL]RELATIVE_AGEING.OBJ   : -
   D0$TRD_UTIL$SOURCE:RELATIVE_AGEING.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]RESET_TRDCOR.OBJ      : -
   D0$TRD_UTIL$SOURCE:RESET_TRDCOR.FOR,-
   D0$INC:TRDCOR.INC
  
D0$SCRATCH:[TRD_UTIL]ROADPH.OBJ      : -
   D0$TRD_UTIL$SOURCE:ROADPH.FOR,-
   D0$INC:ANGLIM.INC,-
   D0$INC:TCNTRL.INC
  
D0$SCRATCH:[TRD_UTIL]RUN1A.OBJ       : -
   D0$TRD_UTIL$SOURCE:RUN1A.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]RUN_NUMBER_ZONE.OBJ   : -
   D0$TRD_UTIL$SOURCE:RUN_NUMBER_ZONE.FOR
  
D0$SCRATCH:[TRD_UTIL]SELTRA.OBJ      : -
   D0$TRD_UTIL$SOURCE:SELTRA.FOR,-
   D0$INC:ANGLIM.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]SUMHIS.OBJ      : -
   D0$TRD_UTIL$SOURCE:SUMHIS.FOR,-
   D0$INC:PAWC.INC
  
D0$SCRATCH:[TRD_UTIL]TANAFL.OBJ      : -
   D0$TRD_UTIL$SOURCE:TANAFL.FOR,-
   D0$INC:TRD_NWORD.INC,-
   D0$INC:WORD_IN_TPRL.INC,-
   D0$INC:TRD_PHI_Z.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TCELLF.OBJ      : -
   D0$TRD_UTIL$SOURCE:TCELLF.FOR,-
   D0$INC:TRENER.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:TRDWIR.INC
  
D0$SCRATCH:[TRD_UTIL]TCELL_IN_ROAD.OBJ     : -
   D0$TRD_UTIL$SOURCE:TCELL_IN_ROAD.FOR,-
   D0$LINKS:IZCDD4.LINK,-
   D0$INC:GCONST.INC,-
   D0$INC:GEOMTC.INC,-
   D0$INC:GEOMTR.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:THIT_INFO.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:ZEBWRK.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TCHNB.OBJ       : -
   D0$TRD_UTIL$SOURCE:TCHNB.FOR,-
   D0$INC:TRD_NB_OF_WIRES.INC
  
D0$SCRATCH:[TRD_UTIL]TCODER.OBJ      : -
   D0$TRD_UTIL$SOURCE:TCODER.FOR,-
   D0$INC:TRD_NB_OF_WIRES.INC
  
D0$SCRATCH:[TRD_UTIL]TDACTV.OBJ      : -
   D0$TRD_UTIL$SOURCE:TDACTV.FOR,-
   D0$INC:GTRHLN.INC,-
   D0$INC:TRDLNK.INC,-
   D0$INC:LTRD.INC,-
   D0$INC:TRPROL.INC,-
   D0$INC:TRTOBN.INC
  
D0$SCRATCH:[TRD_UTIL]TDBINI.OBJ      : -
   D0$TRD_UTIL$SOURCE:TDBINI.FOR,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]TDEFLI.OBJ      : -
   D0$TRD_UTIL$SOURCE:TDEFLI.FOR,-
   D0$INC:LTRD.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPHY.LINK,-
   D0$LINKS:IZTCHA.LINK,-
   D0$LINKS:IZTPRO.LINK,-
   D0$LINKS:IZTCA1.LINK,-
   D0$LINKS:IZTCA2.LINK,-
   D0$LINKS:IZTPR1.LINK,-
   D0$LINKS:IZTPR2.LINK,-
   D0$LINKS:IZTMAE.LINK,-
   D0$LINKS:IZTMXE.LINK,-
   D0$LINKS:IZTPET.LINK,-
   D0$LINKS:IZTPE3.LINK,-
   D0$LINKS:IZTPTR.LINK,-
   D0$LINKS:IZTPT3.LINK,-
   D0$LINKS:IZTPLE.LINK,-
   D0$LINKS:IZTPEC.LINK,-
   D0$LINKS:IZTMAA.LINK,-
   D0$LINKS:IZTMAB.LINK,-
   D0$LINKS:IZTMAC.LINK,-
   D0$LINKS:IZTPCA.LINK,-
   D0$LINKS:IZTPCB.LINK,-
   D0$LINKS:IZTPCC.LINK
  
D0$SCRATCH:[TRD_UTIL]TDIFWIRE.OBJ    : -
   D0$TRD_UTIL$SOURCE:TDIFWIRE.FOR,-
   D0$INC:FIRSHT.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:TRDBGU.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TDSTDRP.OBJ     : -
   D0$TRD_UTIL$SOURCE:TDSTDRP.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TDSTFL.OBJ      : -
   D0$TRD_UTIL$SOURCE:TDSTFL.FOR,-
   D0$INC:TRD_DST_ENERGIES.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TFOURIER.OBJ    : -
   D0$TRD_UTIL$SOURCE:TFOURIER.FOR,-
   D0$INC:HTFIRS.INC
  
D0$SCRATCH:[TRD_UTIL]TGNINI.OBJ      : -
   D0$TRD_UTIL$SOURCE:TGNINI.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:QUEST.INC,-
   D0$LINKS:IZTGCH.LINK,-
   D0$LINKS:IZCRCP.LINK
  
D0$SCRATCH:[TRD_UTIL]TGTGNS.OBJ      : -
   D0$TRD_UTIL$SOURCE:TGTGNS.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGNS.LINK,-
   D0$LINKS:IZTGCH.LINK
  
D0$SCRATCH:[TRD_UTIL]TGTPDS.OBJ      : -
   D0$TRD_UTIL$SOURCE:TGTPDS.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPED.LINK,-
   D0$LINKS:IZTPCH.LINK
  
D0$SCRATCH:[TRD_UTIL]THIST_VER.OBJ   : -
   D0$TRD_UTIL$SOURCE:THIST_VER.FOR,-
   D0$LINKS:IZZTRK.LINK,-
   D0$INC:FIRSHT.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]THITFIL.OBJ     : -
   D0$TRD_UTIL$SOURCE:THITFIL.FOR,-
   D0$INC:FIRSHT.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]THIT_GET.OBJ    : -
   D0$TRD_UTIL$SOURCE:THIT_GET.FOR,-
   D0$INC:CLUREC.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:THIT_INFO.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTROP.LINK
  
D0$SCRATCH:[TRD_UTIL]THIT_UNPACK.OBJ       : -
   D0$TRD_UTIL$SOURCE:THIT_UNPACK.FOR,-
   D0$INC:CLUREC.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:THIT_INFO.INC,-
   D0$INC:ZEBWRK.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]THOTWIRE.OBJ    : -
   D0$TRD_UTIL$SOURCE:THOTWIRE.FOR,-
   D0$INC:FIRSHT.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:TRINTR.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC
  
D0$SCRATCH:[TRD_UTIL]TLYRFL.OBJ      : -
   D0$TRD_UTIL$SOURCE:TLYRFL.FOR,-
   D0$INC:TRTOBN.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TMULAY.OBJ      : -
   D0$TRD_UTIL$SOURCE:TMULAY.FOR,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TPDINI.OBJ      : -
   D0$TRD_UTIL$SOURCE:TPDINI.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:QUEST.INC,-
   D0$LINKS:IZTPCH.LINK,-
   D0$LINKS:IZCRCP.LINK
  
D0$SCRATCH:[TRD_UTIL]TPRLFIL.OBJ     : -
   D0$TRD_UTIL$SOURCE:TPRLFIL.FOR,-
   D0$INC:TPRL_VERSION_NB.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TCLUS_PER_WIRE.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:CLUREC.INC,-
   D0$INC:TRTOBN.INC,-
   D0$INC:TRDCOR.INC,-
   D0$INC:TR_INFO_HIT.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:URAN_COR.INC,-
   D0$INC:TRD_NWORD.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TPRLFL.OBJ      : -
   D0$TRD_UTIL$SOURCE:TPRLFL.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRATRD.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRATRD.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRINTR.INC
  
D0$SCRATCH:[TRD_UTIL]TRCELL.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRCELL.FOR,-
   D0$INC:FIRSHT.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:GEOMTC.INC,-
   D0$INC:GEOMTR.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRDVOL.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:TRD_PHI_Z.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRCFAD.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRCFAD.FOR,-
   D0$INC:CLUREC.INC,-
   D0$INC:FADCCN.INC,-
   D0$INC:FADTRD.INC,-
   D0$INC:FIRSHT.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRINTR.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:THIT_INFO.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:VARTRD.INC,-
   D0$INC:TCLUS_PER_WIRE.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRDCOR.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZCDD4.LINK,-
   D0$INC:ZEBWRK.INC
  
D0$SCRATCH:[TRD_UTIL]TRCHAN.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRCHAN.FOR
  
D0$SCRATCH:[TRD_UTIL]TRCROSS.OBJ     : -
   D0$TRD_UTIL$SOURCE:TRCROSS.FOR,-
   D0$INC:TR_CROSS_CELL.INC,-
   D0$INC:TRD_NB_OF_WIRES.INC
  
D0$SCRATCH:[TRD_UTIL]TRDANA.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDANA.FOR,-
   D0$INC:FADTRD.INC,-
   D0$INC:FIRSHT.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:CLUREC.INC,-
   D0$INC:GEOMTR.INC,-
   D0$INC:TRDEFF.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRDBOK.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDBOK.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:FIRSHT.INC
  
D0$SCRATCH:[TRD_UTIL]TRDBOK_ON.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRDBOK_ON.FOR,-
   D0$INC:HTFIRS.INC,-
   D0$INC:PI.DEF,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC
  
D0$SCRATCH:[TRD_UTIL]TRDCAN_UPDATE.OBJ     : -
   D0$TRD_UTIL$SOURCE:TRDCAN_UPDATE.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTROP.LINK,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:DBMUKEY.INC
  
D0$SCRATCH:[TRD_UTIL]TRDCON.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDCON.FOR,-
   D0$INC:GCONST.INC,-
   D0$INC:GCUNIT.INC,-
   D0$INC:D0LOG.INC,-
   D0$INC:GEOMTC.INC,-
   D0$INC:GEOMTR.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDVOL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTACH.LINK
  
D0$SCRATCH:[TRD_UTIL]TRDDEF.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDDEF.FOR,-
   D0$INC:GCONST.INC,-
   D0$INC:GCUNIT.INC,-
   D0$INC:FADCCN.INC
  
D0$SCRATCH:[TRD_UTIL]TRDDMP.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDDMP.FOR
  
D0$SCRATCH:[TRD_UTIL]TRDDRP.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDDRP.FOR
  
D0$SCRATCH:[TRD_UTIL]TRDFIL.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDFIL.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:FIRSHT.INC,-
   D0$INC:GEOMTR.INC,-
   D0$INC:TCLUS_PER_WIRE.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TR_CROSS_CELL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:TRINTR.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TRDFIX.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDFIX.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRDHIT.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDHIT.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:UNPTRD.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$LINKS:IZCDD4.LINK,-
   D0$INC:TCNTRL.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:TRHITW.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRDHIT_U.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRDHIT_U.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:UNPTRD.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:TRHITW.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRDHV_UPDATE.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDHV_UPDATE.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZTROP.LINK,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:DBMUKEY.INC
  
D0$SCRATCH:[TRD_UTIL]TRDINI.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDINI.FOR
  
D0$SCRATCH:[TRD_UTIL]TRDISA.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDISA.FOR,-
   D0$INC:GEOMTR.INC,-
   D0$INC:TRDVOL.INC
  
D0$SCRATCH:[TRD_UTIL]TRDNDR.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDNDR.FOR
  
D0$SCRATCH:[TRD_UTIL]TRDNOR.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDNOR.FOR,-
   D0$INC:HTFIRS.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRHITW.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TRDPAR.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDPAR.FOR,-
   D0$INC:TCNTRL.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZCDD4.LINK
  
D0$SCRATCH:[TRD_UTIL]TRDPAT.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDPAT.FOR,-
   D0$INC:TRDBGU.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TRDPAT_LEV2.OBJ       : -
   D0$TRD_UTIL$SOURCE:TRDPAT_LEV2.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TRDTFIL.OBJ     : -
   D0$TRD_UTIL$SOURCE:TRDTFIL.FOR,-
   D0$INC:TRDT_VERSION_NB.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:TRDEFF.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:VARTRD.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:URAN_COR.INC,-
   D0$LINKS:IZTROP.LINK
  
D0$SCRATCH:[TRD_UTIL]TRDTFL.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDTFL.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRDTMIN.OBJ     : -
   D0$TRD_UTIL$SOURCE:TRDTMIN.FOR,-
   D0$INC:FADTRD.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC
  
D0$SCRATCH:[TRD_UTIL]TRDUNP.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDUNP.FOR,-
   D0$INC:D0LOG.INC,-
   D0$INC:GCUNIT.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRDUSM.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRDUSM.FOR,-
   D0$INC:FIRSHT.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_ANALYSIS.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRD_ANALYSIS.FOR,-
   D0$INC:TRD_NWORD.INC,-
   D0$INC:TRDLIK.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:THIT_INFO.INC,-
   D0$INC:TRD_PHI_Z.INC,-
   D0$INC:TRD_DST_ENERGIES.INC,-
   D0$INC:WORD_IN_TPRL.INC,-
   D0$INC:ZEBWRK.INC,-
   D0$INC:ZLINKC.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_ANALYSIS_INI.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_ANALYSIS_INI.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_ANALYSIS_IN_RECO.OBJ : -
   D0$TRD_UTIL$SOURCE:TRD_ANALYSIS_IN_RECO.FOR,-
   D0$INC:TRD_NWORD.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:THIT_INFO.INC,-
   D0$INC:TRD_DST_ENERGIES.INC,-
   D0$INC:WORD_IN_TPRL.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_ANAL_CATH.OBJ     : -
   D0$TRD_UTIL$SOURCE:TRD_ANAL_CATH.FOR,-
   D0$INC:TRD_PHI_Z.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_BADRUN.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_BADRUN.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_BADSECTOR.OBJ     : -
   D0$TRD_UTIL$SOURCE:TRD_BADSECTOR.FOR,-
   D0$INC:PI.DEF
  
D0$SCRATCH:[TRD_UTIL]TRD_CALURAPT.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRD_CALURAPT.FOR,-
   D0$INC:URAN_COR.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZLINKC.INC,-
   D0$LINKS:IZCDD4.LINK
  
D0$SCRATCH:[TRD_UTIL]TRD_CHECK_BANK.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_CHECK_BANK.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_CHECK_GEOM.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_CHECK_GEOM.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_CHECK_INTEGRITY.OBJ : -
   D0$TRD_UTIL$SOURCE:TRD_CHECK_INTEGRITY.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZZTRK.LINK,-
   D0$INC:ISACAN.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_CHGHBK.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_CHGHBK.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_CLEAN_CLUST.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRD_CLEAN_CLUST.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TCLUS_PER_WIRE.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_COMBINE_ELEMENTS.OBJ : -
   D0$TRD_UTIL$SOURCE:TRD_COMBINE_ELEMENTS.FOR,-
   D0$INC:TRD_NWORD.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_CORGAS.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_CORGAS.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_CORHV.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRD_CORHV.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_COR_STATUS.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_COR_STATUS.FOR,-
   D0$INC:TRDCOR.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_COR_TEMP.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRD_COR_TEMP.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_CYLIND.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_CYLIND.FOR,-
   D0$INC:ISACAN.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_DISPATCH.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRD_DISPATCH.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_DO_PRINT.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRD_DO_PRINT.FOR,-
   D0$INC:TCNTRL.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_DST_COR.OBJ       : -
   D0$TRD_UTIL$SOURCE:TRD_DST_COR.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:TRD_COR_VALUES.INC,-
   D0$INC:ZEBWRK.INC,-
   D0$LINKS:IZTCY1.LINK,-
   D0$INC:TRD_NWORD.INC,-
   D0$INC:ZLINKC.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_DST_COR_ERR.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRD_DST_COR_ERR.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_DST_COR_IN_RECO.OBJ : -
   D0$TRD_UTIL$SOURCE:TRD_DST_COR_IN_RECO.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRD_NWORD.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_ELECTRON_PION.OBJ : -
   D0$TRD_UTIL$SOURCE:TRD_ELECTRON_PION.FOR,-
   D0$INC:TRDLIK.INC,-
   D0$INC:ZLINKC.INC,-
   D0$INC:TRD_PHI_Z.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBWRK.INC,-
   D0$INC:PI.DEF,-
   D0$LINKS:IZTPHY.LINK,-
   D0$LINKS:IZT1A0.LINK,-
   D0$LINKS:IZT1B0.LINK,-
   D0$LINKS:IZTLIK.LINK,-
   D0$LINKS:IZTPIO.LINK,-
   D0$LINKS:IZTELE.LINK,-
   D0$LINKS:IZTPI1.LINK,-
   D0$LINKS:IZTPI2.LINK,-
   D0$LINKS:IZTPDE.LINK,-
   D0$LINKS:IZTEL1.LINK,-
   D0$LINKS:IZTEL2.LINK,-
   D0$LINKS:IZTEDE.LINK,-
   D0$LINKS:IZTLTA.LINK
  
D0$SCRATCH:[TRD_UTIL]TRD_END_UPDATE.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_END_UPDATE.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_ENERGY_FIRED_CELLS.OBJ : -
   D0$TRD_UTIL$SOURCE:TRD_ENERGY_FIRED_CELLS.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRD_NWORD.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_ENERGY_MAX_CELLS.OBJ : -
   D0$TRD_UTIL$SOURCE:TRD_ENERGY_MAX_CELLS.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRD_NWORD.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_ENVIRONMENT.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRD_ENVIRONMENT.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRD_NWORD.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_EPS_COR.OBJ       : -
   D0$TRD_UTIL$SOURCE:TRD_EPS_COR.FOR,-
   D0$INC:TRDLIK.INC,-
   D0$INC:ZLINKC.INC,-
   D0$INC:TRD_PHI_Z.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:PI.DEF,-
   D0$LINKS:IZTPHY.LINK,-
   D0$LINKS:IZT1A0.LINK,-
   D0$LINKS:IZT1B0.LINK,-
   D0$LINKS:IZTLIK.LINK,-
   D0$LINKS:IZTPIO.LINK,-
   D0$LINKS:IZTELE.LINK,-
   D0$LINKS:IZTPI1.LINK,-
   D0$LINKS:IZTPI2.LINK,-
   D0$LINKS:IZTPDE.LINK,-
   D0$LINKS:IZTEL1.LINK,-
   D0$LINKS:IZTEL2.LINK,-
   D0$LINKS:IZTEDE.LINK,-
   D0$LINKS:IZTLTA.LINK
  
D0$SCRATCH:[TRD_UTIL]TRD_EPS_MC.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_EPS_MC.FOR,-
   D0$INC:TRD_DST_ENERGIES.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_EXM_ANAL.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRD_EXM_ANAL.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_FILLS_EVT.OBJ     : -
   D0$TRD_UTIL$SOURCE:TRD_FILLS_EVT.FOR,-
   D0$INC:TCNTRL.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_FINDS_GROUP.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRD_FINDS_GROUP.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRHITW.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_FIND_VER.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRD_FIND_VER.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZGEAN.LINK,-
   D0$LINKS:IZHSTR.LINK
  
D0$SCRATCH:[TRD_UTIL]TRD_FIRST_UPDATE.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_FIRST_UPDATE.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTROP.LINK
  
D0$SCRATCH:[TRD_UTIL]TRD_HISTOS.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_HISTOS.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRHITW_512.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_HITS.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_HITS.FOR,-
   D0$LINKS:IZCDD4.LINK,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_INTERSECTION.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_INTERSECTION.FOR,-
   D0$INC:TRD_PHI_Z.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_MENU.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_MENU.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_NEXT.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_NEXT.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_NUM_LAYERS.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_NUM_LAYERS.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:PI.DEF,-
   D0$INC:TRD_PHI_Z.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_NWIRE_PER_LAYER.OBJ : -
   D0$TRD_UTIL$SOURCE:TRD_NWIRE_PER_LAYER.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_ON_MICRO.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRD_ON_MICRO.FOR,-
   D0$INC:TRD_NWORD.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_DST_ENERGIES.INC,-
   D0$INC:WORD_IN_TPRL.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_PREVIOUS.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRD_PREVIOUS.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_REWB.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_REWB.FOR,-
   D0$INC:TPRL_VERSION_NB.INC,-
   D0$INC:TRDT_VERSION_NB.INC,-
   D0$INC:TRD_NWORD.INC,-
   D0$INC:TRD_PHI_Z.INC,-
   D0$INC:URAN_COR.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_SEPARATE_ELEMENTS.OBJ : -
   D0$TRD_UTIL$SOURCE:TRD_SEPARATE_ELEMENTS.FOR,-
   D0$INC:TRD_NWORD.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_TO_CDC_DEDX.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRD_TO_CDC_DEDX.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRD_NWORD.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_UPDATE_EVENT.OBJ  : -
   D0$TRD_UTIL$SOURCE:TRD_UPDATE_EVENT.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTROP.LINK,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_URAN_FETCH.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_URAN_FETCH.FOR,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_URAN_INSERT.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRD_URAN_INSERT.FOR,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_USER_DIALOG.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRD_USER_DIALOG.FOR
  
D0$SCRATCH:[TRD_UTIL]TRD_ZCATH.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRD_ZCATH.FOR,-
   D0$INC:TRD_PHI_Z.INC
  
D0$SCRATCH:[TRD_UTIL]TRD_ZPOS.OBJ    : -
   D0$TRD_UTIL$SOURCE:TRD_ZPOS.FOR,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRD_NWORD.INC
  
D0$SCRATCH:[TRD_UTIL]TREAD_MONITOR.OBJ     : -
   D0$TRD_UTIL$SOURCE:TREAD_MONITOR.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$INC:D3U.INC,-
   D0$INC:DBMUKEY.INC,-
   D0$LINKS:IZTROP.LINK,-
   D0$LINKS:IZCDD4.LINK
  
D0$SCRATCH:[TRD_UTIL]TREDEP.OBJ      : -
   D0$TRD_UTIL$SOURCE:TREDEP.FOR,-
   D0$INC:CLUREC.INC,-
   D0$INC:FIRSHT.INC,-
   D0$INC:QUEST.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:THIT_INFO.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:VARTRD.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTROP.LINK
  
D0$SCRATCH:[TRD_UTIL]TREDEP_LEV2.OBJ       : -
   D0$TRD_UTIL$SOURCE:TREDEP_LEV2.FOR,-
   D0$INC:CLUREC.INC,-
   D0$INC:FADCCN.INC,-
   D0$INC:FIRSHT.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:VARTRD.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:TRD_PED.INC
  
D0$SCRATCH:[TRD_UTIL]TRFPNT.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRFPNT.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:TRDBGU.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:TRTOBN.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRGGN.OBJ       : -
   D0$TRD_UTIL$SOURCE:TRGGN.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTGAI.LINK,-
   D0$LINKS:IZSTPC.LINK,-
   D0$LINKS:IZSTRD.LINK,-
   D0$LINKS:IZTWGH.LINK,-
   D0$INC:TRDWIR.INC
  
D0$SCRATCH:[TRD_UTIL]TRGPED.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRGPED.FOR,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZTPDH.LINK,-
   D0$LINKS:IZSTPC.LINK,-
   D0$LINKS:IZSTRD.LINK,-
   D0$INC:TRDWIR.INC
  
D0$SCRATCH:[TRD_UTIL]TRGVER.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRGVER.FOR,-
   D0$INC:FIRSHT.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:GEOMTR.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TRH_ON.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRH_ON.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:VARTRD.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRH_OUT.OBJ     : -
   D0$TRD_UTIL$SOURCE:TRH_OUT.FOR,-
   D0$INC:CLUREC.INC,-
   D0$INC:FIRSHT.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:TRWCOD.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRISIS.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRISIS.FOR,-
   D0$INC:TCNTRL.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRISRC.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRISRC.FOR
  
D0$SCRATCH:[TRD_UTIL]TRISRC_CLUST_EM.OBJ   : -
   D0$TRD_UTIL$SOURCE:TRISRC_CLUST_EM.FOR,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZLINKC.INC
  
D0$SCRATCH:[TRD_UTIL]TRISRC_CLUST_PHOT.OBJ : -
   D0$TRD_UTIL$SOURCE:TRISRC_CLUST_PHOT.FOR,-
   D0$INC:GEOMTR.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:ZLINKC.INC
  
D0$SCRATCH:[TRD_UTIL]TRISRC_FULL.OBJ       : -
   D0$TRD_UTIL$SOURCE:TRISRC_FULL.FOR,-
   D0$LINKS:IZZFIT.LINK,-
   D0$INC:GCONST.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRISRC_TRACK.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRISRC_TRACK.FOR,-
   D0$LINKS:IZZFIT.LINK,-
   D0$LINKS:IZZTRK.LINK,-
   D0$LINKS:IZZTMP.LINK,-
   D0$INC:GCONST.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TRISTP.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRISTP.FOR,-
   D0$INC:ZEBSTP.INC,-
   D0$LINKS:IZSTPC.LINK,-
   D0$LINKS:IZSTRD.LINK,-
   D0$LINKS:IZTPDH.LINK,-
   D0$LINKS:IZTGAI.LINK,-
   D0$LINKS:IZTGEN.LINK,-
   D0$LINKS:IZTGEO.LINK
  
D0$SCRATCH:[TRD_UTIL]TRISTR.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRISTR.FOR,-
   D0$INC:GEOMTR.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDVOL.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZISAE.LINK,-
   D0$LINKS:IZISV1.LINK,-
   D0$LINKS:IZISV2.LINK,-
   D0$LINKS:IZISP1.LINK,-
   D0$LINKS:IZISP2.LINK
  
D0$SCRATCH:[TRD_UTIL]TRREAD.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRREAD.FOR,-
   D0$INC:TRDVOL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:GEOMTR.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:GCONST.INC,-
   D0$INC:TRINFO.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:TRTOBN.INC,-
   D0$LINKS:IZCDD4.LINK
  
D0$SCRATCH:[TRD_UTIL]TRREMP.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRREMP.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:HTFIRS.INC,-
   D0$INC:TCNTRL.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:TRHITW.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TRUNIT.OBJ      : -
   D0$TRD_UTIL$SOURCE:TRUNIT.FOR,-
   D0$INC:GCUNIT.INC,-
   D0$INC:TRDBGU.INC
  
D0$SCRATCH:[TRD_UTIL]TSETWC.OBJ      : -
   D0$TRD_UTIL$SOURCE:TSETWC.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:QUEST.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:THIT_INFO.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:VARTRD.INC,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZCDD4.LINK
  
D0$SCRATCH:[TRD_UTIL]TSETWC_LEV2.OBJ       : -
   D0$TRD_UTIL$SOURCE:TSETWC_LEV2.FOR,-
   D0$INC:FADCCN.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:TRD_PED.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:VARTRD.INC,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TTRAKS.OBJ      : -
   D0$TRD_UTIL$SOURCE:TTRAKS.FOR,-
   D0$INC:PROVL.INC,-
   D0$INC:TCNTRL.INC,-
   D0$INC:TRENER.INC,-
   D0$INC:TRINTR.INC,-
   D0$INC:TRTOBN.INC,-
   D0$INC:TRDBGU.INC,-
   D0$INC:VARTRD.INC,-
   D0$LINKS:IZCDD4.LINK,-
   D0$INC:TTRAK_TYPE.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$LINKS:IZZTRK.LINK
  
D0$SCRATCH:[TRD_UTIL]TTRHFL.OBJ      : -
   D0$TRD_UTIL$SOURCE:TTRHFL.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]TVERIF.OBJ      : -
   D0$TRD_UTIL$SOURCE:TVERIF.FOR,-
   D0$INC:FADCCN.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]TWIRCOR.OBJ     : -
   D0$TRD_UTIL$SOURCE:TWIRCOR.FOR,-
   D0$INC:TCNTRL.INC
  
D0$SCRATCH:[TRD_UTIL]TWIRHOT.OBJ     : -
   D0$TRD_UTIL$SOURCE:TWIRHOT.FOR
  
D0$SCRATCH:[TRD_UTIL]T_COR_CABLE.OBJ       : -
   D0$TRD_UTIL$SOURCE:T_COR_CABLE.FOR
  
D0$SCRATCH:[TRD_UTIL]UNPACK_INTEGER.OBJ    : -
   D0$TRD_UTIL$SOURCE:UNPACK_INTEGER.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]UNPACK_REAL.OBJ       : -
   D0$TRD_UTIL$SOURCE:UNPACK_REAL.FOR,-
   D0$INC:ZEBCOM.INC
  
D0$SCRATCH:[TRD_UTIL]UNPACK_REAL_STP.OBJ   : -
   D0$TRD_UTIL$SOURCE:UNPACK_REAL_STP.FOR,-
   D0$INC:ZEBSTP.INC
  
D0$SCRATCH:[TRD_UTIL]UNPACK_TPRL.OBJ       : -
   D0$TRD_UTIL$SOURCE:UNPACK_TPRL.FOR,-
   D0$INC:TRD_NWORD.INC,-
   D0$INC:TRD_PHI_Z.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:WORKSP.INC
  
D0$SCRATCH:[TRD_UTIL]URANIUM_TO_EPICOR.OBJ : -
   D0$TRD_UTIL$SOURCE:URANIUM_TO_EPICOR.FOR
  
D0$SCRATCH:[TRD_UTIL]VAXTIMECOMP.OBJ       : -
   D0$TRD_UTIL$SOURCE:VAXTIMECOMP.FOR
  
D0$SCRATCH:[TRD_UTIL]WRITE_TRDCOR.OBJ      : -
   D0$TRD_UTIL$SOURCE:WRITE_TRDCOR.FOR,-
   D0$INC:TRDCOR.INC,-
   D0$INC:TRENER.INC
  
D0$SCRATCH:[TRD_UTIL]ZDEXPD_TRD.OBJ  : -
   D0$TRD_UTIL$SOURCE:ZDEXPD_TRD.FOR,-
   D0$PARAMS:TRD_NB_OF_WIRES.PARAMS,-
   D0$INC:TRD_NB_OF_WIRES.INC,-
   D0$INC:TRWCOD_512.INC,-
   D0$INC:ZEBCOM.INC,-
   D0$INC:CDPARA.INC,-
   D0$INC:ZCDDLK.INC,-
   D0$LINKS:IZCDD1.LINK,-
   D0$LINKS:IZCDD4.LINK
  
D0$SCRATCH:[TRD_UTIL]Z_CATHODE.OBJ   : -
   D0$TRD_UTIL$SOURCE:Z_CATHODE.FOR,-
   D0$INC:GEOMTR.INC,-
   D0$INC:GEOMTC.INC,-
   D0$LINKS:IZZTRK.LINK,-
   D0$PARAMS:MAXLEV.DEF,-
   D0$INC:WORKSP.INC,-
   D0$INC:ZEBCOM.INC
  
 
NOTHING.NL : SYS$LOGIN:LOGIN.COM
  @ WRITE SYS$OUTPUT "%RELEASE-I-No main processing to be executed
 
.ENDIF
