CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VTRD_UTIL()
      VTRD_UTIL = ' TRD_UTIL'//
     X                   '  OFFICIAL V1.16'//
     X                   ' 14-JUL-1997 17:27:41.65'
      Return
      End
