CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VTRD_UTIL()
      VTRD_UTIL = ' TRD_UTIL'//
     X                   '  TEST V1.16_01'//
     X                   '  2-SEP-1997 09:27:09.66'
      Return
      End
