PACKAGE := isajet
$(PACKAGE)_LIB := yes
include GNUmakefile.subcommon

ISAJET_F77 := isajet
$(foreach f,$(ISAJET_F77),tmp/DEB/isajet/source/$(f).o tmp/OPT/isajet/source/$(f).o) : FORT := $(F77)
$(foreach f,$(ISAJET_F77),tmp/DEB/isajet/source/$(f).o tmp/OPT/isajet/source/$(f).o) : FORT_COMMON_FLAGS := $(F77_COMMON_FLAGS)

