#! /bin/csh -f

foreach file (`ls $cwd/source/*.c`)
   echo $file
   if( ! -f ${file}.vax )mv ${file} ${file}.vax

   set s1 = 's@D0\$XFRAME\$SOURCE:@'$cwd'/source/@g'
   set s2 = 's@d0\$xframe\$source:@'$cwd'/source/@g'
   set s3 = 's@D0X_C.H@d0x_c.h@g'
   set s4 = 's@D0X.H@d0x.h@g'
   set s5 = 's@TREE.H@tree.h@g'
   set s6 = 's@TREEP.H@treep.h@g'

   sed $s1 ${file}.vax | \
   sed $s2 | \
   sed $s3 | \
   sed $s4 | \
   sed $s5 | \
   sed $s6 >& ${file}

end

