

      SUBROUTINE CPHLC(IETAC,IPHC,LAYERC,XL,YL,ZL,ARGSOK)
C----------------------------------------------------------------------
C-
C-   Purpose and Methods :
C-
C-   Inputs  :
C-   Outputs :
C-   Controls:
C-
C-   Created  12-DEC-1988   Michael W. Peters
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
C----------------------------------------------------------------------
      INTEGER IETAC,IPHC,LAYERC
      REAL XL(8),YL(8),ZL(8)
      INTEGER ARGSOK,AROKIN
      REAL CPH,DPH,CTH,DTH,CRAD,DRAD,CZED,DZED
C
      ARGSOK=1
      CALL CALPHI(IPHC,IETAC,CPH,DPH,AROKIN)
      IF(AROKIN.NE.0) GO TO 999
      CALL CALTH(IETAC,CTH,DTH,AROKIN)
      IF(AROKIN.NE.0) GO TO 999
      CALL CALRAD(IETAC,LAYERC,CRAD,DRAD,AROKIN)
      IF(AROKIN.NE.0) GO TO 100
      CALL CCCPTS(CTH+DTH/2.,CPH+DPH/2.,CRAD+DRAD/2.,XL(1),YL(1),ZL(1))
      CALL CCCPTS(CTH-DTH/2.,CPH+DPH/2.,CRAD+DRAD/2.,XL(2),YL(2),ZL(2))
      CALL CCCPTS(CTH-DTH/2.,CPH-DPH/2.,CRAD+DRAD/2.,XL(3),YL(3),ZL(3))
      CALL CCCPTS(CTH+DTH/2.,CPH-DPH/2.,CRAD+DRAD/2.,XL(4),YL(4),ZL(4))
      CALL CCCPTS(CTH+DTH/2.,CPH+DPH/2.,CRAD-DRAD/2.,XL(5),YL(5),ZL(5))
      CALL CCCPTS(CTH-DTH/2.,CPH+DPH/2.,CRAD-DRAD/2.,XL(6),YL(6),ZL(6))
      CALL CCCPTS(CTH-DTH/2.,CPH-DPH/2.,CRAD-DRAD/2.,XL(7),YL(7),ZL(7))
      CALL CCCPTS(CTH+DTH/2.,CPH-DPH/2.,CRAD-DRAD/2.,XL(8),YL(8),ZL(8))
      ARGSOK=0
      GO TO 999
  100 CONTINUE
      CALL CALZED(LAYERC,IETAC,CZED,DZED,AROKIN)
      IF(AROKIN.NE.0) GO TO 200
      CALL CECPTS(CTH+DTH/2.,CPH+DPH/2.,CZED+DZED/2.,XL(1),YL(1),ZL(1))
      CALL CECPTS(CTH-DTH/2.,CPH+DPH/2.,CZED+DZED/2.,XL(2),YL(2),ZL(2))
      CALL CECPTS(CTH-DTH/2.,CPH-DPH/2.,CZED+DZED/2.,XL(3),YL(3),ZL(3))
      CALL CECPTS(CTH+DTH/2.,CPH-DPH/2.,CZED+DZED/2.,XL(4),YL(4),ZL(4))
      CALL CECPTS(CTH+DTH/2.,CPH+DPH/2.,CZED-DZED/2.,XL(5),YL(5),ZL(5))
      CALL CECPTS(CTH-DTH/2.,CPH+DPH/2.,CZED-DZED/2.,XL(6),YL(6),ZL(6))
      CALL CECPTS(CTH-DTH/2.,CPH-DPH/2.,CZED-DZED/2.,XL(7),YL(7),ZL(7))
      CALL CECPTS(CTH+DTH/2.,CPH-DPH/2.,CZED-DZED/2.,XL(8),YL(8),ZL(8))
      ARGSOK=0
      GO TO 999
  200 CONTINUE
      ARGSOK=2
  999 RETURN
      END
