CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VOFFLINE_UTIL()
      VOFFLINE_UTIL = ' OFFLINE_UTIL'//
     X                   '  TEST V4.28_02'//
     X                   ' 24-NOV-1997 15:43:54.08'
      Return
      End
