CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VOFFLINE_UTIL()
      VOFFLINE_UTIL = ' OFFLINE_UTIL'//
     X                   '  OFFICIAL V4.28'//
     X                   ' 11-JUL-1997 12:19:20.48'
      Return
      End
