      SUBROUTINE PBDINI                                                         
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-    This routine must be called by the FrameWork to initialize                
C-    the run time switches associated with the packages                        
C-    Created by the PROGRAM BUILDER                                            
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL WRNGOK                                                            
      INTEGER LOGUNT,MAXLOG,MAXWRN                                              
      CHARACTER*32 STRGLG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
C-                                                                              
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      LOGUNT = 0                                                                
      WRNGOK = .TRUE.                                                           
      CALL ERRINI(LOGUNT,WRNGOK)                                                
      MAXLOG = 1                                                                
      MAXWRN = 1                                                                
      STRGLG = ' '                                                              
      CALL ERRMAX(STRGLG,MAXLOG,MAXWRN)                                         
C-                                                                              
      PBD_FLAG_MAX =  3                                                         
C-                                                                              
      PBD_FLAG_VALUE( 1) = .TRUE.                                               
      PBD_FLAG_NAME( 1) = 'CALOR'                                               
      PBD_FLAG_VALUE( 2) = .TRUE.                                               
      PBD_FLAG_NAME( 2) = 'COMPUTE_EM_QUALITY'                                  
      PBD_FLAG_VALUE( 3) = .TRUE.                                               
      PBD_FLAG_NAME( 3) = 'TOP_LEPTONS'                                         
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-    The following routine has been generated by the Program Builder           
C-    because the size of the common blocks has been modified                   
C-    by the user.                                                              
C-                                                                              
C-    Created by the PROGRAM BUILDER                                            
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      SUBROUTINE INZCOM(I)                                                      
C----------------------------------------------------------------------         
C-                                                                              
C-   Purpose and Methods :                                                      
C-       Initialize ZEBCOM (event data Zebra common)                            
C-                                                                              
C-   Inputs  : I = 1 data in division 1, otherwise in division 2                
C-   Outputs : NONE                                                             
C-                                                                              
C-   Created  28-OCT-1988   Serban D. Protopopescu                              
C-                                                                              
C----------------------------------------------------------------------         
      IMPLICIT NONE                                                             
C-                                                                              
C     INCLUDE 'D0$INC:ZEBCOM.INC'                                               
C-                                                                              
C-                                                                              
C DEC/CMS REPLACEMENT HISTORY, Element ZEBCOM.INC                               
C *12   19-DEC-1988 11:45:39 D0LIBRARY "added IXCOM, removed IXDIV"             
C *11   29-NOV-1988 16:25:17 D0LIBRARY "added comments"                         
C *10   29-NOV-1988 16:21:03 D0LIBRARY "added IXDIV and IXDVR"                  
C *9    22-SEP-1986 11:26:53 JONCKHEERE "Increase ZEBCOM size for GEANT"        
C *8     2-SEP-1986 13:45:57 SERBAN "links are now in .LINKS files"             
C *7    15-JUL-1986 16:00:14 JONCKHEERE "PARAMETER FOR MUHT,CAHT,CDHT ADDED (MUH
C *6    27-MAY-1986 13:10:11 SERBAN "parameter NNQ changed from 50000 to 100000"
C *5    15-MAY-1986 16:51:11 SERBAN "added more pointers for ISAJET"            
C *4    12-MAY-1986 18:41:24 HEDIN "Put in Muon Zebra Links"                    
C *3    12-MAY-1986 16:46:40 SERBAN "added parameters for link pointers"        
C *2     7-MAY-1986 21:41:19 KUNORI "convert to standard 77 (drop *4)"          
C *1    14-JAN-1986 17:22:30 PROTOPOPESCU "Zebra common block for event data"   
C DEC/CMS REPLACEMENT HISTORY, Element ZEBCOM.INC                               
C                                                                               
C  ZEBCOM is the main zebra common block for event data storage                 
C                                                                               
      INTEGER NNQ,NREF                                                          
C     PARAMETER (NNQ=200000)                                                    
C-                                                                              
C-    The following is the new parameter value                                  
C-                                                                              
      PARAMETER (NNQ=3000000 )                                                  
C-                                                                              
      PARAMETER (NREF=9)                                                        
      COMMON/ZEBCOM/IXCOM,IXMAIN,IXDVR,FENCE,LHEAD,LHEADR,LREF,                 
     &  ZSTOR,ENDZS                                                             
      INTEGER IXCOM    ! store number                                           
     &       ,IXMAIN   ! event division number                                  
     &       ,IXDVR    ! run division number                                    
      INTEGER FENCE(8),LREF(NREF),ZSTOR(NNQ),ENDZS                              
      INTEGER LHEAD     ! pointer to event HEAD bank                            
      INTEGER LHEADR    ! pointer to begin run HEAD bank                        
      REAL Q(NNQ)                                                               
      INTEGER IQ(NNQ),LQ(NNQ)                                                   
      EQUIVALENCE (LHEAD,LQ(1)),(LQ(9),IQ(1),Q(1))                              
C                                                                               
C-                                                                              
C-                                                                              
      INTEGER I                                                                 
      LOGICAL FIRST                                                             
      SAVE FIRST                                                                
      DATA FIRST/.TRUE./                                                        
C----------------------------------------------------------------------         
C                                                                               
      IF(FIRST) THEN                                                            
C                                                                               
C **** Initialize store in /ZEBCOM/ common (store 0)                            
C                                                                               
        IXCOM=0                                                                 
        CALL MZSTOR (IXCOM,'/ZEBCOM/','Q',FENCE,LHEAD,LREF(1),ZSTOR(1),         
     &   ZSTOR(40000),ENDZS)                                                    
C                                                                               
C **** Use division IXMAIN for event data                                       
C                                                                               
        IXMAIN=IXCOM+2                                                          
        IF(I.EQ.1) IXMAIN=IXCOM+1                                               
C                                                                               
C **** Create a division for run header (3rd division)                          
C                                                                               
        CALL MZDIV(IXCOM,IXDVR,'RUN DIV',100,40000,'L')                         
        FIRST=.FALSE.                                                           
      ENDIF                                                                     
  999 RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
C-                                                                              
C-    The following routine has been generated by the Program Builder           
C-    because the size of the common blocks has been modified                   
C-    by the user.                                                              
C-                                                                              
C-    Created by the PROGRAM BUILDER                                            
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      SUBROUTINE INZSTP                                                         
C----------------------------------------------------------------------         
C-                                                                              
C-   Purpose and Methods :                                                      
C-       Initialize ZEBSTP (Zebra common for static parameters)                 
C-                                                                              
C-   Created  28-OCT-1988   Serban D. Protopopescu                              
C-                                                                              
C----------------------------------------------------------------------         
      IMPLICIT NONE                                                             
C-                                                                              
C     INCLUDE 'D0$INC:ZEBSTP.INC'                                               
C-                                                                              
C-                                                                              
C ZEBSTP.INC                                                                    
      INTEGER NNC                                                               
C     PARAMETER (NNC=200000)                                                    
C-                                                                              
C-    The following is the new parameter value                                  
C-                                                                              
      PARAMETER (NNC=3000000 )                                                  
C-                                                                              
      COMMON/ZEBSTP/IXSTP,IDVSTP,IDVSUM,FENSTP,LSTPH,LZSUM,                     
     1 LSLV0,LLPDH,LLGNH,LLTMH,LLGEH,LLV,   ! level 0 links                     
     2 LSMUO,LMPDH,LMGNH,LMTMH,LMGEH,LMU,   ! muon links                        
     3 LSVTX,LVPDH,LVGNH,LVTMH,LVGEH,LVT,   ! vertex chamber links              
     4 LSCDC,LDPDH,LDGNH,LDTMH,LDGEH,LDALH,LDC,   ! cdc links                   
     5 LSTRD,LTPDH,LTGAI,LTGEN,LTGEO,LTR,   ! trd links                         
     6 LSFDC,LFPDH,LFGNH,LFTMH,LFGEH,LFD,   ! fdc links                         
     7 LSCAL,LCPDH,LCGNH,LCGEH,LCA,         ! calorimeter links                 
     8 ZCONS,ENDZC                                                              
      INTEGER IXSTP,IDVSTP,IDVSUM,FENSTP(10),LZSUM,ZCONS(NNC),ENDZC             
      REAL C(NNC)                                                               
      INTEGER IC(NNC),LC(NNC)                                                   
      EQUIVALENCE (LSTPH,LC(1)),(LC(9),IC(1),C(1))                              
      INTEGER LSTPH     ! static parameter header                               
     $,  LSLV0      ! level 0 constants header                                  
     $,  LLPDH      ! level 0 pedestal header                                   
     $,  LLGNH      ! level 0 gain header                                       
     $,  LLTMH      ! level 0 time constants header                             
     $,  LLGEH      ! level 0 geometry constants header                         
     $,  LLV(10)    ! available                                                 
C                                                                               
      INTEGER LSMUO      ! Muon constants header                                
     $,  LMPDH      ! Muon pedestal header                                      
     $,  LMGNH      ! Muon gain header                                          
     $,  LMTMH      ! Muon time constants header                                
     $,  LMGEH      ! Muon geometry constants header                            
     $,  LMU(10)    ! available                                                 
C                                                                               
      INTEGER LSVTX      ! Vertex chamber constants header                      
     $,  LVPDH      ! Vertex chamber pedestal header                            
     $,  LVGNH      ! Vertex chamber gain header                                
     $,  LVTMH      ! Vertex chamber time constants header                      
     $,  LVGEH      ! Vertex chamber geometry constants header                  
     $,  LVT(10)    ! available                                                 
C                                                                               
      INTEGER LSCDC      ! CDC constants header                                 
     $,  LDPDH      ! CDC pedestal header                                       
     $,  LDGNH      ! CDC gain header                                           
     $,  LDTMH      ! CDC time constants header                                 
     $,  LDGEH      ! CDC geometry constants header                             
     $,  LDALH      ! CDC wire alignment constants header                       
     $,  LDC(9)     ! available                                                 
C                                                                               
      INTEGER LSTRD      ! TRD constants header                                 
     $,  LTPDH      ! TRD pedestal header                                       
     $,  LTGAI      ! TRD gains header                                          
     $,  LTGEN      ! TRD general header                                        
     $,  LTGEO      ! TRD geometry constants header                             
     $,  LTR(10)    ! available                                                 
C                                                                               
      INTEGER LSFDC      ! FDC constants header                                 
     $,  LFPDH      ! FDC pedestal header                                       
     $,  LFGNH      ! FDC gain header                                           
     $,  LFTMH      ! FDC time constants header                                 
     $,  LFGEH      ! FDC geometry constants header                             
     $,  LFD(10)    ! available                                                 
C                                                                               
      INTEGER LSCAL      ! Calorimeter constants header                         
     $,  LCPDH      ! Calorimeter pedestal header                               
     $,  LCGNH      ! Calorimeter gain header                                   
     $,  LCGEH      ! Calorimeter geometry constants header                     
     $,  LCA(11)    ! available                                                 
C                                                                               
C-                                                                              
C-                                                                              
      LOGICAL FIRST                                                             
      SAVE FIRST                                                                
      DATA FIRST/.TRUE./                                                        
C----------------------------------------------------------------------         
C                                                                               
      IF(FIRST) THEN                                                            
C                                                                               
C          Note that 10 words are set aside for reference links                 
C          but are not specifically named in the common block                   
C                                                                               
        CALL MZSTOR (IXSTP,'/ZEBSTP/','C',FENSTP,LSTPH,ZCONS,ZCONS(10),         
     &   ZCONS(10000),ENDZC)                                                    
C                                                                               
C **** IDVSTP is the 2nd division in the ZEBSTP store.                          
C                                                                               
        IDVSTP=IXSTP+2                                                          
        CALL CONSTP                 ! construct STP headers                     
        FIRST=.FALSE.                                                           
      ENDIF                                                                     
  999 RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
C-                                                                              
C-    The following routine has been generated by the Program Builder           
C-    because the size of the common blocks has been modified                   
C-    by the user.                                                              
C-                                                                              
C-    Created by the PROGRAM BUILDER                                            
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      SUBROUTINE INPAWC                                                         
C----------------------------------------------------------------------         
C-                                                                              
C-   Purpose and Methods :                                                      
C-       Initialize PAWC common for HBOOK4                                      
C-                                                                              
C-   Created  27-MAR-1989   Serban D. Protopopescu                              
C-   Updated  17-APR-1991   Rajendran Raja  Updated to have Global sections     
C-   Updated   3-MAR-1992   K. Wyatt Merritt  Put global sections in machine    
C-                           block for unix compatibility                       
C-                                                                              
C----------------------------------------------------------------------         
      IMPLICIT NONE                                                             
C-                                                                              
C     INCLUDE 'D0$INC:PAWC.INC'                                                 
C-                                                                              
C-                                                                              
C----------------------------------------------------------------------         
C-                                                                              
C-   Created  16-MAY-1989   Serban D. Protopopescu                              
C-   Updated   1-JUN-1991   Rajendran Raja                                      
C-                                                                              
C----------------------------------------------------------------------         
      INTEGER NPAWC                                                             
C     PARAMETER (NPAWC=100000)                                                  
C-                                                                              
C-    The following is the new parameter value                                  
C-                                                                              
      PARAMETER (NPAWC=2000000 )                                                
C-                                                                              
      INTEGER PAGELEN                                                           
      PARAMETER( PAGELEN = 128 )        ! LENGTH OF PAGE                        
      INTEGER MAXPAGES                                                          
      PARAMETER( MAXPAGES = NPAWC/PAGELEN )                                     
      CHARACTER*32 GNAME                                                        
C                                                                               
      COMMON/PAWC/NWPAW,IXPAWC,IHDIV,IXHIGZ,IXKU,FENC(5),LPMAIN,                
     &  HCV(9989)                                                               
C                                                                               
      REAL HMEMOR(PAGELEN*MAXPAGES)                                             
      INTEGER NWPAW,IXPAWC,IHDIV,IXHIGZ,IXKU,FENC,LPMAIN,HCV                    
      EQUIVALENCE(NWPAW,HMEMOR(1))                                              
      INTEGER IP(2),LP(8000)                                                    
      REAL    P(2)                                                              
      EQUIVALENCE (LP(1),LPMAIN),(IP(1),LP(9)),(P(1),IP(1))                     
C-                                                                              
C-                                                                              
      INTEGER NPAGES,HCREATEG                                                   
      INTEGER TRNLNM,STATUS,LENG                                                
      INTEGER TRULEN                                                            
C----------------------------------------------------------------------         
C                                                                               
      STATUS = TRNLNM('GLOBAL$PAWC',GNAME,LENG)                                 
      IF ( GNAME(1:LENG).EQ.'GLOBAL$PAWC' ) THEN          ! NO GLOBAL SECTION   
        CALL HLIMIT(-PAGELEN*MAXPAGES)                                          
      ELSE                                                                      
C&IF VAXVMS                                                                     
        NPAGES = HCREATEG(GNAME(1:LENG),HMEMOR,PAGELEN*MAXPAGES)                
        IF ( NPAGES.GT.0 ) THEN                                                 
          CALL ERRMSG(' INPAWC ','INPAWC',                                      
     &    ' GLOBAL SECTION: '//GNAME(1:LENG)//' CREATED ','S')                  
          CALL HLIMIT(-PAGELEN*MAXPAGES)                                        
        ELSE                                                                    
          CALL ERRMSG(' INPAWC ','INPAWC ',                                     
     &    ' GLOBAL SECTION ERROR ','S')                                         
        ENDIF                                                                   
C&ELSE                                                                          
C&        CALL HLIMIT(-PAGELEN*MAXPAGES)                                        
C&        CALL ERRMSG(' INPAWC ','INPAWC ',                                     
C&     &    'Global section not created on non-VMS system','S')                 
C&ENDIF                                                                         
      ENDIF                                                                     
C                                                                               
  999 RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION STSWCH()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-    This routine allows the Program Builder user to set                       
C-    and reset(ON/OFF) the run time switches associated                        
C-    with the packages.                                                        
C-    Created by the PROGRAM BUILDER                                            
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      LOGICAL PRODUC                                                            
      LOGICAL LCALOR                                                            
      LOGICAL LCOMPUTE_EM_QUALITY                                               
      LOGICAL LTOP_LEPTONS                                                      
      INTEGER NUMPAR                                                            
      CHARACTER*30 LABELS( 3)                                                   
      CHARACTER TYPARR( 3)                                                      
      INTEGER LIMITS(2, 3)                                                      
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      EXTERNAL PRODUC                                                           
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      DATA NUMPAR / 3/                                                          
      DATA LABELS /                                                             
     &          'CALOR Selected'                                                
     &         ,'COMPUTE_EM_QUALITY Selected'                                   
     &         ,'TOP_LEPTONS Selected'                                          
     &       /                                                                  
      DATA TYPARR /                                                             
     &           'L'                                                            
     &          ,'L'                                                            
     &          ,'L'                                                            
     &       /                                                                  
C-                                                                              
      IF (.NOT. PRODUC()) THEN                                                  
         LCALOR = PBD_FLAG_VALUE( 1)                                            
         LCOMPUTE_EM_QUALITY = PBD_FLAG_VALUE( 2)                               
         LTOP_LEPTONS = PBD_FLAG_VALUE( 3)                                      
         CALL GETDIS(NUMPAR,LABELS,TYPARR,LIMITS                                
     &              ,LCALOR                                                     
     &              ,LCOMPUTE_EM_QUALITY                                        
     &              ,LTOP_LEPTONS                                               
     &                                          )                               
C-                                                                              
         PBD_FLAG_VALUE( 1) = LCALOR                                            
         PBD_FLAG_VALUE( 2) = LCOMPUTE_EM_QUALITY                               
         PBD_FLAG_VALUE( 3) = LTOP_LEPTONS                                      
      END IF                                                                    
C-                                                                              
      STSWCH = .TRUE.                                                           
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION PBD_SET_FLAG(FLAG_NAME,VALUE)                            
C-                                                                              
      IMPLICIT NONE                                                             
C-                                                                              
      CHARACTER*(*) FLAG_NAME                                                   
      CHARACTER*80 TMP_FLAG_NAME                                                
      INTEGER I                                                                 
      LOGICAL DONE,VALUE                                                        
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
C-                                                                              
      I = 1                                                                     
      DONE = .FALSE.                                                            
      CALL PBD_UPCASE(FLAG_NAME,TMP_FLAG_NAME)                                  
      DO WHILE ((I.LE.PBD_FLAG_MAX).AND.(.NOT.DONE))                            
        IF (TMP_FLAG_NAME(1:LEN(FLAG_NAME)).EQ.                                 
     &      PBD_FLAG_NAME(I)(1:LEN(FLAG_NAME))) THEN                            
          PBD_FLAG_VALUE(i) = VALUE                                             
          DONE = .TRUE.                                                         
        END IF                                                                  
        I = I + 1                                                               
      END DO                                                                    
      PBD_SET_FLAG = DONE                                                       
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION PBD_GET_FLAG(FLAG_NAME,VALUE)                            
C-                                                                              
      IMPLICIT NONE                                                             
C-                                                                              
      CHARACTER*(*) FLAG_NAME                                                   
      CHARACTER*80 TMP_FLAG_NAME                                                
      INTEGER I                                                                 
      LOGICAL DONE,VALUE                                                        
C-                                                                              
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      I = 1                                                                     
      DONE = .FALSE.                                                            
      CALL PBD_UPCASE(FLAG_NAME,TMP_FLAG_NAME)                                  
      DO WHILE ((I.LE.PBD_FLAG_MAX).AND.(.NOT.DONE))                            
        IF (TMP_FLAG_NAME(1:LEN(FLAG_NAME)).EQ.                                 
     &      PBD_FLAG_NAME(I)(1:LEN(FLAG_NAME))) THEN                            
          VALUE = PBD_FLAG_VALUE(I)                                             
          DONE = .TRUE.                                                         
        END IF                                                                  
        I = I + 1                                                               
      END DO                                                                    
      PBD_GET_FLAG = DONE                                                       
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      SUBROUTINE PBD_DUMP_FLAGS                                                 
C-                                                                              
      IMPLICIT NONE                                                             
C-                                                                              
      INTEGER I                                                                 
C-                                                                              
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
      DO I = 1, PBD_FLAG_MAX                                                    
        WRITE (6,'('' '',A,'' : '',L)') PBD_FLAG_NAME(I)(1:32),                 
     &PBD_FLAG_VALUE(I)                                                         
      END DO                                                                    
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      SUBROUTINE PBD_UPCASE(IN_STRING,OUT_STRING)                               
      IMPLICIT NONE                                                             
      CHARACTER*(*) IN_STRING,OUT_STRING                                        
      INTEGER I,OFFSET                                                          
C-                                                                              
C-                                                                              
C-                                                                              
      OFFSET = ICHAR('A') - ICHAR('a')                                          
      DO I = 1, LEN(IN_STRING)                                                  
        IF ((IN_STRING(I:I).GE.'a').AND.(IN_STRING(I:I).LE.'z')) THEN           
          OUT_STRING(I:I) = CHAR(ICHAR(IN_STRING(I:I)) + OFFSET)                
        ELSE                                                                    
          OUT_STRING(I:I) = IN_STRING(I:I)                                      
        END IF                                                                  
      END DO                                                                    
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION EVENT_READ_OK()                                          
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      EVENT_READ_OK = .TRUE.                                                    
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USREVT()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL COMPUTE_EM_QUALITY                                                
      EXTERNAL COMPUTE_EM_QUALITY                                               
      LOGICAL TOP_LEPTONS_EVENT                                                 
      EXTERNAL TOP_LEPTONS_EVENT                                                
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USREVT = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
      IF ( (PBD_FLAG_VALUE( 2))                                                 
     &    ) THEN                                                                
         IF (.NOT. COMPUTE_EM_QUALITY()) THEN                                   
            USREVT = .FALSE.                                                    
            MESSID = '!COMPUTE_EM_QUALITY is false.'                            
            CALLER = 'COMPUTE_EM_QUALITY'                                       
            MESSAG = 'Further processing is skipped'                            
            CALL ERRMSG(MESSID,CALLER,MESSAG,'W')                               
            RETURN                                                              
         END IF                                                                 
      END IF                                                                    
C-                                                                              
      IF ( (PBD_FLAG_VALUE( 3))                                                 
     &    ) THEN                                                                
         IF (.NOT. TOP_LEPTONS_EVENT()) THEN                                    
            USREVT = .FALSE.                                                    
            MESSID = '!TOP_LEPTONS_EVENT is false.'                             
            CALLER = 'TOP_LEPTONS_EVENT'                                        
            MESSAG = 'Further processing is skipped'                            
            CALL ERRMSG(MESSID,CALLER,MESSAG,'W')                               
            RETURN                                                              
         END IF                                                                 
      END IF                                                                    
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USRINI()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL CALOR_INI                                                         
      EXTERNAL CALOR_INI                                                        
      LOGICAL COMPUTE_EM_QUALITY_INI                                            
      EXTERNAL COMPUTE_EM_QUALITY_INI                                           
      LOGICAL TOP_LEPTONS_INIT                                                  
      EXTERNAL TOP_LEPTONS_INIT                                                 
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USRINI = .TRUE.                                                           
C-                                                                              
C-                                                                              
      IF ( (PBD_FLAG_VALUE( 1))                                                 
     &    ) THEN                                                                
         IF (.NOT. CALOR_INI()) THEN                                            
            USRINI = .FALSE.                                                    
            MESSID = '!CALOR_INI is false.'                                     
            CALLER = 'CALOR_INI'                                                
            MESSAG = 'Program execution is aborted'                             
            CALL ERRMSG(MESSID,CALLER,MESSAG,'F')                               
C-                                                                              
C-          ERRMSG will trigger error messages printing                         
C-          and will abort the execution.                                       
C-          The following RETURN statement is only there                        
C-          to satisfy the FORTRAN compiler.                                    
C-                                                                              
            RETURN                                                              
         END IF                                                                 
      END IF                                                                    
C-                                                                              
      IF ( (PBD_FLAG_VALUE( 2))                                                 
     &    ) THEN                                                                
         IF (.NOT. COMPUTE_EM_QUALITY_INI()) THEN                               
            USRINI = .FALSE.                                                    
            MESSID = '!COMPUTE_EM_QUALITY_INI is false.'                        
            CALLER = 'COMPUTE_EM_QUALITY_INI'                                   
            MESSAG = 'Program execution is aborted'                             
            CALL ERRMSG(MESSID,CALLER,MESSAG,'F')                               
C-                                                                              
C-          ERRMSG will trigger error messages printing                         
C-          and will abort the execution.                                       
C-          The following RETURN statement is only there                        
C-          to satisfy the FORTRAN compiler.                                    
C-                                                                              
            RETURN                                                              
         END IF                                                                 
      END IF                                                                    
C-                                                                              
      IF ( (PBD_FLAG_VALUE( 3))                                                 
     &    ) THEN                                                                
         IF (.NOT. TOP_LEPTONS_INIT()) THEN                                     
            USRINI = .FALSE.                                                    
            MESSID = '!TOP_LEPTONS_INIT is false.'                              
            CALLER = 'TOP_LEPTONS_INIT'                                         
            MESSAG = 'Program execution is aborted'                             
            CALL ERRMSG(MESSID,CALLER,MESSAG,'F')                               
C-                                                                              
C-          ERRMSG will trigger error messages printing                         
C-          and will abort the execution.                                       
C-          The following RETURN statement is only there                        
C-          to satisfy the FORTRAN compiler.                                    
C-                                                                              
            RETURN                                                              
         END IF                                                                 
      END IF                                                                    
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USDIAL()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USDIAL = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USENDR()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USENDR = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USRPAR()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USRPAR = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USRPST()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USRPST = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USETSS()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USETSS = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION EVT_DSTDROP()                                            
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      EVT_DSTDROP = .TRUE.                                                      
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION PXEXEC()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      PXEXEC = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USRSSM()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL TOP_LEPTONS_END                                                   
      EXTERNAL TOP_LEPTONS_END                                                  
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USRSSM = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
      IF ( (PBD_FLAG_VALUE( 3))                                                 
     &    ) THEN                                                                
         IF (.NOT. TOP_LEPTONS_END()) THEN                                      
            USRSSM = .FALSE.                                                    
            CALLER = 'TOP_LEPTONS_END'                                          
            MESSAG = 'This error is ignored'                                    
            CALL ERRMSG(MESSID,CALLER,MESSAG,'I')                               
         END IF                                                                 
      END IF                                                                    
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USRUSM()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USRUSM = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USRWRT()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL EVTWOS                                                            
      EXTERNAL EVTWOS                                                           
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USRWRT = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
      IF ( (PBD_FLAG_VALUE( 3))                                                 
     &    ) THEN                                                                
         IF (.NOT. EVTWOS()) THEN                                               
            USRWRT = .FALSE.                                                    
            MESSID = '!EVTWOS is false.'                                        
            CALLER = 'EVTWOS'                                                   
            MESSAG = 'Further processing is skipped'                            
            CALL ERRMSG(MESSID,CALLER,MESSAG,'W')                               
            RETURN                                                              
         END IF                                                                 
      END IF                                                                    
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USRZEV()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL CALEVZ                                                            
      EXTERNAL CALEVZ                                                           
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USRZEV = .TRUE.                                                           
C-                                                                              
C-                                                                              
      IF ( (PBD_FLAG_VALUE( 1))                                                 
     &    ) THEN                                                                
         IF (.NOT. CALEVZ()) THEN                                               
            USRZEV = .FALSE.                                                    
            CALLER = 'CALEVZ'                                                   
            MESSAG = 'This error is ignored'                                    
            CALL ERRMSG(MESSID,CALLER,MESSAG,'I')                               
         END IF                                                                 
      END IF                                                                    
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION USZERO()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      USZERO = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION DMPUDF()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      DMPUDF = .TRUE.                                                           
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION DMPUSR()                                                 
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL CALDMP                                                            
      EXTERNAL CALDMP                                                           
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      DMPUSR = .TRUE.                                                           
C-                                                                              
C-                                                                              
      IF ( (PBD_FLAG_VALUE( 1))                                                 
     &    ) THEN                                                                
         IF (.NOT. CALDMP()) THEN                                               
            DMPUSR = .FALSE.                                                    
            CALLER = 'CALDMP'                                                   
            MESSAG = 'This error is ignored'                                    
            CALL ERRMSG(MESSID,CALLER,MESSAG,'I')                               
         END IF                                                                 
      END IF                                                                    
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
      LOGICAL FUNCTION UQUIT()                                                  
C-                                                                              
C-                                                                              
C-    Purposes and Methods:                                                     
C-    --------------------                                                      
C-                                                                              
C-    Created by the PROGRAM BUILDER Release                                    
C-    12-MAY-93 09:01:08                                                        
C-                                                                              
C-                                                                              
      CHARACTER*32 MESSID,CALLER                                                
      CHARACTER*80 MESSAG                                                       
      LOGICAL PBD_FLAG_VALUE( 3)                                                
      CHARACTER*32 PBD_FLAG_NAME( 3)                                            
      INTEGER PBD_FLAG_MAX                                                      
      COMMON /PBD_COMMON/ PBD_FLAG_VALUE,PBD_FLAG_NAME,PBD_FLAG_MAX             
C-                                                                              
      UQUIT = .TRUE.                                                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: CALOR                            
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: COMPUTE_EM_QUALITY               
C-                                                                              
C-                                                                              
C-    No routine was provided for the package: TOP_LEPTONS                      
C-                                                                              
      RETURN                                                                    
      END                                                                       
C-                                                                              
C-                                                                              
C-                                                                              
