      INTEGER FUNCTION GZRECO(I)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CC    RETURNS POINTER TO ZEBRA BANK RECO
CC
CC    HEDIN 10-7-86
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INCLUDE 'D0$LINKS:IZRECO.LINK'
      INTEGER I
      GZRECO=LQ(LHEAD-IZRECO)
      RETURN
      END
