CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VPROGRAM_BUILDER()
      VPROGRAM_BUILDER = ' PROGRAM_BUILDER'//
     X                   '  OFFICIAL V2.13'//
     X                   ' 29-JUN-1994 15:43:02.20'
      Return
      End
