CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VPROGRAM_BUILDER()
      VPROGRAM_BUILDER = ' PROGRAM_BUILDER'//
     X                   '  TEST V2.13_01'//
     X                   ' 13-AUG-1997 09:21:49.66'
      Return
      End
