CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VCD_UTIL()
      VCD_UTIL = ' CD_UTIL'//
     X                   '  OFFICIAL V1.16'//
     X                   ' 14-JUL-1997 10:44:05.25'
      Return
      End
