CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VD0HPLT()
      VD0HPLT = ' D0HPLT'//
     X                   '  OFFICIAL V1.34'//
     X                   '  6-APR-1995 17:33:17.14'
      Return
      End
