      FUNCTION MU_SOLVER(MU2)

      IMPLICIT NONE
      INCLUDE 'D0$SPYTHIA$INC:VARS.INC'
      INCLUDE 'D0$SPYTHIA$INC:MASSMAT.INC'
      REAL*8 MU_SOLVER,MU2,SIG1,SIG2
      REAL*8 MUPASS,MZZ
      INCLUDE 'D0$SPYTHIA$INC:SOFT.INC'

      MUPASS=MU2
      CALL ONE_LOOP_CORRS(MUPASS,SIG1,SIG2)

      MZZ=2.*(MH1SQ*200.**2+MU2+SIG1 - (MH2SQ*200.**2+MU2+SIG2)
     &      *TBETA**2)/(TBETA**2-1.)

      MU_SOLVER=MZ**2-MZZ
Cc      write(*,*) 'MU_SOLVER=',mz**2-mzz, '  MU2=',mu2

      RETURN
      END
