      SUBROUTINE TDEFLI
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : Define ZEBRA bank links for TRD analysis
C-
C-   Inputs  : 
C-   Outputs : 
C-   Controls: 
C-
C-   Created   7-SEP-1989   A. Zylberstejn
C-   Updated   8-DEC-1989   A. Zylberstejn   
C-   Updated   1-FEB-1990   a. Zylberstejn  Obsolete.Kept for testing 
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:LTRD.INC'
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$LINKS:IZTPHY.LINK'
      INCLUDE 'D0$LINKS:IZTCHA.LINK'
      INCLUDE 'D0$LINKS:IZTPRO.LINK'
      INCLUDE 'D0$LINKS:IZTCA1.LINK'
      INCLUDE 'D0$LINKS:IZTCA2.LINK'
      INCLUDE 'D0$LINKS:IZTPR1.LINK'
      INCLUDE 'D0$LINKS:IZTPR2.LINK'
      INCLUDE 'D0$LINKS:IZTMAE.LINK'
      INCLUDE 'D0$LINKS:IZTMXE.LINK'
      INCLUDE 'D0$LINKS:IZTPET.LINK'
      INCLUDE 'D0$LINKS:IZTPE3.LINK'
      INCLUDE 'D0$LINKS:IZTPTR.LINK'
      INCLUDE 'D0$LINKS:IZTPT3.LINK'
      INCLUDE 'D0$LINKS:IZTPLE.LINK'
      INCLUDE 'D0$LINKS:IZTPEC.LINK'
      INCLUDE 'D0$LINKS:IZTMAA.LINK'
      INCLUDE 'D0$LINKS:IZTMAB.LINK'
      INCLUDE 'D0$LINKS:IZTMAC.LINK'
      INCLUDE 'D0$LINKS:IZTPCA.LINK'
      INCLUDE 'D0$LINKS:IZTPCB.LINK'
      INCLUDE 'D0$LINKS:IZTPCC.LINK'
      LOGICAL FIRST
      DATA FIRST/.TRUE./
C----------------------------------------------------------------------
      call intmsg('TRD error: call to tdefli')
      IF(LTRD(1).EQ.0)then
      return
      end if
      CALL MZLINT(IXSTP,'/LTRD/',LTRD,LTPC,LTRD)
      IF(LTPHY.LE.0)LTPHY=LC(LTGEN-IZTPHY)
      IF(LTCHA.LE.0)LTCHA=LC(LTPHY-IZTCHA)
      IF(LTPRO.LE.0)LTPRO=LC(LTPHY-IZTPRO)
      IF(LTCA1.LE.0)LTCA1=LC(LTCHA-IZTCA1)
      IF(LTCA2.LE.0)LTCA2=LC(LTCHA-IZTCA2)
      IF(LTPR1.LE.0)LTPR1=LC(LTPRO-IZTPR1)
      IF(LTPR2.LE.0)LTPR2=LC(LTPRO-IZTPHY)
      IF(LTMAE1.LE.0)LTMAE1=LC(LTCA1-IZTMAE)
      IF(LTMAE2.LE.0)LTMAE2=LC(LTCA2-IZTMAE)
      IF(LTMXE1.LE.0)LTMXE1=LC(LTCA1-IZTMXE)
      IF(LTMXE2.LE.0)LTMXE2=LC(LTCA2-IZTMXE)
      IF(LTPET1.LE.0)LTPET1=LC(LTPR1-IZTPET)
      IF(LTPET2.LE.0)LTPET2=LC(LTPR2-IZTPET)
      IF(LTPE31.LE.0)LTPE31=LC(LTPR1-IZTPE3)
      IF(LTPE32.LE.0)LTPE32=LC(LTPR2-IZTPE3)
      IF(LTPTR1.LE.0)LTPTR1=LC(LTPR1-IZTPTR)
      IF(LTPTR2.LE.0)LTPTR2=LC(LTPR2-IZTPTR)
      IF(LTPT31.LE.0)LTPT31=LC(LTPR1-IZTPT3)
      IF(LTPT32.LE.0)LTPT32=LC(LTPR2-IZTPT3)
      IF(LTPLE1.LE.0)LTPLE1=LC(LTPR1-IZTPLE)
      IF(LTPLE2.LE.0)LTPLE2=LC(LTPR2-IZTPLE)
      IF(LTPEC1.LE.0)LTPEC1=LC(LTPR1-IZTPEC)
      IF(LTPEC2.LE.0)LTPEC2=LC(LTPR2-IZTPEC)
      IF(LTPCA1.LE.0)LTPCA1=LC(LTPEC1-IZTPCA)
      IF(LTPCA2.LE.0)LTPCA2=LC(LTPEC2-IZTPCA)
      IF(LTPCB1.LE.0)LTPCB1=LC(LTPEC1-IZTPCB)
      IF(LTPCB2.LE.0)LTPCB2=LC(LTPEC2-IZTPCB)
      IF(LTPCC1.LE.0)LTPCC1=LC(LTPEC1-IZTPCC)
      IF(LTPCC2.LE.0)LTPCC2=LC(LTPEC2-IZTPCC)
C        CALL DZSHOW(' STRUCTURE TCHA',IXSTP,LTCHA,'BDLVS',0,0,0,0)
  999 RETURN
      END
