      SUBROUTINE TRH_ON
C----------------------------------------------------------------------
C-
C-   PURPOSE AND METHODS : HANDLE TRD HITS ON RECONSTRUCTED TRACKS
C-
C-   INPUTS  :
C-   OUTPUTS :
C-   CONTROLS:
C-
C-   CREATED  26-APR-1989   A. ZYLBERSTEJN
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:FADCCN.INC'
      INCLUDE 'D0$INC:TCNTRL.INC'
      INCLUDE 'D0$INC:VARTRD.INC'
      INCLUDE 'D0$INC:TRDBGU.INC'
      INCLUDE 'D0$INC:WORKSP.INC'
      INCLUDE 'D0$INC:ZEBCOM.INC'
      INTEGER I,ICH,IHIT,TRUNIT,LOUT,LZTRDT,GZTRDT,LZTRDH,GZTRDH,LZTPRL
      INTEGER CHA1,NHIT,IERR,IMIN,UBIT,TDATA(NMFADC+10)
      integer WIRE,NDRAW,TWIRCOR
      LOGICAL NOCALL
      REAL PEDES,VSUM,XUN(nmfadc)
      LOGICAL DOPRINT,FIRST,DO_HISTO
      DATA FIRST/.TRUE./
      IF(FIRST)THEN
        FIRST=.FALSE.
        LOUT=TRUNIT()
        CALL EZPICK('TRD_RCP')
        DO_HISTO=.FALSE.
        CALL EZGET('HSTBOK',IWS,IERR)
        IF(IERR.EQ.0)DO_HISTO=IWS(1).EQ.1HY .OR. IWS(1).EQ.1HY
     &    .OR. IWS(1).EQ.3HYES
        CALL EZRSET
        DOPRINT=SWTDBG.EQ.1 .AND. LOUT.NE.0
        DO I=1,nmfadc
          XUN(I)=I
        END DO
        NDRAW=100
        IF(DOPRINT)NDRAW=0
        NOCALL=.FALSE.
      END IF
      IF(NOCALL)GO TO 999
      IF(.NOT.DOPRINT)GO TO 999
C      IF(DO_HISTO)CALL HCDIR('//PAWC/TRD',' ')  ! GO TO TRD DIRECTORY
      DOPRINT=DOPRINT.AND.TNEVDG.GT.0
      LZTRDH=GZTRDH()
      IF(LZTRDH.LE.0)THEN
C        WRITE(LOUT,*)' IN TRH_ON,LZTRDH',LZTRDH
        GO TO 999
      END IF
      LZTRDT=GZTRDT()
      IMIN=TMIN_CDC*.1+.5
      IMIN=MAX0(1,IMIN-10)
   10 IF(LZTRDT.LE.0)GO TO 999 ! LOOP ON TRACKS
      DO 54 ICH=1,3
        LZTPRL=LQ(LZTRDT-ICH)
        IF(LZTPRL.LE.0)THEN
          IF(DOPRINT)WRITE(LOUT,*)' LZTPRL=0'
          GO TO 54
        END IF
        IF(Q(LZTPRL+1).GT.1.8)THEN
          NOCALL=.TRUE.
          GO TO 999
        END IF
C  DRAWING OF 20 FIRST EVENTS WITH SEVERAL HIT ANODES
        IF(IQ(LZTPRL+14).LT.2 .OR. NDRAW.GT.20)GO TO 54
        NDRAW=NDRAW+1
        NHIT=IQ(LZTPRL+14)
        WRITE(LOUT,1032 )IQ(LHEAD+9),NHIT, (Q(LZTPRL+17+IHIT),
     &                                            IHIT=1,NHIT)
        WRITE(LOUT,1033) (Q(LZTPRL+17+IHIT+NHIT), IHIT=1,NHIT)
 1032   FORMAT( '1 EVENT',I5,I3,' HIT ANODES ',5F10.1)
 1033   FORMAT( '  ---- ',8X,   '  ENERGIES      ',5G10.4)
        DO 52 IHIT=1,NHIT! LOOP ON THE CELLS ON A TRACK
          I=Q(LZTPRL+17+IHIT)
C  DRAWING OF ON_TRACK WIRES
          WIRE=I
          IF(.NOT.MCDATA .AND. ICH.EQ.3 )WIRE=TWIRCOR(I)
          CALL TCODER(CHA1,ICH-1,WIRE-1,UBIT,2)
          CALL ZDEXPD(4,CHA1,TDATA)
          IF (TDATA(1).EQ.0)GO TO 52
          CALL TRGPED('BID',I,ICH,PEDES,IERR) ! GET PEDESTALS
          IF(IERR.NE.0)THEN
            WRITE(LOUT,*)' ERROR IN TRGPED,ICH,II',ICH,I
            PEDES=0
          END IF
          CALL VFLOAT(TDATA(3),WS,TDATA(1))
          CALL VBIAS(WS,-PEDES,WS,TDATA(1))
          WRITE(LOUT,1044)I ,ICH, VSUM(WS,TDATA(1)),TMIN_CDC*.1
 1044     FORMAT('  ON TRACK WIRE ',I4,' CHAMBER',I2,
     &      ' ETOT FOR 256 BINS',G10.4, ' TMIN CDC',F5.0)
          CALL DRAWPT_XY(XUN(IMIN),WS(IMIN),120,1,LOUT)
   52   CONTINUE
   54 CONTINUE
      LZTRDT=LQ(LZTRDT)
      IF(LZTRDT.NE.0)GO TO 10
  999 RETURN
      END
