
      SUBROUTINE ISAMKMU3(EPI,EMU,PPI,PMU)
CC  RETURNS ENERGY AND MOMENTUM OF MU AND PI IN C. OF M.
CC  FOR KL --> PI + MU + NU
CC    DH 8/84
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      REAL EPI,EMU,PPI,PMU,XI0,OLAMD,EPM,ELG,WMAX,EMMU,EMPI,
     A EMK,ELMIN,ELMAX,DEPI,ENU,QSQ,F,XI,OMXI,WDIST,RANF
      DATA XI0,OLAMD,EPM,ELG,WMAX/-.14,.034,.25719,.24049,.020/
      DATA EMMU,EMPI/.10566,.13957/
      DATA EMK/.498/
CC
1     CONTINUE
      EPI=EMPI+(EPM-EMPI)*RANF()
      PPI=SQRT(EPI**2-EMPI**2)
      ELMIN=((EMK-EPI-PPI)**2+EMMU**2)/(2.*(EMK-EPI-PPI))
      ELMAX=((EMK-EPI+PPI)**2+EMMU**2)/(2.*(EMK-EPI+PPI))
CC GET E MUON
      EMU=EMMU+(ELG-EMMU)*RANF()
      IF(EMU.LT.ELMIN.OR.EMU.GT.ELMAX) GO TO 1
      PMU=SQRT(EMU**2-EMMU**2)
      ENU=EMK-EMU-EPI
      DEPI=EPM-EPI
      QSQ=EMK**2+EMPI**2-2.*EMK*EPI
      F=1.+OLAMD*QSQ/EMPI**2
      XI=XI0/F
      OMXI=1.-XI
      OMXIQ=OMXI**2
CC                   DALITZ PLOT DENSITY
      WDIST=ENU*(2.*EMK*EMU-OMXI*EMMU**2)-DEPI*(EMK**2-EMMU**2*OMXIQ/
     A 4.)
      WDIST=WDIST*F*F
      IF(WMAX*RANF().GT.WDIST) GO TO 1
      RETURN
      END
