
      SUBROUTINE ISAMLORTRN(B,G,DIRO,P,E,PTOT,EM)
CC
CC   LORENTZ TRANSFORMS
CC     8/84 DH
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      REAL B,G,E,PTOT,EM,GBDOTP
      REAL DIRO(3),P(3),TEMP(3)
      INTEGER I
      DO 1 I=1,3
      TEMP(I)=P(I)
 1    CONTINUE
      GBDOTP=B*G/(G+1.)*(DIRO(1)*P(1)+DIRO(2)*P(2)+DIRO(3)*P(3))
      P(1)=TEMP(1)+B*DIRO(1)*G*(GBDOTP+E)
      P(2)=TEMP(2)+B*DIRO(2)*G*(GBDOTP+E)
      P(3)=TEMP(3)+B*DIRO(3)*G*(GBDOTP+E)
      PTOT=SQRT(P(1)**2+P(2)**2+P(3)**2)
      E=SQRT(PTOT**2+EM**2)
      DIRO(1)=P(1)/PTOT
      DIRO(2)=P(2)/PTOT
      DIRO(3)=P(3)/PTOT
      RETURN
      END
