CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VCALOR_FILTER()
      VCALOR_FILTER = ' CALOR_FILTER'//
     X                   '  OFFICIAL V1.05'//
     X                   '  3-JUL-1996 17:52:03.54'
      Return
      End
