PACKAGE := d0geant
d0geant_LIB := yes
d0geant_EXCEPT_DIR := mach_flavor cps
include GNUmakefile.subcommon

D0GEANT_NO_LOOPOPT := gtswch gltrac
$(foreach f,$(D0GEANT_NO_LOOPOPT), tmp/OPT/d0geant/dzero/$(f).o) : FORT_COMMON_FLAGS += -fno-aggressive-loop-optimizations
