$!SUBMITS 1 GEANT JOB WHICH CHAINS ON ITSELF.
$SET VERIFY
$Write sys$output "Running alpha release D0GEANT "
$NF=P1
$ SUBMIT/NOPRINTER/NOTIFY/QUEUE=D0SF13_BATCH/NAME=SHLB'NF'/PARAMETERS='NF'-
 D0GEANT
$EXIT:
