PACKAGE := lcompack
lcompack_LIB := yes
include GNUmakefile.subcommon

LCOMPACK_NO_RANGE_CHECK := reaset
$(foreach f,$(LCOMPACK_NO_RANGE_CHECK),tmp/DEB/lcompack/source/$(f).o tmp/OPT/lcompack/source/$(f).o) : FORT_COMMON_FLAGS += -fno-range-check
