#! /bin/csh -f
###############################################################################
#
# Name:  tpmfarm_pre_release
#
# Purpose: UNIX release script for tpmfarm d0library section.  This
#          script performs the following actions:
#
#          1.  Deletes tpmfarm.mms
#
#          2.  Builds tpmfarm library.
#
# Usage Notes:
#
# 1.  This script should be executed from the top directory of the
#     tpmfarm library section.
#
# 2.  This script should be released via the VMS d0library release procedures
#     so that is gets to the top directory of the tpmfarm library
#     section.
#
# Created 25-Jun-1992  Herbert Greenlee
#
##############################################################################
#
# Delete tpmfarm.mms to disable usual build phase.  This scipt
# supersedes.
#
rm -f tpmfarm.mms >& /dev/null
#
# Execute script to build libraries.
#
eval `uff $d0tpmfarm/shell/build_tpmfarm.csh`
#
# Execute script to link main programs.
#
eval `uff $d0tpmfarm/shell/link_tpmfarm.csh`
