      SUBROUTINE CLGAEE
C---------------------------------------------------------------
C
C     CREATES ACTIVE CYLINDERS WHICH CONTAIN THE ACTIVE MODULES
C     FOR THE END CAP ELECTROMAGNETIC CALORIMETER.  CORRESPONDS
C     TO EC-EM FINAL DESIGN REVIEW (D0 NOTE #687)
C     BANKS LIFTED:   CLGA, CSHA
C
C     AUTHOR:    S KAHN      8 AUG 1988
C     REVISIONS:  DATA NOW OBTAINED FROM SRCP BANKS -- S KAHN 15 FEB 89
C---------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$INC:CLINKS.INC'
      INCLUDE 'D0$PARAMS:CLGA.PARAMS'
      INCLUDE 'D0$INC:REGION.DEF'
      INCLUDE 'D0$INC:CSHA.DEF'
      INCLUDE 'D0$INC:PI.DEF'
      INCLUDE 'D0$LINKS:IZCLGA.LINK'
      INCLUDE 'D0$LINKS:IZCLGI.LINK'
      INCLUDE 'D0$LINKS:IZCREG.LINK'
      INCLUDE 'D0$LINKS:IZCMAT.LINK'
      INCLUDE 'D0$LINKS:IZCSHA.LINK'
      INCLUDE 'D0$LINKS:IZCLNK.LINK'
      INTEGER MCLGA(5), MCSHA(5), LORIG, MCLNK(5)
      INTEGER LZFIND
      CHARACTER*4 CHAR4,CHAS4, CHAL4
      INTEGER ICHARR
      CHARACTER*4 CHARR
      EQUIVALENCE (ICHARR,CHARR)
      EQUIVALENCE (CHAR4,MCLGA(1))
      EQUIVALENCE (CHAS4,MCSHA(1))
      EQUIVALENCE (CHAL4,MCLNK(1))
      DATA MCLGA / 0, 6, 1, 18, 9/
      DATA MCSHA / 0, 0, 0,  5, 9/
      DATA MCLNK / 0, 1, 0,  4, 2/
      DATA CHAR4 / 'CLGA'/
      DATA CHAS4 / 'CSHA'/
      DATA CHAL4 / 'CLNK'/
C
C   END CAP ELECTROMAGNETIC CYLINDERS
C
      LQCREG = LZFIND(IDVSTP,LC(LCGEH-IZCREG),ISEMCL,IGREGN) ! get CREG
C
C
      MCLGA(5) = IOCLGA                         ! put in form address
C 
C     FIRST EM REGION REGION
C
      CALL MZLIFT(IDVSTP,LQCLNK,LQCREG,-IZCLNK,MCLNK,0)
      IC(LQCLNK + IGIDEN) = ICEC1A
      IC(LQCLNK + IGNSEG) = 1
      IC(LQCLNK + IGJPHI) = 1
      IC(LQCLNK + IGN1) = 0
      CALL MZLIFT(IDVSTP,LQCLGA,LQCREG,-IZCLGA,MCLGA,0)
      IC(LQCLGA+IGIDEN) = ICEC1A ! EC1 ACTIVE REGION
      IC(LQCLGA+IGNLAY) = 1
      CHARR='EC1A'
      IC(LQCLGA+IGNAM ) = ICHARR
      IC(LQCLGA+IGCOOR) = 123
      IC(LQCLGA+IGPERP) = 3
      C(LQCLGA +IGDPHI) = TWOPI
      C(LQCLGA +IGNRDL) = 0.3          ! # radiation lengths
      C(LQCLGA +IGNABL) = 0.05         ! # interation lengths
      C(LQCLGA +IGCRAK) = 0.     ! crack width
      CALL CLGSRC(LQCLGA,'EC_EEM+EM+1','EM_MOTHER_VOLUME+Z')
      CALL SBIT1(IC(LQCLGA),IBZRFL)  ! reflect on Z
      LC(LQCLNK - 1) = LQCLGA
C
C     EC1 SHAPE INFORMATION
C
C
      MCSHA(5) = IOCSHA
      CALL MZLIFT(IDVSTP,LQCSHA,LCGEH,-IZCSHA,MCSHA,0)
C
      CALL SHPSRC(LQCSHA,'EC_EEM+EM+1')
      LQCMAT = LZFIND(IDVSTP,LC(LCGEH-IZCMAT),IC(LQCLGA+IGMATE),1) ! get CMAT
      LQCLGI = LZFIND(IDVSTP,LC(LQCREG-IZCLGI),ICEC1I,IGIDEN)   ! get
C                                        ! associated CLGI bank
      LC(LQCLGA-IXCLGI) = LQCLGI   ! ref link to CLGI
      LC(LQCLGI-IXCLGA) = LQCLGA   ! ref link to 1st CLGA from CLGI
      LC(LQCLGA-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGA-IXCSHA) = LQCSHA   ! ref link to CSHA
C     CALL SPNMOD(LQCLGA,16)         ! make the other modules
C
C     SECOND EM REGION ACTIVE CYLINDER
C
      CALL MZLIFT(IDVSTP,LQCLNK,LQCREG,-IZCLNK,MCLNK,0)
      IC(LQCLNK + IGIDEN) = ICEC2A
      IC(LQCLNK + IGNSEG) = 1
      IC(LQCLNK + IGJPHI) = 1
      IC(LQCLNK + IGN1) = 0
      CALL MZLIFT(IDVSTP,LQCLGA,LQCLGA,0,MCLGA,0)
C
      IC(LQCLGA+IGIDEN) = ICEC2A
      IC(LQCLGA+IGNLAY) = 1
      CHARR= 'EC2A'
      IC(LQCLGA+IGNAM ) = ICHARR
      IC(LQCLGA+IGCOOR) = 123
      IC(LQCLGA+IGPERP) = 3
      C(LQCLGA +IGDPHI) = TWOPI
      C(LQCLGA +IGNRDL) = 2.6        ! # radiation lengths
      C(LQCLGA +IGNABL) = 0.10       ! # interation lengths
      C(LQCLGA +IGCRAK) = 0.
      CALL CLGSRC(LQCLGA,'EC_EEM+EM+2','EM_MOTHER_VOLUME+Z')
      CALL SBIT1(IC(LQCLGA),IBZRFL)  ! reflect on Z
      LC(LQCLNK - 1) = LQCLGA
C
C     EC2  TUBE SHAPE INFO
C
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CALL SHPSRC(LQCSHA,'EC_EEM+EM+2')
C
      LQCMAT = LZFIND(IDVSTP,LC(LCGEH-IZCMAT),IC(LQCLGA+IGMATE),1) ! get CMAT
      LC(LQCLGA-IXCLGI) = LQCLGI   ! ref link to CLGI
      LC(LQCLGI-IXCLGA) = LQCLGA   ! ref link to 1st CLGA from CLGI
      LC(LQCLGA-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGA-IXCSHA) = LQCSHA
C     CALL SPNMOD(LQCLGA,16)         ! make the other modules
C
C     THIRD EM ACTIVE CYLINDER
C
      CALL MZLIFT(IDVSTP,LQCLNK,LQCREG,-IZCLNK,MCLNK,0)
      IC(LQCLNK + IGIDEN) = ICEC3A
      IC(LQCLNK + IGNSEG) = 1
      IC(LQCLNK + IGJPHI) = 1
      IC(LQCLNK + IGN1) = 0
      CALL MZLIFT(IDVSTP,LQCLGA,LQCLGA,0,MCLGA,0)
C
      IC(LQCLGA+IGIDEN) = ICEC3A
      IC(LQCLGA+IGNLAY) = 1
      CHARR= 'EC3A'
      IC(LQCLGA+IGNAM ) = ICHARR
      IC(LQCLGA+IGCOOR) = 123
      IC(LQCLGA+IGPERP) = 3
      C(LQCLGA +IGDPHI) = TWOPI
      C(LQCLGA +IGNRDL) = 7.9        ! # radiation lengths
      C(LQCLGA +IGNABL) = 0.31       ! # interation lengths
      C(LQCLGA +IGCRAK) = 0.         ! crack width
      CALL CLGSRC(LQCLGA,'EC_EEM+EM+3','EM_MOTHER_VOLUME+Z')
      CALL SBIT1(IC(LQCLGA),IBZRFL)  ! reflect on Z
      LC(LQCLNK - 1) = LQCLGA
C
C     MFH TUBE SHAPE INFO
C
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CALL SHPSRC(LQCSHA,'EC_EEM+EM+3')
      LQCMAT = LZFIND(IDVSTP,LC(LCGEH-IZCMAT),IC(LQCLGA+IGMATE),1) ! get CMAT
      LC(LQCLGA-IXCLGI) = LQCLGI   ! ref link to CLGI
      LC(LQCLGI-IXCLGA) = LQCLGA   ! ref link to 1st CLGA from CLGI
      LC(LQCLGA-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGA-IXCSHA) = LQCSHA   ! ref link to CSHA
C     CALL SPNMOD(LQCLGA,16)         ! make the other modules
C
C     FOURTH EM ACTIVE CYLINDER
C
      CALL MZLIFT(IDVSTP,LQCLNK,LQCREG,-IZCLNK,MCLNK,0)
      IC(LQCLNK + IGIDEN) = ICEC4A
      IC(LQCLNK + IGNSEG) = 1
      IC(LQCLNK + IGJPHI) = 1
      IC(LQCLNK + IGN1) = 0
      CALL MZLIFT(IDVSTP,LQCLGA,LQCLGA,0,MCLGA,0)
C
      IC(LQCLGA+IGIDEN) = ICEC4A
      IC(LQCLGA+IGNLAY) = 1
      CHARR= 'EC4A'
      IC(LQCLGA+IGNAM ) = ICHARR
      IC(LQCLGA+IGCOOR) = 123
      IC(LQCLGA+IGPERP) = 3
      C(LQCLGA +IGDPHI) = TWOPI 
      C(LQCLGA +IGNRDL) = 9.3        ! # radiation lengths
      C(LQCLGA +IGNABL) = 0.48       ! # interaction lengths         
      C(LQCLGA +IGCRAK) = 0.         ! crack width
      CALL CLGSRC(LQCLGA,'EC_EEM+EM+4','EM_MOTHER_VOLUME+Z')
      CALL SBIT1(IC(LQCLGA),IBZRFL)  ! reflect on Z
      LC(LQCLNK - 1) = LQCLGA
C
C     EC4 TUBE SHAPE INFO
C
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CALL SHPSRC(LQCSHA,'EC_EEM+EM+4')
C
      LQCMAT = LZFIND(IDVSTP,LC(LCGEH-IZCMAT),IC(LQCLGA+IGMATE),1) ! get CMAT
C                                        ! associated CLGI bank
      LC(LQCLGA-IXCLGI) = LQCLGI   ! ref link to CLGI
      LC(LQCLGI-IXCLGA) = LQCLGA   ! ref link to 1st CLGA from CLGI
      LC(LQCLGA-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGA-IXCSHA) = LQCSHA   ! ref link to CSHA
C     CALL SPNMOD(LQCLGA,16)         ! make the other modules
C
      RETURN
      END
