      SUBROUTINE CLGICC
C---------------------------------------------------------------
C
C     CREATES INACTIVE CYLINDERS WHICH CONTAIN THE ACTIVE MODULES
C     BANKS LIFTED:   CLGI, CSHA
C
C     AUTHOR:    S KAHN      22 APRIL 1987
C     REVISIONS: UPDATE TO D0-GEANT V1.0  SAK 16 JUNE 1987
C                USING DATA SRCP BANKS S KAHN 3 FEB 1989
C---------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$INC:CLINKS.INC'
      INCLUDE 'D0$PARAMS:CLGA.PARAMS'
      INCLUDE 'D0$PARAMS:MATERIAL_TYPES.PARAMS'
      INCLUDE 'D0$INC:REGION.DEF'
      INCLUDE 'D0$INC:CSHA.DEF'
      INCLUDE 'D0$INC:PI.DEF'
      INCLUDE 'D0$LINKS:IZCLGI.LINK'
      INCLUDE 'D0$LINKS:IZCMAT.LINK'
      INCLUDE 'D0$LINKS:IZCSHA.LINK'
      INCLUDE 'D0$LINKS:IZCREG.LINK'
      INTEGER MCLGI(5), MCSHA(5), LORIG
      INTEGER LZFIND
      CHARACTER*4 CHAR4,CHAS4
      INTEGER ICHARR
      CHARACTER*4 CHARR
      EQUIVALENCE (ICHARR,CHARR)
      EQUIVALENCE (CHAR4,MCLGI(1))
      EQUIVALENCE (CHAS4,MCSHA(1))
      DATA MCLGI / 0, 6, 1, 18, 9/
      DATA MCSHA / 0, 0, 0,  5, 9/
      DATA CHAR4 / 'CLGI'/
      DATA CHAS4 / 'CSHA'/
C
C   CENTRAL CALORIMETER CYLINDERS
C
      LQCREG = LZFIND(IDVSTP,LC(LCGEH-IZCREG),ICCAL,IGREGN) ! get CREG
C
      CALL MZFORM('CLGA','5I2H-F',IOCLGA)       ! set form for CLGA,CLGI,CRYO
C
      MCLGI(5) = IOCLGA                         ! put in form address
C 
C    CEN CAL EM REGION
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCREG,-IZCLGI,MCLGI,0)
      IC(LQCLGI+IGIDEN) = ICCEMI ! CENCAL EM INACTIVE REGION
      IC(LQCLGI+IGNLAY) = 4
      CHARR= 'CEMI'
      IC(LQCLGI+IGNAM ) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 4
      C(LQCLGI +IGDPHI) = TWOPI
      CALL CLGSRC(LQCLGI,'CC_EM_MOTHER_VOLUME','NONE')  ! fill from SRCP bank
C
C     PUT IT SHAPE INFORMATION
C
      CALL MZFORM('CSHA','1H1I-F',IOCSHA)
C
      MCSHA(5) = IOCSHA
      CALL MZLIFT(IDVSTP,LQCSHA,LCGEH,-IZCSHA,MCSHA,0)
C
      CALL SHPSRC(LQCSHA,'CC_EM_MOTHER_VOLUME')  ! fill from SRCP bank
C
      LQCMAT = LZFIND(IDVSTP,LC(LCGEH-IZCMAT),IMLIQA,1) ! get CMAT
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA   ! ref link to CSHA
C
C     CEN CAL FH INACTIVE CYLINDER
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCLGI,0,MCLGI,0)
C
      IC(LQCLGI+IGIDEN) = ICCFHI
      IC(LQCLGI+IGNLAY) = 3
      CHARR= 'CFHI'
      IC(LQCLGI+IGNAM ) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 4
      C(LQCLGI +IGDPHI) = TWOPI
      CALL CLGSRC(LQCLGI,'CC_FH_MOTHER_VOLUME','NONE')  ! fill from SRCP bank
C
C     FH TUBE SHAPE INFO
C
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CALL SHPSRC(LQCSHA,'CC_FH_MOTHER_VOLUME')  ! fill from SRCP bank
C
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA
C
C     CEN CAL CH INACTIVE CYLINDER
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCLGI,0,MCLGI,0)
C
      IC(LQCLGI+IGIDEN) = ICCCHI
      IC(LQCLGI+IGNLAY) = 1
      CHARR= 'CCHI'
      IC(LQCLGI+IGNAM ) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 4
      C(LQCLGI +IGDPHI) = TWOPI
      CALL CLGSRC(LQCLGI,'CC_CH_MOTHER_VOLUME','NONE')  ! fill from SRCP bank
C
C     CH TUBE SHAPE INFO
C
      MCSHA(4) = 17
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CALL SHPSRC(LQCSHA,'CC_CH_MOTHER_VOLUME')  ! fill from SRCP bank
C
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA   ! ref link to CSHA
C
      RETURN
      END
