      SUBROUTINE CLGIEE
C---------------------------------------------------------------
C
C     CREATES INACTIVE CYLINDERS WHICH CONTAIN THE ACTIVE MODULES
C     FOR THE END CAP ELECTROMAGNETIC CALORIMETER.  CORRESPONDS
C     TO EC-EM FINAL DESIGN REVIEW (D0 NOTE #687)
C     BANKS LIFTED:   CLGI, CSHA
C
C     AUTHOR:    S KAHN      8 AUG 1988
C     REVISIONS: USING DATA FROM SRCP BANKS - S KAHN 3 FEB 1989
C---------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$INC:CLINKS.INC'
      INCLUDE 'D0$PARAMS:CLGA.PARAMS'
      INCLUDE 'D0$PARAMS:MATERIAL_TYPES.PARAMS'
      INCLUDE 'D0$INC:REGION.DEF'
      INCLUDE 'D0$INC:CSHA.DEF'
      INCLUDE 'D0$INC:PI.DEF'
      INCLUDE 'D0$LINKS:IZCMAT.LINK'
      INCLUDE 'D0$LINKS:IZCLGI.LINK'
      INCLUDE 'D0$LINKS:IZCSHA.LINK'
      INCLUDE 'D0$LINKS:IZCREG.LINK'
      INTEGER MCLGI(5), MCSHA(5), LORIG
      INTEGER LZFIND
      CHARACTER*4 CHAR4,CHAS4
      INTEGER ICHARR
      CHARACTER*4 CHARR
      EQUIVALENCE (ICHARR,CHARR)
      EQUIVALENCE (CHAR4,MCLGI(1))
      EQUIVALENCE (CHAS4,MCSHA(1))
      DATA MCLGI / 0, 6, 1, 18, 9/
      DATA MCSHA / 0, 0, 0, 16, 9/
      DATA CHAR4 / 'CLGI'/
      DATA CHAS4 / 'CSHA'/
C
C   END CAP ELECTROMAGNETIC CYLINDERS
C
      LQCREG = LZFIND(IDVSTP,LC(LCGEH-IZCREG),ISEMCL,IGREGN) ! get CREG
C
C
      MCLGI(5) = IOCLGA                         ! put in form address
C 
C     FIRST EM REGION REGION
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCREG,-IZCLGI,MCLGI,0)
      IC(LQCLGI+IGIDEN) = ICEC1I ! EC1 INACTIVE REGION
      IC(LQCLGI+IGNLAY) = 1
      CHARR= 'EC1I'
      IC(LQCLGI+IGNAM ) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 3
      C(LQCLGI +IGDPHI) = TWOPI
      CALL CLGSRC(LQCLGI,'EM_MOTHER_VOLUME+Z','NONE')   ! fill from SRCP bank
      CALL SBIT1(IC(LQCLGI),IBZRFL)  ! reflect on Z
C
C     EC1 SHAPE INFORMATION
C
C
      MCSHA(5) = IOCSHA
      CALL MZLIFT(IDVSTP,LQCSHA,LCGEH,-IZCSHA,MCSHA,0)
C
      CALL SHPSRC(LQCSHA,'EM_MOTHER_VOLUME+Z')   ! fill from SRCP bank
C
      LQCMAT = LZFIND(IDVSTP,LC(LCGEH-IZCMAT),IMECRK,1) ! get CMAT
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA   ! ref link to CSHA
C
C     SUPPORT PLATE INACTIVE CYLINDER
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCLGI,0,MCLGI,0)
C
      IC(LQCLGI+IGIDEN) = ICESUP
      IC(LQCLGI+IGNLAY) = 1
      CHARR= 'ECSP'
      IC(LQCLGI+IGNAM ) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 3
      C(LQCLGI +IGDPHI) = TWOPI
      CALL CLGSRC(LQCLGI,'EM_SUPPORT_PLATE+Z',
     &  'EM_MOTHER_VOLUME+Z')   ! fill from SRCP bank
      CALL SBIT1(IC(LQCLGI),IBZRFL)  ! reflect on Z
      LQCMAT = LZFIND(IDVSTP,LC(LCGEH-IZCMAT),IMIRON,1) ! get CMAT
C
C     SUPPORT PLATE TUBE SHAPE INFO
C
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CALL SHPSRC(LQCSHA,'EM_SUPPORT_PLATE+Z')   ! fill from SRCP bank
C
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA   ! ref link to CSHA
C
      RETURN
      END
