      SUBROUTINE CLGIEH
C---------------------------------------------------------------
C
C     CREATES INACTIVE CYLINDERS WHICH CONTAIN THE ACTIVE MODULES
C     FOR THE END CAP HADRONIC CALORIMETER.
C     ZEBRA BANKS LIFTED:   CLGI, CSHA
C
C     AUTHOR:    S KAHN      27 JAN 1987
C     REVISIONS: UPDATED TO D0-GEANT V1.0  S KAHN 16 JUNE 1987
C                UPDATED DIMENSIONS -- S KAHN 14 OCT 1988
C                SRCP VERSION -- S KAHN 27-FEB-1989
C---------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:ZEBSTP.INC'
      INCLUDE 'D0$INC:CLINKS.INC'
      INCLUDE 'D0$PARAMS:CLGA.PARAMS'
      INCLUDE 'D0$INC:REGION.DEF'
      INCLUDE 'D0$INC:CSHA.DEF'
      INCLUDE 'D0$INC:PI.DEF'
      INCLUDE 'D0$LINKS:IZCREG.LINK'
      INCLUDE 'D0$LINKS:IZCLGA.LINK'
      INCLUDE 'D0$LINKS:IZCLGI.LINK'
      INCLUDE 'D0$LINKS:IZCMAT.LINK'
      INCLUDE 'D0$LINKS:IZCSHA.LINK'
      INTEGER MCLGI(5), MCSHA(5), LORIG
      INTEGER LZFIND
      INTEGER IMVACU
      CHARACTER*4 CHAR4,CHAS4
      INTEGER ICHARR
      CHARACTER*4 CHARR
      EQUIVALENCE (ICHARR,CHARR)
      EQUIVALENCE (CHAR4,MCLGI(1))
      EQUIVALENCE (CHAS4,MCSHA(1))
      DATA IMVACU / 16 /
      DATA MCLGI / 4HCLGI, 6, 1, 18, 9/
      DATA MCSHA / 4HCSHA, 0, 0,  5, 9/
      DATA CHAR4 / 'CLGI'/
      DATA CHAS4 / 'CSHA'/
C
C   END CAP HADRONIC CYLINDERS
C
      LQCREG = LZFIND(IDVSTP,LC(LCGEH-IZCREG),ISECAL,IGREGN) ! get CREG
C
C
      MCLGI(5) = IOCLGA                         ! put in form address
C 
C    INNER FINE HADRONIC REGION
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCREG,-IZCLGI,MCLGI,0)
      IC(LQCLGI+IGIDEN) = ICIFHI ! IFH INACTIVE REGION
      IC(LQCLGI+IGNLAY) = 4
      CHARR= 'IFHI'
      IC(LQCLGI+IGNAM ) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 3
      C(LQCLGI +IGDPHI) = TWOPI
      C(LQCLGI +IGCRAK) = 1.36   ! crack width
      CALL CLGSRC(LQCLGI,'IFH_MOTHER_VOLUME+Z','NONE')
      CALL SBIT1(IC(LQCLGI),IBZRFL)  ! reflect on Z
C
C     IFH SHAPE INFORMATION
C
C
      MCSHA(5) = IOCSHA
      CALL MZLIFT(IDVSTP,LQCSHA,LCGEH,-IZCSHA,MCSHA,0)
C
      CALL SHPSRC(LQCSHA,'IFH_MOTHER_VOLUME+Z')
C
      LQCMAT = LZFIND(IDVSTP,LC(LCGEH-IZCMAT),IC(LQCLGI+IGMATE),1) ! get CMAT
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA   ! ref link to CSHA
C
C     INNER COARSE HADRONIC INACTIVE CYLINDER
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCLGI,0,MCLGI,0)
C
      IC(LQCLGI+IGIDEN) = ICICHI
      IC(LQCLGI+IGNLAY) = 1
      CHARR= 'ICHI'
      IC(LQCLGI+IGNAM ) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 3
      C(LQCLGI +IGDPHI) = TWOPI
      C(LQCLGI +IGCRAK) = 1.36
      CALL CLGSRC(LQCLGI,'ICH_MOTHER_VOLUME+Z','NONE')
      CALL SBIT1(IC(LQCLGI),IBZRFL)  ! reflect on Z
C
C     ICH TUBE SHAPE INFO
C
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CALL SHPSRC(LQCSHA,'ICH_MOTHER_VOLUME+Z')
C
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA
C
C     MIDDLE FINE INACTIVE CYLINDER -- (old numbers since new numbers are
C       not available from SRCP)
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCLGI,0,MCLGI,0)
C
      IC(LQCLGI+IGIDEN) = ICMFHI
      IC(LQCLGI+IGNLAY) = 4
      IC(LQCLGI+IGMATE) = IMVACU
      CHARR= 'MFHI'
      IC(LQCLGI+IGNAM ) = ICHARR
      CHARR= 'TUBE'
      IC(LQCLGI+IGSHAP) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 3
      C(LQCLGI +IGZCEN) = 231.99     ! z pos of MFH center
      C(LQCLGI +IGDPHI) = TWOPI
      C(LQCLGI +IGCRAK) = 0.7        ! crack width
      CALL SBIT1(IC(LQCLGI),IBZRFL)  ! reflect on Z
C
C     MFH TUBE SHAPE INFO
C
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CHARR= 'TUBE'
      IC(LQCSHA+IGDESC) = ICHARR
      IC(LQCSHA+IGNPAR) = 3
      C(LQCSHA+ IGPAR1) = 87.96    ! MFH inner radius
      C(LQCSHA+ IGPAR2) = 160.373  ! MFH outer radius
      C(LQCSHA+ IGPAR3) = 36.411   ! MFH half length of cyl
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA   ! ref link to CSHA
C
C     MIDDLE COARSE INACTIVE CYLINDER
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCLGI,0,MCLGI,0)
C
      IC(LQCLGI+IGIDEN) = ICMCHI
      IC(LQCLGI+IGNLAY) = 1
      IC(LQCLGI+IGMATE) = IMVACU
      CHARR= 'MCHI'
      IC(LQCLGI+IGNAM ) = ICHARR
      CHARR= 'TUBE'
      IC(LQCLGI+IGSHAP) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 3
      C(LQCLGI +IGZCEN) = 306.333    ! z pos of MCH center
      C(LQCLGI +IGDPHI) = TWOPI
      C(LQCLGI +IGCRAK) = 1.36       ! crack width
      CALL SBIT1(IC(LQCLGI),IBZRFL)  ! reflect on Z
C
C     MCH TUBE SHAPE INFO
C
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CHARR= 'TUBE'
      IC(LQCSHA+IGDESC) = ICHARR
      IC(LQCSHA+IGNPAR) = 3
      C(LQCSHA+ IGPAR1) = 87.63    ! MCH inner radius
      C(LQCSHA+ IGPAR2) = 160.57   ! MCH outer radius
      C(LQCSHA+ IGPAR3) = 37.431   ! MCH half length of cyl
C
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA   ! ref link to CSHA
C
C
C     OUTER HADRONIC REGION -- 
C
      CALL MZLIFT(IDVSTP,LQCLGI,LQCLGI,0,MCLGI,0)
C
      IC(LQCLGI+IGIDEN) = ICOCHI
      IC(LQCLGI+IGNLAY) = 3
      IC(LQCLGI+IGMATE) = IMVACU       ! vacuum
      CHARR= 'OCHI'
      IC(LQCLGI+IGNAM ) = ICHARR
      IC(LQCLGI+IGCOOR) = 123
      IC(LQCLGI+IGPERP) = 3
      C(LQCLGI +IGDPHI) = TWOPI
      C(LQCLGI +IGCRAK) = 1.905    ! crack width
      CALL CLGSRC(LQCLGI,'OH_BIG_MVOLUME+Z','NONE')
      CALL SBIT1(IC(LQCLGI),IBZRFL)  ! reflect on z
C
C     OCH PGON SHAPE INFO
C
      MCSHA(4) = 18
      CALL MZLIFT(IDVSTP,LQCSHA,LQCSHA,0,MCSHA,0)
      CALL SHPSRC(LQCSHA,'OH_BIG_MVOLUME+Z')
C
      LC(LQCLGI-IXCMAT) = LQCMAT   ! ref link to CMAT
      LC(LQCLGI-IXCSHA) = LQCSHA   ! ref link to CSHA
C
      RETURN
      END
