      SUBROUTINE ECMH_PLATE_GEOM
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : Create the ECMH module GEANT volumes.
C-
C-   Inputs  :
C-   Outputs :
C-   Controls:
C-
C-   Created  20-MAR-1990   Norman A. Amos
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:SRCP_VOLUME.INC'
      INCLUDE 'D0$INC:WRITE_UNIT.INC'
      INCLUDE 'D0$INC:MATRIX.INC'
      INCLUDE 'D0$INC:IUSET.INC'
      INCLUDE 'D0$INC:ECMH_MODULE.INC'
      REAL XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS
      REAL CUTBACK,CCUTBACK,SCUTBACK,PI,CM_PER_IN
      REAL THICK,ECVOLUME,ANGLE
      REAL ETABOUNDS(5),PHIBOUNDS(3)
      INTEGER IER,IGAP,NGAPS,MFH_GAPMAX
      INTEGER IREADOUT,READOUT_GAP(5)
      INTEGER N_ETABOUNDS,N_PHIBOUNDS,I
      INTEGER ISTEP,LAST_GAP_PER_STEP(11)
      INTEGER ABSORBER_COPY,ARGONGAP_COPY
      INTEGER SIGNALBOARD_COPY,READOUT_COPY
      CHARACTER SECT*5,VOLNAM*4,VOLMOT*4,GAP*2
      CHARACTER STEP*2,STEP_CODE*1
      EQUIVALENCE(VOLNAM,VOLUME_NAME)
      EQUIVALENCE(VOLMOT,VOLUME_MOTHER)
C-
      DATA SIGNALBOARD_COPY/0/
      DATA ABSORBER_COPY/0/
      DATA ARGONGAP_COPY/0/
      DATA READOUT_COPY/0/
      DATA IREADOUT/1/
      DATA YCURS/0./
      DATA ISTEP/1/
      DATA IGAP/0/
C----------------------------------------------------------------------
C- Constants.
C----------------------------------------------------------------------
      CALL EZGET('PI',PI,IER)
      CALL EZGET('CM_PER_INCH',CM_PER_IN,IER)
      CALL EZGET_i('ECMH_NUMBER_GAPS',NGAPS,IER)
      CALL EZGET_i('ECMFH_NUMBER_GAPS',MFH_GAPMAX,IER)
      CALL EZGET_iarr('ECMH_READOUT_GAPS',READOUT_GAP,IER)
      CALL EZGET('RESISTCOAT_CUTBACK',CUTBACK,IER)
      CALL EZGET('ECMH_MODULE_ANGLE',ANGLE,IER)
      CCUTBACK=CUTBACK/COS(PI*ANGLE/180.)
      SCUTBACK=CUTBACK/SIN(PI*ANGLE/180.)
      CALL EZGET_i('ECMH_N_PHI_BOUNDS',N_PHIBOUNDS,IER)
      CALL EZGET_rarr('ECMH_PHI_BOUNDS',PHIBOUNDS,IER)
      CALL EZGET_iarr('ECMH_LAST_GAP_PER_STEP',LAST_GAP_PER_STEP,IER)
      CALL EZGET_i('ECMH_PLATE_MODULE_VOLUME_NAME',VOLUME_MOTHER,IER)
C----------------------------------------------------------------------
C- Generate the FRONTPLATE.
C----------------------------------------------------------------------
C     WRITE (*,*) 'ECMH Front Plate'
      COPY_NUMBER=1
      CALL EZGET_i('ECMH_FRONTPLATE_VOLUME_NAME',VOLUME_NAME,IER)
      CALL EZGET_i('STAINLESS_STEEL_CODE',VOLUME_MATERIAL_CODE,IER)
      CALL EZGET('ECMH_FRONTPLATE_THICKNESS',THICK,IER)
      CALL EZGET('ECMH_MODULE_X_INC',XINC,IER)
      CALL EZGET('ECMH_MODULE_Y_INC',YINC,IER)
      CALL EZGET('ECMH_MODULE_X_OUC',XOUC,IER)
      CALL EZGET('ECMH_MODULE_Y_OUC',YOUC,IER)
      CALL EZGET('ECMH_MODULE_X_TOP',XTOP,IER)
      CALL EZGET('ECMH_MODULE_Y_TOP',YTOP,IER)
      VOLUME_LABEL='ECMH_FRONTPLATE_VOLUME_TOP'
      VOLNAM(4:4)='T'
      VOLMOT(4:4)='T'
      CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,1,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
      X_POSITION=X_POSITION-X_MOTHER_TOP
      Y_POSITION=Y_POSITION-Y_MOTHER_TOP
      Z_POSITION=Z_POSITION-Z_MOTHER_TOP
      ROTATION_MATRIX = 1               ! Identity
      CALL WRITE_VOLUME
      VOLUME_LABEL='ECMH_FRONTPLATE_VOLUME_BOT'
      VOLNAM(4:4)='B'
      VOLMOT(4:4)='B'
      CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,2,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
      X_POSITION=X_POSITION-X_MOTHER_BOT
      Y_POSITION=Y_POSITION-Y_MOTHER_BOT
      Z_POSITION=Z_POSITION-Z_MOTHER_BOT
      ROTATION_MATRIX = 1               ! Identity
      CALL WRITE_VOLUME
      YCURS=YCURS+THICK
C----------------------------------------------------------------------
C- Loop over all BOARDS and ABSORBERS in the ECMH.
C----------------------------------------------------------------------
      DO IGAP=1,NGAPS
        WRITE (GAP,'(I2.2)') IGAP
        WRITE (STEP_CODE,'(Z1)') ISTEP
C-    Choose between MFH and MCH.
        IF (IGAP.GT.MFH_GAPMAX) then
          CALL EZGET_i('STAINLESS_STEEL_CODE',VOLUME_MATERIAL_CODE,IER)
          IF (SECT.EQ.'ECMFH') THEN
            SIGNALBOARD_COPY=0
            ABSORBER_COPY=0
            READOUT_COPY=0
          ENDIF
          SECT='ECMCH'
        ELSE
          CALL EZGET_i('URANIUM_CODE',VOLUME_MATERIAL_CODE,IER)
          SECT='ECMFH'
        ENDIF
C----------------------------------------------------------------------
C-    Generate an ABSORBER.
C----------------------------------------------------------------------
C-    There is no ABSORBER before GAP 1, only the frontplate.
        IF (IGAP.EQ.1) goto 100
C         WRITE (*,*) 'ECMH Absorber '//GAP
          ABSORBER_COPY=ABSORBER_COPY+1
          COPY_NUMBER=ABSORBER_COPY
          CALL EZGET_i('ECMH_ABSORBER_VOLUME_NAME',VOLUME_NAME,IER)
          CALL EZGET(SECT//'_ABSORBER_THICKNESS',THICK,IER)
          CALL EZGET(SECT//'_ABSORB_X_INC',XINC,IER)
          CALL EZGET(SECT//'_ABSORB_Y_INC',YINC,IER)
          CALL EZGET(SECT//'_ABSORB_X_OUC',XOUC,IER)
          CALL EZGET('ECMH_MODULE_Y_OUC',YOUC,IER)
          CALL EZGET(SECT//'_ABSORB_X_TOP',XTOP,IER)
          CALL EZGET(SECT//'_ABSORB_Y_TOP',YTOP,IER)
          VOLUME_LABEL='ECMH_ABSORBER'//GAP//'_VOLUME_TOP'
          IF (SECT.EQ.'ECMFH') VOLNAM(4:4)='T'
          IF (SECT.EQ.'ECMCH') VOLNAM(4:4)='U'
          VOLMOT(4:4)='T'
          CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,1,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
          X_POSITION=X_POSITION-X_MOTHER_TOP
          Y_POSITION=Y_POSITION-Y_MOTHER_TOP
          Z_POSITION=Z_POSITION-Z_MOTHER_TOP
          ROTATION_MATRIX = 1           ! Identity
          CALL WRITE_VOLUME
          VOLUME_LABEL='ECMH_ABSORBER'//GAP//'_VOLUME_BOT'
          IF (SECT.EQ.'ECMFH') VOLNAM(4:4)='B'
          IF (SECT.EQ.'ECMCH') VOLNAM(4:4)='D'
          VOLMOT(4:4)='B'
          CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,2,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
          X_POSITION=X_POSITION-X_MOTHER_BOT
          Y_POSITION=Y_POSITION-Y_MOTHER_BOT
          Z_POSITION=Z_POSITION-Z_MOTHER_BOT
          ROTATION_MATRIX = 1           ! Identity
          CALL WRITE_VOLUME
          YCURS=YCURS+THICK
100     CONTINUE
C----------------------------------------------------------------------
C-    Generate the front ARGON GAP.
C-    An ARGON GAP has dimensions of the signal board
C-    MINUS the resist-coat cutback.
C----------------------------------------------------------------------
C       WRITE (*,*) 'ECMH Argon Gap '//GAP
        ARGONGAP_COPY=ARGONGAP_COPY+1
        COPY_NUMBER=ARGONGAP_COPY
        CALL EZGET_i('ECMH_ARGONGAP_VOLUME_NAME',VOLUME_NAME,IER)
        CALL EZGET_i('LIQUID_ARGON_CODE',VOLUME_MATERIAL_CODE,IER)
        CALL EZGET('ECMH_ARGONGAP_THICKNESS',THICK,IER)
        CALL EZGET(SECT//'_BOARD_X_INC',XINC,IER)
        XINC=XINC-CCUTBACK
        CALL EZGET(SECT//'_BOARD_Y_INC',YINC,IER)
        YINC=YINC+CUTBACK
        CALL EZGET(SECT//'_BOARD_X_OUC',XOUC,IER)
        XOUC=XOUC-SCUTBACK
        CALL EZGET('ECMH_MODULE_Y_OUC',YOUC,IER)
        CALL EZGET(SECT//'_BOARD_X_TOP',XTOP,IER)
        CALL EZGET(SECT//'_BOARD_Y_TOP',YTOP,IER)
        YTOP=YTOP-CCUTBACK
        VOLUME_LABEL='ECMH_ARGONGAP'//GAP//'_VOLUME_FTOP'
        VOLNAM(3:4)=STEP_CODE//'T'
        VOLMOT(4:4)='T'
        CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,1,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
        X_POSITION=X_POSITION-X_MOTHER_TOP
        Y_POSITION=Y_POSITION-Y_MOTHER_TOP
        Z_POSITION=Z_POSITION-Z_MOTHER_TOP
        ROTATION_MATRIX = 1             ! Identity
        CALL WRITE_VOLUME
        CALL EZGET(SECT//'_BOARD_X_OUC',XOUC,IER)
        XOUC=XOUC-CCUTBACK
        VOLUME_LABEL='ECMH_ARGONGAP'//GAP//'_VOLUME_FBOT'
        VOLNAM(3:4)=STEP_CODE//'B'
        VOLMOT(4:4)='B'
        CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,2,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
        X_POSITION=X_POSITION-X_MOTHER_BOT
        Y_POSITION=Y_POSITION-Y_MOTHER_BOT
        Z_POSITION=Z_POSITION-Z_MOTHER_BOT
        ROTATION_MATRIX = 1             ! Identity
        CALL WRITE_VOLUME
        YCURS=YCURS+THICK
C----------------------------------------------------------------------
C-    Generate a signal BOARD.
C----------------------------------------------------------------------
C       WRITE (*,*) 'ECMH Signal Board '//GAP
        SIGNALBOARD_COPY=SIGNALBOARD_COPY+1
        COPY_NUMBER=SIGNALBOARD_COPY
        CALL EZGET_i('ECMH_SIGNALBOARD_VOLUME_NAME',VOLUME_NAME,IER)
        CALL EZGET_i('G10_CODE',VOLUME_MATERIAL_CODE,IER)
        CALL EZGET('ECMH_SIGNALBOARD_THICKNESS',THICK,IER)
        CALL EZGET(SECT//'_BOARD_X_INC',XINC,IER)
        CALL EZGET(SECT//'_BOARD_Y_INC',YINC,IER)
        CALL EZGET(SECT//'_BOARD_X_OUC',XOUC,IER)
        CALL EZGET('ECMH_MODULE_Y_OUC',YOUC,IER)
        CALL EZGET(SECT//'_BOARD_X_TOP',XTOP,IER)
        CALL EZGET(SECT//'_BOARD_Y_TOP',YTOP,IER)
        VOLUME_LABEL='ECMH_SIGNALBOARD'//GAP//'_VOLUME_TOP'
        IF (SECT.EQ.'ECMFH') VOLNAM(4:4)='T'
        IF (SECT.EQ.'ECMCH') VOLNAM(4:4)='U'
        VOLMOT(4:4)='T'
        CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,1,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
        X_POSITION=X_POSITION-X_MOTHER_TOP
        Y_POSITION=Y_POSITION-Y_MOTHER_TOP
        Z_POSITION=Z_POSITION-Z_MOTHER_TOP
        ROTATION_MATRIX = 1             ! Identity
        CALL WRITE_VOLUME
        VOLUME_LABEL='ECMH_SIGNALBOARD'//GAP//'_VOLUME_BOT'
        IF (SECT.EQ.'ECMFH') VOLNAM(4:4)='B'
        IF (SECT.EQ.'ECMCH') VOLNAM(4:4)='D'
        VOLMOT(4:4)='B'
        CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,2,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
        X_POSITION=X_POSITION-X_MOTHER_BOT
        Y_POSITION=Y_POSITION-Y_MOTHER_BOT
        Z_POSITION=Z_POSITION-Z_MOTHER_BOT
        ROTATION_MATRIX = 1             ! Identity
        CALL WRITE_VOLUME
        YCURS=YCURS+THICK
C----------------------------------------------------------------------
C-    Generate the back ARGON GAP.
C----------------------------------------------------------------------
C       WRITE (*,*) 'ECMH Argon Gap '//GAP
        ARGONGAP_COPY=ARGONGAP_COPY+1
        COPY_NUMBER=ARGONGAP_COPY
        CALL EZGET_i('ECMH_ARGONGAP_VOLUME_NAME',VOLUME_NAME,IER)
        CALL EZGET_i('LIQUID_ARGON_CODE',VOLUME_MATERIAL_CODE,IER)
        CALL EZGET('ECMH_ARGONGAP_THICKNESS',THICK,IER)
        CALL EZGET(SECT//'_BOARD_X_INC',XINC,IER)
        XINC=XINC-SCUTBACK
        CALL EZGET(SECT//'_BOARD_Y_INC',YINC,IER)
        YINC=YINC+CUTBACK
        CALL EZGET(SECT//'_BOARD_X_OUC',XOUC,IER)
        XOUC=XOUC-CCUTBACK
        CALL EZGET('ECMH_MODULE_Y_OUC',YOUC,IER)
        CALL EZGET(SECT//'_BOARD_X_TOP',XTOP,IER)
        CALL EZGET(SECT//'_BOARD_Y_TOP',YTOP,IER)
        YTOP=YTOP-CCUTBACK
        VOLUME_LABEL='ECMH_ARGONGAP'//GAP//'_VOLUME_BTOP'
        VOLNAM(3:4)=STEP_CODE//'T'
        VOLMOT(4:4)='T'
        CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,1,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
        X_POSITION=X_POSITION-X_MOTHER_TOP
        Y_POSITION=Y_POSITION-Y_MOTHER_TOP
        Z_POSITION=Z_POSITION-Z_MOTHER_TOP
        ROTATION_MATRIX = 1             ! Identity
        CALL WRITE_VOLUME
        CALL EZGET(SECT//'_BOARD_X_OUC',XOUC,IER)
        XOUC=XOUC-CCUTBACK
        VOLUME_LABEL='ECMH_ARGONGAP'//GAP//'_VOLUME_BBOT'
        VOLNAM(3:4)=STEP_CODE//'B'
        VOLMOT(4:4)='B'
        CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,2,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
        X_POSITION=X_POSITION-X_MOTHER_BOT
        Y_POSITION=Y_POSITION-Y_MOTHER_BOT
        Z_POSITION=Z_POSITION-Z_MOTHER_BOT
        ROTATION_MATRIX = 1             ! Identity
        CALL WRITE_VOLUME
        YCURS=YCURS+THICK
C----------------------------------------------------------------------
C-    If at a READOUT gap, generate a READOUT BOARD.
C----------------------------------------------------------------------
        IF (IGAP.EQ.READOUT_GAP(IREADOUT)) then
C         WRITE (*,*) 'ECMH Readout Board '//GAP
          READOUT_COPY=READOUT_COPY+1
          COPY_NUMBER=READOUT_COPY
          IREADOUT=IREADOUT+1
          CALL EZGET_i('ECMH_READOUTBOARD_VOLUME_NAME',VOLUME_NAME,IER)
          CALL EZGET('ECMH_READOUTBOARD_THICKNESS',THICK,IER)
          CALL EZGET(SECT//'_BOARD_X_INC',XINC,IER)
          CALL EZGET(SECT//'_BOARD_Y_INC',YINC,IER)
          CALL EZGET(SECT//'_BOARD_X_OUC',XOUC,IER)
          CALL EZGET('ECMH_MODULE_Y_OUC',YOUC,IER)
          CALL EZGET(SECT//'_BOARD_X_TOP',XTOP,IER)
          CALL EZGET(SECT//'_BOARD_Y_TOP',YTOP,IER)
          VOLUME_LABEL='ECMH_READOUTBOARD'//GAP//'_VOLUME_TOP'
          IF (SECT.EQ.'ECMFH') VOLNAM(4:4)='T'
          IF (SECT.EQ.'ECMCH') VOLNAM(4:4)='U'
          VOLMOT(4:4)='T'
          CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,1,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
          X_POSITION=X_POSITION-X_MOTHER_TOP
          Y_POSITION=Y_POSITION-Y_MOTHER_TOP
          Z_POSITION=Z_POSITION-Z_MOTHER_TOP
          ROTATION_MATRIX = 1           ! Identity
          CALL WRITE_VOLUME
          VOLUME_LABEL='ECMH_READOUTBOARD'//GAP//'_VOLUME_BOT'
          IF (SECT.EQ.'ECMFH') VOLNAM(4:4)='B'
          IF (SECT.EQ.'ECMCH') VOLNAM(4:4)='D'
          VOLMOT(4:4)='B'
          CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,2,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
          X_POSITION=X_POSITION-X_MOTHER_BOT
          Y_POSITION=Y_POSITION-Y_MOTHER_BOT
          Z_POSITION=Z_POSITION-Z_MOTHER_BOT
          ROTATION_MATRIX = 1           ! Identity
          CALL WRITE_VOLUME
          YCURS=YCURS+THICK
        ENDIF
C----------------------------------------------------------------------
C-    Write out the Steps Info.
C----------------------------------------------------------------------
        IF (IGAP.EQ.LAST_GAP_PER_STEP(ISTEP)) THEN
          WRITE (STEP,'(I2.2)') ISTEP
C         WRITE (*,*) 'ECMH End of Step '//STEP
          ISTEP=ISTEP+1
          ARGONGAP_COPY=0
          CALL EZGET_i('ECMH_STEP'//STEP//'_NCELLS',N_ETABOUNDS,IER)
          CALL EZGET_rarr('ECMH_STEP'//STEP//'_CELLS',ETABOUNDS,IER)
          WRITE (OUT_SET,200) 'ECMH_STEP'//STEP//'_CELLS'
200       FORMAT('\ARRAY ',A18)
          WRITE (OUT_SET,210) N_PHIBOUNDS
210       FORMAT(6X,I2,'  ! Number of phi boundaries',/,
     &    8X,'  ! phi boundaries (degrees) follow')
          WRITE (OUT_SET,220) (PHIBOUNDS(I),I=1,N_PHIBOUNDS)
220       FORMAT(9x,5F9.3)
          WRITE (OUT_SET,230) N_ETABOUNDS
230       FORMAT(6X,I2,'  ! Number of eta boundaries',/,
     &    8X,'  ! eta boundaries (cm) follow')
          WRITE (OUT_SET,220) (ETABOUNDS(I)*CM_PER_IN,I=1,N_ETABOUNDS)
          WRITE (OUT_SET,240)
240       FORMAT('\END')
        ENDIF
C-
      ENDDO
C----------------------------------------------------------------------
C- Generate the ENDPLATE.
C----------------------------------------------------------------------
C     WRITE (*,*) 'ECMH END Plate'
      COPY_NUMBER=1
      CALL EZGET_i('ECMH_ENDPLATE_VOLUME_NAME',VOLUME_NAME,IER)
      CALL EZGET_i('STAINLESS_STEEL_CODE',VOLUME_MATERIAL_CODE,IER)
      CALL EZGET('ECMH_ENDPLATE_THICKNESS',THICK,IER)
      CALL EZGET('ECMH_MODULE_X_INC',XINC,IER)
      CALL EZGET('ECMH_MODULE_Y_INC',YINC,IER)
      CALL EZGET('ECMH_MODULE_X_OUC',XOUC,IER)
      CALL EZGET('ECMH_MODULE_Y_OUC',YOUC,IER)
      CALL EZGET('ECMH_MODULE_X_TOP',XTOP,IER)
      CALL EZGET('ECMH_MODULE_Y_TOP',YTOP,IER)
      VOLUME_LABEL='ECMH_ENDPLATE_VOLUME_TOP'
      VOLNAM(4:4)='T'
      VOLMOT(4:4)='T'
      CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,1,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
      X_POSITION=X_POSITION-X_MOTHER_TOP
      Y_POSITION=Y_POSITION-Y_MOTHER_TOP
      Z_POSITION=Z_POSITION-Z_MOTHER_TOP
      ROTATION_MATRIX = 1               ! Identity
      CALL WRITE_VOLUME
      VOLUME_LABEL='ECMH_ENDPLATE_VOLUME_BOT'
      VOLNAM(4:4)='B'
      VOLMOT(4:4)='B'
      CALL ECMH_UNIT(XINC,YINC,XOUC,YOUC,XTOP,YTOP,YCURS,THICK,2,
     &               PARAM,X_POSITION,Y_POSITION,Z_POSITION,ECVOLUME)
      X_POSITION=X_POSITION-X_MOTHER_BOT
      Y_POSITION=Y_POSITION-Y_MOTHER_BOT
      Z_POSITION=Z_POSITION-Z_MOTHER_BOT
      ROTATION_MATRIX = 1               ! Identity
      CALL WRITE_VOLUME
C-
  999 RETURN
      END
