CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VD0USER()
      VD0USER = ' D0USER'//
     X                   '  TEST V5.45_02'//
     X                   ' 14-AUG-1997 08:32:55.02'
      Return
      End
