CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VGRAPHICS_UTIL()
      VGRAPHICS_UTIL = ' GRAPHICS_UTIL'//
     X                   '  OFFICIAL V1.07'//
     X                   '  4-NOV-1996 15:21:18.25'
      Return
      End
