C            ACOL_VALUES.INC
C----------------------------------------------------------------------
C-
C-   Created  09-MAY-1994   Lewis Taylor Goss
C-
C----------------------------------------------------------------------
C     *** values to be stored in the result bank ACOL ***
      INTEGER PAIR_STATUS,OBJN_VAL
      REAL MET,PHIMET,PAIR_VAL(4,3)
C
      COMMON /ACOL_VALUES/ PAIR_VAL,PAIR_STATUS,OBJN_VAL,MET,PHIMET
