C
C=================================================================
C      COMMON /CALPAR/ CONTIANS RUN PARAMETERS NEEDED BY SHOWER SIMULATION
C      AND TRACING ROUTINES
C
       REAL
     1      SIGINT,            
     2      DEMIN,             
     3      ZINTER,            
     4      XINTER,            
     5      XDECAY,            
     6      ERES,              
     7      HRES,              
     8      EMIN,              
     9      HMIN,              
     1      DZE,               
     2      DZH,               
     3      BE,AE,             
     4      ALPHAE,BETAE,
     5      AH,BH,CH,DH,W,     
     6      ALPHAH,BETAH,
     7      SIGMAE,SIGMAH,     
     8      ESHOW,             
     9      ECUT               
C
       COMMON/CALPAR/SIGINT,DEMIN,ZINTER,XDECAY,ERES,HRES,EMIN
     1      ,HMIN,DZE,DZH,BE,AE,ALPHAE,BETAE,AH,BH,CH,DH,W,ALPHAH
     2      ,BETAH,SIGMAE,SIGMAH,ESHOW,ECUT
C      ===================================================================
