C DEC/CMS REPLACEMENT HISTORY, Element CARG.INC
C *2    27-NOV-1989 08:13:08 SACLAY "A. Zylberstejn"
C *1    15-AUG-1986 15:46:23 JONCKHEERE "V3.10.61 version"
C DEC/CMS REPLACEMENT HISTORY, Element CARG.INC
C----------------------------------------------------------------------
C-
C-   Created   7-JUL-1989   A. Zylberstejn
C-
C----------------------------------------------------------------------
      integer narg
      PARAMETER( narg =400  )
      COMMON /CARG/ ARG(narg)
      real arg
