C DEC/CMS REPLACEMENT HISTORY, Element CC_UNIT.INC
C *2    10-DEC-1988 15:35:21 FUESS "Add CCEM front plate"
C *1     8-DEC-1988 14:45:46 FUESS "Initial entry of CC .INC files"
C DEC/CMS REPLACEMENT HISTORY, Element CC_UNIT.INC
C----------------------------------------------------------------------
C-
C-      /CC_UNIT/
C-
C-      CC Geometry Logical Unit Assignments
C-
C-   Created   7-DEC-1988   Stuart Fuess
C-
C----------------------------------------------------------------------
      INTEGER CC_OUT_VOL                
      INTEGER CC_OUT_SET                
      COMMON /CC_UNIT/ CC_OUT_VOL,
     &                 CC_OUT_SET
