C----------------------------------------------------------------------
C-
C-   Created   9-MAR-1988   Stephen Kahn, Esq.
C-   CLINKS contains links to calorimeter geometry banks
C-
C----------------------------------------------------------------------
      INTEGER LQSTPH, LQSCAL, LQCGEH, LQCREG, LQCLGI, LQCLGA, LQCRYO, 
     + LQCLAY, LQCLNK, LQCLIN, LQCTOW, LQCCEL, LQCMAT, LQCSHA, LQCRAK,
     + LQCENP, LQCPOS, LQCSCN, LQCABS,
     + LQCEDP, LQCETA, LQCLYR
      COMMON/ CLINKS / LQSTPH, LQSCAL, LQCGEH, LQCREG, LQCLGI, LQCLGA, 
     + LQCRYO, LQCLAY, LQCLNK, LQCLIN, LQCTOW, LQCCEL, LQCMAT, LQCSHA,
     + LQCRAK, LQCENP, LQCPOS, LQCSCN, LQCABS,
     + LQCEDP, LQCETA, LQCLYR
