C----------------------------------------------------------------------
C-
C-   Created  12-FEB-1989   Srini Rajagopalan
C-
C----------------------------------------------------------------------
C
C   AMPLTA  =  Amplitude of test pulse - step A
C   AMPLTB  =  Amplitude of test pulse - step B
C   PLRTY   =  Polarity of test pulse
C   PULSPA  =  Control for pulsing through preamp
C   SHCRD   =  Shaper card number to be pulsed
C   SHHLF   =  Shaper Half to be pulsed
C
      COMMON /CTSHPR/ AMPLTA,AMPLTB,PLRTY,PULSPA,SHCRD,SHHLF
C
      INTEGER AMPLTA,AMPLTB,PLRTY,PULSPA,SHCRD,SHHLF

C-----------------------------------------------------------------------
