C----------------------------------------------------------------------
C-
C-   Cernlib CSPACK common /CZSOCK/ 
C-
C-   Created   5-MAY-1993   Herbert Greenlee
C-
C----------------------------------------------------------------------
      COMMON/CZSOCK/LUNCZ,IADTCP,LBUF,ISKIN,ISKOUT,IPROT,
     +              JUNIT(99),JSKIN(99),JSKOUT(99),CUNODE,
     +              CHNODE(99),CHUSER(99)
      INTEGER LUNCZ,IADTCP,LBUF,ISKIN,ISKOUT,IPROT, 
     +        JUNIT,JSKIN,JSKOUT
      CHARACTER*12  CHNODE,CUNODE,CHUSER
