C----------------------------------------------------------------------
C-
C-   Created   7-JAN-1990   Rajendran Raja
C-   RECREATION OF OLD COMMON BLOCK
C----------------------------------------------------------------------
       COMMON/DATARR/JTYP,JRUN,JEVT,PPP,DPP,ALAM,APHI,EEE,DEE,
     &   EXX,EYY,ERY,EZZ,ERZ,ETOT,IERR,NTYP1,NTYP2,ETEL,ETNU,
     &   PEL(4),PNUT(4),CHEL,PW(4),PELGEN(4),PNUGEN(4)
       INTEGER JTYP,JRUN,JEVT,IERR,NTYP1,NTYP2
       REAL    PPP,DPP,ALAM,APHI,EEE,DEE,EXX,EYY,ERY,EZZ,ERZ,ETOT
       REAL    ETEL,ETNU,PEL,PNUT,CHEL,PW,PELGEN,PNUGEN
