C         Parameters for digitization

C          Readout parameters
      INTEGER NCRATE,OADC,NADC,NTIMSL,NCHN
      PARAMETER (NCRATE=1)
      PARAMETER (NADC =6)
      PARAMETER (OADC =8)
      PARAMETER (NTIMSL=16)
      PARAMETER (NCHN = 24 )
C         Cable parameters
      INTEGER NDEP,NPHI,NETA,NSECT,NQUAD
      PARAMETER (NDEP=12)
      PARAMETER (NPHI=2)
      PARAMETER (NETA=12)
      PARAMETER (NSECT=4)
      PARAMETER (NQUAD=2)
C         Module parameters
      INTEGER MDEP,MPHI,META,MSECT,MQUAD
      PARAMETER (MDEP=7)
      PARAMETER (MPHI=2)
      PARAMETER (META=12)
      PARAMETER (MSECT=5)
      PARAMETER (MQUAD=2)
