C----------------------------------------------------------------------
C-
C-      /ECIH_MODULE/
C-
C-      ECIH 'Module volume' geometrical properties
C-
C-   Created  18-MAR-1990   Stuart Fuess
C-
C----------------------------------------------------------------------
      REAL ECIH_MODULE_INNER_RADIUS     
      REAL ECIH_MODULE_OUTER_RADIUS     
      REAL ECIH_MODULE_LENGTH           
      REAL ECIH_MODULE_VOLUME           
      COMMON /ECIH_MODULE/ ECIH_MODULE_INNER_RADIUS,
     &                     ECIH_MODULE_OUTER_RADIUS,
     &                     ECIH_MODULE_LENGTH,
     &                     ECIH_MODULE_VOLUME
