C            EMSV_VALUES.INC
C----------------------------------------------------------------------
C-
C-   Created  30-SEP-1994   Lewis Taylor Goss
C-
C----------------------------------------------------------------------
C     *** values to be stored in the result bank EMSV ***
      LOGICAL PASSED
      INTEGER ICAND,IETA,IPHI,LYR,L1ETA,L1PHI
      REAL EFLOOR(8),ET_VTX0,ET_CAND,E_EM,EM3(-2:2,-2:2),E3,E5,E7,AETA
      REAL APHI,XYZ_CLUS(3),SIG_PHI,SIG_ETA,ETA_PHYS,ET_Z_E_CORR
