C	=====================================================
C	Parameter Definitions for the Data Acquisition System
C	=====================================================
C
C	Modulename:-
C	============
C	DAQ$CMS:EVTCTDEF.INC
C
C	Description:-
C	=============
C	This Include File contains the EVT_CT (EVenT Control Table)
C	entry definitions.
C
C	Creation Date :  8 Mar 1983
C	===========================
C
      Parameter EVT_CT_NEXT    = 0	
      Parameter EVT_CT_PREV    = 1	
      Parameter EVT_CT_NOCC    = 2	
      Parameter EVT_CT_POCC    = 3	
      Parameter EVT_CT_NXTSUB  = 2	
      Parameter EVT_CT_PRVSUB  = 3	
      Parameter EVT_CT_DATA    = 4	
      Parameter EVT_CT_DLEN    = 5	
      Parameter EVT_CT_HOLE    = 6	
      Parameter EVT_CT_ENUM    = 7	
      Parameter EVT_CT_PARTID  = 8	
      Parameter EVT_CT_ETYP    = 9	
      Parameter EVT_CT_TMSK    = 10     
      Parameter EVT_CT_TMSKB   = 11     
      Parameter EVT_CT_TMSKC   = 12     
      Parameter EVT_CT_TMSKD   = 13     
      Parameter EVT_CT_DESTA   = 14	
      Parameter EVT_CT_DESTB   = 15	
      Parameter EVT_CT_DESTC   = 16 	
      Parameter EVT_CT_USER    = 17	
      Parameter EVT_CT_STAT    = 18	
      Parameter EVT_CT_OWNER   = 19	
      Parameter EVT_CT_LENG    = 20     
C
      Parameter EVT_FREE       = 0	
      Parameter EVT_RESREAD    = 1	
      Parameter EVT_RESWRIT    = 2	
      Parameter EVT_OCCUPIED   = 3	
      Parameter EVT_NOUSE      = 4	
C
