C----------------------------------------------------------------------
C
C   /EXM_UNIT_NOS/
C   Created  9-SEP-1988   Wyatt Merritt
C
C       Contains unit numbers necessary for program EXAMINE
C
C       EV_UNIT         unit number for input file for data
C       DMP_UNIT        unit number for event dump file
C----------------------------------------------------------------------
C
      INTEGER EV_UNIT,DMP_UNIT
C
      COMMON /EXM_UNIT_NOS/ EV_UNIT,DMP_UNIT
C----------------------------------------------------------------------
C----------------------------------------------------------------------
