C----------------------------------------------------------------------
C
C   Created  13-APR-1988   Wyatt Merritt
C
C       Contains event statistics kept by the EXAMINE framework
C       Filled in EVENT_PROCESSIING or STATISTICS
C----------------------------------------------------------------------
      INTEGER NEVENTS, NEVS
C
      COMMON /EXM_STATISTICS/ NEVENTS, NEVS
C----------------------------------------------------------------------
