C     FDLOCA.INC
C----------------------------------------------------------------------
C-
C-   Created   4-NOV-1988   Jeffrey Bantly
C-   Updated  19-MAR-1990   Jeffrey Bantly  add UB,LOGCHA 
C-
C-   Local variables for FDC processing
C-
C----------------------------------------------------------------------
      COMMON /FDLOCA/ HALF, UNIT, QUAD, SECTOR, WIRE, UB, LOGCHA
      INTEGER HALF, UNIT, QUAD, SECTOR, WIRE, UB, LOGCHA
C
