C DEC/CMS REPLACEMENT HISTORY, Element GDIAUX.INC
C *1     2-NOV-1988 17:13:54 ABACHI ""
C DEC/CMS REPLACEMENT HISTORY, Element GDIAUX.INC
C''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
C-   S. ABACHI  2-NOV-1988
C-
C''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
      INTEGER   NCOLR(36),NVLU,ICC1,ICL1
      REAL QMATL(4,4)
      COMMON/GDIAUX/NCOLR,NVLU,ICC1,ICL1,QMATL
      DATA NCOLR/2,5,4,7,6,1,3,8,9,2,7,5,4,6,1,3,8,9,
     1       2,5,4,7,6,1,3,8,9,2,7,5,4,6,1,3,8,9/
