C DEC/CMS REPLACEMENT HISTORY, Element GDITRP.INC
C *2     3-NOV-1988 02:21:18 ABACHI ""
C *1     2-NOV-1988 17:14:01 ABACHI ""
C DEC/CMS REPLACEMENT HISTORY, Element GDITRP.INC
C''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
C-   S. ABACHI  2-NOV-1988
C-
C''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
       INTEGER   ITRLOC,IDICOT(10),IDILWT(10),IDILST(10),IDICOM(20),
     1           IDITYM(20)
       REAL      ADICMP
       COMMON /GDITRP/ITRLOC,IDICOT,IDILWT,IDILST,IDICOM,
     1                IDITYM,ADICMP
