C----------------------------------------------------------------------------
C      GEOMETRY.INC COMMONS  --------  SEE BLOCK DATA GEODAT FOR DEFINTIONS
c      THESE COMMONS ARE CONSISTENT WITH USE OF "IMPLICIT NONE"
C      S. KAHN -- 01-MAY-1985
C----------------------------------------------------------------------------
C....  GEOM BLOCK LOCATIONS
      INCLUDE '/d0library/scratch/inc/igeom.inc'
C....  DETECTOR TYPES
      INCLUDE '/d0library/scratch/inc/idetyp.inc'
C....  DETECTOR SHAPES
      INCLUDE '/d0library/scratch/inc/ishape.inc'
C....  LAYER TYPES  -- (currently CDF unchanged)
      INCLUDE '/d0library/scratch/inc/iltype.inc'
C....  LAYER SHAPES
      INCLUDE '/d0library/scratch/inc/ilshap.inc'
C....  MATERIAL TYPES
      INCLUDE '/d0library/scratch/inc/imate.inc'
C....  REGION NUMBERS -- CALORIMETER
      INCLUDE '/d0library/scratch/inc/iregion.inc'
C----------------------------------------------------------------
