C  --------COMMON,GEOMTR :TEMPORARY COMMON TO FILL THE  GEOMETRICAL
C                         QUANTITIES FOR THE TRD
      COMMON/GEOMTR/RADIN(3) ,RADWIN(3),RADGRI(3),DRGRAN(3),RADAN(3)
     +             ,RADEXT(3),DISTAN(3),OFSDPH(3),DPHIAN(3),NWIRE(3)
     +             ,DRWINA(3),DRWING(3)
      REAL          RADIN    ,RADWIN   ,RADGRI   ,DRGRAN   ,RADAN
     +             ,RADEXT   ,DISTAN   ,OFSDPH   ,DPHIAN
     +             ,DRWINA   ,DRWING
      INTEGER                                               NWIRE
