C----------------------------------------------------------------------
C-
C-   Created  11-OCT-1988   J.R. HUBBARD (TRICKY DICK)
C-
C----------------------------------------------------------------------
      COMMON /GEOMTC/ WIDCAT(3),DPHICA(3),DISTCA(3),DPHIDZ(3),
     1                OFSCAT(3),NSTRIP(3)
      REAL            WIDCAT,   DPHICA,   DISTCA,   DPHIDZ,   OFSCAT
      INTEGER                   NSTRIP

