C  --------COMMON,GEOTRD :TEMPORARY COMMON TO FILL THE  GEOMETRICAL
C                         QUANTITIES FOR THE TRD
      COMMON/GEOTRD/RADIN(3) ,RADWIN(3),RADGRI(3),DRGRAN(3),RADAN(3)
     +             ,RADEXT(3),DISTAN(3),OFSDPH(3),DPHIAN(3),NWIRE(3)
      REAL          RADIN    ,RADWIN   ,RADGRI   ,DRGRAN   ,RADAN   
     +             ,RADEXT   ,DISTAN   ,OFSDPH   ,DPHIAN   
      INTEGER                                               NWIRE   
