C----------------------------------------------------------------------
C
C ****  Handles variables for X ray generation according to Garibian et al.
C ****   (irregular stack)
C
C-   Created                B. Mansoulie  
C-   Updated  12-JUL-1989   A. Zylberstejn   
C----------------------------------------------------------------------
      COMMON/GRUTIL/D(2),XFOIL,AG(2),PA(2),PAB,PABN,PAB1H,
     >C1MA(2),C2MA(2),CPSI(2),TT(2),ANE,AMLIM(2),DPI,DTWOPI
      REAL*8 D,XFOIL,AG,PA,PAB,PABN,PAB1H,
     >C1MA,C2MA,CPSI,TT,ANE,AMLIM,DPI,DTWOPI
