C            HTSM_VALUES.INC
C----------------------------------------------------------------------
C-
C-   Created  14-FEB-1995   Lewis Taylor Goss
C-
C----------------------------------------------------------------------
C     *** values to be stored in the result bank HTSM ***
      INTEGER STATUS,NUM_JET
      REAL ETA_LIMIT,CONE_SIZE,SUM_HT,HT_ETA,HT_PHI
C
      COMMON /HTSM_VALUES/ STATUS,NUM_JET,ETA_LIMIT,CONE_SIZE,SUM_HT,
     &  HT_ETA,HT_PHI
