C----------------------------------------------------------------------
C-
C-   Created   4-APR-1994   Zhengzhi Zhang
C-
C----------------------------------------------------------------------
      INTEGER L15C_PASS(L15CT_NUM_MIN:L15CT_NUM_MAX,
     +                  L15TM_NUM_MIN:L15TM_NUM_MAX)
      INTEGER L15C_SPTRG(L15CT_NUM_MIN:L15CT_NUM_MAX,
     +                   L15TM_NUM_MIN:L15TM_NUM_MAX,
     +                   L15ST_NUM_MIN:L15ST_NUM_MAX)
      COMMON /L15C_TERM_INIT/ L15C_PASS,L15C_SPTRG

