C----------------------------------------------------------------------
C-                                                      L2JETS_CONT.INC
C-   Created   6-MAY-1990   Richard V. Astur
C-
C-  Common block L2JETS_CHARS. Character variables for JETS tool
C----------------------------------------------------------------------
      CHARACTER*80 NOWERRMESS           
      CHARACTER*16 NOWSMESS             
      CHARACTER*32 NOWERRID             
      CHARACTER*1  ERR_FLAG             
      COMMON/L2JETS_CHARS/ NOWERRMESS,NOWERRID, ERR_FLAG, NOWSMESS
