C----------------------------------------------------------------------
C-
C-   Created   7-SEP-1989   A. Zylberstejn
C-
C----------------------------------------------------------------------
      COMMON/LTRD/LTRD(2),LTPHY,LTCHA,LTPRO,LTCA1,LTCA2,LTPR1,LTPR2,
     +                    LTMAE,LTMXE,LTMAA,LTMAB,LTMAC,LTPET,LTPE3,
     &                    LTPTR,LTPT3,LTPLE,LTPEC,LTPCA,LTPCB,LTPCC,
     +                    LTMAE1,LTMAE2,LTMXE1,LTMXE2,LTPET1,LTPET2,
     +                    LTPE31,LTPE32,LTPTR1,LTPTR2,LTPT31,LTPT32,
     +                    LTPLE1,LTPLE2,
     +                    LTPEC1,LTPEC2,LTMAA1,LTMAA2,LTMAB1,LTMAB2,
     +                    LTMAC1,LTMAC2,LTPCA1,LTPCA2,LTPCB1,LTPCB2,
     +                    LTPCC1,LTPCC2,LT    ,LTCA  ,LTPR  ,LTMA  ,
     +                    LTPC
      INTEGER LTRD
      INTEGER LTPHY,LTCHA,LTPRO,LTCA1,LTCA2,LTPR1,LTPR2
      INTEGER LTMAE,LTMXE,LTMAA,LTMAB,LTMAC
      INTEGER LTPET,LTPE3,LTPTR,LTPT3,LTPLE,LTPEC,LTPCA,LTPCB,LTPCC
      INTEGER             LTMAE1,LTMAE2,LTMXE1,LTMXE2,LTPET1,LTPET2
      INTEGER             LTPE31,LTPE32,LTPTR1,LTPTR2,LTPT31,LTPT32
      INTEGER             LTPLE1,LTPLE2
      INTEGER             LTPEC1,LTPEC2,LTMAA1,LTMAA2,LTMAB1,LTMAB2
      INTEGER             LTMAC1,LTMAC2,LTPCA1,LTPCA2,LTPCB1,LTPCB2
      INTEGER             LTPCC1,LTPCC2,LT    ,LTCA  ,LTPR  ,LTMA  
      INTEGER             LTPC
