C----------------------------------------------------------------------
C-
C-   LV0CON.INC - basic Level 0 parameters.
C-
C-   Created  30-DEC-1993   Jeffrey Bantly
C-
C----------------------------------------------------------------------
C
      INTEGER NL0_SCALERS
      PARAMETER( NL0_SCALERS = 18 )
C
      INTEGER NL0_CHANS
      PARAMETER( NL0_CHANS = 80 )
C
      INTEGER NL0_CNTRS
      PARAMETER( NL0_CNTRS = 72 )
C
      INTEGER NL0_BUNCHES
      PARAMETER( NL0_BUNCHES = 6 )
