C
      INTEGER NPARTW
      PARAMETER (NPARTW=14)
      COMMON/MCPART/IPTPAR,IPLPAR,IPHPAR,IEPAR,IDPAR,IOPAR,
     1  IXPAR,IYPAR,IZPAR,ICUML,ICUMGM,ICUMRL,ICUMAL,IELE
C
C Common MCPART contains pointers for YBOS group PART 1020
C
      INTEGER IPTPAR  
     1       ,IPLPAR  
     2       ,IPHPAR  
     3       ,IEPAR   
     4       ,IDPAR   
     5       ,IOPAR   
     6       ,IXPAR   
     7       ,IYPAR   
     8       ,IZPAR   
     9       ,ICUML   
     A       ,ICUMGM  
     B       ,ICUMRL  
     C       ,ICUMAL  
     D       ,IELE    
