C----------------------------------------------------------------------
C-
C-   Created  15-FEB-1995   EN  PARAMETERS BASED ON PRESHOWER GEOMETRY NEEDED
C-   FOR DIGITIZATION, BASED ON 90DEGREES STEREO ANGLE DESIGN
C-
C----------------------------------------------------------------------
      COMMON /PRSHPARFORDIG/AXMINRAD,AXMAXRAD,AXNCELLS,AXHALFLENZ,
     +                      S0MINRAD,S0MAXRAD,S0HALFLENZ,S0NCELLS,
     +                      S0S0PHILO,S0S0PHIHI,S0S1PHILO,S0S1PHIHI,
     +                      S1MINRAD,S1MAXRAD,S1HALFLENZ,S1NCELLS,
     +                      S1S0PHILO,S1S0PHIHI,S1S1PHILO,S1S1PHIHI,
     +                      FRACFUDGE,AXSCALE,AXIPED,AXIDIGTHR,
     +                      SSCALE,SPED,SDIGTHR
      REAL AXMINRAD,AXMAXRAD     
                                  
      REAL AXHALFLENZ             
      INTEGER AXNCELLS            
      REAL S0MINRAD,S0MAXRAD     
      REAL S0HALFLENZ             
                                  
      REAL S0S0PHILO,S0S0PHIHI    
                                  
      REAL S0S1PHILO,S0S1PHIHI    
                                  
      INTEGER S0NCELLS            
                                  
                                  
      REAL S1MINRAD,S1MAXRAD     
      REAL S1HALFLENZ             
                                  
      REAL S1S0PHILO,S1S0PHIHI    
                                  
      REAL S1S1PHILO,S1S1PHIHI    
                                  
      INTEGER S1NCELLS            
                                  
                                  
      REAL FRACFUDGE              
                                  
                                  
      REAL AXSCALE,AXIPED,AXIDIGTHR 
                                    
                                    
                                    
      REAL SSCALE,SPED,SDIGTHR 
                                    
                                    
                                    
