      COMMON/PTABLE/CTAU(13),EMASS(14),IMBEG(13),IMEND(13),BR(17),
     1              MODE(3,17)
C
C  This common contains information about all the stable particles
C  except the photon. The order is as given by the particle id's
C  defined for YBOS group PART except KS and KL are in locations
C  12 and 13.
C
      REAL CTAU,       
     1     EMASS,      
     2     BR          
C
      INTEGER IMBEG,   
     1        IMEND,   
     2        MODE     
C
