C----------------------------------------------------------------------
C-
C-   Created  10-APR-1990   C.E.Cretsinger
C-
C----------------------------------------------------------------------
      COMMON /PTBOPT/ INOPIX,IDEMO,IGEOM

      INTEGER INOPIX                    
      INTEGER IDEMO                     
      INTEGER IGEOM                     
                                        
      
