C----------------------------------------------------------------------
C
C ****  Description of the radiator
C
C-   Created                A. Zylberstejn
C-   Updated  12-JUL-1989   A. Zylberstejn
C-
C----------------------------------------------------------------------
C
C   -------COMMON,RADDSC: RADIATOR
C                         --------
      COMMON/RADDSC/NFOIL,XFOIL,XGAP,DXFOIL,DXGAP
      INTEGER NFOIL
      REAL                XFOIL,XGAP,DXFOIL,DXGAP
