C	=====================================================
C	Parameter Definitions for the Data Acquisition System
C	=====================================================
C
C	Modulename:-
C	============
C	DAQ$CMS:REQCTDEF.INC
C
C	Description:-
C	=============
C	This Include File contains the REQ_CT (REQuirements Control Table)
C	entry definitions.
C
C	Creation Date :  8 Mar 1983
C	===========================
C
      Parameter REQ_CT_NEXT   = 0	
      Parameter REQ_CT_PREV   = 1	
      Parameter REQ_CT_ETYP   = 2	
      Parameter REQ_CT_TMSK   = 3	
      Parameter REQ_CT_TMSKB  = 4	
      Parameter REQ_CT_TMSKC  = 5	
      Parameter REQ_CT_TMSKD  = 6	
      Parameter REQ_CT_VMSK   = 7	
      Parameter REQ_CT_VMSKB  = 8	
      Parameter REQ_CT_VMSKC  = 9	
      Parameter REQ_CT_VMSKD  = 10	
      Parameter REQ_CT_RTYP   = 11	
      Parameter REQ_CT_FREQ   = 12	
      Parameter REQ_CT_FRQACT = 13	
      Parameter REQ_CT_FRQSEN = 14	
      Parameter REQ_CT_ACTUAL = 15	
      Parameter REQ_CT_SEEN   = 16	
      Parameter REQ_CT_ACUSER = 17	
      Parameter REQ_CT_SEUSER = 18	
      Parameter REQ_CT_LENG   = 20      
C
      Parameter REQ_TYPE_VIP  = 0	
      Parameter REQ_TYPE_ANDOR= 1	
      Parameter REQ_TYPE_3264 = 2	
      Parameter REQ_TYPE_64128= 3	
      Parameter REQ_TYPE_FREQ = 4	
      Parameter REQ_FREQ_LT   = 4	! Frequency Type '<'
      Parameter REQ_FREQ_GT   = 5	! Frequency Type '>'
C
