C----------------------------------------------------------------------
C-
C-   Created  13-MAY-1993   Tom McKibben II
C-
C-   For wamus/samus examine2 from SMBOOK.FOR
C----------------------------------------------------------------------
      COMMON /RESCLB0/ PEDS0,SIGP0,AFIT0,BFIT0,SIGA0,SIGB0,
     &                 CHISQR0, NONLIN0
      REAL    PEDS0(896), SIGP0(896)
      REAL    AFIT0(896), BFIT0(896), SIGA0(896), SIGB0(896)
      REAL    CHISQR0(896), NONLIN0(896)

