      
      
      
      
      !                     in SCI_STPFILE.DAT, or there'll be a mess.
      
      INTEGER NHDIM  
      PARAMETER (NHDIM=11)
      
      INTEGER HITSEL_XIN, HITSEL_YIN, HITSEL_ZIN, HITSEL_XOUT,
     1        HITSEL_YOUT, HITSEL_ZOUT, HITSEL_TRLN, HITSEL_TRID,
     2        HITSEL_TIN, HITSEL_TOUT, HITSEL_ELOS
  
      PARAMETER(HITSEL_XIN  = 1)   
      PARAMETER(HITSEL_YIN  = 2)   
      PARAMETER(HITSEL_ZIN  = 3)   
      PARAMETER(HITSEL_XOUT = 4)   
      PARAMETER(HITSEL_YOUT = 5)   
      PARAMETER(HITSEL_ZOUT = 6)   
      PARAMETER(HITSEL_TRLN = 7)   
                                     
      PARAMETER(HITSEL_TRID = 8)   
                                     
                                     
                                     
                                     
      PARAMETER(HITSEL_TIN  = 9)   
      PARAMETER(HITSEL_TOUT = 10)  
      PARAMETER(HITSEL_ELOS = 11)  
