C DEC/CMS REPLACEMENT HISTORY, Element RMINMAX.INC
C *1    13-FEB-1990 14:59:30 JONCKHEERE "Stephen Kahn: MASSLESS GAPS AND EDGE ELEMENTS"
C DEC/CMS REPLACEMENT HISTORY, Element RMINMAX.INC
C----------------------------------------------------------------------
C-
C-   Created  28-OCT-1989   Stephen Kahn
C-
C----------------------------------------------------------------------
      COMMON /RMINMAX/ JCLGA, JETA
      INTEGER JCLGA, JETA
