C----------------------------------------------------------------------
C-
C-      /SCCCH_FRONTPLATE/
C-
C-      CCCH 'Front plate volume' geometrical properties
C-
C-   Created   10-DEC-1988   Stuart Fuess   
C-
C----------------------------------------------------------------------
      REAL CCCH_FRONTPLATE_LENGTH         
      REAL CCCH_FRONTPLATE_WIDTH          
      REAL CCCH_FRONTPLATE_THICKNESS      
      REAL CCCH_FRONTPLATE_VOLUME         
      COMMON /SCCCH_FRONTPLATE/ CCCH_FRONTPLATE_LENGTH,
     &                         CCCH_FRONTPLATE_WIDTH,
     &                         CCCH_FRONTPLATE_THICKNESS,
     &                         CCCH_FRONTPLATE_VOLUME
