C----------------------------------------------------------------------
C-
C-      /SCCCH_BACKPLATE/
C-
C-      CCCH 'Back plate volume' geometrical properties
C-
C-   Created   28-DEC-1988   Stuart Fuess   
C-
C----------------------------------------------------------------------
      REAL CCCH_BACKPLATE_LENGTH         
      REAL CCCH_BACKPLATE_WIDTH          
      REAL CCCH_BACKPLATE_THICKNESS      
      REAL CCCH_BACKPLATE_VOLUME         
      COMMON /SCCCH_BACKPLATE/ CCCH_BACKPLATE_LENGTH,
     &                        CCCH_BACKPLATE_WIDTH,
     &                        CCCH_BACKPLATE_THICKNESS,
     &                        CCCH_BACKPLATE_VOLUME
