C----------------------------------------------------------------------
C-
C-      /SCCEM_FRONTPLATE/
C-
C-      CCEM 'Front plate volume' geometrical properties
C-
C-   Created   10-DEC-1988   Stuart Fuess   
C-
C----------------------------------------------------------------------
      REAL CCEM_FRONTPLATE_LENGTH         
      REAL CCEM_FRONTPLATE_WIDTH          
      REAL CCEM_FRONTPLATE_THICKNESS      
      REAL CCEM_FRONTPLATE_VOLUME         
      COMMON /SCCEM_FRONTPLATE/ CCEM_FRONTPLATE_LENGTH,
     &                         CCEM_FRONTPLATE_WIDTH,
     &                         CCEM_FRONTPLATE_THICKNESS,
     &                         CCEM_FRONTPLATE_VOLUME
