C----------------------------------------------------------------------
C-
C-      /SCCEM_BACKPLATE/
C-
C-      CCEM 'Back plate volume' geometrical properties
C-
C-   Created   28-DEC-1988   Stuart Fuess   
C-
C----------------------------------------------------------------------
      REAL CCEM_BACKPLATE_LENGTH         
      REAL CCEM_BACKPLATE_WIDTH          
      REAL CCEM_BACKPLATE_THICKNESS      
      REAL CCEM_BACKPLATE_VOLUME         
      COMMON /SCCEM_BACKPLATE/ CCEM_BACKPLATE_LENGTH,
     &                        CCEM_BACKPLATE_WIDTH,
     &                        CCEM_BACKPLATE_THICKNESS,
     &                        CCEM_BACKPLATE_VOLUME
