C----------------------------------------------------------------------
C-
C-      /SCCFH_ENDPLATE/
C-
C-      CCFH 'Endplate volume' geometrical properties
C-
C-   Created   7-NOV-1988   Stuart Fuess
C-
C----------------------------------------------------------------------
      REAL CCFH_ENDPLATE_INNER_WIDTH    
      REAL CCFH_ENDPLATE_OUTER_WIDTH    
      REAL CCFH_ENDPLATE_HEIGHT         
      REAL CCFH_ENDPLATE_THICKNESS      
      REAL CCFH_ENDPLATE_POSITION       
      REAL CCFH_ENDPLATE_VOLUME         
      INTEGER CCFH_ENDPLATE_MATERIAL    
      COMMON /SCCFH_ENDPLATE/ CCFH_ENDPLATE_INNER_WIDTH,
     &                       CCFH_ENDPLATE_OUTER_WIDTH,
     &                       CCFH_ENDPLATE_HEIGHT,
     &                       CCFH_ENDPLATE_THICKNESS,
     &                       CCFH_ENDPLATE_POSITION,
     &                       CCFH_ENDPLATE_VOLUME,
     &                       CCFH_ENDPLATE_MATERIAL
