C----------------------------------------------------------------------
C-
C-      /SCCFH_FRONTPLATE/
C-
C-      CCFH 'Front plate volume' geometrical properties
C-
C-   Created   06-JAN-1989   Stuart Fuess   
C-
C----------------------------------------------------------------------
      REAL CCFH_FRONTPLATE_LENGTH         
      REAL CCFH_FRONTPLATE_WIDTH          
      REAL CCFH_FRONTPLATE_THICKNESS      
      REAL CCFH_FRONTPLATE_VOLUME         
      COMMON /SCCFH_FRONTPLATE/ CCFH_FRONTPLATE_LENGTH,
     &                         CCFH_FRONTPLATE_WIDTH,
     &                         CCFH_FRONTPLATE_THICKNESS,
     &                         CCFH_FRONTPLATE_VOLUME
