C----------------------------------------------------------------------
C-
C-      /SCCFH_BACKPLATE/
C-
C-      CCFH 'Back plate volume' geometrical properties
C-
C-   Created   06-JAN-1989   Stuart Fuess   
C-
C----------------------------------------------------------------------
      REAL CCFH_BACKPLATE_LENGTH         
      REAL CCFH_BACKPLATE_WIDTH          
      REAL CCFH_BACKPLATE_THICKNESS      
      REAL CCFH_BACKPLATE_VOLUME         
      COMMON /SCCFH_BACKPLATE/ CCFH_BACKPLATE_LENGTH,
     &                        CCFH_BACKPLATE_WIDTH,
     &                        CCFH_BACKPLATE_THICKNESS,
     &                        CCFH_BACKPLATE_VOLUME
