C----------------------------------------------------------------------
C-
C-   Created  27-FEB-1995   EN
C-
C----------------------------------------------------------------------
      COMMON /SHITCL/ SHITCL,SNHITCL,SPTHLGCL,PHIBIN
      INTEGER SNCLMX        
      PARAMETER(SNCLMX=100)
      INTEGER SHITCL(SNCLMX)
      INTEGER SNHITCL       
      REAL SPTHLGCL(SNCLMX)  
                            
      INTEGER PHIBIN(SNCLMX) 
