C----------------------------------------------------------------------
C-
C-   Created  24-APR-1992   Gregory L. Landsberg
C-
C----------------------------------------------------------------------
      Integer           T0DLNT2,   LT0TH,LT0TD,LT0TZ,LT0HT,LT0DH,LT0FH,
     &                             LT0RW
      Common /T0DLNT2/  T0DLNT2(2),LT0TH,LT0TD,LT0TZ,LT0HT,LT0DH,LT0FH,
     &                             LT0RW
