C----------------------------------------------------------------------
C-
C-   T0DREC is the T0 detector library common with reco parametersc
C-
C-   Created  17-MAR-1993   Greg Landsberg   
C-   
C----------------------------------------------------------------------
      Logical           L_T0D_REC, L_T0D_FUL, N_T0D_EVT, L_T0D_ZTRK,
     &                  L_Hist
      Common /T0DREC/   L_T0D_REC, L_T0D_FUL, N_T0D_EVT, L_T0D_ZTRK,
     &                  L_Hist
