C----------------------------------------------------------------------
C-
C-   Created  25-AUG-1995   A. ZYLBERSTEJN
C-   Modified 22-FEB-1996   Y. DUCROS
C----------------------------------------------------------------------
      COMMON /TRDLIK/ like_layer(3),EPSLP,LIK1PI ,LIK1EL,LIK2PI ,LIK2EL,
     &  LIK_ION_PI, LIK_ION_EL, DENS_ION_3CH,DENS_3CH,DENS_ION_2CH,
     &  DENS_2CH
      REAL LIK1PI ,LIK1EL,LIK2PI ,LIK2EL, LIK_ION_PI,LIK_ION_EL
      REAL LIKE_LAYER,EPSLP,DENS_ION_3CH,DENS_3CH,DENS_ION_2CH
      REAL DENS_2CH
