C----------------------------------------------------------------------
C     COMMON /TRDLNK/ contains the TRD chamber links for hits under TRDH
C-
C-   Created                A. Zylberstejn
C-   Updated  25-NOV-1988   A. Zylberstejn  :add LCDD4 .
C-                                        Name changed from TRDHLN
C-
C----------------------------------------------------------------------
      COMMON /TRDLNK/ TRDLNK(2), LTRDH,LTLYR(3),LCDD4
      INTEGER         TRDLNK  , LTRDH,LTLYR   ,LCDD4
