C----------------------------------------------------------------------
C   -------COMMON/TRINFO/  General TRD informations
C-
C-   Created  19-JUN-1989   A. Zylberstejn
C-
C----------------------------------------------------------------------
      COMMON/TRINFO/NOPUN,NOINEF,SHIFTE,ECLMIN,TRHIST,PRTRD,TRDOUT
      INTEGER     NOPUN,NOINEF                             ,TRDOUT
      REAL                     SHIFTE,ECLMIN  ,       PRTRD
      LOGICAL                                  TRHIST
