C
C=================================================================
C
C COMMON/UPDATE/ contains quantities that must be updated by the
C dispatching subroutines each time they are called by INTRPT
C
      REAL CUMA,	
     4	CUML,		
     5	CUMR,		
     6	CUMI,		
     8	ELE		
C
      LOGICAL QBEFOR    
C
      COMMON/UPDATE/CUMA,CUML,CUMR,CUMI,ELE,QBEFOR
C
C====================================================================
C
