C DEC/CMS REPLACEMENT HISTORY, Element VTXPSH.INC
C *1    17-JUN-1992 13:40:09 WYATT "New common for new pulse shape code"
C DEC/CMS REPLACEMENT HISTORY, Element VTXPSH.INC
C----------------------------------------------------------------------
C-
C-   Created   6-MAY-1992   Alexandre Zinchenko
C-
C----------------------------------------------------------------------
      COMMON /VTXPSH/ IFADCC, INHITS, NMEAN(100), AREA1(100)
      INTEGER IFADCC, INHITS, NMEAN
      REAL AREA1

