C----------------------------------------------------------------------
C-
C-      /WRITE_UNIT/
C-
C-      CC Geometry Logical Unit Assignments
C-
C-   Created   7-DEC-1988   Stuart Fuess
C-
C----------------------------------------------------------------------
      INTEGER OUT_VOL                
      INTEGER OUT_SET                
      COMMON /WRITE_UNIT/ OUT_VOL,
     &                    OUT_SET
