C----------------------------------------------------------------------
C-
C-   Created  24-APR-1992   Gregory L. Landsberg
C-
C----------------------------------------------------------------------
      Integer           ZCDLNT2,   LZDTH,LZDTD,LZDTZ,LZDHT,LZDDH,LZDFH,
     &                             LZDRW, LHITS
      Common /ZCDLN2/   ZCDLNT2(2),LZDTH,LZDTD,LZDTZ,LZDHT,LZDDH,LZDFH,
     &                             LZDRW, LHITS
