C----------------------------------------------------------------------
C-
C-   ZCDREC is the ZCD detector library common with reco parametersc
C-
C-   Created  17-MAR-1993   Greg Landsberg   
C-   
C----------------------------------------------------------------------
      Logical           L_ZCD_REC, L_ZCD_FUL, N_ZCD_EVT, L_ZCD_ZTRK,
     &                  L_Hist
      Common /ZCDREC/   L_ZCD_REC, L_ZCD_FUL, N_ZCD_EVT, L_ZCD_ZTRK,
     &                  L_Hist
