C----------------------------------------------------------------------
C-  a temporary link area used during the global fitting for the 
C-  ZTRK (Central Detector tracks) in a road
C-
C-   Created  19-JUN-1990   Qizhong Li-Demarteau
C-
C----------------------------------------------------------------------
      COMMON /ZFTLNK/ ZFTLNK(2), LZTRK, LZFIT, LVTXT, LDTRK, LFTRK
      INTEGER LZTRK, LZFIT, LVTXT, LDTRK, LFTRK, ZFTLNK

