
C----------------------------------------------------------------------
C-  Zero-suppression simulation parameters for VTX, CDC, FDC
C-
C-   Created  15-JUN-1989   Qizhong Li-Demarteau
C-
C----------------------------------------------------------------------
      COMMON /ZZEROP/ BINTH1(0:2), BINTH2(0:2), BINTH3(0:2),
     &                  BINTH4(0:2),
     &                  DIFTH1(0:2), DIFTH2(0:2), DIFTH3(0:2) 
      INTEGER BINTH1, BINTH2, BINTH3, BINTH4, DIFTH1, DIFTH2, DIFTH3
