CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VLEVEL2()
      VLEVEL2 = ' LEVEL2'//
     X                   '  OFFICIAL V1.06'//
     X                   ' 25-OCT-1994 20:55:30.24'
      Return
      End
