      SUBROUTINE GAP_NTUP_BOOK
C-----------------------------------------------------------------------
C-
C-   Purpose and Methods : Books gap words called by
C-   QCD_NTUP_FILL   these words are filled in  GAP_NTUP_FILL
C-   Created 02-SEP-1995  Andrew G. Brandt
C-   Created 13-NOV-1995  Andrew G. Brandt add CATE words
C-   Updated  24-JAN-1996 Bob Hirosky   keep gap_head everywhere
C-   Updated  25-JAN-1996 Bob Hirosky   ADD NEW SLICE WORDS
C-   Updated  29-FEB-1996 Andrew G. Brandt Add GAP_SAMULT
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:GAP_CATD_INFO.INC/LIST'
      INCLUDE 'D0$INC:GAP_TRACK.INC/LIST'
      INCLUDE 'D0$INC:GAP_TRACK_FDC.INC/LIST'
      INCLUDE 'D0$INC:GAP_FSEG.INC/LIST'
      INCLUDE 'D0$INC:L0HITS.INC/LIST'
      INCLUDE 'D0$INC:GAP_SAMULT.INC/LIST'
C
      CALL HBNAME(1, 'GAP_HEAD',DELTA_ETA_C,GAP_CATD_HEAD_TAG)
      IF(DO_NEMEVT) THEN
        CALL HBNAME(1, 'GAP_EVT',NEM_EVT,GAP_CATD_EVT_TAG)
      ENDIF
      IF(DO_EM_IETA_GAP) THEN
        CALL HBNAME(1, 'GAP_IETA',NEM_IETA_GAPS,GAP_CATD_IETA_TAG)
      ENDIF
      IF(DO_PACKED_EM) THEN
        CALL HBNAME(1, 'GAP_EM',NPKEM,GAP_CATD_EM_TAG)
      ENDIF
      IF(DO_PACKED_EMB) THEN
        CALL HBNAME(1, 'GAP_EMB',NPKEMB,GAP_CATD_EMB_TAG)
      ENDIF
      IF(DO_EM_ETABIN) THEN
        CALL HBNAME(1, 'GAP_BIN',NBIN,GAP_CATD_ETABIN_TAG)
      END IF
      IF(DO_TRACK) THEN
        CALL HBNAME(1,'TRACK',NTRACKS,GAP_TRACK_TAG)
      END IF
      IF(DO_FDCTRK) THEN
        CALL HBNAME(1,'FTRACK',NTK_FDC,GAP_TRACK_FDC_TAG)
      END IF
      IF(DO_FDCSEG) THEN
        CALL HBNAME(1,'FDCSEG',NFSGIN,GAP_FSEG_TAG)
      END IF
      IF(DO_SAMULT) THEN
        CALL HBNAME(1,'SAMULT',NHITS_SAMUS,GAP_SAMULT_TAG)
      END IF
      IF(DO_L0HITS) THEN
        CALL HBNAME(1,'LEVEL0',NHITS_SCN,CH_L0)
      END IF
C
C Don't fill these for CATDE=2
C
      IF(CATDE.LT.2) THEN
        IF(DO_EM_CATD) THEN
          CALL HBNAME(1, 'GAP_NEM',NEM_ET,GAP_CATD_NEM_TAG)
        ENDIF
        IF(DO_HD_CATD) THEN
          CALL HBNAME(1, 'GAP_NHD',NHD_ET,GAP_CATD_NHD_TAG)
        ENDIF
        IF(DO_EM_CONE) THEN
          CALL HBNAME(1, 'GAP_CONE',NEM_CONE_DR,GAP_CATD_CONE_TAG)
        ENDIF
        IF(DO_EM_DELTA_R) THEN
          CALL HBNAME(1, 'GAP_DR',NEM_DELTA_R_DR,GAP_CATD_DR_TAG)
        ENDIF
        IF(DO_EM_IETA_IN_GAP) THEN
          CALL HBNAME(1, 'GAP_IETA',NEM_IETAG,GAP_CATD_IETAG_TAG)
        ENDIF
        IF(DO_REMOVE_JETS_IN_GAP) THEN
          CALL HBNAME(1, 'GAP_REMJ',NEM_REMOVE_DR,GAP_CATD_REMJ_TAG)
        ENDIF
        IF(DO_PACKED_EMJ) THEN
          CALL HBNAME(1, 'GAP_EMJ',NPKEMJ,GAP_CATD_EMJ_TAG)
        ENDIF
      ENDIF
C
C New CATE blocks
C
      IF(CATDE.GT.0) THEN
        CALL HBNAME(1, 'GAPE_EVT',NEM_POS,GAP_CATE_EVT_TAG)
        IF(DO_PACKED_NEG) THEN
          CALL HBNAME(1, 'GAPE_NEG',NPKNEG,GAP_CATE_NEG_TAG)
        END IF
        IF(DO_EM_MORBIN) THEN
          CALL HBNAME(1, 'GAPE_EMM',NMORB,GAP_CATE_EMMOR_TAG)
        END IF
        CALL HBNAME(1, 'GAPE_HD',NHD_POS,GAP_CATE_HD_TAG)
        IF(DO_HD_ETABIN) THEN
          CALL HBNAME(1, 'GAPE_HDB',NHDBIN,GAP_CATE_HDBIN_TAG)
        END IF
        IF(DO_HD_MORBIN) THEN
          CALL HBNAME(1, 'GAPE_HDM',NHDMOR,GAP_CATE_HDMOR_TAG)
        END IF
        IF(DO_EMNEG_ETABIN) THEN
          CALL HBNAME(1, 'GAP_NGBN',NNEGB,GAP_CATE_EMNEGBIN_TAG)
        ENDIF
        IF(DO_EMNEG_MORBIN) THEN
          CALL HBNAME(1, 'GAP_NGMR',NNEGMOR,GAP_CATE_EMNEGMOR_TAG)
        ENDIF
        IF(DO_HDNEG_ETABIN) THEN
          CALL HBNAME(1, 'GAP_HNGB',NHDNEGB,GAP_CATE_HDNEGBIN_TAG)
        ENDIF
        IF(DO_HDNEG_MORBIN) THEN
          CALL HBNAME(1, 'GAP_HNGM',NHDNEGMOR,GAP_CATE_HDNEGMOR_TAG)
        ENDIF
        IF(DO_ENERGY_SLICES) THEN
          CALL HBNAME(1, 'GAP_SLIC',E_NEG,GAP_CATE_ESLICE_TAG)
          CALL HBNAME(1, 'GAP_SLIC',H_NEG,GAP_CATE_HSLICE_TAG)
        ENDIF
      END IF
C
  999 RETURN
      END
