      SUBROUTINE GAP_GET_RCP
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : Get Rap gap RCP information
C-
C-   Inputs  :
C-   Outputs :
C-   Controls:
C-
C-   Created   7-FEB-1994   Brent J. May
C-   Updated  07-NOV-1994  Andrew G. Brandt updated for CW
C-   Updated  13-NOV-1995  Andrew G. Brandt add CATE switches
C-   Updated  25-JAN-1996  Bob Hirosky  ADD NEW SLICE WORDS, NSAMUS HITS
C-   Updated  02-MAR-1996  Andrew G. Brandt add DO_FDCTRK
C-   Updated  10-MAR-1996  Andrew G. Brandt add DO_FDCSEG
C-   Updated  14-MAR-1996  Andrew G. Brandt allow 1000 packed words
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:GAP_CATD_INFO.INC'
      INTEGER L,IER
C----------------------------------------------------------------------
      CALL INRCP('GAP_NTUP_RCP',IER)
      CALL EZPICK('GAP_NTUP_RCP')
      CALL EZERR ( IER )
      IF(IER.NE.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','GAP_NTUP_RCP',
     &      ' GAP_NTUP_RCP file does not have a GAP_NTUP bank.','W')
      ENDIF
C
C
      CALL EZGET('DO_EM_CATD',DO_EM_CATD,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_EM_CATD',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_NEMEVT',DO_NEMEVT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_NEMEVT',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET_VALUE_TYPE('EM_ET_THRESHOLDS',
     &                        EM_ET_THRESHOLDS,TYPE,NEM_ET,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','EM_ET_THRESHOLDS',
     &      'NO VARIABLE FOUND','W')
      END IF
      IF (NEM_ET.GT.20) THEN
        NEM_ET = 20
        CALL ERRMSG('GAP_NTUP_RCP','EM_ET_THRESHOLDS',
     &      'Too many values','W')
      ENDIF
C
      CALL EZGET('DO_HD_CATD',DO_HD_CATD,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_HD_CATD',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET_VALUE_TYPE('HD_ET_THRESHOLDS',
     &                        HD_ET_THRESHOLDS,TYPE,NHD_ET,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','HD_ET_THRESHOLDS',
     &      'NO VARIABLE FOUND','W')
      END IF
      IF (NHD_ET.GT.20) THEN
        NHD_ET = 20
        CALL ERRMSG('GAP_NTUP_RCP','HD_ET_THRESHOLDS',
     &      'Too many values','W')
      ENDIF
C
      CALL EZGET('DO_PACKED_EM',DO_PACKED_EM,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_PACKED_EM',
     &      'NO VARIABLE FOUND','W')
      END IF
      CALL EZGET('NUM_PACKED_EM',NUM_PACKED_EM,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','NUM_PACKED_EM',
     &      'NO VARIABLE FOUND','W')
        NUM_PACKED_EM=0
      ELSE IF ( NUM_PACKED_EM.GT.1000) THEN
        CALL ERRMSG('GAP_NTUP_RCP','NUM_PACKED_EM',
     &      'NUM_PACKED_EM set to MAX of 1000','W')
        NUM_PACKED_EM=1000
      END IF
C
      CALL EZGET('DO_PACKED_EMJ',DO_PACKED_EMJ,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_PACKED_EMJ',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('NUM_PACKED_EMJ',NUM_PACKED_EMJ,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','NUM_PACKED_EMJ',
     &      'NO VARIABLE FOUND','W')
        NUM_PACKED_EMJ=0
      ELSE IF ( NUM_PACKED_EMJ.GT.1000) THEN
        CALL ERRMSG('GAP_NTUP_RCP','NUM_PACKED_EMJ',
     &      'NUM_PACKED_EMJ set to MAX of 1000','W')
        NUM_PACKED_EMJ=1000
      END IF
C
      CALL EZGET('DO_PACKED_EMB',DO_PACKED_EMB,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_PACKED_EMB',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('NUM_PACKED_EMB',NUM_PACKED_EMB,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','NUM_PACKED_EMB',
     &      'NO VARIABLE FOUND','W')
        NUM_PACKED_EMB=0
      ELSE IF ( NUM_PACKED_EMB.GT.1000) THEN
        CALL ERRMSG('GAP_NTUP_RCP','NUM_PACKED_EMB',
     &      'NUM_PACKED_EMB set to MAX of 1000','W')
        NUM_PACKED_EMB=1000
      END IF
C
      CALL EZGET('DO_EM_CONE',DO_EM_CONE,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_EM_CONE',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET_VALUE_TYPE('EM_CONE_DR',EM_CONE_DR,
     &                      TYPE,NEM_CONE_DR,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','EM_CONE_DR',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_EM_DELTA_R',DO_EM_DELTA_R,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_EM_DELTA_R',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET_VALUE_TYPE('EM_DELTA_R_DR',EM_DELTA_R_DR,
     &                      TYPE,NEM_DELTA_R_DR,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','EM_DELTA_R_DR',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_EM_IETA_GAP',DO_EM_IETA_GAP,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_EM_IETA_GAP',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_EM_IETA_IN_GAP',DO_EM_IETA_IN_GAP,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_EM_IETA_IN_GAP',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET_VALUE_TYPE('EM_IETA_GAPS',EM_IETA_GAPS,TYPE,
     &                       NEM_IETA_GAPS,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','EM_IETA_GAPS',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_REMOVE_JETS_IN_GAP',DO_REMOVE_JETS_IN_GAP,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_REMOVE_JETS_IN_GAP',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET_VALUE_TYPE('REMOVE_JET_RADIUS',REMOVE_JET_RADIUS,
     &                       TYPE,NEM_REMOVE_DR,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','REMOVE_JET_RADIUS',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('REMOVE_JET_ET',REMOVE_JET_ET,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','REMOVE_JET_ET',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('GAP_CONE_RADIUS',GAP_CONE_RADIUS,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','GAP_CONE_RADIUS',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_HOT_KILL',DO_HOT_KILL,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_HOT_KILL',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_FIXED_LIST',DO_FIXED_LIST,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_FIXED_LIST',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_BY_RUN',DO_BY_RUN,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_BY_RUN',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('HOT_SIGMA_CUT',HOT_SIGMA_CUT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','HOT_SIGMA_CUT',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('LOW_STATS_CUT',LOCUT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','LOW_STATS_CUT',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('HIGH_STATS_CUT',HICUT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','HIGH_STATS_CUT',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGETS('HOT_RUN_FILE',1,HOT_RUN_FILE,L,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','HOT_RUN_FILE',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGETS('RUN_LIST_FILE',1,RUN_LIST_FILE,L,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','RUN_LIST_FILE',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('GAP_NJETS_CUT',GAP_NJETS_CUT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','GAP_NJETS_CUT',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DELTA_ETA_C_CUT',DELTA_ETA_C_CUT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DELTA_ETA_C_CUT',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('ABS_ETA_BOOST_CUT',ABS_ETA_BOOST_CUT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','ABS_ETA_BOOST_CUT',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('USER_CUT',USER_CUT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','USER_CUT',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_WRITE_RUN_EVT',DO_WRITE_RUN_EVT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_WRITE_RUN_EVT',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_TRACK',DO_TRACK,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_TRACK',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_L0HITS',DO_L0HITS,IER)
      IF ( IER.LT.0) THEN
        DO_L0HITS=.FALSE.
        CALL ERRMSG('GAP_NTUP_RCP','DO_L0HITS',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('DO_EM_ETABIN',DO_EM_ETABIN,IER)
      IF ( IER.LT.0) THEN
        DO_EM_ETABIN=.FALSE.
        CALL ERRMSG('GAP_NTUP_RCP','DO_EM_ETABIN',
     &      'NO VARIABLE FOUND','W')
      END IF
C
      CALL EZGET('MBIETA',MBIETA,IER)
      IF ( IER.LT.0) THEN
        MBIETA=20
        CALL ERRMSG('GAP_NTUP_RCP','MBIETA',
     &      'NO VARIABLE FOUND DEFAULT 20','W')
      END IF
C
      CALL EZGET('CATDE',CATDE,IER)
      IF ( IER.LT.0) THEN
        CATDE=0
        CALL ERRMSG('GAP_NTUP_RCP','CATDE',
     &      'NO VARIABLE FOUND DEFAULT 0 (CATD)','W')
      END IF
C
      CALL EZGET_VALUE_TYPE('EM_POS_THRESHOLDS',
     &                        EM_POS_THRESHOLDS,TYPE,NEM_POS,IER)
      IF ( IER.LT.0) THEN
        IF(CATDE.EQ.0) THEN
          CALL ERRMSG('GAP_NTUP_RCP','EM_POS_THRESHOLDS',
     &        'NO VARIABLE FOUND--NEEDED FOR CATE NOT CATD','W')
        ELSE
          CALL ERRMSG('GAP_NTUP_RCP','EM_POS_THRESHOLDS',
     &        'NO VARIABLE FOUND--NEEDED FOR CATE','F')
        END IF
      END IF
      IF ( NEM_POS.GT.5) THEN
        CALL ERRMSG('GAP_NTUP_RCP','EM_POS_THRESHOLDS',
     &      'Too many EM_POS_THRESHOLDS--set to 5','W')
        NEM_POS=5
      END IF
C
      CALL EZGET_VALUE_TYPE('EM_NEG_THRESHOLDS',
     &                        EM_NEG_THRESHOLDS,TYPE,NEM_NEG,IER)
      IF ( IER.LT.0) THEN
        IF(CATDE.EQ.0) THEN
          CALL ERRMSG('GAP_NTUP_RCP','EM_NEG_THRESHOLDS',
     &        'NO VARIABLE FOUND--NEEDED FOR CATE NOT CATD','W')
        ELSE
          CALL ERRMSG('GAP_NTUP_RCP','EM_NEG_THRESHOLDS',
     &        'NO VARIABLE FOUND--NEEDED FOR CATE','F')
        END IF
      END IF
      IF ( NEM_NEG.GT.5) THEN
        CALL ERRMSG('GAP_NTUP_RCP','EM_NEG_THRESHOLDS',
     &      'Too many EM_NEG_THRESHOLDS--set to 5','W')
        NEM_NEG=5
      END IF
C
      CALL EZGET_VALUE_TYPE('HD_POS_THRESHOLDS',
     &                        HD_POS_THRESHOLDS,TYPE,NHD_POS,IER)
      IF ( IER.LT.0) THEN
        IF(CATDE.EQ.0) THEN
          CALL ERRMSG('GAP_NTUP_RCP','HD_POS_THRESHOLDS',
     &        'NO VARIABLE FOUND--NEEDED FOR CATE NOT CATD','W')
        ELSE
          CALL ERRMSG('GAP_NTUP_RCP','HD_POS_THRESHOLDS',
     &        'NO VARIABLE FOUND--NEEDED FOR CATE','F')
        END IF
      END IF
      IF ( NHD_POS.GT.5) THEN
        CALL ERRMSG('GAP_NTUP_RCP','HD_POS_THRESHOLDS',
     &      'Too many HD_POS_THRESHOLDS--set to 5','W')
        NHD_POS=5
      END IF
C
      CALL EZGET_VALUE_TYPE('HD_NEG_THRESHOLDS',
     &                        HD_NEG_THRESHOLDS,TYPE,NHD_NEG,IER)
      IF ( IER.LT.0) THEN
        IF(CATDE.EQ.0) THEN
          CALL ERRMSG('GAP_NTUP_RCP','HD_NEG_THRESHOLDS',
     &        'NO VARIABLE FOUND--NEEDED FOR CATE NOT CATD','W')
        ELSE
          CALL ERRMSG('GAP_NTUP_RCP','HD_NEG_THRESHOLDS',
     &        'NO VARIABLE FOUND--NEEDED FOR CATE','F')
        END IF
      END IF
      IF ( NHD_NEG.GT.5) THEN
        CALL ERRMSG('GAP_NTUP_RCP','HD_NEG_THRESHOLDS',
     &      'Too many HD_NEG_THRESHOLDS--set to 5','W')
        NHD_NEG=5
      END IF
C
      CALL EZGET('DO_PACKED_NEG',DO_PACKED_NEG,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_PACKED_NEG',
     &      'NO VARIABLE FOUND--USED FOR CATE','W')
      END IF
C
      CALL EZGET('NUM_PACKED_NEG',NUM_PACKED_NEG,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','NUM_PACKED_NEG',
     &      'NO VARIABLE FOUND','W')
        NUM_PACKED_NEG=0
      ELSE IF ( NUM_PACKED_NEG.GT.200) THEN
        CALL ERRMSG('GAP_NTUP_RCP','NUM_PACKED_NEG',
     &      'NUM_PACKED_NEG set to MAX of 200','W')
        NUM_PACKED_NEG=200
      END IF
C
      CALL EZGET('DO_EM_MORBIN',DO_EM_MORBIN,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_EM_MORBIN',
     &      'NO VARIABLE FOUND--USED FOR CATE','W')
      ELSEIF(DO_EM_MORBIN.AND.NEM_POS.LT.3) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_EM_MORBIN',
     &      'NOT ENOUGH MORE BINS CHECK POS THRESH ','W')
        DO_EM_MORBIN=.FALSE.
      END IF
C
      CALL EZGET('DO_EMNEG_ETABIN',DO_EMNEG_ETABIN,IER)
      IF ( IER.LT.0) THEN
        DO_EMNEG_ETABIN=.FALSE.
        CALL ERRMSG('GAP_NTUP_RCP','DO_EMNEG_ETABIN',
     &      'NO VARIABLE FOUND--USED FOR CATE','W')
      END IF
C
      CALL EZGET('DO_EMNEG_MORBIN',DO_EMNEG_MORBIN,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_EMNEG_MORBIN',
     &      'NO VARIABLE FOUND--USED FOR CATE','W')
      ELSEIF(DO_EMNEG_MORBIN.AND.NEM_NEG.LT.3) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_EMNEG_MORBIN',
     &      'NOT ENOUGH MORE BINS CHECK POS THRESH ','W')
        DO_EMNEG_MORBIN=.FALSE.
      END IF
C
      CALL EZGET('DO_HD_ETABIN',DO_HD_ETABIN,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_HD_ETABIN',
     &      'NO VARIABLE FOUND--USED FOR CATE','W')
        DO_HD_ETABIN = .FALSE.
      END IF
C
      CALL EZGET('DO_HD_MORBIN',DO_HD_MORBIN,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_HD_MORBIN',
     &      'NO VARIABLE FOUND--USED FOR CATE','W')
      ELSEIF(DO_HD_MORBIN.AND.NHD_POS.LT.3) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_HD_MORBIN',
     &      'NOT ENOUGH MORE BINS CHECK POS THRESH ','W')
        DO_HD_MORBIN=.FALSE.
      END IF
C
      CALL EZGET('DO_HDNEG_ETABIN',DO_HDNEG_ETABIN,IER)
      IF ( IER.LT.0) THEN
        DO_HDNEG_ETABIN=.FALSE.
        CALL ERRMSG('GAP_NTUP_RCP','DO_HDNEG_ETABIN',
     &      'NO VARIABLE FOUND--USED FOR CATE','W')
      END IF
C
      CALL EZGET('DO_HDNEG_MORBIN',DO_HDNEG_MORBIN,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_HDNEG_MORBIN',
     &      'NO VARIABLE FOUND--USED FOR CATE','W')
      ELSEIF(DO_HDNEG_MORBIN.AND.NHD_NEG.LT.3) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_HDNEG_MORBIN',
     &      'NOT ENOUGH MORE BINS CHECK POS THRESH ','W')
        DO_HDNEG_MORBIN=.FALSE.
      END IF
C
      CALL EZGET('DO_ENERGY_SLICES',DO_ENERGY_SLICES,IER)
      IF ( IER.LT.0) THEN
        DO_ENERGY_SLICES=.FALSE.
        CALL ERRMSG('GAP_NTUP_RCP','DO_ENERGY_SLICES',
     &      'NO VARIABLE FOUND--USED FOR CATE','W')
      END IF
C
      CALL EZGET('DO_SAMULT',DO_SAMULT,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_SAMULT',
     &      'NO VARIABLE FOUND','W')
        DO_SAMULT = .FALSE.
      END IF
C
      CALL EZGET('DO_FDCTRK',DO_FDCTRK,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_FDCTRK',
     &      'NO VARIABLE FOUND','W')
        DO_FDCTRK = .FALSE.
      END IF
C
      CALL EZGET('DO_FDCSEG',DO_FDCSEG,IER)
      IF ( IER.LT.0) THEN
        CALL ERRMSG('GAP_NTUP_RCP','DO_FDCSEG',
     &      'NO VARIABLE FOUND','W')
        DO_FDCSEG = .FALSE.
      END IF
C
  999 RETURN
      END
