.FACILITY       D0CHECK, 1790 /PREFIX=D0CK_

.SEVERITY       SUCCESS
CONFORMS        <!AS Conforms TO D0 standards> /FAO=1

.SEVERITY       INFORMATION
COMPILE         <Compiling !AS> /FAO=1
CHECKING        <Checking compiler listing !AS> /FAO=1
BADEXTN         <Wrong file extention : !AS> /FAO=1
VIOLATES        <!AS VIOLATES D0 standards, check listing file !AS> /FAO=2
NOTFOUND        <listing: !AS> /FAO=1
FAILED          <One or more files failed D0 standard test>

.END
