CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VLEVEL0()
      VLEVEL0 = ' LEVEL0'//
     X                   '  TEST V0.04_02'//
     X                   '  7-MAY-1996 16:23:53.37'
      Return
      End
