#! /bin/csh -f
#
# Created:   John D. Hobbs   7-JAN-1994
#
 
# Translate the d0library entry-point file into the unix version
 
if( -f unix_entry_point.lis ) rm unix_entry_point.lis
if( -f entry_point_trans.sed ) rm entry_point_trans.sed
 
cat - >entry_point_trans.sed <<EOF
s/D0\\\$/\\\$d0/g
s/000000\.//g
s/000000\]//g
s/\\\$ROOT:\[/\//g
s/;[0-9]* *\$//g
s/\]/\//g
EOF

sed -f entry_point_trans.sed < entry_point.lis | tr '[A-Z]' '[a-z]' \
   >unix_entry_point.lis
 
rm entry_point_trans.sed
 
