#! /bin/csh -f
#------------------------------------------------------------------------------
#
# Name      : Physics_util_pre_release
#
# Purpose   : Delete unwanted files from release
#
# Usage     :
#
# % physics_util_pre_release
#
# Created 29-NOV-1993   Herbert B. Greenlee
#
#------------------------------------------------------------------------------
rm -rf $d0physics_util/gm >& /dev/null
rm -rf $d0physics_util/gmpaw >& /dev/null
