#! /bin/csh -f
source `uff $d0unix/d0local.cshrc`
#------------------------------------------------------------------------------
#
# Name      : Program_builder_release
#
# Purpose   : Release script for program builder section of d0library.  Builds
#             executable from library.
#
# Usage     :
#
# % program_builder_release
#
# Created 23-May-1992   Herbert B. Greenlee
#
#------------------------------------------------------------------------------
foreach deb ( 'deb_' '' )
  ar x `uff $d0program_builder/${deb}program_builder.a` \
    pbd.o `archive_name pbd_fatmen_dummies.o`
  $f77 -o ${deb}pbd $ldflags pbd.o `archive_name pbd_fatmen_dummies.o`\
    `uff $d0program_builder/${deb}program_builder.a` \
    `uff $d0general/${deb}general.a` \
    `uff $d0unix/${deb}unix.a` \
    `uff $d0cernlib/packlib.a` \
    `uff $d0cernlib/kernlib.a` \
    $syslibs
end
rm *.o

