#! /bin/csh -f
#------------------------------------------------------------------------------
#
# Name      : Stp_pre_release
#
# Purpose   : Delete unwanted files from release
#
# Usage     :
#
# % stp_pre_release
#
# Created 29-NOV-1993   Herbert B. Greenlee
#
#------------------------------------------------------------------------------
rm -rf $d0stp/tb90_data >& /dev/null
rm -rf $d0stp/tb90l2 >& /dev/null
rm -rf $d0stp/geotbm >& /dev/null
