#! /bin/csh -f
###############################################################################
#
# Name:  util_release
#
# Purpose: UNIX release script for util d0library section.  This
#          script performs the following actions:
#
#          1.  Link copy_fz ane evnt_list.
#
#          2.  Builds d0flavor executable.
#
#          3.  Builds fzdiff executable.
#
# Usage Notes:
#
# 1.  This script should be executed from the top directory of the
#     util library section.
#
#
# Created 25-Jun-1992  Herbert Greenlee
#
##############################################################################
#
# Execute scripts to link copy_fz and evnt_list executables
#
eval `uff $d0util/files/evnt_list_lnk.csh` debug
eval `uff $d0util/files/evnt_list_lnk.csh`
eval `uff $d0util/files/copy_fz_lnk.csh` debug
eval `uff $d0util/files/copy_fz_lnk.csh`
#
# Execute script to build d0flavor executable.
#
eval `uff $d0util/d0flavor/build_d0flavor.csh`
#
# Execute script to build fzdiff executable.
#
eval `uff $d0util/fzdiff/build_fzdiff.csh`
#
# Execute script to build fzbrowse (map) executable.
#
eval `uff $d0util/files/build_fzbrowse.csh`
