#! /bin/csh -f
###############################################################################
#
# Name:  util_pre_release
#
# Purpose: UNIX release script for util d0library section.  This
#          script performs the following actions:
#
#          1.  Deletes unwanted groups from util library.
#
# Usage Notes:
#
# 1.  This script should be executed from the top directory of the
#     util library section.
#
# 2.  This script should be released via the VMS d0library release procedures
#     so that is gets to the top directory of the util library
#     section.
#
# Created 25-Jun-1992  Herbert Greenlee
#
##############################################################################
rm -rf $d0util/clist >& /dev/null
rm -rf $d0util/comp_stat >& /dev/null
rm -rf $d0util/sources >& /dev/null
rm -rf $d0util/swing >& /dev/null
rm -rf $d0util/util >& /dev/null
