$ SET VERIFY
$ !
$ ! command file to create ISAJET5.OLB from PAM file
$ !
$ YPATCHY
D0$PATCHY:ISAJET5 ISAJET5 TTY TTY .GO
+USE,*ISAJET,VAX.
+USE,INTERACT.
+USE,NOCERN,T=INHIBIT.
+USE,CERN.
+USE,D0.
+PATCH,P=D0.
+DEL,P=ISARUN,D=ISARUN,C=1-96.
+EXE,P=ISACDE.
+EXE,P=ISADATA.
+EXE,P=ISAJET.
+EXE,P=ISARUN.
+PAM.
+QUIT.
$ FOR ISAJET5
$ LIB/CREATE ISAJET5 ISAJET5
$ DEL ISAJET5.OBJ;
$ DEL ISAJET5.FOR;
$ SET NOVERIFY
