PACKAGE := level1
$(PACKAGE)_LIB := yes

# Obsolete routines that are not built anymore, though they remained
# in the source distribution.
$(PACKAGE)_EXCEPT_FOR += actual_geometry.for level1_data_block_dump.for

# Uses single-quote notation for direct record access; not supported by g77.
$(PACKAGE)_EXCEPT_FOR += mu_otc_lookup.for mu_trig_crate_l15.for \
                         mu_wam_otc.for samcen_chsel.for samcen_consec.for
include GNUmakefile.subcommon
