CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VLEVEL1()
      VLEVEL1 = ' LEVEL1'//
     X                   '  OFFICIAL V2.00'//
     X                   ' 21-DEC-1994 11:49:32.65'
      Return
      End
