PACKAGE := showerlibrary
$(PACKAGE)_LIB := yes

# Keyed I/O.
$(PACKAGE)_EXCEPT_FOR += mulaux_read.for mulib_aux_write.for \
                         muon_rzvin1.for muonlib_aux_open.for \
                         muonlib_open.for rzvin1.for shlaux_read.for \
                         shlaux_write.for showerlib_aux_open.for \
                         showerlib_open.for
include GNUmakefile.subcommon
