CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VSHOWERLIBRARY()
      VSHOWERLIBRARY = ' SHOWERLIBRARY'//
     X                   '  OFFICIAL V1.02'//
     X                   ' 17-JUL-1997 22:02:34.32'
      Return
      End
