#! /bin/csh -f
#-----------------------------------------------------------------------
#
# Name:       check_prod
#
# Purpose:    Produce a list of files, checksums and block sizes for a
#             production release.
#
# Arguments:  $1 - Root directory of production release
#
#-----------------------------------------------------------------------
set root = $1
set dir = $root:t
find $root \
  \! -name $dir \( \! -name new -type d -prune \) -o \
  -type f -exec sum {} \; | \
  sed -e "s@$root/@@" | \
  sort +2 -3
