#! /bin/csh -f
source `uff $d0unix/d0local.cshrc`
#------------------------------------------------------------------------------
#
# Name      : d0czar
#
# Purpuse   : Print the czar(s) e-mail addresses associated with given
#             library sections.
#
# Usage     :
#
# % d0czar section1 section2 ...
#
# Arguments:
#
# section - Library section(s)
#
# Notes:
#
# 1.  If no sections are specified, then the czars of all sections are
#     output, preceded by the library section names.
#
# Created 30-Jul-1994   Herbert B. Greenlee
#
#------------------------------------------------------------------------------
if( $#argv == 0 )then
  set sections = ( `lib_sect` )
else
  set sections = ( $argv )
endif
#
# Get sections to loop over
#
foreach section ( $sections )
  set mailing_list = ''
#
# Czar list
#
  if( $section == fitting_util ) \
    set mailing_list = ( daria@fnal.gov $mailing_list )
  if( $section == b_physics ) \
    set mailing_list = ( daria@fnal.gov $mailing_list )
  if( $section == c_inc ) \
    set mailing_list = ( greenlee@fnal.gov $mailing_list )
  if( $section == calor_filter ) \
    set mailing_list = ( linnemann@fnal.gov $mailing_list )
  if( $section == nodi3000 ) \
    set mailing_list = ( hagopian@fnal.gov $mailing_list )
  if( $section == graphics_util ) \
    set mailing_list = ( oshima@fnal.gov $mailing_list )
  if( $section == xframe ) \
    set mailing_list = ( drew@fnal.gov $mailing_list )
  if( $section == physics_util ) \
    set mailing_list = ( meena@fnal.gov $mailing_list )
  if( $section == wz ) \
    set mailing_list = ( heintz@fnal.gov $mailing_list )
  if( $section == pixie ) \
    set mailing_list = ( hagopian@fnal.gov oshima@fnal.gov $mailing_list )
  if( $section == dbl3 ) \
    set mailing_list = ( srini@fnal.gov $mailing_list )
  if( $section == d0dad ) \
    set mailing_list = ( hobbs@fnal.gov $mailing_list )
  if( $section == d0hplt ) \
    set mailing_list = ( hagopian@fnal.gov $mailing_list )
  if( $section == dspack ) \
    set mailing_list = ( ssnyder@fnal.gov $mailing_list )
  if( $section == event_util ) \
    set mailing_list = ( serban@fnal.gov $mailing_list )
  if( $section == errmsg_util ) \
    set mailing_list = ( linnemann@fnal.gov $mailing_list )
  if( $section == isajet ) \
    set mailing_list = ( serban@fnal.gov $mailing_list )
  if( $section == isazeb ) \
    set mailing_list = ( serban@fnal.gov $mailing_list )
  if( $section == isajet_util ) \
    set mailing_list = ( serban@fnal.gov $mailing_list )
  if( $section == offline_util ) \
    set mailing_list = ( qzli@fnal.gov $mailing_list )
  if( $section == srcp_util ) \
    set mailing_list = ( harry@fnal.gov $mailing_list )
  if( $section == zebra_util ) \
    set mailing_list = ( serban@fnal.gov $mailing_list )
  if( $section == level0 ) \
    set mailing_list = ( cmiao@fnal.gov $mailing_list )
  if( $section == muon_util ) \
    set mailing_list = ( fortner@fnal.gov $mailing_list )
  if( $section == muon_reco ) \
    set mailing_list = ( daria@fnal.gov $mailing_list )
  if( $section == calor_off ) \
    set mailing_list = ( dhiman@fnal.gov $mailing_list )
  if( $section == calor_util ) \
    set mailing_list = ( dhiman@fnal.gov $mailing_list )
  if( $section == cdc_util ) \
    set mailing_list = ( ngraf@fnal.gov madaras@fnal.gov $mailing_list )
  if( $section == fdc_util ) \
    set mailing_list = ( may@d0gs01.fnal.gov madaras@fnal.gov $mailing_list )
  if( $section == vtx_util ) \
    set mailing_list = ( lchen@d0gs01.fnal.gov madaras@fnal.gov $mailing_list )
  if( $section == trd_util ) \
    set mailing_list = ( azylber@fnal.gov ltgoss@fnal.gov madaras@fnal.gov $mailing_list )
  if( $section == cd_util ) \
    set mailing_list = ( srini@fnal.gov madaras@fnal.gov $mailing_list )
  if( $section == d0geant ) \
    set mailing_list = ( diesburg@fnal.gov $mailing_list )
  if( $section == qcd ) \
    set mailing_list = ( daniel@fnal.gov $mailing_list )
  if( $section == stp ) \
    set mailing_list = ( jonckheere@fnal.gov $mailing_list )
  if( $section == util ) \
    set mailing_list = ( jonckheere@fnal.gov $mailing_list )
  if( $section == unix ) \
    set mailing_list = ( greenlee@fnal.gov $mailing_list )
  if( $section == lcompack ) \
    set mailing_list = ( greenlee@fnal.gov $mailing_list )
  if( $section == program_builder ) \
    set mailing_list = ( serban@fnal.gov $mailing_list )
  if( $section == d0user ) \
    set mailing_list = ( serban@fnal.gov $mailing_list )
  if( $section == d0reco ) \
    set mailing_list = ( serban@fnal.gov $mailing_list )
  if( $section == level1 ) \
    set mailing_list = ( laurens@d0gs01.fnal.gov $mailing_list )
  if( $section == level2 ) \
    set mailing_list = ( linnemann@fnal.gov $mailing_list )
  if( $section == top_physics ) \
    set mailing_list = ( raja@fnal.gov serban@fnal.gov $mailing_list )
  if( $section == tpmfarm ) \
    set mailing_list = ( greenlee@fnal.gov $mailing_list )
  if( $section == pythia ) \
    set mailing_list = ( ngraf@fnal.gov $mailing_list )
  if( $section == spythia ) \
    set mailing_list = ( lyon@fnal.gov $mailing_list )
  if( $section == neural ) \
    set mailing_list = ( harry@fnal.gov bhat@fnal.gov $mailing_list )
  d0echo $section "$mailing_list " | tr ' ' '	'
end
