#! /bin/csh -f
#------------------------------------------------------------------------------
#
# Name      : find_all
#
# Purpuse   : echo the all existent files in the argument list
#
# Arguments : One or more.
#
# Created 21-JUN-1991   Herbert B. Greenlee
#
#------------------------------------------------------------------------------
foreach file ($argv)
    if(-e $file)then
        echo $file
    endif
end
