#! /bin/csh -f
#------------------------------------------------------------------------------
#
# Name      : find_first
#
# Purpuse   : echo the first existent file in the argument list
#
# Arguments : One or more.
#
# Created 21-JUN-1991   Herbert B. Greenlee
#
#------------------------------------------------------------------------------
foreach file ($argv)
    if(-e $file)then
        echo $file
        break
    endif
end
