#! /bin/csh -f
#------------------------------------------------------------------------------
#
# Name      : getoptc
#
# Purpuse   : Equivalent to getopt
#
# Usage     : 
#
# % getoptc args
#
# Created 16-Jul-1992   Herbert B. Greenlee
#
#------------------------------------------------------------------------------
getopt $argv:q
