#! /bin/csh -f
source `uff $d0unix/d0local.cshrc`
#------------------------------------------------------------------------------
#
# Name      : main_list
#
# Purpose   : List all modules in an object archive library than contain main
#             programs.
#
# Arguments : Archive library.
#
# Created 6-DEC-1991   Herbert B. Greenlee
#
#------------------------------------------------------------------------------
#
# Quick help
#
if($#argv == 0) then
help:
  echo "usage: main_list library"
  exit 1
endif
#
# Scan options
#
set argv = (`getopt - $argv`)
while("$argv[1]" != '--')
  switch($argv[1])
  default:
    echo "main_list: bad option $argv[1]"
    goto help
  endsw
end
shift                       # Get rid of terminating --
if($#argv == 0) goto help
set archive = $argv[1]
if( ! -f $archive) then
  echo "Non-existent archive $archive"
  exit 1
endif
d0nm $archive | awk \
'{module = substr($0,0,match($0,":")-1)};/[Mm][Aa][Ii][Nn]/{print module};/yylex/{print module}' | \
sort -u

