#! /bin/csh -f
#------------------------------------------------------------------------------
#
# Name      : Showlibtest
#
# Purpuse   : Output a list of test mode libraries
#
# Arguments : None
#
# Created 24-JUN-1991   Herbert B. Greenlee
#
#------------------------------------------------------------------------------
foreach sect (`all_sect`)
    set cmd=(find_first \$d0$sect)
    set dir=`eval $cmd`
    if($dir:h == $d0test)echo $sect
end
