#! /bin/csh -f
#------------------------------------------------------------------------------
#
# Name      : unix_pre_release
#
# Purpuse   : UNIX pre-build release procedure
#
# Arguments : none
#
# Created 21-JUN-1991   Herbert B. Greenlee
# Modified 2-FEB-1994   Micheal J. Wendling
#                       Added setup of the batrun directory
# Modified 17-Aug-1994  Herbert Greenlee
#                       Execute batrun_build.csh out of either test or
#                       official release.
#------------------------------------------------------------------------------
#
# Make shell scripts executable and link them to the top directory of library
#
chmod +x shell/*
ln -f shell/* $cwd >& /dev/null
rehash
#
# Delete mms file to inhibit build phase (release script supersedes).
#
rm -f unix.mms >& /dev/null
#
# Setup the batrun area
#
#chmod +x batrun/batrun_build.csh
#`uff $d0unix/batrun/batrun_build.csh`
ln -f batrun/*.csh $cwd >& /dev/null
#ln -f batrun/make_copy_fz_rcp $cwd >& /dev/null
rehash
#
