CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VSRCP_UTIL()
      VSRCP_UTIL = ' SRCP_UTIL'//
     X                   '  OFFICIAL V1.27'//
     X                   ' 11-JUL-1997 12:35:47.58'
      Return
      End
