CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VPIXIE()
      VPIXIE = ' PIXIE'//
     X                   '  TEST V3.16_01'//
     X                   ' 16-FEB-1996 17:08:50.04'
      Return
      End
