      SUBROUTINE D_MATSCA(X,Y,Z,TMATR)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      REAL TSCL(4,4),TMATR(4,4)
      CALL D_MATUNI(TSCL)
      TSCL(1,1)=X
      TSCL(2,2)=Y
      TSCL(3,3)=Z
      CALL D_MATMUL(TSCL,TMATR)
      END
