      SUBROUTINE D_MATTRA(X,Y,Z,TMATR)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      REAL TTRN(4,4),TMATR(4,4)
      CALL D_MATUNI(TTRN)
      TTRN(1,4)=X
      TTRN(2,4)=Y
      TTRN(3,4)=Z
      CALL D_MATMUL(TTRN,TMATR)
      END
