      SUBROUTINE DEV_SCALE(X,Y,Z)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      REAL TSCL(4,4)
      CALL D_MATUNI(TSCL)
      TSCL(1,1)=X
      TSCL(2,2)=Y
      TSCL(3,3)=Z
      CALL D_MATMUL(TMODEL,TSCL)
      CALL D_MATCPY(TTOTAL,TDEVIC)
      CALL D_MATMUL(TTOTAL,TMODEL)
      END
