      SUBROUTINE DEV_LINEWI(N)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IDLWID=N
      IF(IDV.EQ.1) THEN
        CALL PS_LINEWI
      ELSE
C        CALL TK_LINEWI
      ENDIF
      END
