      SUBROUTINE DEV_COLOR(INDEX)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IDCOLR=INDEX
      IF(IDV.EQ.1) THEN
        CALL PS_COLOR(INDEX)
      ELSE
        CALL TK_COLOR(INDEX)
      ENDIF
      END
