      SUBROUTINE DEV_SETLIN(N)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IDLSTY=N
      IF(IDV.EQ.1) THEN
        CALL PS_SETLIN
      ELSE
C        CALL TK_SETLIN
      ENDIF
      END
