      SUBROUTINE DMPSEG(IUNITD)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      WRITE(IUNITD,444)ISPTR,NSEGS
  444 FORMAT(' ISPTR,NSEGS:',2I)
      DO KKK=1,NSEGS
        WRITE(IUNITD,447)KKK,NUMSEG(KKK),NCALLS(KKK),INDS1(KKK)
  447   FORMAT(' N,NUMSEG,NCALLS,INDS1:',4I)
      ENDDO
      WRITE(IUNITD,445)(IBLOC(III),III=1,ISPTR)
  445 FORMAT(1000(2X,5(2X,O),/))
      END
