      SUBROUTINE J_DELSEGM(NAME)
C  DELETE A RETAINED SEGMENT FROM THE SOFTWARE SEGMENT STORAGE
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IF(NSEGS.EQ.0) GO TO 2000
      IF(NSEGS.EQ.1) GO TO 2000
      DO 10 I=1,NSEGS
        IF(NAME.NE.NUMSEG(I))GO TO 10
        NS=I
        GO TO 20
   10 CONTINUE
      GO TO 1000
C  FOUND IT
   20 CONTINUE
C  SEE IF THIS IS THE LAST SEGMENT
      IF(NS.EQ.NSEGS) THEN
        NSEGS=NSEGS-1
        IF(NSEGS.EQ.0) GO TO 2000
        RETURN
      ENDIF
C  COPY BACK, THROUGH LAST SEGMENT
      NNEXT=NS+1
      DO NSNOW=NNEXT,NSEGS
        NPREV=NSNOW-1
        NUMSEG(NPREV)=NUMSEG(NSNOW)
        IVIS(NPREV)=IVIS(NSNOW)
        INDS1(NPREV)=INDS1(NSNOW)
        NCALLS(NPREV)=NCALLS(NSNOW)
        ITTYP(NPREV)=ITTYP(NSNOW)
        IDETEC(NPREV)=IDETEC(NSNOW)
      ENDDO
      NSEGS=NSEGS-1
      RETURN
 1000 WRITE(JUNIT,*)'SEG. # DOESNT EXIST'
      RETURN
 2000 NSEGS=0
      ISEGNM=-1
      END
