      SUBROUTINE J_DEVTRN
C  CALCULATE THE DEVICE TRANSFORMATION MATRIX (TSCREE)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
C
C  FIND THE CORNERS OF THE VIEWSPACE IN JWINDO COORDINATES
      DVX=VXMAX-VXMIN
      DU=UMAX-UMIN
      EPSU=.001*DU
      UCENTR=.5*(UMAX+UMIN)
      IF(DU.EQ.0.) DU=1.
      XSCALE=DVX/DU
      XCENTR=.5*(VXMAX+VXMIN)
C
      DVY=VYMAX-VYMIN
      DV=VMAX-VMIN
      EPSV=.001*DV
      VCENTR=.5*(VMAX+VMIN)
      IF(DV.EQ.0.) DV=1.
      YSCALE=DVY/DV
      YCENTR=.5*(VYMAX+VYMIN)
C
C  PUT IN MARGINS TO GET DISPLAY WINDOW CORNERS IN JWINDO COORDS
      WLEFT=(VCXMN-XCENTR-XMARG)/XSCALE+UCENTR-EPSU
      WRIGHT=(VCXMX-XCENTR+XMARG)/XSCALE+UCENTR+EPSU
      WBOTM=(VCYMN-YCENTR-YMARG)/YSCALE+VCENTR-EPSV
      WTOP=(VCYMX-YCENTR+YMARG)/YSCALE+VCENTR+EPSV
C
C  LOAD THE SCREEN TRANSFORMATION MATRIX (SEE GL APPENDICES)
      CALL D_MATUNI(TSCREE)
      DEN=WRIGHT-WLEFT
      TSCREE(1,1)=.998*2./DEN
      TSCREE(1,4)=-.998*(WRIGHT+WLEFT)/DEN
      DEN=WTOP-WBOTM
      TSCREE(2,2)=.998*2./DEN
      TSCREE(2,4)=-.998*(WTOP+WBOTM)/DEN
      call d_dmpmat('J_PROJS-TSCREE',TSCREE)
      RETURN
      END
