#! /bin/csh -f
#---------------------------------------------------------------
#
# Name   : pixie_setup
#
# Purpose: Setup everything to run the simple D0 event display
#          program PIXIE_DISPLAY in $d0graphics_util/sgidi3
#
# Created 03-DEC-1992 Lupe Howell
#
#---------------------------------------------------------------
 set data = "$d0pixie"
ln -sf `ff ${data}/px_combdis.rcp`     px_combdis_rcp
ln -sf `ff ${data}/px_caldis.rcp`      px_caldis_rcp
ln -sf `ff ${data}/px_user_lego.rcp`   px_user_lego_rcp
ln -sf `ff ${data}/px_cdcdis.rcp`      px_cdcdis_rcp
ln -sf `ff ${data}/px_fdcdis.rcp`      px_fdcdis_rcp
ln -sf `ff ${data}/px_muodis.rcp`      px_muodis_rcp
ln -sf `ff ${data}/px_trddis.rcp`      px_trddis_rcp
ln -sf `ff ${data}/px_ztraksdis.rcp`   px_ztraksdis_rcp
ln -sf `ff ${data}/px_vtxdis.rcp`      px_vtxdis_rcp
ln -sf `ff ${data}/px_cosmic_rays.rcp` px_cosmic_rays_rcp
ln -sf `ff ${data}/px_iszgrf.rcp`      px_iszgrf_rcp
ln -sf `ff ${data}/px_samdis.rcp`      px_samdis_rcp
ln -sf `ff ${data}/px_mutraksdis.rcp`  px_mutraksdis_rcp
ln -sf `ff ${data}/px_phydis.rcp`      px_phydis_rcp
ln -sf `ff ${data}/px_system.rcp`      px_system_rcp
ln -sf `ff ${data}/pixie.rcp`          pixie_rcp
#
ln -sf `ff $d0cd_util/ztraks.rcp`         ztraks_rcp
ln -sf `ff $d0cd_util/vertex.rcp`         vertex_rcp
ln -sf `ff $d0cd_util/vees.rcp`           vees_rcp
ln -sf `ff $d0fdc_util/ftraks.rcp`        ftraks_rcp
ln -sf `ff $d0cdc_util/dtraks.rcp`        dtraks_rcp
ln -sf `ff $d0vtx_util/vtraks.rcp`        vtraks_rcp
ln -sf `ff $d0trd_util/trd.rcp`           trd_rcp
ln -sf `ff $d0calor_off/calevt.rcp`       calevt_rcp
ln -sf `ff $d0calor_off/cahits.rcp`       cahits_rcp
ln -sf `ff $d0library/muon_reco/mureco.rcp`       mureco_rcp
ln -sf `ff $d0calor_off/csf_ecem.rcp`     csf_ecem_rcp
ln -sf `ff $d0calor_off/csf_ccem.rcp`     csf_ccem_rcp
ln -sf `ff $d0calor_off/csf_icd.rcp`      csf_icd_rcp
ln -sf `ff $d0muon_reco/samreco.rcp`      samreco_rcp
#
ln -sf `ff $d0stp/cdc_stpfile.dat` cdc_stpfile 
ln -sf `ff $d0stp/cal_stpfile.dat` cal_stpfile 
ln -sf `ff $d0stp/fdc_d0stpfile.dat` fdc_stpfile 
ln -sf `ff $d0stp/muo_stpfile.dat` muo_stpfile
ln -sf `ff $d0stp/sam_stpfile.dat` sam_stpfile 
ln -sf `ff $d0stp/trd_stpfile.dat` trd_stpfile 
ln -sf `ff $d0stp/vtx_stpfile.dat` vtx_stpfile 
ln -sf `ff $d0stp/lv0_stpfile.dat` lv0_stpfile
ln -sf `ff $d0stp/cad_stpfile.dat` cad_table
# 
# Set up you data file here.  For example:
# ln -sf /usr1/d0library/data/sta_k_18001_01.gen pixie_datafile

