C DEC/CMS REPLACEMENT HISTORY, Element JELSEG.FOR
C *1     3-JUN-1992 13:49:50 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JELSEG.FOR
      SUBROUTINE JELSEG(DSPDEV,PHYDEV,NAME,IASSC)
      INTEGER DSPDEV,PHYDEV
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IF(NSEGS.EQ.0) GO TO 1000
      DO 10 I=1,NSEGS
        ISEG=I
        IF(NAME.EQ.NUMSEG(I)) GO TO 20
   10 CONTINUE
      GO TO 1000
   20 IASSO(ISEG)=IASSC
      RETURN
 1000 WRITE(JUNIT,*) ' NO SUCH SEGMENT EXISTS',NAME
      END
