C DEC/CMS REPLACEMENT HISTORY, Element JPARAL.FOR
C *1     3-JUN-1992 14:09:33 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JPARAL.FOR
      SUBROUTINE JPARAL
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IPROJ=1
      IF(DI3DIN.GT.0) CALL J_PROJS
      IF(IDEBUG.GT.0) TYPE *,' >>>>> JPARAL'
      END
