C DEC/CMS REPLACEMENT HISTORY, Element JDCOLR.FOR
C *1     3-JUN-1992 13:26:59 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDCOLR.FOR
      SUBROUTINE JDCOLR(IDDD)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      ICLRDF=IDDD
      CALL JCOLOR(IDDD)
      END
