C DEC/CMS REPLACEMENT HISTORY, Element J1IGET.FOR
C *1     3-JUN-1992 12:59:35 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element J1IGET.FOR
      SUBROUTINE J1IGET(ICOD,IVAL)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IVAL=IJ1(ICOD)
      END
