C DEC/CMS REPLACEMENT HISTORY, Element JSAALL.FOR
C *1     3-JUN-1992 14:43:40 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JSAALL.FOR
      SUBROUTINE JSAALL(IDEV,IFLAG)
CPIXYES
CSET THIS UP WHEN HARDCOPY ESTABLISHED!
      COMMON/J_DI3PR/JUNIT
      WRITE(JUNIT,*)'JSAALL dummied'
      END
