C DEC/CMS REPLACEMENT HISTORY, Element JFSOPN.FOR
C *1     3-JUN-1992 13:54:50 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JFSOPN.FOR
      SUBROUTINE JFSOPN
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
C       WRITE(JUNIT,*)'JFSOPN dummied'
      END
