C DEC/CMS REPLACEMENT HISTORY, Element JDPINT.FOR
C *1     3-JUN-1992 13:46:58 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDPINT.FOR
      SUBROUTINE JDPINT(IDDD)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IPINDF=IDDD
      CALL JPINTR(IDDD)
      END
