C DEC/CMS REPLACEMENT HISTORY, Element JDINIT.FOR
C *1     3-JUN-1992 13:43:43 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDINIT.FOR
      SUBROUTINE JDINIT(IDEV)
C      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      END
