C DEC/CMS REPLACEMENT HISTORY, Element JEXTNT.FOR
C *1     3-JUN-1992 13:52:01 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JEXTNT.FOR
      SUBROUTINE JEXTNT(NCHARS,STRING,XXTENT,YXTENT)
C  RETURN X AND Y EXTENT OF A STROKE LEVEL STRING
      COMMON/J_DI3PR/JUNIT
C       WRITE(JUNIT,*)'JEXTNT dummied'
      END
