C DEC/CMS REPLACEMENT HISTORY, Element JFRAME.FOR
C *1     3-JUN-1992 13:54:13 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JFRAME.FOR
      SUBROUTINE JFRAME
C  CLEAR THE DISPLAY AREA AND REDRAW ALL RETAINED SEGMENTS
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      COMMON/J_RMODIF/MODWIN,UMINZ,UMAXZ,VMINZ,VMAXZ
      LOGICAL MODWIN
      COMMON/J_DI3CTL/LWINDO,LRWNDO
C  REWINDOW IF REQUESTED
      IF(LRWNDO.GT.0) THEN
        CALL REWINDOW
        LRWNDO=0
      ENDIF
C  CLEAR THE DISPLAY
      CALL JCOLOR(9)
      CALL CLEAR()
C  ZERO THE POSITION
      VPOSN(1)=0.
      VPOSN(2)=0.
      VPOSN(3)=0.
C
C  DRAW ALL VISIBLE SEGMENTS
      IF(NSEGS.EQ.0) RETURN
C
C  RUN THROUGH THE SEGMENTS
      DO ISEG=1,NSEGS
        ISEGNM=NUMSEG(ISEG)
        CALL CALLOB(OBJID(ISEG))
      ENDDO
C
      ISEGNM=-1
      RETURN
      END
