C DEC/CMS REPLACEMENT HISTORY, Element JIQDIL.FOR
C *1     3-JUN-1992 14:00:45 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JIQDIL.FOR
      SUBROUTINE JIQDIL(RLEVEL)
C  FAKE THE RELEASE LEVEL.
      RLEVEL=5.
C!!!      RLEVEL=-2.
      END
