C DEC/CMS REPLACEMENT HISTORY, Element JYON.FOR
C *1     3-JUN-1992 15:00:33 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JYON.FOR
      SUBROUTINE JYON(ZVAL)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      RJ3(3,10)=ZVAL
      END
