C DEC/CMS REPLACEMENT HISTORY, Element JR3MRK.FOR
C *1     3-JUN-1992 14:29:08 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JR3MRK.FOR
      SUBROUTINE JR3MRK(X,Y,Z)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      XNOW=VPOSN(1)+X
      YNOW=VPOSN(2)+Y
      VPOSN(3)=VPOSN(3)+Z
      CALL JMARK(XNOW,YNOW)
      END
