      SUBROUTINE JOPEN
C  OPEN TEMPORARY SEGMENT
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      LOGICAL RECALC
C  OPEN NON-RETAINED SEGMENT (0)
      if(idebwr.gt.0) then
        write(idebwr,8008)
 8008   format(' JOPEN called')
      endif
      ISEGNM=0
C  RESET TO DEFAULTS
      CALL JARSET
      IF(IDEBUG.GE.20) CALL J_DUMP
C  UPDATE PROJECTION TRANSFORMATIONS IF NEEDED
C      IF(IRSPRJ.EQ.1) THEN
C        IRSPRJ=0
C        CALL J_PROJS
C      ENDIF
      IF(HCPY) RETURN
      END
