C DEC/CMS REPLACEMENT HISTORY, Element JDEND.FOR
C *1     3-JUN-1992 13:29:43 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDEND.FOR
      SUBROUTINE JDEND(IDEV)
C  TERMINATE ACTIVE DISPLAY DEVICE
      COMMON/J_DI3PR/JUNIT
      WRITE(JUNIT,*) ' JDEND DUMMIED'
      END
