C DEC/CMS REPLACEMENT HISTORY, Element JRIGHT.FOR
C *1     3-JUN-1992 14:37:16 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JRIGHT.FOR
      SUBROUTINE JRIGHT(IRIGH)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      LOGICAL IRIGH
      IF(IRIGH) THEN
        IRIGHT=1
      ELSE
        IRIGHT=0
      ENDIF
      IF(IDEBUG.GT.0) TYPE *,' JRIGHT CALLED. IRIGHT = ',IRIGHT
      END
