C DEC/CMS REPLACEMENT HISTORY, Element JSASSO.FOR
C *1     3-JUN-1992 14:44:55 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JSASSO.FOR
      SUBROUTINE JSASSO
      COMMON/J_DI3PR/JUNIT
      WRITE(JUNIT,*)'JSASSO dummied'
      END
