      SUBROUTINE JWINDO(X1,X2,Y1,Y2)
C  OPEN VIEWPLANE WINDOW
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
C  RESET CLIPPING PLANES
      WNEAR=-999999.
      WFAR=999999.
      if(idebwr.gt.0) then
        write(idebwr,8008) x1,x2,y1,y2
 8008   format(' JWINDO - x1,x2,y1,y2:',4f)
      endif
      IF(IDEBUG.GT.0) TYPE *,' JWINDO:',X1,X2,Y1,Y2
      IF(IFSPAC.EQ.0) CALL JVSPAC(VCXMN,VCXMX,VCYMN,VCYMX)
      UMIN=X1
      UMAX=X2
      VMIN=Y1
      VMAX=Y2
      IF(HCPY) CALL DEV_WINDOW_CORNERS(UMIN,UMAX,VMIN,VMAX)
      IF(DI3DIN.GT.0) CALL J_PROJS
      IF(IDEBUG.LT.3) RETURN
      TYPE 444
  444 FORMAT(' *****AT END OF JWINDO*****')
      IF(IDEBUG.GT.20) CALL J_DUMP
      RETURN
      END
