C DEC/CMS REPLACEMENT HISTORY, Element JTTYPE.FOR
C *1     3-JUN-1992 14:52:00 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JTTYPE.FOR
      SUBROUTINE JTTYPE(IT)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      ITYPDF=IT
      END
