C DEC/CMS REPLACEMENT HISTORY, Element JIQDIM.FOR
C *1     3-JUN-1992 14:01:16 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JIQDIM.FOR
      SUBROUTINE JIQDIM(DSPDEV,FLAG,MAXDIM)
      INTEGER DSPDEV
      LOGICAL FLAG
      REAL MAXDIM(4)
C  THIS DEVICE IS NOT CAPABLE OF EXACT SIZING
      FLAG=.FALSE.
      END
