C DEC/CMS REPLACEMENT HISTORY, Element JPRMRK.FOR
C *1     3-JUN-1992 14:22:47 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JPRMRK.FOR
      SUBROUTINE JPRMRK(X,Y,N)
      REAL X(2),Y(2)
      DO I=1,N
        CALL JRMARK(X(I),Y(I))
      ENDDO
      END
