C DEC/CMS REPLACEMENT HISTORY, Element JVUPLN.FOR
C *1     3-JUN-1992 14:57:01 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JVUPLN.FOR
      SUBROUTINE JVUPLN(ZVAL)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      VDIST=ZVAL
      END
