C DEC/CMS REPLACEMENT HISTORY, Element J1STRG.FOR
C *1     3-JUN-1992 13:00:07 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element J1STRG.FOR
      SUBROUTINE J1STRG(STRING)
C  OUTPUT A HARDWARE FONT STRING
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      CHARACTER*(*) STRING
      ILEN=LEN(STRING)
      IF(HCPY) GO TO 10
      X0=-.4*(IHJUST-1)*ILEN*XSIZE      !HORIZ JUSTIF
      Y0=-.4*(IVJUST-1)*YSIZE           !VERT JUSTIF
      CALL CMOV2(VPOSN(1)+X0,VPOSN(2)+Y0)
      CALL CHARST(STRING,ILEN)
      RETURN
   10 CONTINUE
      CALL J3STRG(STRING)
      END
