C DEC/CMS REPLACEMENT HISTORY, Element JHCLIP.FOR
C *1     3-JUN-1992 13:55:18 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JHCLIP.FOR
      SUBROUTINE JHCLIP
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
C       WRITE(JUNIT,*)'JHCLIP dummied'
      END
