C DEC/CMS REPLACEMENT HISTORY, Element JYCLIP.FOR
C *1     3-JUN-1992 15:00:00 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JYCLIP.FOR
      SUBROUTINE JYCLIP
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
C       WRITE(JUNIT,*)'JYCLIP dummied'
      END
