C DEC/CMS REPLACEMENT HISTORY, Element JENBAT.FOR
C *1     3-JUN-1992 13:50:16 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JENBAT.FOR
      SUBROUTINE JENBAT(LEVEL)
C  END-OF-BATCH UPDATES
      END
