C DEC/CMS REPLACEMENT HISTORY, Element JIQDDL.FOR
C *1     3-JUN-1992 13:59:41 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JIQDDL.FOR
      SUBROUTINE JIQDDL(DSPDEV,RLEVEL)
      INTEGER DSPDEV
      RLEVEL=5.
C!!!      RLEVEL=-2.
      END
