C DEC/CMS REPLACEMENT HISTORY, Element JCOTBL.FOR
C *1     3-JUN-1992 13:24:45 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JCOTBL.FOR
      SUBROUTINE JCOTBL(DSPDEV,COUNT,INDEXS,HUES,SATS,LIGHTS)
      INTEGER DSPDEV,COUNT
      INTEGER INDEXS(*),HUES(*),SATS(*),LIGHTS(*)
      INTEGER ICNDXX
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      CONV=3.1415927/180.
C!!!! SHUNT FOR NOW
      IF(ID0PIX.EQ.0) RETURN
C!!!!
C
      IF(IDEBUG.GT.1) THEN
c        TYPE *,' JCOTBL CALLED:'
        DO J=1,COUNT
c           TYPE *,INDEXS(J),HUES(J),SATS(J),LIGHTS(J)
        ENDDO
      ENDIF
C
      DO 10 J=1,COUNT
        ICINDX=INDEXS(J)
        IF(ICINDX.LT.0.OR.ICINDX.GT.256) GO TO 100
        HANG=FLOAT(HUES(J))-120.
        IF(HANG.LT.0.) HANG=HANG+360.
        SAT=FLOAT(SATS(J))/32767.
        IF(SAT.LE.0.) SAT=.01
        ALIGHT=FLOAT(LIGHTS(J))/32767.
        IF(ALIGHT.LE.0.) ALIGHT=.01
        CALL HLS_TO_RGB(HANG,ALIGHT,SAT,RV,GV,BV)
        JRV=255.*RV
        JGV=255.*GV
        JBV=255.*BV
        RVEC(ICINDX)=JRV
        BVEC(ICINDX)=JBV
        GVEC(ICINDX)=JGV
        IF(IDEBUG.GT.1) TYPE *,' IN JCOTBL-MAPCOL:',ICINDX,RV,GV,BV
        CALL MAPCOL(ICINDX,JRV,JGV,JBV)
        GO TO 10
  100   TYPE 110,ICINDX
  110   FORMAT(' JCOTBL--COLOR NOT LOADED IN MAP:',I)
   10 CONTINUE
      END
