      SUBROUTINE JCLEAR
C  PURGE DISPLAY SURFACES AND SEGMENT STORAGE
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      CALL JCOLOR(9)
      CALL CLEAR
      IF(ICSUPP.EQ.1) RETURN
      ISEGNM=-1
      NSEGS=0
      END
