C DEC/CMS REPLACEMENT HISTORY, Element JPKID.FOR
C *1     3-JUN-1992 14:17:54 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JPKID.FOR
      SUBROUTINE JPKID(IVAL)
C  SET THE CURRENT PICK_ID PRIMITIVE VALUE
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IPICID=IVAL
      END
