C DEC/CMS REPLACEMENT HISTORY, Element JMODON.FOR
C *1     3-JUN-1992 14:06:29 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JMODON.FOR
      SUBROUTINE JMODON(ION)
      LOGICAL ION
C  TURN ON MODELING
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IMODEL=0
      IF(ION)THEN
        IMODEL=1
        CALL PUSHMA
        CALL LOADMA(MMODEL)
      ELSE
        CALL POPMAT
      ENDIF
      END
