C DEC/CMS REPLACEMENT HISTORY, Element JDDETE.FOR
C *1     3-JUN-1992 13:28:58 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDDETE.FOR
      SUBROUTINE JDDETE(IVAL)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IDETDF=IVAL
      END
