C DEC/CMS REPLACEMENT HISTORY, Element JDPINX.FOR
C *1     3-JUN-1992 13:47:30 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDPINX.FOR
      SUBROUTINE JDPINX(IC,IN)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IPCLDF=IC
      IPNTDF=IN
      CALL JPIDEX(IC,IN)
      END
