C DEC/CMS REPLACEMENT HISTORY, Element JDVISB.FOR
C *1     3-JUN-1992 13:49:22 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDVISB.FOR
      SUBROUTINE JDVISB(IVISF)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IVISDF=IVISF
      END
