C DEC/CMS REPLACEMENT HISTORY, Element JEND.FOR
C *1     3-JUN-1992 13:50:48 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JEND.FOR
      SUBROUTINE JEND
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IF(IDEBUG.GT.5)TYPE 2222
 2222 FORMAT(' JEND')
      END
