C DEC/CMS REPLACEMENT HISTORY, Element JLOCAT.FOR
C *1     3-JUN-1992 14:03:57 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JLOCAT.FOR
      SUBROUTINE JLOCAT(DSPDEV,PHYDEV,ECHOLV,BUTTON,VX,VY)
C  "INVOKE THE VIRTUAL LOCATOR INPUT FUNCTION"
C   (VIRTUOUSLY LOQUACIOUS!)
C  VX AND VY ARE IN VIRTUAL COORDINATES IN THE RANGE -1,+1.
C  JCONVW MAY BE USED TO CONVERT THESE TO WORLD COORDINATES
      INCLUDE 'fgl.h'
      INCLUDE 'fdevice.h'
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      INTEGER DSPDEV,PHYDEV,ECHOLV,BUTTON
      INTEGER LEFT,RIGHT,BOTTOM,TOP
      INTEGER*2 QVAL
C
      IF(IDEBUG.GT.0) type *,' ENTERING JLOCAT'
      CALL GETORI(LEFT,BOTTOM)
      CALL GETSIZ(IXSPAN,IYSPAN)
      XSPAN=FLOAT(IXSPAN)
      YSPAN=FLOAT(IYSPAN)
      CALL QRESET()
C  POINTER LOOP
   10 IDEV=QREAD(QVAL)
      IF(IDEV.NE.LEFTMO) GO TO 10
      IF(QVAL.NE.1) GO TO 10
      IVX=GETVAL(MOUSEX)
      IVY=GETVAL(MOUSEY)
      VX=(VCXMX-VCXMN+2.*XMARG)*FLOAT(IVX-LEFT)/XSPAN+VCXMN-XMARG
      VY=(VCYMX-VCYMN+2.*YMARG)*FLOAT(IVY-BOTTOM)/YSPAN+VCYMN-YMARG
      IF(IDEBUG.GT.0) type *,' JLOCAT VX,VY:',vx,vy
      RETURN
      END
