C DEC/CMS REPLACEMENT HISTORY, Element JBACKG.FOR
C *1     3-JUN-1992 13:13:01 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JBACKG.FOR
      SUBROUTINE JBACKG(IBCOLR)
      INCLUDE 'fgl.h'
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      RETURN
      END
