C DEC/CMS REPLACEMENT HISTORY, Element JWCLIP.FOR
C *1     3-JUN-1992 14:58:31 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JWCLIP.FOR
      SUBROUTINE JWCLIP
      COMMON/J_DI3PR/JUNIT
C       WRITE(JUNIT,*)'JWCLIP dummied'
      END
