C DEC/CMS REPLACEMENT HISTORY, Element JDLSTY.FOR
C *1     3-JUN-1992 13:44:54 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDLSTY.FOR
      SUBROUTINE JDLSTY(LSTDF)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      ILSTDF=LSTDF
      CALL JLSTYL(LSTDF)
      END
