C DEC/CMS REPLACEMENT HISTORY, Element JFONT.FOR
C *1     3-JUN-1992 13:53:30 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JFONT.FOR
      SUBROUTINE JFONT(I)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IFONT=I
C  ONLY ONE FONT FOR NOW.
      END
