C DEC/CMS REPLACEMENT HISTORY, Element JSETDB.FOR
C *1     3-JUN-1992 14:46:45 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JSETDB.FOR
      SUBROUTINE JSETDB(I)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IDEBUG=I
      END
