C DEC/CMS REPLACEMENT HISTORY, Element JHITHR.FOR
C *1     3-JUN-1992 13:56:55 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JHITHR.FOR
      SUBROUTINE JHITHR(ZVAL)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      RJ3(2,10)=ZVAL
      END
