C DEC/CMS REPLACEMENT HISTORY, Element JDEVOF.FOR
C *1     3-JUN-1992 13:31:13 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDEVOF.FOR
      SUBROUTINE JDEVOF(IDEVI)
C  SHUT DOWN CURRENTLY ACTIVE DEVICE
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IF(IDEBUG.GT.0) TYPE *,' IN JDEVOF-IDEVI:',IDEVI
      IF(IDEVI.EQ.1) THEN
C!!!        IF(WDID.GT.0) CALL WINCLO(WDID)
C!!!        WDID=0
        HCPY=.FALSE.
      ELSEIF(IDEVI.EQ.2) THEN
        CALL J_HCOPY_END
        IDEVIC=1
        HCPY=.FALSE.
      ENDIF
      END
