      SUBROUTINE JJUST(IHORIZ,IVERT)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IF(IHORIZ.LT.1.OR.IHORIZ.GT.3)THEN
        WRITE(JUNIT,*)'JJUST HORIZONTAL NO GOOD:',IHORIZ
        RETURN
      ENDIF
      IF(IVERT.LT.1.OR.IVERT.GT.3)THEN
        WRITE(JUNIT,*)'JJUST VERTICAL NO GOOD:',IVERT
        RETURN
      ENDIF
      IHJUST=IHORIZ
      IVJUST=IVERT
      END
