C DEC/CMS REPLACEMENT HISTORY, Element JBUILD.FOR
C *1     3-JUN-1992 13:15:42 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JBUILD.FOR
      SUBROUTINE JBUILD(MAT,IT,P1,P2,P3,P4,P5,P6,P7)
      REAL*4 MAT(4,4),MAT2(4,4)
      COMMON/J_DI3PR/JUNIT
C  CONVERT THE LATEST TRANSFORMATION TO A MATRIX
      CALL JTRANS(MAT2,IT,P1,P2,P3,P4,P5,P6,P7)
      CALL PUSHMA
      CALL LOADMA(MAT)
      CALL MULTMA(MAT2)
      CALL GETMAT(MAT)
      CALL POPMAT
      END
