C DEC/CMS REPLACEMENT HISTORY, Element JVISBL.FOR
C *1     3-JUN-1992 14:53:42 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JVISBL.FOR
      SUBROUTINE JVISBL(NM,IVISF)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IF(NSEGS.EQ.0) RETURN
      IF(NSEGS.GT.100)RETURN
      ISG=0
      DO 10 I=1,NSEGS
        IF(NM.NE.NUMSEG(I)) GO TO 10
        ISG=I
        GO TO 20
   10 CONTINUE
      RETURN
   20 IVIS(ISG)=IVISF
      END
