C DEC/CMS REPLACEMENT HISTORY, Element JIQDEV.FOR
C *1     3-JUN-1992 14:00:17 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JIQDEV.FOR
      SUBROUTINE JIQDEV(DSPDEV,ICODE,LIST)
C  VARIOUS PROPERTIES OF THE DISPLAY DEVICE
      INTEGER DSPDEV
      DIMENSION LIST(10)
      LIST(1)=0
      IF(ICODE.EQ.1)  THEN
        IF(DSPDEV.EQ.2) THEN
           LIST(1)=256
        ELSE
           LIST(1)=12
        ENDIF
      ENDIF
      IF(ICODE.EQ.8)  LIST(1)=10
      IF(ICODE.EQ.16) LIST(1)=2
      IF(ICODE.EQ.17) LIST(1)=1        ! 3D CAPABILITY
      END
