      SUBROUTINE JDEVON(IDEVI)
C-----------------------------------------------------------------
C-  SUBROUTINE FOR SELECTING ACTIVE DEVICE
C-     IDEVI=1   SGI WORKSTATION
C-     IDEVI=2   HARDCOPY.
C-  NOTE:  IN THIS VERSION BOTH CANNOT BE ENABLED SIMULTANEOUSLY.
C-        WHEN HARDCOPY IS ENABLED, SCREEN DRAWING IS DISABLED.
C-
C-   Created XX-XXX-XXXX Mike shupe
C-   Updated  3-DEC-1992   Lupe Howell  Clean up
C-   Updated 12-APR-1993 Lupe Howell Clean up, Double Buffer fix  
C-----------------------------------------------------------------
      IMPLICIT NONE
C
      INTEGER IDEVI
C
      INCLUDE 'fgl.h'
      INCLUDE 'fdevice.h'
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      LOGICAL SETRAS,FIRST
      INTEGER IEXTW,ICOL,IERR
      REAL FX0,FY0,FWID,FHEI,LWINDO,LRWNDO 
C------------------------------------------------------------------
C
C *** /DIWNDW/ USED TO SET ABSOLUTE WINDOW POSITION IN 
C *** FRACTIONS OF SCRX,SCRY.
C
      COMMON/J_DIWNDW/IEXTW,FX0,FY0,FWID,FHEI
C
C *** /DI3CTL/ USED TO TRIGGER WINDOW RESETS IN JFRAME
C 
      COMMON/J_DI3CTL/LWINDO,LRWNDO
C
C *** DEFAULT COLOR INDICES COMMON TO DI3000 AND GL:
C *** 1-RED, 2-GREEN, 3-YELLOW, 4-BLUE, 5-MAGENTA, 6-CYAN, 7-WHITE
C *** DIFFERING CONVENTIONS:
C *** FOR DI3000 0-NORMAL (USUALLY WHITE)
C ***          8-BLACK
C ***          9-COMPLEMENT (USUALLY BLACK)
C *** FOR GL   0-BLACK
C ***          8,9-UNDEFINED INITIALLY
C *** BRIGHTER COLORS (1=RED, ETC):
C
      INTEGER RVC(8),GVC(8),BVC(8) 
      DATA RVC/255, 31,255, 31,255, 31,255,0/
      DATA GVC/ 31,255,255, 31, 31,255,255,0/
      DATA BVC/ 31, 31, 31,255,255,255,255,0/
      DATA LWINDO/3/
      DATA FIRST/.TRUE./
      SAVE
C------------------------------------------------------------------
      IDUBL=1
      IF(FIRST) THEN
        FIRST=.FALSE.
      ENDIF
C
C *** CHECK FOR DEVICE 2 (HARDCOPY)
C
      IDEVIC=IDEVI
      HCPY=.FALSE.
      IF(IDEVIC.EQ.2) GO TO 2000
C
      SETRAS=.FALSE.
      DI3DIN=1
      GO TO 1111
C-------------------------------------------------------------
C-   ENTRY J_SETRASP
C-------------------------------------------------------------
      ENTRY J_SETRASP
      SETRAS=.TRUE.
C
C *** GET X AND Y SIZE OF THE SCREEN IN PIXELS
C *** USUALLY SCRX=1280. AND SCRY=1024.
C
 1111 SCRX=GETGDE(GDXPMA)
      SCRY=GETGDE(GDYPMA)
C
C *** LWINDO 1=SMALL,2=MEDIUM,3=FULL SCREEN
C
      IF(LWINDO.EQ.1) THEN
        WIDTH=.8*SCRX
        HEIGHT=.8*SCRY
        IX1W=.01*SCRX
        IX2W=.81*SCRX
        IY1W=.17*SCRY
        IY2W=.97*SCRY
      ELSEIF(LWINDO.EQ.2) THEN
        WIDTH=.9*SCRX
        HEIGHT=.9*SCRY
        IX1W=.01*SCRX
        IX2W=.91*SCRX
        IY1W=.06*SCRY
        IY2W=.97*SCRY
      ELSE
        WIDTH=.79*SCRX
        HEIGHT=.80*SCRY
        IX1W=.005*SCRX
        IX2W=.795*SCRX
        IY1W=.17*SCRY
        IY2W=.97*SCRY
      ENDIF
      IF(IEXTW.EQ.0) GO TO 10
C
C *** EXTERNALLY SPECIFIED WINDOW
C
      IX1W=FX0*SCRX
      IY1W=FY0*SCRY
      WIDTH=FWID*SCRX
      HEIGHT=FHEI*SCRY
      IX2W=(FX0+FWID)*SCRX
      IY2W=(FY0+FHEI)*SCRY
C
C *** INITIALIZE VIEWSPACE AND VIEWPORT COORDS
C
   10 CONTINUE
      RASP=HEIGHT/WIDTH
      XMARG=0.
      YMARG=0.
      IF(SETRAS) RETURN
C
C *** PROTECT AGAINST MULTIPLE WINDOWS
C
      IF(WDID.GT.0) RETURN
C
C *** SET UP WINDOW SIZE AND POSITION
C
      CALL PREFPO(IX1W,IX2W,IY1W,IY2W)
      CALL FOREGR
C
C *** REWINDOW IF REQUESTED
C
      IF(LRWNDO.GT.0) THEN
        LRWNDO=0
        CALL WINCON
        RETURN
      ENDIF
C
C *** CREATE THE WINDOW
C
      LWDID=19
      WDID=WINOPE('SGI DI3000 Emulator',LWDID)
      CALL WINSET(WDID)
C
C *** DOUBLE BUFFER MODE
C
      CALL DOUBLE
C
C *** SET UP THE ABOVE CONFIGURATION
C
      CALL GCONFI()
      CALL JVSPAC(VCXMN,VCXMX,VCYMN,VCYMX)
C
C *** SET UP THE DEFAULT COLORS.  THE TACTIC HERE IS TO BRIGHTEN THE
C *** COLORS WITHOUT CHANGING THEIR MAP POSITIONS.  THE INCOMPATIBILITIES
C *** ARE THEN TAKEN CARE OF IN JCOLOR.     
C *** BLACK BACKGROUND
C
      CALL BACKBU(.FALSE.)
      CALL FRONTB(.TRUE.)
      CALL JCOLOR(9)
      CALL CLEAR
C
C *** WHITE LINES
C
      CALL JCOLOR(0)
C
C *** CONCAVE POLYGONS
C
C
C *** QUEUE THE KEYBOARD AND MOUSE BUTTONS
C
      CALL QDEVIC(KEYBD)
      CALL QDEVIC(LEFTMO)
      CALL QRESET()
      HCPY=.FALSE.
      RETURN
C--------------------------------------------------------------
      ENTRY REWINDOW
C--------------------------------------------------------------
      GO TO 1111
C
C ***  DEVICE 2 IS SELECTED.  HARDCOPY IS BEING DONE BY REPEATING ALL
C ***  CALLS (NOT FROM SEGMENT STORAGE PLAYBACK.)
C
 2000 CONTINUE
      PUTS=.FALSE.                 
      HCPY=.TRUE.
C                  
C *** COLOR HARDCOPY
C
      ICOL=1
      CALL J_HCOPY_BEGIN('SGI PIXIE GRAPHICS',ICOL,IERR)
      END
