      SUBROUTINE JLWIDE(LWIDE)
C  SET LINE WIDTH.  DEFAULT=16383.
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      INTEGER*4 WIDDLE
      WIDDLE=FLOAT(LWIDE-16383)*20./16383.
      IF(WIDDLE.LT.1) WIDDLE=1
C  WIDDLE IS THE WIDTH IN PIXELS
      IF(HCPY) THEN
        CALL DEV_LINEWI(WIDDLE)
      ELSE
        CALL LINEWI(WIDDLE)
      ENDIF
      END
