C DEC/CMS REPLACEMENT HISTORY, Element JIQTXT.FOR
C *1     3-JUN-1992 14:01:41 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JIQTXT.FOR
      SUBROUTINE JIQTXT(IDEV,CXSIZE,CYSIZE,ACTXSZ,ACTYSZ)
C  ANYTHING IS POSSIBLE?
      ACTXSZ=CXSIZE
      ACTYSZ=CYSIZE
      END
