C DEC/CMS REPLACEMENT HISTORY, Element JPAROB.FOR
C *1     3-JUN-1992 14:10:05 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JPAROB.FOR
      SUBROUTINE JPAROB(DU,DV,DN)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IPROJ=2
      IF(DI3DIN.GT.0) CALL J_PROJS
      END
