C DEC/CMS REPLACEMENT HISTORY, Element JVPORT.FOR
C *1     3-JUN-1992 14:54:56 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JVPORT.FOR
      SUBROUTINE JVPORT(X1,X2,Y1,Y2)
C  SPECIFY AND SETUP VIEWPORT
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      if(idebwr.gt.0) then
        write(idebwr,8008) x1,x2,y1,y2
 8008   format(' JVPORT - x1,x2,y1,y2:',4f)
      endif
      IF(IDEBUG.GT.0) TYPE *,' JVPORT:',X1,X2,Y1,Y2
      IF(IFSPAC.EQ.0) CALL JVSPAC(VCXMN,VCXMX,VCYMN,VCYMX)
      VXMIN=X1
      VXMAX=X2
      VYMIN=Y1
      VYMAX=Y2
      IF(HCPY) CALL DEV_VPORT(X1,X2,Y1,Y2)
      IF(DI3DIN.GT.0) CALL J_PROJS
      END
