C DEC/CMS REPLACEMENT HISTORY, Element JHILIT.FOR
C *1     3-JUN-1992 13:56:25 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JHILIT.FOR
      SUBROUTINE JHILIT
      ENTRY JDHILI
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
       WRITE(JUNIT,*)'JHILIT dummied'
      END
