C DEC/CMS REPLACEMENT HISTORY, Element JSGPRI.FOR
C *1     3-JUN-1992 14:48:14 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JSGPRI.FOR
      SUBROUTINE JSGPRI(NAME,SEGPRI)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      INTEGER NAME,SEGPRI
      IF(NSEGS.EQ.0)RETURN
      DO 10 I=1,NSEGS
        IF(NAME.NE.NUMSEG(I)) GO TO 10
        IFOUND=I
        GO TO 100
   10 CONTINUE
      RETURN
  100 ISPRIO(IFOUND)=SEGPRI
      END
