C DEC/CMS REPLACEMENT HISTORY, Element JCONPK.FOR
C *1     3-JUN-1992 13:22:10 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JCONPK.FOR
      SUBROUTINE JCONPK
C  CONTINUE PICK INPUT
      COMMON/J_DI3PR/JUNIT
C       WRITE(JUNIT,*)'JCONPK dummied'
      END
