C DEC/CMS REPLACEMENT HISTORY, Element JMSTRG.FOR
C *1     3-JUN-1992 14:07:26 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JMSTRG.FOR
      SUBROUTINE JMSTRG
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
C       WRITE(JUNIT,*)'JMSTRG dummied'
      END
