C DEC/CMS REPLACEMENT HISTORY, Element JDD3D.FOR
C *1     3-JUN-1992 13:28:29 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDD3D.FOR
      SUBROUTINE JDD3D(IYESNO)
C  TURN ON THE 3D HARDWARE
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      LOGICAL IYESNO
      IF(IYESNO) THEN
        ENAB3D=.TRUE.
      ELSE
        ENAB3D=.FALSE.
      ENDIF
      END
