C DEC/CMS REPLACEMENT HISTORY, Element JDLWID.FOR
C *1     3-JUN-1992 13:45:28 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDLWID.FOR
      SUBROUTINE JDLWID(LWDDF)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      ILWDDF=LWDDF
      CALL JLWIDE(LWDDF)
      END
