      SUBROUTINE JVLOAD(ARY)
C  ARY IS AT LEAST DIMENSION 85 EXTERNALLY
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      REAL ARY(*),RVW3(21),RVW4(14),RVW1(5),RHC4(16)
      EQUIVALENCE (RVW3,XVW),(RVW4,UMIN),(RVW1,IWCLIP)
      EQUIVALENCE (RHC4,WNX)
      DO I=1,21
        RVW3(I)=ARY(I)
      ENDDO
      DO I=1,14
        RVW4(I)=ARY(I+21)
      ENDDO
      DO I=1,5
        RVW1(I)=ARY(I+35)
      ENDDO
      DO I=1,16
        RHC4(I)=ARY(I+40)
      ENDDO
C  RESTORE ALL THE TRANSFORMATIONS
      CALL J_PROJS
      END
