C DEC/CMS REPLACEMENT HISTORY, Element JATTRB.FOR
C *1     3-JUN-1992 13:12:32 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JATTRB.FOR
      SUBROUTINE JATTRB(ICOD,IVAL)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IVAL=IJ1(ICOD+4)
      RETURN
      END
