      SUBROUTINE JROPEN(NAME)
C  OPEN A RETAINED SEGMENT
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      INTEGER GENOBJ
      DATA NSMXX/100/
C
      if(idebwr.gt.0) then
        write(idebwr,8008) name
 8008   format(' JROPEN - segment:',i)
      endif
      CALL JARSET
      IF(HCPY) RETURN
      IF(NSEGS.GE.NSMXX) GO TO 1000
      NSEGS=NSEGS+1
      ISEGNM=NAME
      IF(IDEBUG.GT.8)TYPE 888,NSEGS,NAME,RJ4
  888 FORMAT(' SEG',I2,I,/,'  WI:',4F,/,'  VP:',4F,/,'  VS:',4F)
      NUMSEG(NSEGS)=NAME
      NCALLS(NSEGS)=0
      ITTYP(NSEGS)=ITYPDF
      IDETEC(NSEGS)=IDETDF
C  GET AN OBJECT ID
      IDNOW=GENOBJ()
      OBJID(NSEGS)=IDNOW
C  "MAKE THE OBJECT"  (OPEN THE RETAINED SEGMENT)
      CALL MAKEOB(IDNOW)
C  SAVE THE WINDOWS FOR THIS SEGMENT
      DO I=1,4
        DO J=1,3
          RJ4SAV(I,J,NSEGS)=RJ4(I,J)
        ENDDO
      ENDDO
      RETURN
 1000 WRITE(JUNIT,*)'TOO MANY SEGMENTS. (NOT OPENED).'
      RETURN
 1010 WRITE(JUNIT,*)'SEGMENT STORAGE OVERFLOW'
      END
