C DEC/CMS REPLACEMENT HISTORY, Element JBGBAT.FOR
C *1     3-JUN-1992 13:15:05 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JBGBAT.FOR
      SUBROUTINE JBGBAT(LEVEL)
C  BEGIN A BATCH OF UPDATES.
      END
