C DEC/CMS REPLACEMENT HISTORY, Element JDETEC.FOR
C *1     3-JUN-1992 13:30:28 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDETEC.FOR
      SUBROUTINE JDETEC(NAME,DETVAL)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      INTEGER NAME,DETVAL
      DO 10 I=1,NSEGS
        IF(NAME.NE.NUMSEG(I)) GO TO 10
        IDETEC(I)=DETVAL
   10 CONTINUE
      END
