C DEC/CMS REPLACEMENT HISTORY, Element JPECHO.FOR
C *1     3-JUN-1992 14:11:06 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JPECHO.FOR
      SUBROUTINE JPECHO(DSPDEV,INPFCT,PHYDEV,VX,VY)
      INTEGER DSPDEV,PHYDEV
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IF(INPFCT.LT.1.OR.INPFCT.GT.6) RETURN
      XECHO(INPFCT)=VX
      YECHO(INPFCT)=VY
      END
