C DEC/CMS REPLACEMENT HISTORY, Element JPICK.FOR
C *1     3-JUN-1992 14:14:56 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JPICK.FOR
      SUBROUTINE JPICK(DSPDEV,PHYDEV,ECHOLV,BUTTON,SEGNAM,PICKID)
C  VIRTUAL PICK FUNCTION
      INTEGER DSPDEV,PHYDEV,ECHOLV,BUTTON,SEGNAM,PICKID
      CALL JLOCAT(DSPDEV,PHYDEV,ECHOLV,BUTTON,VX,VY)
      CALL JSPICK(VX,VY,DSPDEV,SEGNAM,PICKID)
      END
