C DEC/CMS REPLACEMENT HISTORY, Element JPAUSE.FOR
C *1     3-JUN-1992 14:10:34 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JPAUSE.FOR
      SUBROUTINE JPAUSE(J)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      type *,' In JPAUSE'
      IF(HCPY) RETURN
      IF(ENAB3D) THEN
        CALL J_MENU3D
      ELSE
        PAUSE
      ENDIF
      END
