C DEC/CMS REPLACEMENT HISTORY, Element JMODEL.FOR
C *1     3-JUN-1992 14:05:58 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JMODEL.FOR
      SUBROUTINE JMODEL(MATRIX)
C  ENABLE MODELING MATRIX (MAKE IT THE DEFAULT)
      REAL MATRIX(4,4)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      CALL LOADMA(MATRIX)
      CALL GETMAT(MMODEL)
      END
