C DEC/CMS REPLACEMENT HISTORY, Element JPEROB.FOR
C *1     3-JUN-1992 14:13:31 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JPEROB.FOR
      SUBROUTINE JPEROB(DU,DV,DN)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IPROJ=4
      VDIST=DN
      IF(DI3DIN.GT.0) CALL J_PROJS
      END
