C DEC/CMS REPLACEMENT HISTORY, Element JPKAPR.FOR
C *1     3-JUN-1992 14:17:05 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JPKAPR.FOR
      SUBROUTINE JPKAPR(DSPDEV,PHYDEV,DX,DY)
C  DEFINE THE SIZE OF THE PICK APERTURE (0.0001 TO 1.000)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      PDXAPR=DX
      PDYAPR=DY
      END
