C DEC/CMS REPLACEMENT HISTORY, Element JSECTR.FOR
C *1     3-JUN-1992 14:46:00 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JSECTR.FOR
      SUBROUTINE JSECTR(X0,Y0,Z0,RADIUS,NSEG,A0,A1)
      CALL JARC(X0,Y0,Z0,RADIUS,NSEG,A1,A0)
      END
