C DEC/CMS REPLACEMENT HISTORY, Element JDMARK.FOR
C *1     3-JUN-1992 13:46:03 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDMARK.FOR
      SUBROUTINE JDMARK(IDDD)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IMRKDF=IDDD
      CALL JMARK(IDDD)
      END
