C DEC/CMS REPLACEMENT HISTORY, Element JIESCP.FOR
C *1     3-JUN-1992 13:58:48 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JIESCP.FOR
      SUBROUTINE JIESCP
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
C       WRITE(JUNIT,*)'JIESCP dummied'
      END
