C DEC/CMS REPLACEMENT HISTORY, Element JDPIDX.FOR
C *1     3-JUN-1992 13:46:29 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JDPIDX.FOR
      SUBROUTINE JDPIDX(DCOLOR,DINTEN)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      INTEGER DCOLOR,DINTEN
      ICLRDF=DCOLOR
      IINTDF=DINTEN
      END
