      SUBROUTINE JBASE(X,Y,Z)
C  BASE AND PLANE VECTORS FOR TEXT
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      R2=X*X+Y*Y+Z*Z
      IF(R2.LE.0)THEN
        WRITE(JUNIT,*)'JBASE CALLED WITH ZERO VECTOR'
        RETURN
      ENDIF
      XBASE=X
      YBASE=Y
      ZBASE=Z
      R=SQRT(R2)
      XBASEN=XBASE/R
      YBASEN=YBASE/R
      ZBASEN=ZBASE/R
      END
