      SUBROUTINE JR3DRA(X,Y,Z)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      VPOSN(1)=VPOSN(1)+X
      VPOSN(2)=VPOSN(2)+Y
      VPOSN(3)=VPOSN(3)+Z
      IF(HCPY) THEN
        CALL DEV_DRAW(VPOSN(1),VPOSN(2),VPOSN(3))
        RETURN
      ENDIF
      CALL DRAW(VPOSN(1),VPOSN(2),VPOSN(3))
      END
