C DEC/CMS REPLACEMENT HISTORY, Element JSETER.FOR
C *1     3-JUN-1992 14:47:31 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JSETER.FOR
      SUBROUTINE JSETER(I)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      IERROR=I
      END
