C DEC/CMS REPLACEMENT HISTORY, Element JHSTRG.FOR
C *1     3-JUN-1992 13:57:23 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element JHSTRG.FOR
      SUBROUTINE JHSTRG(STRING)
      CHARACTER*(*)STRING
      CALL J3STRG(STRING)        !PRINT STRING
      END
