C DEC/CMS REPLACEMENT HISTORY, Element J4RGET.FOR
C *1     3-JUN-1992 13:05:51 LUPE "Release of DI3GL after split"
C DEC/CMS REPLACEMENT HISTORY, Element J4RGET.FOR
      SUBROUTINE J4RGET(ICOD,V1,V2,V3,V4)
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      V1=RJ4(1,ICOD)
      V2=RJ4(2,ICOD)
      V3=RJ4(3,ICOD)
      V4=RJ4(4,ICOD)
      END
