      SUBROUTINE TK_MOVE(X,Y,Z)
C  World coordinates
      INCLUDE 'D0$GRAPHICS_UTIL$SGIDI3:DI3GL.INC'
      COMMON/J_TKTEM/X1,Y1,X2,Y2
      CALL DEV_TRANSF(X,Y,Z,X1,Y1)
      XPOSN=X
      YPOSN=Y
      ZPOSN=Z
      END
