	SUBROUTINE SAGFDCMTCH(LMUKF,DIR,LFT,DIST,DIST2,FFIT,FINF,
     +			ISEG,KFIT,KINF)
	IMPLICIT NONE
	INCLUDE 'D0$INC:ZEBCOM.INC/LIST'
	INCLUDE 'D0$INC:ZEBSTP.INC'
	INCLUDE 'D0$INC:PI.DEF'
C<<
	REAL	KFIT(5),KERR(5,5),ZKFIT,KINF(5,5),
     +		FFIT(5),FINF(5,5)
C     +	  	KFITV(5),KERRV(5,5),ZKFITV,CHI2V,BDLV,KINFV(5,5),
	INTEGER IOK,DIR,I,J,K,LFT
	INTEGER	LFDCT,GZFDCT,IMIN,LMUKF,VERS,NP
	REAL	DIST,DIST2,Z0
	REAL	MINDIST,FBFIT(5),FBINF(5,5)
	REAL	MIN2DIST
	REAL	KFDIST,CHI2,BDL
	INTEGER	NSEG,ISEG,NH
C
	IF(LMUKF.LE.0) GOTO 999
c
	I = 1
	IMIN = -1
	MINDIST = 1.E15
	MIN2DIST = 1.E15
	DIST = MINDIST
	DIST2 = 0.
C-
C-	Fetch SAMUS track info
C-
	NSEG = 0
	CALL	GTMUKF(LMUKF,0,NSEG,VERS,NP,NH,ZKFIT,CHI2,BDL,KFIT,KERR)
	IF(VERS.NE.1) GOTO 999
	IF(NSEG.LT.2) GOTO 999
	ISEG = NSEG-1		! The last segment is for G.F.
	CALL	GTMUKF(LMUKF,0,ISEG,VERS,NP,NH,ZKFIT,CHI2,BDL,KFIT,KERR)
	IF(NP.NE.5) GOTO 999
	IF(KFIT(5).EQ.0.) GOTO 999
C-
	CALL UCOPY(KERR,KINF,25)
	CALL RSINV(5,KINF,5,IOK)
	IF(IOK.NE.0) GOTO 999
C-
C-	Find track
C-
	DO WHILE(I.GT.0)
	    LFDCT = GZFDCT(I)
	    IF(LFDCT.LE.0) THEN
		IOK = -1
		I = -2
		GOTO 100
	    END IF
C
C	Check it
C
	    IF( IQ(LFDCT-5).NE.I ) GOTO 100
	    IF( BTEST(IQ(LFDCT+1),1) ) GOTO 100	! For now ...
	    CALL FGETZ0(I,Z0)
	    IF(Z0.LT.0. .AND. DIR.EQ.2
     +	      .OR. Z0.GT.0. .AND. DIR.EQ.1 ) GOTO 100
c-
c-	Make FDC information matrix
c-
	    CALL    VZERO(FINF,25)
	    FINF(1,1) = Q(LFDCT+9)
	    FINF(1,2) = Q(LFDCT+10)
	    FINF(1,3) = Q(LFDCT+11)
	    FINF(1,4) = Q(LFDCT+12)
	    FINF(2,2) = Q(LFDCT+13)
	    FINF(2,3) = Q(LFDCT+14)
	    FINF(2,4) = Q(LFDCT+15)
	    FINF(3,3) = Q(LFDCT+16)
	    FINF(3,4) = Q(LFDCT+17)
	    FINF(4,4) = Q(LFDCT+18)
	    FINF(5,5) = 1.
	    DO J=1,4
		DO K=J+1,4
		    FINF(K,J) = FINF(J,K)
		END DO
	    END DO
	    CALL RSINV(5,FINF,5,IOK)
	    IF(IOK.NE.0) GOTO 100
	    FINF(5,5) = 0.
	    FFIT(1) = Q(LFDCT+4)
	    FFIT(2) = Q(LFDCT+5)
	    FFIT(3) = Q(LFDCT+7)
	    FFIT(4) = Q(LFDCT+8)
	    FFIT(5) = KFIT(5)
	    CALL    KFPROP(0,Z0,FFIT,FINF,ZKFIT,FFIT,FINF)
	    DIST = KFDIST(FFIT,FINF,KFIT,KINF)
	    IF( DIST.GE.0. ) THEN
		IF(DIST.LT.MINDIST) THEN
		    IMIN = I
		    MIN2DIST = MINDIST
		    MINDIST = DIST
		    LFT = LFDCT
		    CALL UCOPY(FFIT,FBFIT,5)
		    CALL UCOPY(FINF,FBINF,25)
		ELSE IF(DIST.LT.MIN2DIST) THEN
		    MIN2DIST = DIST
		END IF
	    END IF
 100	    CONTINUE
	    I = I+1
	END DO
C<<
	IF( IMIN.GT.0 ) THEN
	    CALL UCOPY(FBINF,FINF,25)
	    CALL UCOPY(FBFIT,FFIT,5)
	    DIST = MINDIST
	    DIST2 = MIN2DIST
	    IOK = 0
	END IF
 999	CONTINUE
	RETURN
	END	
