      SUBROUTINE KDECN(STR,INUM)
      IMPLICIT NONE
      INTEGER BASE
      PARAMETER (BASE=37)
      INTEGER INUM, STRL, I, JNDX
      CHARACTER*(*) STR
      CHARACTER*(BASE) VALS
      DATA VALS/'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ$'/

      STRL = LEN(STR)
      INUM = 0
      DO 10 I=1,STRL
         JNDX = INDEX(VALS,STR(I:I))
         IF (JNDX .EQ. 0) RETURN
         INUM = INUM * BASE + JNDX - 1
   10 CONTINUE
      RETURN
      END
