PACKAGE := compack
$(PACKAGE)_LIB := yes
include GNUmakefile.subcommon

COMPACK_NO_RANGE_CHECK := gethlp reaset readme keydef curso1 diabox libind chkcom conhex greads windis
$(foreach f,$(COMPACK_NO_RANGE_CHECK),tmp/DEB/compack/source/$(f).o tmp/OPT/compack/source/$(f).o) : F77_COMMON_FLAGS += -fno-range-check
