CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VCOMPACK()
      VCOMPACK = ' COMPACK'//
     X                   '  TEST V4.33_01'//
     X                   ' 13-AUG-1997 10:08:30.03'
      Return
      End
