      SUBROUTINE JR3MOV(X,Y,Z)
      REAL X,Y,Z
      INCLUDE 'D0$INC:DI3INC.INC'
      XPOSN=XPOSN+X
      YPOSN=YPOSN+Y
      ZPOSN=ZPOSN+Z
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IR3MOV,X)
      CALL J_PUTSG(IR3MOV,Y)
      CALL J_PUTSG(-IR3MOV,Z)
      IF(IPICID.NE.0) CALL J_PIKDO(XPOSN,YPOSN,ZPOSN)
      END
