      SUBROUTINE JDJUST(IHORIZ,IVERT)
      INCLUDE 'D0$INC:DI3INC.INC'
      IF(IHORIZ.LT.1.OR.IHORIZ.GT.3)THEN
        WRITE(JUNIT,*)'JDJUST HORIZONTAL NO GOOD:',IHORIZ
        RETURN
      ENDIF
      IF(IVERT.LT.1.OR.IVERT.GT.3)THEN
        WRITE(JUNIT,*)'JDJUST VERTICAL NO GOOD:',IVERT
        RETURN
      ENDIF
      IHJUDF=IHORIZ
      IVJUDF=IVERT
      CALL JJUST(IHORIZ,IVERT)
      END
