      SUBROUTINE JIQTXT(IDEV,CXSIZE,CYSIZE,ACTXSZ,ACTYSZ)
C  FIND ACTUAL SIZE OF FONT NEAREST TO (SMALLER THAN) DESIRED SIZE
      COMMON/FSIZES/FSIZE(14),FONT_ID(14),GR_FONT   ! Font file names
      CHARACTER*32 FONT_ID,GR_FONT
C  ANYTHING IS POSSIBLE?
      ACTXSZ=CXSIZE
      ACTYSZ=CYSIZE
      END
