      SUBROUTINE JPIDEX(ICOLR,INTEN)
C  CURRENT POLYGON INTERIOR COLOR AND INTENSITY (12,13)
      INCLUDE 'D0$INC:DI3INC.INC'
      IPCOLO=ICOLR
      IPINT=INTEN
      IF(.NOT.PUTS) RETURN
      CALL J_PUTSG(IJPCOL,ICOLR)
      CALL J_PUTSG(-IJPCOL,INTEN)
      END
