      SUBROUTINE JRMARK(X,Y)
      REAL X,Y
      INCLUDE 'D0$INC:DI3INC.INC'
      XNOW=X+XPOSN
      YNOW=Y+YPOSN
      PUTSUP=.TRUE.
      CALL JMARK(XNOW,YNOW)
      PUTSUP=.FALSE.
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IRMARK,X)
      CALL J_PUTSG(-IRMARK,Y)
      IF(IPICID.NE.0) CALL J_PIKDO(XNOW,YNOW,0.)
      END
