      SUBROUTINE J3POLY(X,Y,Z,N)
      INCLUDE 'D0$INC:DI3INC.INC'
      REAL X(2000),Y(2000),Z(2000)
      INTEGER I,N
C
      IF(N.GT.1999) GO TO 1000
	CALL J_TR3XYZ(XPOSN,YPOSN,ZPOSN,XPOLY(1),YPOLY(1),ZPOLY(1))
      DO 500 I=1,N
        CALL J_TR3XYZ(X(I),Y(I),Z(I),XPOLY(I+1),YPOLY(I+1)
     &         ,ZPOLY(I+1))
  500 CONTINUE
      NN=N+1
      CALL J_PLOT_ARRAY(VD_ID,ATB,NN,XPOLY,YPOLY)
      XPOSN=X(N)
      YPOSN=Y(N)
      ZPOSN=Z(N)
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSGN_i(I3POLY,1,N)
      CALL J_PUTSGN(I3POLY,N,X)
      CALL J_PUTSGN(I3POLY,N,Y)
      CALL J_PUTSGN(-I3POLY,N,Z)
      IF(IPICID.EQ.0) RETURN
      DO 3000 II=1,N
        CALL J_PIKDO(X(II),Y(II),Z(II))
 3000 CONTINUE
 1000 RETURN
      END
