      SUBROUTINE JCVIEW(XVRP,YVRP,ZVRP,XEYE,YEYE,ZEYE,VANGLE)
      INCLUDE 'D0$INC:DI3INC.INC'
      ACONV=3.1415927/180.
      XVW=XVRP
      YVW=YVRP
      ZVW=ZVRP
      XPROJ=XEYE
      YPROJ=YEYE
      ZPROJ=ZEYE
      DX=XVRP-XEYE
      DY=YVRP-YEYE
      DZ=ZVRP-ZEYE
      DN = SQRT(DX**2+DY**2+DZ**2)
      CALL JNORML(DX,DY,DZ)
C SET UP DEFAULT OR REQUESTED WINDOW
      VNG=15.*ACONV
      IF(VANGLE.GT.0.) VNG=VANGLE*ACONV/2.
C  SYMMETRICAL FOR NOW. (ANY OTHER CASE?)
      TN=TAN(VNG)
      VMX=DN*TN
      VMN=-VMX
      ASP=(VMAX-VMIN)/(UMAX-UMIN)
      UMX=VMX*ASP
      UMN=VMN*ASP
      CALL JWINDO(UMN,UMX,VMN,VMX)
      CALL JPERSP(DN)
      END
