      SUBROUTINE JISGMT(NAME,AARRAY)
      INCLUDE 'D0$INC:DI3INC.INC'
      INTEGER NAME,AARRAY(19)
      DO 10 I=1,19
        AARRAY(I)=0
  10  CONTINUE
      IF(NSEGS.EQ.0) RETURN
      DO 100 I=1,NSEGS
        IF(NAME.NE.NUMSEG(I)) GO TO 100
        IFOUND=I
        GO TO 200
  100 CONTINUE
      RETURN
C  SEGMENT EXISTS
  200 AARRAY(1)=1
      AARRAY(2)=IVIS(IFOUND)
      AARRAY(3)=IDETEC(IFOUND)
      AARRAY(5)=ITTYP(IFOUND)
C  THERE MAY BE MORE OF THESE IN THE FUTURE!!!
      END
