      SUBROUTINE J3STRG(STRING)
      INCLUDE 'D0$INC:DI3INC.INC'
      COMMON/FRAME/LFRAME,LENST
      LOGICAL LFRAME
      CHARACTER*(*) STRING
      INCLUDE 'D0$INC:VAXFONT.INC'
      CHARACTER*1 CHAR(0:127)
      CHARACTER*1 CHR
      LOGICAL*1 BCHR
      EQUIVALENCE(CHR,BCHR)
      INTEGER DI3CBD,DI3CHR
      INTEGER*4 ASAVE
      REAL X0,Y0,X,Y,XX,YY,ZZ,JCP(3),X1,Y1
C  IF THIS IS CALLED BY JFRAME, GET STRING LENGTH FROM SEGMENT STORAGE
      LENSTR=LEN(STRING)
      IF(LFRAME) LENSTR=LENST
C  SHUT OFF SEGMENT STORAGE OF STROKES. JUST STORE STRING
      PUTSUP=.TRUE.
      XSAVE=XPOSN                   !GET COPY OF ORIG POSITION
      YSAVE=YPOSN
      ZSAVE=ZPOSN
      X0=-.5*(IHJUST-1)*LENSTR      !HORIZ JUSTIF on drwg plane (CHAR UNITS)
      Y0=-.5*(IVJUST-1)             !VERT JUSTIF on drwg plane
      DO 700 ICC=1,LENSTR
        CHR=STRING(ICC:ICC)
        IASCII=BCHR
        IASCII=iand(IASCII,255)       !8 BITS
        IF(IASCII.GT.133)IASCII=32  !UNPRINTABLE
        IF(IASCII.LT.32)IASCII=32   !UNPRINTABLE
        DO 100 I=1,16
          IC=ICHAR(I,IASCII)
          IF(IC.GE.128)GOTO 200           !TERMINATOR
          X=X0+(1./6.)*(1+iand((IC/8),7))
          X=X*XSIZE*.95                   !X SIZE
          Y=Y0+(1./9.)*(1+iand(IC,7))
          Y=Y*YSIZE                       !Y SIZE
          XPOS=XSAVE+X*XBASEN+Y*XPLANN
          YPOS=YSAVE+X*YBASEN+Y*YPLANN
          ZPOS=ZSAVE+X*ZBASEN+Y*ZPLANN
C!!!!          IF(IFONT.EQ.1) GO TO 16
C  ITALISIZED
C!!!!DEBUG
C!!!!          XPOS=XPOS+.414*Y*XBASEN
C!!!!  16 CONTINUE
          IF(iand(IC,64).NE.0)THEN
            CALL J3MOVE(XPOS,YPOS,ZPOS)
          ELSE
            ASAVE=ATB
            ATB=ATB_TXT
C!!!PUT IN A 2D FLAG TO SPEED UP
            CALL J3DRAW(XPOS,YPOS,ZPOS)
            ATB=ASAVE
          ENDIF
  100   CONTINUE
  200   CONTINUE
C  X POSN FOR NEXT CHARACTER
        X0=X0+1.
  700 CONTINUE
      YPOSN=YSAVE
      XPOSN=XPOSN+.190*XSIZE
C  UNSUPPRESS STROKE WRITING
      PUTSUP=.FALSE.
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSTR(I3STRG,LENSTR,STRING)
      IF(IPICID.EQ.0)RETURN
      CALL J_PIKDO(XSAVE,YSAVE,ZPOSN)
      CALL J_PIKDO(XPOSN,YSAVE+.2*YSIZE,ZPOSN)
      END
