      SUBROUTINE JLSTYL(LSTYL)
      INCLUDE 'D0$INC:DI3INC.INC'
      ILSTYL=LSTYL
      IF(PUTS) CALL J_PUTSG(-IJSTYL,ILSTYL)
      LL=MOD(LSTYL,10)+1
      GO TO (1,2,3,4,5,6,7,8,9,10)LL
    1 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'FFFFFFFF'X)
      RETURN
    2 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'F0F0F0F0'X)
      RETURN
    3 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'55555555'X)
      RETURN
    4 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'F5F5F5F5'X)
      RETURN
    5 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'33333333'X)
      RETURN
    6 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'FF00FF00'X)
      RETURN
    7 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'FF33FF33'X)
      RETURN
    8 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'FFF5FFF5'X)
      RETURN
    9 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'FFF0FFF0'X)
      RETURN
   10 CALL J_SET_LINE_STYLE(VD_ID,ATB,ATB,'FFFFFFF0'X)
      RETURN
      END
