      SUBROUTINE J_PUTSG(IDSUBR,VAL)
C  PUT DISPLAY LIST STUFF INTO SEGMENT BLOC STORAGE
      INCLUDE 'D0$INC:DI3INC.INC'
      DATA IDCUR/0/
      IF(IFMODE.EQ.1)RETURN
      IF(IABS(IDSUBR).EQ.IDCUR) GO TO 10
      IBLOC(ISPTR)=IABS(IDSUBR)
      ISPTR=ISPTR+1
      IDCUR=IDSUBR
      IF(ISPTR.EQ.NBLOCX) GO TO 1000
   10 SBLOC(ISPTR)=VAL
      ISPTR=ISPTR+1
      IF(ISPTR.EQ.NBLOCX) GO TO 1000
      IF(IDSUBR.GE.0) RETURN
      IDCUR=0
      NCALLS(NSEGS)=NCALLS(NSEGS)+1
      RETURN
 1000 WRITE(JUNIT,*)' J_PUTSG--SEGMENT STORAGE OVERFLOW'
C  BE DRASTIC FOR NOW
      CALL JRCLOS
      NSEGS=0
      ISPTR=1
      RETURN
      END
