      SUBROUTINE JSAALL(IDEV,IFLAG)
      IF(IDEV.NE.2.OR.IFLAG.NE.1) RETURN
C  REDRAW THE SCREEN.  UIS DISPLAY LIST HAS BEEN ENABLED IN
C  JDEVON(2), AND JDEVOF(2) WILL OUTPUT THE UIS FILE WHEN CALLED.
      CALL JFRAME
      END
