      SUBROUTINE JRDRAW(X,Y)
      REAL*4 X,Y,XNEW,YNEW,XNOW,YNOW,XOLD,YOLD
      INCLUDE 'D0$INC:DI3INC.INC'
C
      XNOW=XPOSN+X
      YNOW=YPOSN+Y
      CALL J_TR2XY(XPOSN,YPOSN,XOLD,YOLD)
      CALL J_TR2XY(XNOW,YNOW,XNEW,YNEW)
      CALL J_LINE2(VD_ID,ATB,XOLD,YOLD,XNEW,YNEW)
      XPOSN=XNOW
      YPOSN=YNOW
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IRDRAW,X)
      CALL J_PUTSG(-IRDRAW,Y)
      IF(IPICID.NE.0) CALL J_PIKDO(XNOW,YNOW,0.)
      RETURN
      END
