      SUBROUTINE JCLEAR
C  PURGE DISPLAY SURFACES AND SEGMENT STORAGE
      INCLUDE 'D0$INC:DI3INC.INC'
      CALL J_ERASE(VD_ID)
      ISEGNM=-1
      NSEGS=0
      ISPTR=1
      PUTS=.FALSE.
      END
