      SUBROUTINE JPURGE(NAME)
C  DELETE A RETAINED SEGMENT
      INCLUDE 'D0$INC:DI3INC.INC'
      IF(NSEGS.EQ.0) GO TO 1000
      IF(NSEGS.EQ.1) GO TO 2000
      DO 10 I=1,NSEGS
        IF(NAME.NE.NUMSEG(I))GO TO 10
        NS=I
        GO TO 20
   10 CONTINUE
      GO TO 1000
C  FOUND IT
   20 CONTINUE
C  COPY BACK, THROUGH LAST SEGMENT
      NNEXT=NS+1
      I1=INDS1(NS)
      I2=INDS1(NNEXT)
      I12=I2-I1
      DO 40 NSNOW=NNEXT,NSEGS
        NPREV=NSNOW-1
        NUMSEG(NPREV)=NUMSEG(NSNOW)
        IVIS(NPREV)=IVIS(NSNOW)
        INDS1(NPREV)=INDS1(NSNOW)
        NCALLS(NPREV)=NCALLS(NSNOW)
        ITTYP(NPREV)=ITTYP(NSNOW)
        IDETEC(NPREV)=IDETEC(NSNOW)
   40 CONTINUE
      DO 50 II=I2,ISPTR
        SBLOC(I1)=SBLOC(II)
        I1=I1+1
   50 CONTINUE
      ISPTR=ISPTR-I12
      NSEGS=NSEGS-1
      RETURN
   30 ISPTR=1
      RETURN
 1000 WRITE(JUNIT,*)'SEG. # DOESNT EXIST'
      RETURN
 2000 ISPTR=1
      NSEGS=0
      ISEGNM=-1
      END
