      SUBROUTINE J3PLGN(X,Y,Z,N)
      INCLUDE 'D0$INC:DI3INC.INC'
      REAL X(2),Y(2),Z(2)
      LOGICAL PUTSV
      IF(N.LE.0.OR.N.GT.1999)RETURN
      PUTSV=PUTS
      PUTS=.FALSE.
      XSAVE=XPOSN
      YSAVE=YPOSN
      ZSAVE=ZPOSN
      XTEM=X(1)
      YTEM=Y(1)
      ZTEM=Z(1)
      NN=N+1
      DO 500 I=1,N
        CALL J_TR3XYZ(X(I),Y(I),Z(I),XPOLY(I),YPOLY(I),ZPOLY(I))
  500 CONTINUE
      CALL J_TR3XYZ(XTEM,YTEM,ZTEM,XPOLY(NN),YPOLY(NN),ZPOLY(NN))
      IF(IPSTYL.EQ.0)GO TO 630
      CALL JCOLOR(IPCOLO)
      CALL J_PLOT_ARRAY(VD_ID,ATB_PLY,NN,XPOLY,YPOLY)
      IF(IPEDGE.GT.0) GO TO 620
      CALL JCOLOR(0)
  630 CALL J_PLOT_ARRAY(VD_ID,ATB,NN,XPOLY,YPOLY)
  620 XPOSN=XSAVE
      YPOSN=YSAVE
      ZPOSN=ZSAVE
      CALL JCOLOR(ICOLOR)
      IF(.NOT.PUTSV)RETURN
      PUTS=.TRUE.
      CALL J_PUTSGN_i(I3PLGN,1,N)
      CALL J_PUTSGN(I3PLGN,N,X)
      CALL J_PUTSGN(I3PLGN,N,Y)
      CALL J_PUTSGN(-I3PLGN,N,Z)
      IF(IPICID.EQ.0) RETURN
      DO 3000 II=1,N
        CALL J_PIKDO(X(II),Y(II),Z(II))
 3000 CONTINUE
 1000 RETURN
      END
