      SUBROUTINE JDRAW(X,Y)
      REAL*4 X,Y,XPR,YPR,XOLD,YOLD
      INCLUDE 'D0$INC:DI3INC.INC'
      CALL J_TR2XY(XPOSN,YPOSN,XOLD,YOLD)
      CALL J_TR2XY(X,Y,XPR,YPR)
      CALL J_LINE2(VD_ID,ATB,XOLD,YOLD,XPR,YPR)
      XPOSN=X
      YPOSN=Y
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(I2DRAW,X)
      CALL J_PUTSG(-I2DRAW,Y)
      IF(IPICID.NE.0) CALL J_PIKDO(X,Y,Z)
      RETURN
      END
