      SUBROUTINE JOPEN
C  OPEN TEMPORARY SEGMENT
      INCLUDE 'D0$INC:DI3INC.INC'
      LOGICAL RECALC,FIRST
      DATA FIRST/.TRUE./
C  OPEN NON-RETAINED SEGMENT (0)
      ISEGNM=0
      PUTS=.FALSE.
C  RESET TO DEFAULTS
      CALL JARSET
C  CALCULATE NORMAL VECTOR
C      IF(RECALC.OR.FIRST)CALL DI3CBS
C      FIRST=.FALSE.
C  GET CRT 0,0 COORDS FROM WORLD COORDS 0,0,0
C      CALL J_TR3XYZ(XPOSN,YPOSN,ZPOSN,CRTX,CRTY,DUM)
C
      IF(IDEBUG.GE.3)CALL J_DUMP
      END
