      SUBROUTINE JRMOVE(X,Y)
      REAL X,Y
      INCLUDE 'D0$INC:DI3INC.INC'
      XPOSN=XPOSN+X
      YPOSN=YPOSN+Y
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IRMOVE,X)
      CALL J_PUTSG(-IRMOVE,Z)
      END
