      SUBROUTINE J_DEVMAT
C  PARAMETERS FOR CONVERSION TO SCREEN COORDINATES
      COMMON/SCRTRN/XSCALE,YSCALE,XSCALS,YSCALS
      INCLUDE 'D0$INC:DI3INC.INC'
C
C  CONVERT TO VIEWPORT COORDINATES
      DVX=VXMAX-VXMIN
      DU=UMAX-UMIN
      IF(DU.EQ.0.) DU=1.
      XSCALE=DVX/DU
      DVY=VYMAX-VYMIN
      DV=VMAX-VMIN
      IF(DV.EQ.0.) DV=1.
      YSCALE=DVY/DV
C  CONVERT TO SCREEN COORDS
      DX=WIDTH-2.*XMARG
      DCX=VCXMX-VCXMN
      IF(DCX.EQ.0.) DCX=1.
      XSCALS=DX/DCX
      DY=HEIGHT-2.*YMARG
      DCY=VCYMX-VCYMN
      IF(DCY.EQ.0.) DCY=1.
      YSCALS=DY/DCY
C  DONE, NOW TRIGGER
      IMDEV=1
      ITRANS=1
      RETURN
      END
