      SUBROUTINE JCONWV(X,Y,Z,VX,VY)
C  CONVERT WORLD TO VIRTUAL WINDOW COORDINATES
      COMMON/SCRTRN/XSCALE,YSCALE,XSCALS,YSCALS
      INCLUDE 'D0$INC:DI3INC.INC'
C  TO ORIGIN OF UVN SYSTEM
   10 XTR=X-XVW
      YTR=Y-YVW
      ZTR=Z-ZVW
C  ROTATE TO UVN AXES
C      XP=XTR*UVECX+YTR*UVECY+ZTR*UVECZ
C      YP=XTR*VVECX+YTR*VVECY+ZTR*VVECZ
C      ZP=XTR*VNORMX+YTR*VNORMY+ZTR*VNORMZ
      XP=XTR
      YP=YTR
C      IF(IPROJ.NE.3)GO TO 20
C  THIS IS A PERSPECTIVE TRANSFORMATION.
C      SFACTR=VDIST/(VDIST+ZP)
C      XP=SFACTR*XP
C      YP=SFACTR*YP
C  (OBLIQUE TRANSFORMATIONS NOT IMPLEMENTED YET)
C  TRANSFORM TO VIEWPORT COORDINATES
   20 VX=(XP-UMIN)*XSCALE+VXMIN
      VY=(YP-VMIN)*YSCALE+VYMIN
      END
