      SUBROUTINE JPOLY(X,Y,N)
C  PLOT A POLYLINE
      INCLUDE 'D0$INC:DI3INC.INC'
      REAL X(2),Y(2)
C
      IF(N.GT.1999) GO TO 1000
      CALL J_TR2XY(XPOSN,YPOSN,XPOLY(1),YPOLY(1))
      DO 500 I=1,N
        CALL J_TR2XY(X(I),Y(I),XPOLY(I+1),YPOLY(I+1))
  500 CONTINUE
      NN=N+1
      CALL J_PLOT_ARRAY(VD_ID,ATB,NN,XPOLY,YPOLY)
      XPOSN=X(N)
      YPOSN=Y(N)
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSGN_i(I2POLY,1,N)
      CALL J_PUTSGN(I2POLY,N,X)
      CALL J_PUTSGN(-I2POLY,N,Y)
      IF(IPICID.EQ.0)RETURN
      DO 3000 II=1,N
        CALL J_PIKDO(X(II),Y(II),0.)
 3000 CONTINUE
 1000 RETURN
      END
