      SUBROUTINE J_PUTSTR(IDSUBR,LEN,STRING)
C  PUT CHARACTER STRING INTO SEGMENT STORAGE
      CHARACTER*(*) STRING
      CHARACTER*120 STR
      INTEGER*4 ISTR(30)
      EQUIVALENCE (STR,ISTR)
      INCLUDE 'D0$INC:DI3INC.INC'
      IF(LEN.EQ.0) RETURN
      IBLOC(ISPTR)=IABS(IDSUBR)
      ISPTR=ISPTR+1
      IF(ISPTR.EQ.NBLOCX) GO TO 1000
      IBLOC(ISPTR)=LEN
      ISPTR=ISPTR+1
      IF(ISPTR.EQ.NBLOCX) GO TO 1000
      NWDS=(LEN-1)/4+1
      STR=STRING
      DO 10 I=1,NWDS
        IBLOC(ISPTR)=ISTR(I)
        ISPTR=ISPTR+1
        IF(ISPTR.EQ.NBLOCX) GO TO 1000
   10 CONTINUE
      NCALLS(NSEGS)=NCALLS(NSEGS)+1
      RETURN
 1000 WRITE(JUNIT,*)' J_PUTSTR--SEGMENT STORAGE OVERFLOW'
C  BE DRASTIC FOR NOW
      CALL JRCLOS
      RETURN
      END
