      SUBROUTINE JMARK(X,Y)
      INCLUDE 'D0$INC:DI3INC.INC'
      CHARACTER*1 MARK(5)
      REAL X,Y
      DATA MARK/'.','+','*','O','X'/
      IMRK=MOD(IMARK-1,5)+1
      IF(IMRK.LT.1) IMRK=1
      IF(IMRK.GT.5) IMRK=5
      XPOSN=X
      YPOSN=Y
C  THE CHARACTER CELL STARTS AT THE UPPER LEFT (UIS)
      CALL J_TR2XY(XPOSN-.5*XSIZE,YPOSN+.5*YSIZE,CRTX,CRTY)
C  NORMAL CHARACTERS ARE 78 CHARS BY 34 LINES.
C  ASSUME NORMAL PIXEL DIMENSIONS ARE 13 IN X BY 23 IN Y.
      CALL J_TEXT(VD_ID,ATB_FNT,MARK(IMRK),CRTX,CRTY)
      IF(.NOT.PUTS)RETURN
      IF(PUTSUP)RETURN
      CALL J_PUTSG(I2MARK,X)
      CALL J_PUTSG(-I2MARK,Y)
      IF(IPICID.NE.0) CALL J_PIKDO(X,Y,Z)
      END
