      SUBROUTINE JSPICK(VX,VY,DSPDEV,SEGNAM,PICKID)
      INTEGER DSPDEV,SEGNAM,PICKID
      INCLUDE 'D0$INC:DI3INC.INC'
      SEGNAM=0
      PICKID=0
      IPRI=0
      IF(NPICKS.EQ.0.OR.NSEGS.EQ.0)RETURN
      DO 10 I=1,NPICKS
        ISG=IPKSEG(I)
        JSG=0
        DO 20 J=1,NSEGS
          IF(NUMSEG(J).NE.ISG) GO TO 20
          JSG=J
          GO TO 30
   20   CONTINUE
        GO TO 1000
   30   IF(IVIS(JSG).EQ.0) GO TO 10
        IF(VX.LT.(PKXMN(I)-PDXAPR)) GO TO 10
        IF(VY.LT.(PKYMN(I)-PDYAPR)) GO TO 10
        IF(VX.GT.(PKXMX(I)+PDXAPR)) GO TO 10
        IF(VY.GT.(PKYMX(I)+PDYAPR)) GO TO 10
        IF(IPRIOR(I).LT.IPRI) GO TO 10
        SEGNAM=IPKSEG(I)
        PICKID=IDPICK(I)
        IPRI=IPRIOR(I)
   10 CONTINUE
      RETURN
C ERROR.  SEGMENT NOT THERE.
 1000 RETURN
      END
