      SUBROUTINE JR3PGN(X,Y,Z,N)
      INCLUDE 'D0$INC:DI3INC.INC'
      REAL X(*),Y(*),Z(*)
      LOGICAL PUTSV
      PUTSV=PUTS
      PUTS=.FALSE.
      XSAVE=XPOSN
      YSAVE=YPOSN
      ZSAVE=ZPOSN
      NN=N+1
      DO 500 I=1,N
        IF(I.EQ.1) THEN
            XI=XPOSN+X(I)
            YI=YPOSN+Y(I)
            ZI=ZPOSN+Z(I)
            CALL J_TR3XYZ(XI,YI,ZI,XPOLY(NN),YPOLY(NN),ZPOLY(NN))
           ELSE
            XI=XI+X(I)
            YI=YI+Y(I)
            ZI=ZI+Z(I)
        ENDIF
        CALL J_TR3XYZ(XI,YI,ZI,XPOLY(I),YPOLY(I),ZPOLY(I))
      IF(IPICID.NE.0) CALL J_PIKDO(XI,YI,ZI)
  500 CONTINUE
      IF(IPSTYL.EQ.0)GO TO 630
      CALL JCOLOR(IPCOLO)
      CALL J_PLOT_ARRAY(VD_ID,ATB_PLY,NN,XPOLY,YPOLY)
      IF(IPEDGE.GT.0) GO TO 620
      CALL JCOLOR(0)
  630 CALL J_PLOT_ARRAY(VD_ID,ATB,NN,XPOLY,YPOLY)
  620 XPOSN=XSAVE
      YPOSN=YSAVE
      ZPOSN=ZSAVE
      CALL JCOLOR(ICOLOR)
      IF(.NOT.PUTSV)RETURN
      PUTS=.TRUE.
      CALL J_PUTSGN_i(IR3PGN,1,N)
      CALL J_PUTSGN(IR3PGN,N,X)
      CALL J_PUTSGN(IR3PGN,N,Y)
      CALL J_PUTSGN(-IR3PGN,N,Z)
 1000 RETURN
      END
