      SUBROUTINE JR3DRA(X,Y,Z)
      REAL*4 X,Y,Z,XNEW,YNEW,ZNEW,XNOW,YNOW,XOLD,YOLD,ZOLD
      INCLUDE 'D0$INC:DI3INC.INC'
C
      XNOW=XPOSN+X
      YNOW=YPOSN+Y
      ZNOW=ZPOSN+Z
      CALL J_TR3XYZ(XPOSN,YPOSN,ZPOSN,XOLD,YOLD,ZOLD)
      CALL J_TR3XYZ(XNOW,YNOW,ZNOW,XNEW,YNEW,ZNEW)
      CALL J_LINE2(VD_ID,ATB,XOLD,YOLD,XNEW,YNEW)
      XPOSN=XNOW
      YPOSN=YNOW
      ZPOSN=ZNOW
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IR3DRA,X)
      CALL J_PUTSG(IR3DRA,Y)
      CALL J_PUTSG(-IR3DRA,Z)
      IF(IPICID.NE.0) CALL J_PIKDO(XNOW,YNOW,ZNOW)
      END
