      SUBROUTINE J_TR2XY(X,Y,XP,YP)
C  DO THE VIEWING TRANSFORMATION ON COORDINATES
      COMMON/SCRTRN/XSCALE,YSCALE,XSCALS,YSCALS
      REAL*4 X,Y,XP,YP
      INCLUDE 'D0$INC:DI3INC.INC'
C
C  DO MODELLING TRANSFORMATION IF CALLED FOR
      IF(IMODEL.EQ.1) GO TO 10
      XP=X
      YP=Y
      GO TO 10
    5 XP=X*MMODEL(1,1)+Y*MMODEL(2,1)+MMODEL(4,1)
      YP=X*MMODEL(1,2)+Y*MMODEL(2,2)+MMODEL(4,2)
C  TRANSLATE TO ORIGIN OF UVN SYSTEM
   10 XTR=X-XVW
      YTR=Y-YVW
C  ROTATE TO UVN AXES
      XP=XTR*UVECX+YTR*UVECY
      YP=XTR*VVECX+YTR*VVECY
C  TRANSFORM TO VIEWPORT COORDINATES
      XP=(XP-UMIN)*XSCALE+VXMIN
      YP=(YP-VMIN)*YSCALE+VYMIN
C  IMAGE TRANSFORMATIONS
      IF(ISEGNM.EQ.0) GO TO 30
      IF(ITYCUR.EQ.0) GO TO 30
      IF(ITYCUR.EQ.1) GO TO 35
      DX=XP-PXC
      DY=YP-PYC
      XP=(DX*CSC-DY*SNC)+PXC
      YP=(DX*SNC+DY*CSC)+PYC
C!!!STICK IN ASSOCIATION STUFF HERE  (JLOCAT 7)
   35 XP=XP+TXC
      YP=YP+TYC
C  TRANSFORM TO SCREEN COORDINATES
   30 XP=(XP-VCXMN)*XSCALS+XMARG
      YP=(YP-VCYMN)*YSCALS+YMARG
      RETURN
      END
