        SUBROUTINE J_BUFWRITE(BUFFER,LENGTH,LUN)   
C  CALLED BY J_META TO OUTPUT FILE
        IMPLICIT INTEGER(A-Z)
        BYTE BUFFER(LENGTH)
        WRITE(LUN,500)BUFFER                       
 500    FORMAT(T3,I7)
        RETURN
        END
