      SUBROUTINE JPECHO(DSPDEV,INPFCT,PHYDEV,VX,VY)
      INTEGER DSPDEV,PHYDEV
      INCLUDE 'D0$INC:DI3INC.INC'
      IF(INPFCT.LT.1.OR.INPFCT.GT.6) RETURN
      XECHO(INPFCT)=VX
      YECHO(INPFCT)=VY
      END
