      SUBROUTINE JSIZE(X,Y)
      REAL X,Y,XTEM,YTEM
      INCLUDE 'D0$INC:DI3INC.INC'
      IF(X.LE.0. .OR. Y.le.0.)THEN
        WRITE(JUNIT,*)'JSIZE BAD X,Y:',X,Y
        RETURN
      ENDIF
      XSIZE=X
      YSIZE=Y
C  SET UP FONT SIZES FOR J1STRG ROUTINE
C  FIRST GET WINDOW SIZE AND SCALE APPROPRIATELY
      DU=UMAX-UMIN
      DV=VMAX-VMIN
      DXTEM=15.*X/DU
      DYTEM=18.*Y/DV
      CALL J_SET_CHAR_SIZE(VD_ID,ATB_FNT,ATB_FNT,0,DXTEM,DYTEM)
      IF(.NOT.PUTS)RETURN
      CALL J_PUTSG(IJSIZE,X)
      CALL J_PUTSG(-IJSIZE,Y)
      IF(IPICID.NE.0) CALL J_PIKDO(X,Y,Z)
      END
