      SUBROUTINE J3MARK(X,Y,Z)
      INCLUDE 'D0$INC:DI3INC.INC'
      CHARACTER*1 MARK(5)
      REAL X,Y
      DATA MARK/'.','+','*','O','X'/
      IMRK=MOD(IMARK-1,5)+1
C!!!!!ADJUST SIZE
      XPOSN=X
      YPOSN=Y
      ZPOSN=Z
C!!!!!BELOW IS NOT QUITE RIGHT FOR JUSTIFICATION
      CALL J_TR3XYZ(XPOSN,YPOSN,ZPOSN,CRTX,CRTY,ZDUMMY)
      CALL J_TEXT(VD_ID,ATB_FNT,MARK(IMRK),
     &  CRTX-6.,CRTY-11.)    ! CENTER JUSTIFY (SEE JMARK)
      IF(.NOT.PUTS)RETURN
      IF(PUTSUP)RETURN
      CALL J_PUTSG(I3MARK,X)
      CALL J_PUTSG(I3MARK,Y)
      CALL J_PUTSG(-I3MARK,Z)
      IF(IPICID.NE.0) CALL J_PIKDO(X,Y,Z)
      END
