      SUBROUTINE JVPORT(X1,X2,Y1,Y2)
C  SPECIFY AND SETUP VIEWPORT
      REAL X1,X2,Y1,Y2,SF
      INCLUDE 'D0$INC:DI3INC.INC'
      IF(IFSPAC.EQ.0) CALL JVSPAC(-1.,1.,-1.,1.)
      VXMIN=X1
      VXMAX=X2
      VYMIN=Y1
      VYMAX=Y2
      CALL J_DEVMAT
      IFPORT=1
      IMDEV=1
      ITRANS=1
      END
