      SUBROUTINE JELSEG(DSPDEV,PHYDEV,NAME,IASSC)
      INTEGER DSPDEV,PHYDEV
      INCLUDE 'D0$INC:DI3INC.INC'
      IF(NSEGS.EQ.0) GO TO 1000
      DO 10 I=1,NSEGS
        ISEG=I
        IF(NAME.EQ.NUMSEG(I)) GO TO 20
   10 CONTINUE
      GO TO 1000
   20 IASSO(ISEG)=IASSC
      RETURN
 1000 WRITE(JUNIT,*) ' NO SUCH SEGMENT EXISTS',NAME
      END
