      SUBROUTINE JMODEL(MATRIX)
C  ENABLE MODELING MATRIX (MAKE IT THE DEFAULT)
      REAL MATRIX(4,4)
      INCLUDE 'D0$INC:DI3INC.INC'
      DO 10 I=1,4
        DO 20 J=1,4
          MMODEL(I,J)=MATRIX(I,J)
   20   CONTINUE
   10 CONTINUE
C  JUST TO BE SURE
      IMODEL=0
      END
