      SUBROUTINE JDEVWN(IDEV,VXMNN,VXMXX,VYMNN,VYMXX)
      IF(IDEBUG.GT.5)TYPE 2222,IDEV,VXMNN,VXMXX,VYMNN,VYMXX
 2222 FORMAT(' JDEVWN:',I,4F)
      CALL JVSPAC(VXMNN,VXMXX,VYMNN,VYMXX)
C!!!!!!THIS MAY BE A KLUDGE.  AND IT PROBABLY NEEDS A
C!!!!!!PUTSGN NUMBER SINCE IT CAN BE CALLED INSIDE SEGMENTS.
      END
