C-   Updated  24-MAR-2004   sss - compile with g77.
      SUBROUTINE JEND
      INCLUDE 'D0$INC:DI3INC.INC'
      IF(IDEBUG.GT.5)write (*,2222)
 2222 FORMAT(' JEND')
C  CLEAR DISPLAY
C      IF(VD_ID.NE.0) CALL J_DELETE_DISPLAY(VD_ID)
C  !!!ALSO CLEAR INTERRUPTS
      END
