C-   Updated  24-MAR-2004   sss - compile with g77.
      SUBROUTINE JDEVWN(IDEV,VXMNN,VXMXX,VYMNN,VYMXX)
      IF(IDEBUG.GT.5)write (*,2222),IDEV,VXMNN,VXMXX,VYMNN,VYMXX
C&IF LINUX
C& 2222 FORMAT(' JDEVWN:',I7,4F6.2)
C&ELSE
 2222 FORMAT(' JDEVWN:',I,4F)
C&ENDIF
      CALL JVSPAC(VXMNN,VXMXX,VYMNN,VYMXX)
C!!!!!!THIS MAY BE A KLUDGE.  AND IT PROBABLY NEEDS A
C!!!!!!PUTSGN NUMBER SINCE IT CAN BE CALLED INSIDE SEGMENTS.
      END
