      SUBROUTINE JIQDEV(DSPDEV,ICODE,LIST)
C  VARIOUS PROPERTIES OF THE DISPLAY DEVICE
      INTEGER DSPDEV
      DIMENSION LIST(10)
      LIST(1)=0
      IF(ICODE.EQ.1) LIST(1)=10
      IF(ICODE.EQ.8) LIST(1)=10
      END
