CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VCALOR_UTIL()
      VCALOR_UTIL = ' CALOR_UTIL'//
     X                   '  TEST V1.44_02'//
     X                   ' 24-OCT-1997 11:07:13.43'
      Return
      End
