CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VFDC_UTIL()
      VFDC_UTIL = ' FDC_UTIL'//
     X                   '  OFFICIAL V1.16'//
     X                   ' 14-JUL-1997 14:53:00.00'
      Return
      End
