PACKAGE := physics_util
physics_util_LIB := yes
include GNUmakefile.subcommon

PHYSICS_UTIL_NO_RANGE_CHECK := dbank/zb_smg_pn1 dbank/zb_smg_pn2 dbank/vbrowse dbank/dbank general/good_photon general/good_electron
$(foreach f,$(PHYSICS_UTIL_NO_RANGE_CHECK),tmp/DEB/physics_util/$(f).o tmp/OPT/physics_util/$(f).o) : FORT_COMMON_FLAGS += -fno-range-check
