CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VPHYSICS_UTIL()
      VPHYSICS_UTIL = ' PHYSICS_UTIL'//
     X                   '  OFFICIAL V0.06'//
     X                   ' 14-JUL-1997 16:57:35.38'
      Return
      End
