CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VPHYSICS_UTIL()
      VPHYSICS_UTIL = ' PHYSICS_UTIL'//
     X                   '  TEST V0.06_03'//
     X                   ' 10-JUN-1998 11:10:01.12'
      Return
      End
