CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VMUON_RECO()
      VMUON_RECO = ' MUON_RECO'//
     X                   '  TEST V2.14_07'//
     X                   '  9-APR-1996 13:59:25.31'
      Return
      End
