      SUBROUTINE NUM_TO_ADDR(ECHN,LCHN,IFL)
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : Determine Electronic/Logical channel
C-                         for IFL = 1/2
C-      Routine ID is 29
C-   Inputs  : ECHN/LCHN for IFL = 1/2
C-   Outputs : ECHN/LCHN for IFL = 2/1
C-   Controls: IFL
C-   Error Status: Output set to -1, if Error in accessing SRCP banks.
C-
C-   Created   2-FEB-1989   Srini Rajagopalan
C-   Updated   5-MAR-1989   SR, introduced I5.5, redefined routine as CTD_
C-   Updated  19-SEP-1989   SR, Store Electronic --> Logical address in an
C-                          array LOGID(*) to reduce SRCP calls.
C-   Updated  16-DEC-1989   SR, Added Reset feature to deal with Multiple
C-                          crates. Compatible with Calib/Non-Calib code.
C-   Updated   2-OCT-1990   Srini Rajagopalan   Change to new SRCP calls.
C-   Updated  10-DEC-1992   Srini Rajagopalan   Fix EZRSET calls.
C- 
C----------------------------------------------------------------------
      IMPLICIT NONE
C
      INTEGER ECHN,LCHN,IFL,CRATE,IERR,I
      INTEGER LOGID(0:255),ELCID(0:64000)
      CHARACTER*4 PATH
      CHARACTER*6 CHAR1,CHAR2
      CHARACTER*10 BNKNAM
      CHARACTER*80 MSG_STRING
C----------------------------------------------------------------------
C
      IF (IFL.EQ.1.AND.LOGID(ECHN).EQ.-1) THEN
        WRITE(CHAR1,10)ECHN
   10   FORMAT('E',I5.5)
C
        CALL EZPICK(BNKNAM)
        CALL EZGET (CHAR1,LCHN,IERR)
        CALL EZRSET
        IF (IERR.NE.0) THEN
          WRITE(MSG_STRING,101)CRATE,ECHN
          CALL INTMSG(MSG_STRING)
          LCHN = -1
          GO TO 999
        ENDIF
        LOGID(ECHN) = LCHN
C
      ELSE IF (IFL.EQ.1.AND.LOGID(ECHN).NE.-1) THEN
        LCHN = LOGID(ECHN)
      ELSE IF (IFL.EQ.2.AND.ELCID(LCHN).EQ.-1) THEN
          WRITE(CHAR2,20)LCHN
   20     FORMAT('L',I5.5)
        CALL EZPICK(BNKNAM)
        CALL EZGET (CHAR2,ECHN,IERR)
        CALL EZRSET
        IF (IERR.NE.0) THEN
          WRITE(MSG_STRING,102)CRATE,LCHN
          CALL INTMSG(MSG_STRING)
          ECHN = -1
          GO TO 999
        ENDIF
        ELCID(LCHN) = ECHN
      ELSE IF (IFL.EQ.2.AND.ELCID(LCHN).NE.-1) THEN
        ECHN = ELCID(LCHN)
      ENDIF
C
  101 FORMAT(' Error in access : Crate = ',I3,' Channel = ',I3,
     &  ' Num_to_Addr')
  102 FORMAT(' Error in access : Crate = ',I3,' Channel = ',I6,
     &  ' Num_to_Addr')
C
  999 RETURN
C
C===========================================================================C
        ENTRY RS_NUM_TO_ADDR
C
C  *** Entry point for initializing arrays in NUM_TO_ADDR Should be called
C  before accessing CRATE_nnn SRCP banks generated by CALIB.
C  The RCP bank where the crate number exists MUST be picked before a 
C  call to this entry point.
C
C===========================================================================C
C
        CALL CPATHG(PATH)
        DO 2 I = 0,255
          LOGID(I) = -1
    2   CONTINUE
        DO 3 I = 0,64000
          ELCID(I) = -1
    3   CONTINUE
        CALL EZGSET('CRATE',CRATE,1)
        WRITE(BNKNAM,5)CRATE,PATH(4:4)
    5   FORMAT('CRATE_',I3.3,A1)
C
      RETURN
      END
