PACKAGE := dbl3
dbl3_LIB := yes
include GNUmakefile.subcommon

DBL3_F77 := dbl3
$(foreach f,$(DBL3_F77),tmp/DEB/dbl3/dbl3/$(f).o tmp/OPT/dbl3/dbl3/$(f).o) : FORT := $(F77)
$(foreach f,$(DBL3_F77),tmp/DEB/dbl3/dbl3/$(f).o tmp/OPT/dbl3/dbl3/$(f).o) : FORT_COMMON_FLAGS := $(F77_COMMON_FLAGS)

