CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C D0 library release version function.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      Character*72 Function VDBL3()
      VDBL3 = ' DBL3'//
     X                   '  TEST V1.21_01'//
     X                   ' 10-OCT-1997 11:59:30.40'
      Return
      End
