      SUBROUTINE MULIB_OPEN(RCP_NAME,RCP_AUX,RZ_NAME,NEW_LIBRARY,
     &  IUNIT,IUNIT_AUX,FILNAM,FILNAM_AUX,
     &  DCYCLES,NO_DCYCLES,NDCYCLES,IER)
C----------------------------------------------------------------------
C-
C-   Purpose and Methods : OPEN A NEW OR EXISTING MUONLIBRARY
C-
C-   Inputs  :RCP_NAME    = RCP_NAME containing file to be opened
C-            RCP_AUX     = RCP NAME FOR THE  Auxilliary file
C-            RZ_NAME     = Name to identify library in later calls to RZCDIR
C-            NEW_LIBRARY = .TRUE. FOR A NEW LIBRARY
C-   Outputs : IUNIT = UNIT NUMBER OPENED for MUONLIBRARY
C-             IUNIT_AUX = Unit number for Auxilliary file
C-             FILNAM = NAME OF MUONLIBRARY file  OPENED
C-             FILNAM_AUX = Name of Auxilliary file Opened
C-             DCYCLES = CYCLES ARRAY FOR THIS LIBRARY
C-             NDCYCLES = TOTAL NUMBER OF TRACKS
C-             IER    = ERROR FLAG
C-   Controls:
C-
C-   Created  24-MAY-1993   Jasbir Singh   (Similar to SHLb_open by R Raja)
C-
C----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'D0$INC:QUEST.INC'
      INCLUDE 'D0$INC:MULCON.INC'
      INTEGER IUNIT,IUNIT_AUX,IER
      CHARACTER*(*)FILNAM,FILNAM_AUX,RCP_NAME,RCP_AUX,RZ_NAME
      INTEGER L,LAUX
      LOGICAL NEW_LIBRARY
      INTEGER NWARN
      INTEGER RZLOGLEV
      INTEGER I1,I2,I3
      INTEGER DCYCLES(NDATA_CYCLES),NDCYCLES,NDCYCLES1
      INTEGER NO_DCYCLES(NDATA_CYCLES)
      INTEGER ICYCLE
      INTEGER SRECL,SRECL_AUX,PRALLOC
      INTEGER NCHAR
      INTEGER IOSTAT_OPEN
      INTEGER NLENGTH
C
      CHARACTER*80 FILNAM_DUM
      INTEGER NTOT_REC,NDC
C
      LOGICAL KEYED,READ_ONLY,ADD_TO_LIBRARY
      INTEGER MUON_KEY
C----------------------------------------------------------------------
      CALL EZPICK('MUONLIBRARY_RCP')              ! select muonLIB bank
      CALL EZ_GET_CHARS(RCP_NAME,NCHAR,FILNAM,IER)
      CALL EZ_GET_CHARS(RCP_AUX,NCHAR,FILNAM_AUX,IER)
      CALL EZGET_l('KEYED_ACCESS',KEYED,IER)
      CALL EZGET_l('ADD_TO_LIBRARY',ADD_TO_LIBRARY,IER)
      CALL EZRSET
C
      READ_ONLY = .TRUE.
      IF(IER.NE.0)THEN
        IUNIT=0
        IUNIT_AUX = 0
        GOTO 9930
      ENDIF

      L=LEN(FILNAM)
      LAUX = LEN(FILNAM_AUX)
      CALL EZGET_i('MUON_USER ',IUSER,IER)
C
C ****  GET UNIT NUMBER FOR THE muon LIBRARY  FILE
C
      CALL GTUNIT(IUSER,IUNIT,IER)
      CALL GTUNIT(IUSER,IUNIT_AUX,IER)
      IF(IER.NE.0)GOTO 9950
C
      IF(NEW_LIBRARY)THEN
        CALL EZPICK('MUONLIBRARY_RCP')              ! select muonLIB bank
        CALL EZGET_i('MUONLIBRARY_RECL',SRECL,IER)
        CALL EZGET('MUONLIBRARY_AUX_RECL',SRECL_AUX,IER)
        CALL EZGET('MUONLIBRARY_ALLOCATION',PRALLOC,IER)
        CALL EZRSET
        READ_ONLY = .FALSE.
C
        IF ( KEYED ) THEN
C
C ****  OPENING NOW DONE IN MULBEG_RUN
C
        ELSE
          CALL MUONLIB_OPEN(IUNIT,FILNAM,SRECL,
     &     NEW_LIBRARY,KEYED,READ_ONLY,IER)
        ENDIF
C
        IF(ADD_TO_LIBRARY)THEN
          READ_ONLY = .FALSE.   ! ADD TO AUX FILE
          CALL MUONLIB_AUX_OPEN(IUNIT_AUX,FILNAM_AUX,SRECL_AUX,
     &    .FALSE.,READ_ONLY,IER)        ! OPEN EXISTING FILE TO WRITE TO
C
          IQUEST(1) = 0
C
C ****  READ AUXILLIARY FILE
C
          CALL MULAUX_READ(IUNIT_AUX,1,NTOT_REC,FILNAM_DUM,DCYCLES,
     &    NO_DCYCLES,NDC,NDCYCLES1,NDCYCLES,.TRUE.)
          NFILE = NTOT_REC                ! TOTAL NUMBER OF FILES SO FAR

        ELSE
          READ_ONLY = .FALSE.            ! OPEN NEW AUX FILE AND WRITE TO it
          CALL MUONLIB_AUX_OPEN(IUNIT_AUX,FILNAM_AUX,SRECL_AUX,
     &    NEW_LIBRARY,READ_ONLY,IER)
C
          DO I3 = 1 ,NDATA_CYCLES         ! Zero cycles array.
            DCYCLES(I3) = 0
          ENDDO
        ENDIF
      ELSE
C
C ****  OLD LIBRARY
C
        READ_ONLY = .TRUE.
        CALL MUONLIB_OPEN(IUNIT,FILNAM,SRECL,
     &     NEW_LIBRARY,KEYED,READ_ONLY,IER)
C
        CALL MUONLIB_AUX_OPEN(IUNIT_AUX,FILNAM_AUX,SRECL_AUX,
     &    NEW_LIBRARY,READ_ONLY,IER)
C
        IQUEST(1) = 0
C
C ****  READ AUXILLIARY FILE
C
        CALL MULAUX_READ(IUNIT_AUX,1,NTOT_REC,FILNAM_DUM,DCYCLES,
     &    NO_DCYCLES,NDC,NDCYCLES1,NDCYCLES,.TRUE.)
        NFILE = NTOT_REC                ! TOTAL NUMBER OF FILES SO FAR
      ENDIF
C
      CALL ERRMSG('MUONLIBRARY','MULIB_OPEN',
     &    'muon LIBRARY INITIALIZATION COMPLETED','W')
C
  999 RETURN
C
 9930 CONTINUE
      CALL ERRMSG('MUONLIBRARY','MULIB_OPEN',
     &  ' ERROR IN RCP FILE','W')
      RETURN
 9950 CALL ERRMSG('MUONLIBRARY','MULIB_OPEN',
     &  ' ERROR GETTING UNIT NUMBER FROM GTUNIT','W')
      RETURN
      END
